Pkg.add("GLUT")
Pkg.clone("https://github.com/SimonDanisch/ModernGL.jl.git")
Pkg.clone("https://github.com/SimonDanisch/Events.jl.git")
Pkg.clone("https://github.com/SimonDanisch/GLUtil.jl.git")
Pkg.clone("https://github.com/SimonDanisch/ModernGL.jl.git")
Pkg.clone("https://github.com/SimonDanisch/GLWindow.jl.git")