import GetC.@getCFun
#function bodies
@getCFun "libGLU" gluQuadricTexture gluQuadricTexture(quad::Ptr{Void},texture::GLboolean)::Void
@getCFun "libGLU" strtoimax strtoimax(__nptr::Ptr,__endptr::Ptr,__base::Int32)::intmax_t
@getCFun "libGLU" wcstoimax wcstoimax(__nptr::Ptr,__endptr::Ptr,__base::Int32)::intmax_t
@getCFun "libGLU" imaxabs imaxabs(__n::intmax_t)::intmax_t
@getCFun "libGLU" imaxdiv imaxdiv(__numer::intmax_t,__denom::intmax_t)::imaxdiv_t
@getCFun "libGLU" strtoumax strtoumax(__nptr::Ptr,__endptr::Ptr,__base::Int32)::uintmax_t
@getCFun "libGLU" gluDisk gluDisk(quad::Ptr{Void},inner::GLdouble,outer::GLdouble,slices::GLint,stacks::GLint)::Void
@getCFun "libGLU" wcstoumax wcstoumax(__nptr::Ptr,__endptr::Ptr,__base::Int32)::uintmax_t
@getCFun "libGLU" gluNewQuadric gluNewQuadric()::Ptr{Void}
@getCFun "libGLU" gluPerspective gluPerspective(fovy::GLdouble,aspect::GLdouble,znear::GLdouble,zfar::GLdouble)::Void
@getCFun "libGLU" gluBuild2DMipmaps gluBuild2DMipmaps(target::GLenum,internalFormat::GLint,width::GLsizei,height::GLsizei,format::GLenum,thetype::GLenum,data::Ptr{Uint8})::GLint
@getCFun "libGLU" gluCylinder gluCylinder(quad::Ptr{Void},base::GLdouble,top::GLdouble,height::GLdouble,slices::GLint,stacks::GLint)::Void
@getCFun "libGLU" gluPartialDisk gluPartialDisk(quad::Ptr{Void},inner::GLdouble,outer::GLdouble,slices::GLint,loops::GLint,start::GLdouble,sweep::GLdouble)::Void
@getCFun "libGLU" gluSphere gluSphere(quad::Ptr{Void},radius::GLdouble,slices::GLint,stacks::GLint)::Void
@getCFun "libGLU" gluQuadricNormals gluQuadricNormals(quad::Ptr{Void},normal::GLenum)::Void
#constants
const GL_GLU_VERTEX                                                   = 100101
const GL_GLU_NURBS_ERROR6                                             = 100256
const GL_GLU_NURBS_TESSELLATOR_EXT                                    = 100161
const GL_GLU_TESS_BOUNDARY_ONLY                                       = 100141
const GL_GLU_TESS_END                                                 = 100102
const GL_GLU_OUTLINE_POLYGON                                          = 100240
const GL_GLU_NURBS_ERROR19                                            = 100269
const GL_GLU_NURBS_ERROR21                                            = 100271
const GL_GLU_NURBS_ERROR20                                            = 100270
const GL_GLU_NURBS_ERROR36                                            = 100286
const GL_GLU_DISPLAY_MODE                                             = 100204
const GL_GLU_SILHOUETTE                                               = 100013
const GL_GLU_OUTSIDE                                                  = 100020
const GL_GLU_CCW                                                      = 100121
const GL_GLU_TESS_WINDING_NEGATIVE                                    = 100133
const GL_GLU_TESS_ERROR8                                              = 100158
const GL_GLU_NURBS_ERROR18                                            = 100268
const GL_GLU_NURBS_BEGIN_EXT                                          = 100164
const GL_GLU_NURBS_NORMAL                                             = 100166
const GL_GLU_CULLING                                                  = 100201
const GL_GLU_EXT_object_space_tess                                    = 1
const GL_GLU_NURBS_TEX_COORD_DATA_EXT                                 = 100174
const GL_GLU_PARAMETRIC_ERROR                                         = 100216
const GL_GLU_TESS_BEGIN_DATA                                          = 100106
const GL_GLU_NURBS_ERROR12                                            = 100262
const GL_GLU_NURBS_MODE                                               = 100160
const GL_GLU_TESS_ERROR3                                              = 100153
const GL_GLU_TESS_NEED_COMBINE_CALLBACK                               = 100156
const GL_GLU_INTERIOR                                                 = 100122
const GL_GLU_INSIDE                                                   = 100021
const GL_GLU_TESS_EDGE_FLAG                                           = 100104
const GL_GLU_NURBS_ERROR9                                             = 100259
const GL_GLU_TESS_MISSING_END_CONTOUR                                 = 100154
const GL_GLU_NURBS_ERROR7                                             = 100257
const GL_GLU_V_STEP                                                   = 100207
const GL_GLU_TESS_MISSING_BEGIN_CONTOUR                               = 100152
const GL_GLU_INVALID_VALUE                                            = 100901
const GL_GLU_PATH_LENGTH                                              = 100215
const GL_GLU_TESS_ERROR_DATA                                          = 100109
const GL_GLU_EXTENSIONS                                               = 100801
const GL_GLU_NURBS_ERROR17                                            = 100267
const GL_GLU_NURBS_ERROR1                                             = 100251
const GL_GLU_NURBS_NORMAL_EXT                                         = 100166
const GL_GLU_NURBS_ERROR29                                            = 100279
const GL_GLU_AUTO_LOAD_MATRIX                                         = 100200
const GL_GLU_MAP1_TRIM_3                                              = 100211
const GL_GLU_NONE                                                     = 100002
const GL_GLU_NURBS_ERROR16                                            = 100266
const GL_GLU_NURBS_VERTEX                                             = 100165
const GL_GLU_EXT_nurbs_tessellator                                    = 1
const GL_GLU_NURBS_ERROR33                                            = 100283
const GL_GLU_OBJECT_PARAMETRIC_ERROR                                  = 100208
const GL_GLU_NURBS_END_EXT                                            = 100169
const GL_GLU_EDGE_FLAG                                                = 100104
const GL_GLU_TESS_ERROR5                                              = 100155
const GL_GLU_TESS_MISSING_END_POLYGON                                 = 100153
const GL_GLU_TRUE                                                     = 1
const GL_GLU_NURBS_ERROR26                                            = 100276
const GL_GLU_NURBS_END_DATA                                           = 100175
const GL_GLU_NURBS_TEXTURE_COORD_DATA                                 = 100174
const GL_GLU_INVALID_ENUM                                             = 100900
const GL_GLU_SAMPLING_TOLERANCE                                       = 100203
const GL_GLU_TESS_WINDING_POSITIVE                                    = 100132
const GL_GLU_LINE                                                     = 100011
const GL_GLU_VERSION_1_1                                              = 1
const GL_GLU_NURBS_COLOR_DATA                                         = 100173
const GL_GLU_NURBS_ERROR25                                            = 100275
const GL_GLU_TESS_ERROR                                               = 100103
const GL_GLU_NURBS_VERTEX_DATA                                        = 100171
const GL_GLU_TESS_ERROR2                                              = 100152
const GL_GLU_NURBS_ERROR                                              = 100103
const GL_GLU_VERSION_1_3                                              = 1
const GL_GLU_TESS_BEGIN                                               = 100100
const GL_GLU_NURBS_RENDERER                                           = 100162
const GL_GLU_TESS_WINDING_ODD                                         = 100130
const GL_GLU_TESS_ERROR1                                              = 100151
const GL_GLU_TESS_ERROR6                                              = 100156
const GL_GLU_OUTLINE_PATCH                                            = 100241
const GL_GLU_VERSION                                                  = 100800
const GL_GLU_OBJECT_PARAMETRIC_ERROR_EXT                              = 100208
const GL_GLU_SAMPLING_METHOD                                          = 100205
const GL_GLU_NURBS_TEX_COORD_EXT                                      = 100168
const GL_GLU_TESS_VERTEX                                              = 100101
const GL_GLU_POINT                                                    = 100010
const GL_GLU_FALSE                                                    = 0
const GL_GLU_NURBS_VERTEX_EXT                                         = 100165
const GL_GLU_NURBS_BEGIN_DATA_EXT                                     = 100170
const GL_GLU_TESS_EDGE_FLAG_DATA                                      = 100110
const GL_GLU_FILL                                                     = 100012
const GL_GLU_OBJECT_PATH_LENGTH                                       = 100209
const GL_GLU_NURBS_ERROR30                                            = 100280
const GL_GLU_SMOOTH                                                   = 100000
const GL_GLU_CW                                                       = 100120
const GL_GLU_TESS_END_DATA                                            = 100108
const GL_GLU_NURBS_ERROR15                                            = 100265
const GL_GLU_NURBS_ERROR27                                            = 100277
const GL_GLU_NURBS_ERROR22                                            = 100272
const GL_GLU_NURBS_ERROR32                                            = 100282
const GL_GLU_EXTERIOR                                                 = 100123
const GL_GLU_TESS_ERROR4                                              = 100154
const GL_GLU_NURBS_ERROR13                                            = 100263
const GL_GLU_DOMAIN_DISTANCE                                          = 100217
const GL_GLU_NURBS_ERROR34                                            = 100284
const GL_GLU_NURBS_ERROR23                                            = 100273
const GL_GLU_NURBS_ERROR4                                             = 100254
const GL_GLU_NURBS_COLOR_DATA_EXT                                     = 100173
const GL_GLU_NURBS_ERROR8                                             = 100258
const GL_GLU_NURBS_COLOR_EXT                                          = 100167
const GL_GLU_NURBS_ERROR31                                            = 100281
const GL_GLU_NURBS_ERROR2                                             = 100252
const GL_GLU_NURBS_ERROR28                                            = 100278
const GL_GLU_TESS_WINDING_ABS_GEQ_TWO                                 = 100134
const GL_GLU_NURBS_ERROR11                                            = 100261
const GL_GLU_NURBS_END_DATA_EXT                                       = 100175
const GL_GLU_NURBS_ERROR37                                            = 100287
const GL_GLU_UNKNOWN                                                  = 100124
const GL_GLU_BEGIN                                                    = 100100
const GL_GLU_NURBS_ERROR24                                            = 100274
const GL_GLU_OBJECT_PATH_LENGTH_EXT                                   = 100209
const GL_GLU_ERROR                                                    = 100103
const GL_GLU_TESS_VERTEX_DATA                                         = 100107
const GL_GLU_TESS_ERROR7                                              = 100157
const GL_GLU_NURBS_NORMAL_DATA_EXT                                    = 100172
const GL_GLU_TESS_COORD_TOO_LARGE                                     = 100155
const GL_GLU_NURBS_BEGIN_DATA                                         = 100170
const GL_GLU_NURBS_VERTEX_DATA_EXT                                    = 100171
const GL_GLU_NURBS_TEXTURE_COORD                                      = 100168
const GL_GLU_NURBS_NORMAL_DATA                                        = 100172
const GL_GLU_NURBS_ERROR10                                            = 100260
const GL_GLU_TESS_MISSING_BEGIN_POLYGON                               = 100151
const GL_GLU_NURBS_END                                                = 100169
const GL_GLU_NURBS_ERROR5                                             = 100255
const GL_GLU_END                                                      = 100102
const GL_GLU_TESS_WINDING_NONZERO                                     = 100131
const GL_GLU_TESS_MAX_COORD                                           = 1.0e150
const GL_GLU_NURBS_ERROR35                                            = 100285
const GL_GLU_TESS_COMBINE_DATA                                        = 100111
const GL_GLU_TESS_WINDING_RULE                                        = 100140
const GL_GLU_NURBS_ERROR3                                             = 100253
const GL_GLU_NURBS_RENDERER_EXT                                       = 100162
const GL_GLU_TESS_TOLERANCE                                           = 100142
const GL_GLU_FLAT                                                     = 100001
const GL_GLU_PARAMETRIC_TOLERANCE                                     = 100202
const GL_GLU_INVALID_OPERATION                                        = 100904
const GL_GLU_NURBS_MODE_EXT                                           = 100160
const GL_GLU_NURBS_TESSELLATOR                                        = 100161
const GL_GLU_TESS_COMBINE                                             = 100105
const GL_GLU_INCOMPATIBLE_GL_VERSION                                  = 100903
const GL_GLU_VERSION_1_2                                              = 1
const GL_GLU_NURBS_ERROR14                                            = 100264
const GL_GLU_MAP1_TRIM_2                                              = 100210
const GL_GLU_OUT_OF_MEMORY                                            = 100902
const GL_GLU_NURBS_COLOR                                              = 100167
const GL_GLU_NURBS_BEGIN                                              = 100164
const GL_GLU_U_STEP                                                   = 100206
# Export everything!
export gluQuadricTexture, strtoimax, wcstoimax, imaxabs, imaxdiv, strtoumax, gluDisk, wcstoumax, gluNewQuadric, gluPerspective, gluBuild2DMipmaps, gluCylinder, gluPartialDisk, gluSphere, gluQuadricNormals, GL_GLU_VERTEX, GL_GLU_NURBS_ERROR6, GL_GLU_NURBS_TESSELLATOR_EXT, GL_GLU_TESS_BOUNDARY_ONLY, GL_GLU_TESS_END, GL_GLU_OUTLINE_POLYGON, GL_GLU_NURBS_ERROR19, GL_GLU_NURBS_ERROR21, GL_GLU_NURBS_ERROR20, GL_GLU_NURBS_ERROR36, GL_GLU_DISPLAY_MODE, GL_GLU_SILHOUETTE, GL_GLU_OUTSIDE, GL_GLU_CCW, GL_GLU_TESS_WINDING_NEGATIVE, GL_GLU_TESS_ERROR8, GL_GLU_NURBS_ERROR18, GL_GLU_NURBS_BEGIN_EXT, GL_GLU_NURBS_NORMAL, GL_GLU_CULLING, GL_GLU_EXT_object_space_tess, GL_GLU_NURBS_TEX_COORD_DATA_EXT, GL_GLU_PARAMETRIC_ERROR, GL_GLU_TESS_BEGIN_DATA, GL_GLU_NURBS_ERROR12, GL_GLU_NURBS_MODE, GL_GLU_TESS_ERROR3, GL_GLU_TESS_NEED_COMBINE_CALLBACK, GL_GLU_INTERIOR, GL_GLU_INSIDE, GL_GLU_TESS_EDGE_FLAG, GL_GLU_NURBS_ERROR9, GL_GLU_TESS_MISSING_END_CONTOUR, GL_GLU_NURBS_ERROR7, GL_GLU_V_STEP, GL_GLU_TESS_MISSING_BEGIN_CONTOUR, GL_GLU_INVALID_VALUE, GL_GLU_PATH_LENGTH, GL_GLU_TESS_ERROR_DATA, GL_GLU_EXTENSIONS, GL_GLU_NURBS_ERROR17, GL_GLU_NURBS_ERROR1, GL_GLU_NURBS_NORMAL_EXT, GL_GLU_NURBS_ERROR29, GL_GLU_AUTO_LOAD_MATRIX, GL_GLU_MAP1_TRIM_3, GL_GLU_NONE, GL_GLU_NURBS_ERROR16, GL_GLU_NURBS_VERTEX, GL_GLU_EXT_nurbs_tessellator, GL_GLU_NURBS_ERROR33, GL_GLU_OBJECT_PARAMETRIC_ERROR, GL_GLU_NURBS_END_EXT, GL_GLU_EDGE_FLAG, GL_GLU_TESS_ERROR5, GL_GLU_TESS_MISSING_END_POLYGON, GL_GLU_TRUE, GL_GLU_NURBS_ERROR26, GL_GLU_NURBS_END_DATA, GL_GLU_NURBS_TEXTURE_COORD_DATA, GL_GLU_INVALID_ENUM, GL_GLU_SAMPLING_TOLERANCE, GL_GLU_TESS_WINDING_POSITIVE, GL_GLU_LINE, GL_GLU_VERSION_1_1, GL_GLU_NURBS_COLOR_DATA, GL_GLU_NURBS_ERROR25, GL_GLU_TESS_ERROR, GL_GLU_NURBS_VERTEX_DATA, GL_GLU_TESS_ERROR2, GL_GLU_NURBS_ERROR, GL_GLU_VERSION_1_3, GL_GLU_TESS_BEGIN, GL_GLU_NURBS_RENDERER, GL_GLU_TESS_WINDING_ODD, GL_GLU_TESS_ERROR1, GL_GLU_TESS_ERROR6, GL_GLU_OUTLINE_PATCH, GL_GLU_VERSION, GL_GLU_OBJECT_PARAMETRIC_ERROR_EXT, GL_GLU_SAMPLING_METHOD, GL_GLU_NURBS_TEX_COORD_EXT, GL_GLU_TESS_VERTEX, GL_GLU_POINT, GL_GLU_FALSE, GL_GLU_NURBS_VERTEX_EXT, GL_GLU_NURBS_BEGIN_DATA_EXT, GL_GLU_TESS_EDGE_FLAG_DATA, GL_GLU_FILL, GL_GLU_OBJECT_PATH_LENGTH, GL_GLU_NURBS_ERROR30, GL_GLU_SMOOTH, GL_GLU_CW, GL_GLU_TESS_END_DATA, GL_GLU_NURBS_ERROR15, GL_GLU_NURBS_ERROR27, GL_GLU_NURBS_ERROR22, GL_GLU_NURBS_ERROR32, GL_GLU_EXTERIOR, GL_GLU_TESS_ERROR4, GL_GLU_NURBS_ERROR13, GL_GLU_DOMAIN_DISTANCE, GL_GLU_NURBS_ERROR34, GL_GLU_NURBS_ERROR23, GL_GLU_NURBS_ERROR4, GL_GLU_NURBS_COLOR_DATA_EXT, GL_GLU_NURBS_ERROR8, GL_GLU_NURBS_COLOR_EXT, GL_GLU_NURBS_ERROR31, GL_GLU_NURBS_ERROR2, GL_GLU_NURBS_ERROR28, GL_GLU_TESS_WINDING_ABS_GEQ_TWO, GL_GLU_NURBS_ERROR11, GL_GLU_NURBS_END_DATA_EXT, GL_GLU_NURBS_ERROR37, GL_GLU_UNKNOWN, GL_GLU_BEGIN, GL_GLU_NURBS_ERROR24, GL_GLU_OBJECT_PATH_LENGTH_EXT, GL_GLU_ERROR, GL_GLU_TESS_VERTEX_DATA, GL_GLU_TESS_ERROR7, GL_GLU_NURBS_NORMAL_DATA_EXT, GL_GLU_TESS_COORD_TOO_LARGE, GL_GLU_NURBS_BEGIN_DATA, GL_GLU_NURBS_VERTEX_DATA_EXT, GL_GLU_NURBS_TEXTURE_COORD, GL_GLU_NURBS_NORMAL_DATA, GL_GLU_NURBS_ERROR10, GL_GLU_TESS_MISSING_BEGIN_POLYGON, GL_GLU_NURBS_END, GL_GLU_NURBS_ERROR5, GL_GLU_END, GL_GLU_TESS_WINDING_NONZERO, GL_GLU_TESS_MAX_COORD, GL_GLU_NURBS_ERROR35, GL_GLU_TESS_COMBINE_DATA, GL_GLU_TESS_WINDING_RULE, GL_GLU_NURBS_ERROR3, GL_GLU_NURBS_RENDERER_EXT, GL_GLU_TESS_TOLERANCE, GL_GLU_FLAT, GL_GLU_PARAMETRIC_TOLERANCE, GL_GLU_INVALID_OPERATION, GL_GLU_NURBS_MODE_EXT, GL_GLU_NURBS_TESSELLATOR, GL_GLU_TESS_COMBINE, GL_GLU_INCOMPATIBLE_GL_VERSION, GL_GLU_VERSION_1_2, GL_GLU_NURBS_ERROR14, GL_GLU_MAP1_TRIM_2, GL_GLU_OUT_OF_MEMORY, GL_GLU_NURBS_COLOR, GL_GLU_NURBS_BEGIN, GL_GLU_U_STEP
