#all OpenGL Types
typealias uint_least64_t                                              Uint64
typealias uint_least16_t                                              Uint16
typealias uint_fast32_t                                               Uint64
typealias int_fast8_t                                                 Uint8
typealias int_fast16_t                                                Int64
typealias int_least64_t                                               Int64
typealias GLubyte                                                     Cuchar
typealias int16_t                                                     Int16
typealias GLfloat                                                     Cfloat
typealias int8_t                                                      Uint8
typealias GLenum                                                      Cuint
typealias GLboolean                                                   Cuchar
typealias uint16_t                                                    Uint16
typealias GLclampd                                                    Cdouble
typealias GLvoid                                                      Void
typealias uint_fast8_t                                                Uint8
typealias int64_t                                                     Int64
typealias int_fast64_t                                                Int64
typealias uint32_t                                                    Uint32
typealias GLint                                                       Cint
typealias uint_least32_t                                              Uint32
typealias GLsizeiptr                                                  Cint
typealias ptrdiff_t                                                   Int64
typealias int_least32_t                                               Int32
typealias GLcharARB                                                   Uint8
typealias GLuint                                                      Cuint
typealias GLbyte                                                      Cuchar
typealias size_t                                                      Int64
typealias GLchar                                                      Cchar
typealias uintptr_t                                                   Uint64
typealias GLclampf                                                    Cfloat
typealias GLbitfield                                                  Cuint
typealias uint_least8_t                                               Uint8
typealias GLhandleARB                                                 Uint32
typealias GLeglImageOES                                               Ptr
typealias Pointer                                                     Ptr{Void}
typealias GLdouble                                                    Cdouble
typealias int_least8_t                                                Uint8
typealias uint64_t                                                    Uint64
typealias GLushort                                                    Cushort
typealias uint8_t                                                     Uint8
typealias int_fast32_t                                                Int64
typealias intmax_t                                                    Int64
typealias wchar_t                                                     Int32
typealias GLhalfARB                                                   Cushort
typealias GLhalf                                                      Cushort
typealias intptr_t                                                    Int64
typealias GLsizei                                                     Csize_t
typealias GLuint64                                                    Culonglong
typealias uintmax_t                                                   Uint64
typealias uint_fast16_t                                               Uint64
typealias int32_t                                                     Int32
typealias __gwchar_t                                                  Int32
typealias GLintptrARB                                                 ptrdiff_t
typealias GLhalfNV                                                    Cushort
typealias GLshort                                                     Cshort
typealias GLint64                                                     Clonglong
typealias int_least16_t                                               Int16
typealias GLintptr                                                    Cptrdiff_t
typealias uint_fast64_t                                               Uint64
typealias GLsync                                                      Ptr{Void}
typealias GLsizeiptrARB                                               ptrdiff_t
typealias GLint64EXT                                                  int64_t
typealias GLuint64EXT                                                 uint64_t
typealias GLvdpauSurfaceNV                                            GLintptr
export uint_least64_t, uint_least16_t, uint_fast32_t, int_fast8_t, int_fast16_t, int_least64_t, GLubyte, int16_t, GLfloat, int8_t, GLenum, GLboolean, uint16_t, GLclampd, GLvoid, uint_fast8_t, int64_t, int_fast64_t, uint32_t, GLint, uint_least32_t, GLsizeiptr, ptrdiff_t, int_least32_t, GLcharARB, GLuint, GLbyte, size_t, GLchar, uintptr_t, GLclampf, GLbitfield, uint_least8_t, GLhandleARB, GLeglImageOES, Pointer, GLdouble, int_least8_t, uint64_t, GLushort, uint8_t, int_fast32_t, intmax_t, wchar_t, GLhalfARB, GLhalf, intptr_t, GLsizei, GLuint64, uintmax_t, uint_fast16_t, int32_t, __gwchar_t, GLintptrARB, GLhalfNV, GLshort, GLint64, int_least16_t, GLintptr, uint_fast64_t, GLsync, GLsizeiptrARB, GLint64EXT, GLuint64EXT, GLvdpauSurfaceNV
