#Types, functions and constants, needed on top of the common ones
#types
const GL_ATI_TYPES = [
]
#constants
const GL_ATI_CONSTANTS = [
:(const LUMINANCE_FLOAT32_ATI                                           = 0x8818),
:(const PN_TRIANGLES_ATI                                                = 0x87F0),
:(const REG_0_ATI                                                       = 0x8921),
:(const REG_1_ATI                                                       = 0x8922),
:(const PRESERVE_ATI                                                    = 0x8762),
:(const LUMINANCE_ALPHA_FLOAT16_ATI                                     = 0x881F),
:(const DRAW_BUFFER7_ATI                                                = 0x882C),
:(const MAX_PN_TRIANGLES_TESSELATION_LEVEL_ATI                          = 0x87F1),
:(const STENCIL_BACK_FAIL_ATI                                           = 0x8801),
:(const REG_25_ATI                                                      = 0x893A),
:(const CON_12_ATI                                                      = 0x894D),
:(const NUM_INSTRUCTIONS_TOTAL_ATI                                      = 0x8972),
:(const ADD_ATI                                                         = 0x8963),
:(const BLUE_BIT_ATI                                                    = 0x00000004),
:(const VERTEX_STREAM6_ATI                                              = 0x8772),
:(const RENDERBUFFER_FREE_MEMORY_ATI                                    = 0x87FD),
:(const DYNAMIC_ATI                                                     = 0x8761),
:(const DRAW_BUFFER15_ATI                                               = 0x8834),
:(const EIGHTH_BIT_ATI                                                  = 0x00000020),
:(const ALPHA_FLOAT32_ATI                                               = 0x8816),
:(const REG_8_ATI                                                       = 0x8929),
:(const PN_TRIANGLES_NORMAL_MODE_LINEAR_ATI                             = 0x87F7),
:(const DOT4_ATI                                                        = 0x8967),
:(const DRAW_BUFFER10_ATI                                               = 0x882F),
:(const TEXT_FRAGMENT_SHADER_ATI                                        = 0x8200),
:(const SWIZZLE_STR_DR_ATI                                              = 0x8978),
:(const GREEN_BIT_ATI                                                   = 0x00000002),
:(const CND0_ATI                                                        = 0x896B),
:(const REG_29_ATI                                                      = 0x893E),
:(const MIRROR_CLAMP_ATI                                                = 0x8742),
:(const CON_29_ATI                                                      = 0x895E),
:(const SWIZZLE_STRQ_DQ_ATI                                             = 0x897B),
:(const BUMP_ROT_MATRIX_SIZE_ATI                                        = 0x8776),
:(const CON_30_ATI                                                      = 0x895F),
:(const REG_10_ATI                                                      = 0x892B),
:(const RGBA_FLOAT16_ATI                                                = 0x881A),
:(const CON_2_ATI                                                       = 0x8943),
:(const DRAW_BUFFER9_ATI                                                = 0x882E),
:(const DRAW_BUFFER2_ATI                                                = 0x8827),
:(const DRAW_BUFFER8_ATI                                                = 0x882D),
:(const STENCIL_BACK_PASS_DEPTH_FAIL_ATI                                = 0x8802),
:(const PN_TRIANGLES_NORMAL_MODE_QUADRATIC_ATI                          = 0x87F8),
:(const SWIZZLE_STRQ_ATI                                                = 0x897A),
:(const CON_20_ATI                                                      = 0x8955),
:(const REG_7_ATI                                                       = 0x8928),
:(const PN_TRIANGLES_NORMAL_MODE_ATI                                    = 0x87F3),
:(const CON_1_ATI                                                       = 0x8942),
:(const ELEMENT_ARRAY_ATI                                               = 0x8768),
:(const CON_7_ATI                                                       = 0x8948),
:(const REG_14_ATI                                                      = 0x892F),
:(const COMP_BIT_ATI                                                    = 0x00000002),
:(const REG_17_ATI                                                      = 0x8932),
:(const LERP_ATI                                                        = 0x8969),
:(const RGB_FLOAT16_ATI                                                 = 0x881B),
:(const CON_14_ATI                                                      = 0x894F),
:(const DRAW_BUFFER0_ATI                                                = 0x8825),
:(const ALPHA_FLOAT16_ATI                                               = 0x881C),
:(const BUMP_TEX_UNITS_ATI                                              = 0x8778),
:(const REG_18_ATI                                                      = 0x8933),
:(const REG_20_ATI                                                      = 0x8935),
:(const MODULATE_SIGNED_ADD_ATI                                         = 0x8745),
:(const LUMINANCE_ALPHA_FLOAT32_ATI                                     = 0x8819),
:(const NUM_INSTRUCTIONS_PER_PASS_ATI                                   = 0x8971),
:(const CON_27_ATI                                                      = 0x895C),
:(const SUB_ATI                                                         = 0x8965),
:(const VBO_FREE_MEMORY_ATI                                             = 0x87FB),
:(const X2X_BIT_ATI                                                     = 0x00000001),
:(const INTENSITY_FLOAT32_ATI                                           = 0x8817),
:(const PN_TRIANGLES_POINT_MODE_ATI                                     = 0x87F2),
:(const PN_TRIANGLES_POINT_MODE_LINEAR_ATI                              = 0x87F5),
:(const CON_18_ATI                                                      = 0x8953),
:(const OBJECT_BUFFER_SIZE_ATI                                          = 0x8764),
:(const X4X_BIT_ATI                                                     = 0x00000002),
:(const MODULATE_SUBTRACT_ATI                                           = 0x8746),
:(const BUMP_NUM_TEX_UNITS_ATI                                          = 0x8777),
:(const OBJECT_BUFFER_USAGE_ATI                                         = 0x8765),
:(const REG_6_ATI                                                       = 0x8927),
:(const CON_24_ATI                                                      = 0x8959),
:(const REG_19_ATI                                                      = 0x8934),
:(const DRAW_BUFFER4_ATI                                                = 0x8829),
:(const DISCARD_ATI                                                     = 0x8763),
:(const HALF_BIT_ATI                                                    = 0x00000008),
:(const DRAW_BUFFER6_ATI                                                = 0x882B),
:(const BUMP_TARGET_ATI                                                 = 0x877C),
:(const STENCIL_BACK_PASS_DEPTH_PASS_ATI                                = 0x8803),
:(const DUDV_ATI                                                        = 0x8779),
:(const SECONDARY_INTERPOLATOR_ATI                                      = 0x896D),
:(const CON_13_ATI                                                      = 0x894E),
:(const REG_31_ATI                                                      = 0x8940),
:(const BUMP_ENVMAP_ATI                                                 = 0x877B),
:(const REG_21_ATI                                                      = 0x8936),
:(const SWIZZLE_STQ_ATI                                                 = 0x8977),
:(const DRAW_BUFFER1_ATI                                                = 0x8826),
:(const DRAW_BUFFER12_ATI                                               = 0x8831),
:(const CON_17_ATI                                                      = 0x8952),
:(const DRAW_BUFFER11_ATI                                               = 0x8830),
:(const CON_3_ATI                                                       = 0x8944),
:(const RGBA_FLOAT_MODE_ATI                                             = 0x8820),
:(const REG_12_ATI                                                      = 0x892D),
:(const RGB_FLOAT32_ATI                                                 = 0x8815),
:(const CON_10_ATI                                                      = 0x894B),
:(const REG_30_ATI                                                      = 0x893F),
:(const DRAW_BUFFER13_ATI                                               = 0x8832),
:(const MAX_DRAW_BUFFERS_ATI                                            = 0x8824),
:(const SWIZZLE_STQ_DQ_ATI                                              = 0x8979),
:(const INTENSITY_FLOAT16_ATI                                           = 0x881D),
:(const SATURATE_BIT_ATI                                                = 0x00000040),
:(const VERTEX_STREAM7_ATI                                              = 0x8773),
:(const RED_BIT_ATI                                                     = 0x00000001),
:(const REG_15_ATI                                                      = 0x8930),
:(const ARRAY_OBJECT_OFFSET_ATI                                         = 0x8767),
:(const VERTEX_STREAM5_ATI                                              = 0x8771),
:(const CND_ATI                                                         = 0x896A),
:(const ELEMENT_ARRAY_POINTER_ATI                                       = 0x876A),
:(const REG_3_ATI                                                       = 0x8924),
:(const REG_22_ATI                                                      = 0x8937),
:(const MUL_ATI                                                         = 0x8964),
:(const REG_27_ATI                                                      = 0x893C),
:(const NUM_FRAGMENT_REGISTERS_ATI                                      = 0x896E),
:(const REG_26_ATI                                                      = 0x893B),
:(const REG_5_ATI                                                       = 0x8926),
:(const FRAGMENT_SHADER_ATI                                             = 0x8920),
:(const CON_26_ATI                                                      = 0x895B),
:(const DRAW_BUFFER3_ATI                                                = 0x8828),
:(const REG_24_ATI                                                      = 0x8939),
:(const NUM_INPUT_INTERPOLATOR_COMPONENTS_ATI                           = 0x8973),
:(const VERTEX_STREAM3_ATI                                              = 0x876F),
:(const DU8DV8_ATI                                                      = 0x877A),
:(const REG_28_ATI                                                      = 0x893D),
:(const CON_16_ATI                                                      = 0x8951),
:(const CON_23_ATI                                                      = 0x8958),
:(const STATIC_ATI                                                      = 0x8760),
:(const RGBA_FLOAT32_ATI                                                = 0x8814),
:(const MOV_ATI                                                         = 0x8961),
:(const CON_15_ATI                                                      = 0x8950),
:(const DOT2_ADD_ATI                                                    = 0x896C),
:(const REG_13_ATI                                                      = 0x892E),
:(const QUARTER_BIT_ATI                                                 = 0x00000010),
:(const VERTEX_STREAM2_ATI                                              = 0x876E),
:(const PN_TRIANGLES_POINT_MODE_CUBIC_ATI                               = 0x87F6),
:(const REG_16_ATI                                                      = 0x8931),
:(const X8X_BIT_ATI                                                     = 0x00000004),
:(const TEXTURE_FREE_MEMORY_ATI                                         = 0x87FC),
:(const BUMP_ROT_MATRIX_ATI                                             = 0x8775),
:(const REG_9_ATI                                                       = 0x892A),
:(const CON_28_ATI                                                      = 0x895D),
:(const CON_0_ATI                                                       = 0x8941),
:(const NEGATE_BIT_ATI                                                  = 0x00000004),
:(const NUM_PASSES_ATI                                                  = 0x8970),
:(const DOT3_ATI                                                        = 0x8966),
:(const CON_8_ATI                                                       = 0x8949),
:(const MODULATE_ADD_ATI                                                = 0x8744),
:(const SWIZZLE_STR_ATI                                                 = 0x8976),
:(const CON_5_ATI                                                       = 0x8946),
:(const NUM_FRAGMENT_CONSTANTS_ATI                                      = 0x896F),
:(const STENCIL_BACK_FUNC_ATI                                           = 0x8800),
:(const LUMINANCE_FLOAT16_ATI                                           = 0x881E),
:(const CON_31_ATI                                                      = 0x8960),
:(const CON_25_ATI                                                      = 0x895A),
:(const DRAW_BUFFER14_ATI                                               = 0x8833),
:(const NUM_LOOPBACK_COMPONENTS_ATI                                     = 0x8974),
:(const BIAS_BIT_ATI                                                    = 0x00000008),
:(const CON_6_ATI                                                       = 0x8947),
:(const VERTEX_STREAM1_ATI                                              = 0x876D),
:(const CON_11_ATI                                                      = 0x894C),
:(const CON_22_ATI                                                      = 0x8957),
:(const COLOR_CLEAR_UNCLAMPED_VALUE_ATI                                 = 0x8835),
:(const VERTEX_STREAM4_ATI                                              = 0x8770),
:(const CON_21_ATI                                                      = 0x8956),
:(const MAD_ATI                                                         = 0x8968),
:(const MAX_VERTEX_STREAMS_ATI                                          = 0x876B),
:(const PN_TRIANGLES_TESSELATION_LEVEL_ATI                              = 0x87F4),
:(const CON_4_ATI                                                       = 0x8945),
:(const REG_2_ATI                                                       = 0x8923),
:(const COLOR_ALPHA_PAIRING_ATI                                         = 0x8975),
:(const REG_11_ATI                                                      = 0x892C),
:(const REG_4_ATI                                                       = 0x8925),
:(const MIRROR_CLAMP_TO_EDGE_ATI                                        = 0x8743),
:(const REG_23_ATI                                                      = 0x8938),
:(const CON_9_ATI                                                       = 0x894A),
:(const ARRAY_OBJECT_BUFFER_ATI                                         = 0x8766),
:(const DRAW_BUFFER5_ATI                                                = 0x882A),
:(const CON_19_ATI                                                      = 0x8954),
:(const VERTEX_SOURCE_ATI                                               = 0x8774),
:(const VERTEX_STREAM0_ATI                                              = 0x876C),
:(const ELEMENT_ARRAY_TYPE_ATI                                          = 0x8769)]
#function bodies
const GL_ATI_FUNCTIONS = [
:(glDrawRangeElementArrayATI(mode::GLenum, start::GLuint, END::GLuint, count::GLsizei)::Void),
:(glColorFragmentOp1ATI(op::GLenum, dst::GLuint, dstMask::GLuint, dstMod::GLuint, arg1::GLuint, arg1Rep::GLuint, arg1Mod::GLuint)::Void),
:(glVertexStream4sATI(stream::GLenum, x::GLshort, y::GLshort, z::GLshort, w::GLshort)::Void),
:(glVertexBlendEnvfATI(pname::GLenum, param::GLfloat)::Void),
:(glVertexStream2sATI(stream::GLenum, x::GLshort, y::GLshort)::Void),
:(glNormalStream3fATI(stream::GLenum, nx::GLfloat, ny::GLfloat, nz::GLfloat)::Void),
:(glMapObjectBufferATI(buffer::GLuint)::Ptr{Void}),
:(glVertexStream4iATI(stream::GLenum, x::GLint, y::GLint, z::GLint, w::GLint)::Void),
:(glGetArrayObjectivATI(array::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexStream2dATI(stream::GLenum, x::GLdouble, y::GLdouble)::Void),
:(glNormalStream3fvATI(stream::GLenum, coords::Ptr{GLfloat})::Void),
:(glVertexStream4dATI(stream::GLenum, x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glVertexStream3ivATI(stream::GLenum, coords::Ptr{GLint})::Void),
:(glAlphaFragmentOp3ATI(op::GLenum, dst::GLuint, dstMod::GLuint, arg1::GLuint, arg1Rep::GLuint, arg1Mod::GLuint, arg2::GLuint, arg2Rep::GLuint, arg2Mod::GLuint, arg3::GLuint, arg3Rep::GLuint, arg3Mod::GLuint)::Void),
:(glVertexStream4ivATI(stream::GLenum, coords::Ptr{GLint})::Void),
:(glVertexStream3fvATI(stream::GLenum, coords::Ptr{GLfloat})::Void),
:(glVertexStream1fATI(stream::GLenum, x::GLfloat)::Void),
:(glStencilOpSeparateATI(face::GLenum, sfail::GLenum, dpfail::GLenum, dppass::GLenum)::Void),
:(glGetObjectBufferfvATI(buffer::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glVertexStream3sATI(stream::GLenum, x::GLshort, y::GLshort, z::GLshort)::Void),
:(glVertexStream4dvATI(stream::GLenum, coords::Ptr{GLdouble})::Void),
:(glGenFragmentShadersATI(range_::GLuint)::Cuint),
:(glVertexStream1svATI(stream::GLenum, coords::Ptr{GLshort})::Void),
:(glDrawElementArrayATI(mode::GLenum, count::GLsizei)::Void),
:(glGetArrayObjectfvATI(array::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glAlphaFragmentOp1ATI(op::GLenum, dst::GLuint, dstMod::GLuint, arg1::GLuint, arg1Rep::GLuint, arg1Mod::GLuint)::Void),
:(glUpdateObjectBufferATI(buffer::GLuint, offset::GLuint, size::GLsizei, pointer::Ptr{Void}, preserve::GLenum)::Void),
:(glVertexStream2svATI(stream::GLenum, coords::Ptr{GLshort})::Void),
:(glVertexStream3dvATI(stream::GLenum, coords::Ptr{GLdouble})::Void),
:(glVertexBlendEnviATI(pname::GLenum, param::GLint)::Void),
:(glDeleteFragmentShaderATI(id::GLuint)::Void),
:(glPNTrianglesfATI(pname::GLenum, param::GLfloat)::Void),
:(glNewObjectBufferATI(size::GLsizei, pointer::Ptr{Void}, usage::GLenum)::Cuint),
:(glUnmapObjectBufferATI(buffer::GLuint)::Void),
:(glGetTexBumpParameterfvATI(pname::GLenum, param::Ptr{GLfloat})::Void),
:(glVertexStream2ivATI(stream::GLenum, coords::Ptr{GLint})::Void),
:(glNormalStream3sATI(stream::GLenum, nx::GLshort, ny::GLshort, nz::GLshort)::Void),
:(glGetVariantArrayObjectivATI(id::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glArrayObjectATI(array::GLenum, size::GLint, type_::GLenum, stride::GLsizei, buffer::GLuint, offset::GLuint)::Void),
:(glVertexStream3dATI(stream::GLenum, x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glGetVertexAttribArrayObjectfvATI(index::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glNormalStream3bATI(stream::GLenum, nx::GLbyte, ny::GLbyte, nz::GLbyte)::Void),
:(glBindFragmentShaderATI(id::GLuint)::Void),
:(glColorFragmentOp2ATI(op::GLenum, dst::GLuint, dstMask::GLuint, dstMod::GLuint, arg1::GLuint, arg1Rep::GLuint, arg1Mod::GLuint, arg2::GLuint, arg2Rep::GLuint, arg2Mod::GLuint)::Void),
:(glDrawBuffersATI(n::GLsizei, bufs::Ptr{GLenum})::Void),
:(glNormalStream3dvATI(stream::GLenum, coords::Ptr{GLdouble})::Void),
:(glTexBumpParameterfvATI(pname::GLenum, param::Ptr{GLfloat})::Void),
:(glVertexAttribArrayObjectATI(index::GLuint, size::GLint, type_::GLenum, normalized::GLboolean, stride::GLsizei, buffer::GLuint, offset::GLuint)::Void),
:(glGetObjectBufferivATI(buffer::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glClientActiveVertexStreamATI(stream::GLenum)::Void),
:(glElementPointerATI(type_::GLenum, pointer::Ptr{Void})::Void),
:(glTexBumpParameterivATI(pname::GLenum, param::Ptr{GLint})::Void),
:(glGetVariantArrayObjectfvATI(id::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glGetTexBumpParameterivATI(pname::GLenum, param::Ptr{GLint})::Void),
:(glColorFragmentOp3ATI(op::GLenum, dst::GLuint, dstMask::GLuint, dstMod::GLuint, arg1::GLuint, arg1Rep::GLuint, arg1Mod::GLuint, arg2::GLuint, arg2Rep::GLuint, arg2Mod::GLuint, arg3::GLuint, arg3Rep::GLuint, arg3Mod::GLuint)::Void),
:(glPassTexCoordATI(dst::GLuint, coord::GLuint, swizzle::GLenum)::Void),
:(glNormalStream3iATI(stream::GLenum, nx::GLint, ny::GLint, nz::GLint)::Void),
:(glNormalStream3svATI(stream::GLenum, coords::Ptr{GLshort})::Void),
:(glVertexStream2dvATI(stream::GLenum, coords::Ptr{GLdouble})::Void),
:(glSampleMapATI(dst::GLuint, interp::GLuint, swizzle::GLenum)::Void),
:(glVertexStream1dvATI(stream::GLenum, coords::Ptr{GLdouble})::Void),
:(glFreeObjectBufferATI(buffer::GLuint)::Void),
:(glVertexStream1sATI(stream::GLenum, x::GLshort)::Void),
:(glVertexStream1dATI(stream::GLenum, x::GLdouble)::Void),
:(glVertexStream2fATI(stream::GLenum, x::GLfloat, y::GLfloat)::Void),
:(glVertexStream3svATI(stream::GLenum, coords::Ptr{GLshort})::Void),
:(glVertexStream3fATI(stream::GLenum, x::GLfloat, y::GLfloat, z::GLfloat)::Void),
:(glVertexStream3iATI(stream::GLenum, x::GLint, y::GLint, z::GLint)::Void),
:(glNormalStream3bvATI(stream::GLenum, coords::Ptr{GLbyte})::Void),
:(glSetFragmentShaderConstantATI(dst::GLuint, value::Ptr{GLfloat})::Void),
:(glIsObjectBufferATI(buffer::GLuint)::Bool),
:(glPNTrianglesiATI(pname::GLenum, param::GLint)::Void),
:(glVertexStream4fATI(stream::GLenum, x::GLfloat, y::GLfloat, z::GLfloat, w::GLfloat)::Void),
:(glVertexStream2iATI(stream::GLenum, x::GLint, y::GLint)::Void),
:(glVertexStream1iATI(stream::GLenum, x::GLint)::Void),
:(glVertexStream1fvATI(stream::GLenum, coords::Ptr{GLfloat})::Void),
:(glNormalStream3dATI(stream::GLenum, nx::GLdouble, ny::GLdouble, nz::GLdouble)::Void),
:(glNormalStream3ivATI(stream::GLenum, coords::Ptr{GLint})::Void),
:(glStencilFuncSeparateATI(frontfunc::GLenum, backfunc::GLenum, ref::GLint, mask::GLuint)::Void),
:(glVertexStream2fvATI(stream::GLenum, coords::Ptr{GLfloat})::Void),
:(glGetVertexAttribArrayObjectivATI(index::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexStream1ivATI(stream::GLenum, coords::Ptr{GLint})::Void),
:(glVertexStream4fvATI(stream::GLenum, coords::Ptr{GLfloat})::Void),
:(glAlphaFragmentOp2ATI(op::GLenum, dst::GLuint, dstMod::GLuint, arg1::GLuint, arg1Rep::GLuint, arg1Mod::GLuint, arg2::GLuint, arg2Rep::GLuint, arg2Mod::GLuint)::Void),
:(glVariantArrayObjectATI(id::GLuint, type_::GLenum, stride::GLsizei, buffer::GLuint, offset::GLuint)::Void),
:(glVertexStream4svATI(stream::GLenum, coords::Ptr{GLshort})::Void)]
