#Types, functions and constants, needed on top of the common ones
#types
const GL_GL21_TYPES = [
]
#constants
const GL_GL21_CONSTANTS = [
]
#function bodies
const GL_GL21_FUNCTIONS = [
:(glMultTransposeMatrixd(m::Ptr{GLdouble})::Void),
:(glRasterPos2i(x::GLint, y::GLint)::Void),
:(glLoadTransposeMatrixf(m::Ptr{GLfloat})::Void),
:(glMap1f(target::GLenum, u1::GLfloat, u2::GLfloat, stride::GLint, order::GLint, points::Ptr{GLfloat})::Void),
:(glMultiTexCoord2d(target::GLenum, s::GLdouble, t::GLdouble)::Void),
:(glWindowPos3i(x::GLint, y::GLint, z::GLint)::Void),
:(glLightfv(light::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glTexCoord2i(s::GLint, t::GLint)::Void),
:(glFogfv(pname::GLenum, params::Ptr{GLfloat})::Void),
:(glLightModelfv(pname::GLenum, params::Ptr{GLfloat})::Void),
:(glColorTableParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glRasterPos3iv(v::Ptr{GLint})::Void),
:(glFogf(pname::GLenum, param::GLfloat)::Void),
:(glRasterPos4i(x::GLint, y::GLint, z::GLint, w::GLint)::Void),
:(glMultiTexCoord3iv(target::GLenum, v::Ptr{GLint})::Void),
:(glVertex4sv(v::Ptr{GLshort})::Void),
:(glCallList(list::GLuint)::Void),
:(glNormalPointer(type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glRectdv(v1::Ptr{GLdouble}, v2::Ptr{GLdouble})::Void),
:(glMultiTexCoord4d(target::GLenum, s::GLdouble, t::GLdouble, r::GLdouble, q::GLdouble)::Void),
:(glTexEnvi(target::GLenum, pname::GLenum, param::GLint)::Void),
:(glWindowPos2fv(v::Ptr{GLfloat})::Void),
:(glPopAttrib()::Void),
:(glPixelTransferf(pname::GLenum, param::GLfloat)::Void),
:(glTexCoordPointer(size::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glGetConvolutionParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertex2dv(v::Ptr{GLdouble})::Void),
:(glTexGendv(coord::GLenum, pname::GLenum, params::Ptr{GLdouble})::Void),
:(glVertexAttrib4Niv(index::GLuint, v::Ptr{GLint})::Void),
:(glTexCoord4i(s::GLint, t::GLint, r::GLint, q::GLint)::Void),
:(glFogi(pname::GLenum, param::GLint)::Void),
:(glConvolutionFilter1D(target::GLenum, internalformat::GLenum, width::GLsizei, format::GLenum, type_::GLenum, image::Ptr{Void})::Void),
:(glVertex4iv(v::Ptr{GLint})::Void),
:(glPopClientAttrib()::Void),
:(glMultiTexCoord2s(target::GLenum, s::GLshort, t::GLshort)::Void),
:(glTexCoord2f(s::GLfloat, t::GLfloat)::Void),
:(glGetLightiv(light::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glMultiTexCoord4fv(target::GLenum, v::Ptr{GLfloat})::Void),
:(glTexGenf(coord::GLenum, pname::GLenum, param::GLfloat)::Void),
:(glEvalCoord1d(u::GLdouble)::Void),
:(glVertexAttrib2dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glMap1d(target::GLenum, u1::GLdouble, u2::GLdouble, stride::GLint, order::GLint, points::Ptr{GLdouble})::Void),
:(glTranslatef(x::GLfloat, y::GLfloat, z::GLfloat)::Void),
:(glMultiTexCoord2dv(target::GLenum, v::Ptr{GLdouble})::Void),
:(glEnableClientState(array::GLenum)::Void),
:(glConvolutionParameteri(target::GLenum, pname::GLenum, params::GLint)::Void),
:(glScalef(x::GLfloat, y::GLfloat, z::GLfloat)::Void),
:(glEnd()::Void),
:(glGetMapiv(target::GLenum, query::GLenum, v::Ptr{GLint})::Void),
:(glIndexMask(mask::GLuint)::Void),
:(glVertexAttrib3d(index::GLuint, x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glColor3iv(v::Ptr{GLint})::Void),
:(glFogCoorddv(coord::Ptr{GLdouble})::Void),
:(glVertex4i(x::GLint, y::GLint, z::GLint, w::GLint)::Void),
:(glRecti(x1::GLint, y1::GLint, x2::GLint, y2::GLint)::Void),
:(glRasterPos2iv(v::Ptr{GLint})::Void),
:(glColor3fv(v::Ptr{GLfloat})::Void),
:(glRasterPos4fv(v::Ptr{GLfloat})::Void),
:(glPixelMapfv(map_::GLenum, mapsize::GLsizei, values::Ptr{GLfloat})::Void),
:(glVertexAttrib4s(index::GLuint, x::GLshort, y::GLshort, z::GLshort, w::GLshort)::Void),
:(glVertex3sv(v::Ptr{GLshort})::Void),
:(glRectfv(v1::Ptr{GLfloat}, v2::Ptr{GLfloat})::Void),
:(glVertexAttrib2sv(index::GLuint, v::Ptr{GLshort})::Void),
:(glTexCoord1d(s::GLdouble)::Void),
:(glVertex2i(x::GLint, y::GLint)::Void),
:(glColorMaterial(face::GLenum, mode::GLenum)::Void),
:(glMultiTexCoord2sv(target::GLenum, v::Ptr{GLshort})::Void),
:(glColor3dv(v::Ptr{GLdouble})::Void),
:(glVertexAttrib4sv(index::GLuint, v::Ptr{GLshort})::Void),
:(glSecondaryColor3bv(v::Ptr{GLbyte})::Void),
:(glVertexAttrib3fv(index::GLuint, v::Ptr{GLfloat})::Void),
:(glRectf(x1::GLfloat, y1::GLfloat, x2::GLfloat, y2::GLfloat)::Void),
:(glTexCoord4sv(v::Ptr{GLshort})::Void),
:(glEvalCoord2f(u::GLfloat, v::GLfloat)::Void),
:(glColor4i(red::GLint, green::GLint, blue::GLint, alpha::GLint)::Void),
:(glMultiTexCoord2f(target::GLenum, s::GLfloat, t::GLfloat)::Void),
:(glColor3s(red::GLshort, green::GLshort, blue::GLshort)::Void),
:(glSecondaryColor3us(red::GLushort, green::GLushort, blue::GLushort)::Void),
:(glEvalCoord2fv(u::Ptr{GLfloat})::Void),
:(glVertex2d(x::GLdouble, y::GLdouble)::Void),
:(glTexGeni(coord::GLenum, pname::GLenum, param::GLint)::Void),
:(glWindowPos3iv(v::Ptr{GLint})::Void),
:(glMapGrid1f(un::GLint, u1::GLfloat, u2::GLfloat)::Void),
:(glMapGrid2d(un::GLint, u1::GLdouble, u2::GLdouble, vn::GLint, v1::GLdouble, v2::GLdouble)::Void),
:(glVertexAttrib2fv(index::GLuint, v::Ptr{GLfloat})::Void),
:(glTexCoord1i(s::GLint)::Void),
:(glRasterPos4dv(v::Ptr{GLdouble})::Void),
:(glTexEnvf(target::GLenum, pname::GLenum, param::GLfloat)::Void),
:(glMultiTexCoord3s(target::GLenum, s::GLshort, t::GLshort, r::GLshort)::Void),
:(glHistogram(target::GLenum, width::GLsizei, internalformat::GLenum, sink::GLboolean)::Void),
:(glIndexdv(c::Ptr{GLdouble})::Void),
:(glColor3us(red::GLushort, green::GLushort, blue::GLushort)::Void),
:(glSecondaryColor3uiv(v::Ptr{GLuint})::Void),
:(glRasterPos2s(x::GLshort, y::GLshort)::Void),
:(glVertex4s(x::GLshort, y::GLshort, z::GLshort, w::GLshort)::Void),
:(glPixelZoom(xfactor::GLfloat, yfactor::GLfloat)::Void),
:(glGetMinmaxParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glRasterPos4s(x::GLshort, y::GLshort, z::GLshort, w::GLshort)::Void),
:(glVertex3dv(v::Ptr{GLdouble})::Void),
:(glLoadMatrixd(m::Ptr{GLdouble})::Void),
:(glMaterialfv(face::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glVertexAttrib4Nbv(index::GLuint, v::Ptr{GLbyte})::Void),
:(glEvalCoord1dv(u::Ptr{GLdouble})::Void),
:(glMultiTexCoord1iv(target::GLenum, v::Ptr{GLint})::Void),
:(glMapGrid2f(un::GLint, u1::GLfloat, u2::GLfloat, vn::GLint, v1::GLfloat, v2::GLfloat)::Void),
:(glEdgeFlag(flag::GLboolean)::Void),
:(glMap2d(target::GLenum, u1::GLdouble, u2::GLdouble, ustride::GLint, uorder::GLint, v1::GLdouble, v2::GLdouble, vstride::GLint, vorder::GLint, points::Ptr{GLdouble})::Void),
:(glNormal3i(nx::GLint, ny::GLint, nz::GLint)::Void),
:(glNormal3f(nx::GLfloat, ny::GLfloat, nz::GLfloat)::Void),
:(glRasterPos4f(x::GLfloat, y::GLfloat, z::GLfloat, w::GLfloat)::Void),
:(glPassThrough(token::GLfloat)::Void),
:(glPushName(name::GLuint)::Void),
:(glTexCoord1f(s::GLfloat)::Void),
:(glLoadTransposeMatrixd(m::Ptr{GLdouble})::Void),
:(glGetPixelMapusv(map_::GLenum, values::Ptr{GLushort})::Void),
:(glAlphaFunc(func_::GLenum, ref::GLfloat)::Void),
:(glNormal3b(nx::GLbyte, ny::GLbyte, nz::GLbyte)::Void),
:(glWindowPos3f(x::GLfloat, y::GLfloat, z::GLfloat)::Void),
:(glVertexAttrib1sv(index::GLuint, v::Ptr{GLshort})::Void),
:(glIndexi(c::GLint)::Void),
:(glWindowPos3d(x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glVertex2fv(v::Ptr{GLfloat})::Void),
:(glSecondaryColor3ub(red::GLubyte, green::GLubyte, blue::GLubyte)::Void),
:(glIsList(list::GLuint)::Bool),
:(glResetHistogram(target::GLenum)::Void),
:(glVertex4d(x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glGetClipPlane(plane::GLenum, equation::Ptr{GLdouble})::Void),
:(glMaterialf(face::GLenum, pname::GLenum, param::GLfloat)::Void),
:(glMultiTexCoord4s(target::GLenum, s::GLshort, t::GLshort, r::GLshort, q::GLshort)::Void),
:(glAccum(op::GLenum, value::GLfloat)::Void),
:(glTexCoord1fv(v::Ptr{GLfloat})::Void),
:(glRasterPos3s(x::GLshort, y::GLshort, z::GLshort)::Void),
:(glWindowPos3s(x::GLshort, y::GLshort, z::GLshort)::Void),
:(glFogCoordfv(coord::Ptr{GLfloat})::Void),
:(glColor3ubv(v::Ptr{GLubyte})::Void),
:(glTexCoord1iv(v::Ptr{GLint})::Void),
:(glMultiTexCoord4iv(target::GLenum, v::Ptr{GLint})::Void),
:(glGetHistogramParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glWindowPos3dv(v::Ptr{GLdouble})::Void),
:(glTexCoord4iv(v::Ptr{GLint})::Void),
:(glTexCoord2d(s::GLdouble, t::GLdouble)::Void),
:(glTexCoord3sv(v::Ptr{GLshort})::Void),
:(glColor4ubv(v::Ptr{GLubyte})::Void),
:(glMultiTexCoord3dv(target::GLenum, v::Ptr{GLdouble})::Void),
:(glVertexAttrib4d(index::GLuint, x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glVertex4dv(v::Ptr{GLdouble})::Void),
:(glColor3bv(v::Ptr{GLbyte})::Void),
:(glLightf(light::GLenum, pname::GLenum, param::GLfloat)::Void),
:(glMultiTexCoord1sv(target::GLenum, v::Ptr{GLshort})::Void),
:(glColor3uiv(v::Ptr{GLuint})::Void),
:(glVertexAttrib4dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glLightiv(light::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glTexCoord1sv(v::Ptr{GLshort})::Void),
:(glCallLists(n::GLsizei, type_::GLenum, lists::Ptr{Void})::Void),
:(glTranslated(x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glSecondaryColor3iv(v::Ptr{GLint})::Void),
:(glWindowPos3fv(v::Ptr{GLfloat})::Void),
:(glWindowPos2iv(v::Ptr{GLint})::Void),
:(glNewList(list::GLuint, mode::GLenum)::Void),
:(glTexCoord2dv(v::Ptr{GLdouble})::Void),
:(glMultiTexCoord4dv(target::GLenum, v::Ptr{GLdouble})::Void),
:(glGetLightfv(light::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glTexCoord3f(s::GLfloat, t::GLfloat, r::GLfloat)::Void),
:(glVertexAttrib4iv(index::GLuint, v::Ptr{GLint})::Void),
:(glSecondaryColor3fv(v::Ptr{GLfloat})::Void),
:(glColor3ui(red::GLuint, green::GLuint, blue::GLuint)::Void),
:(glTexCoord2iv(v::Ptr{GLint})::Void),
:(glArrayElement(i::GLint)::Void),
:(glNormal3d(nx::GLdouble, ny::GLdouble, nz::GLdouble)::Void),
:(glTexCoord3iv(v::Ptr{GLint})::Void),
:(glLoadMatrixf(m::Ptr{GLfloat})::Void),
:(glVertexAttrib1s(index::GLuint, x::GLshort)::Void),
:(glGetTexGendv(coord::GLenum, pname::GLenum, params::Ptr{GLdouble})::Void),
:(glFrustum(left::GLdouble, right::GLdouble, bottom::GLdouble, top::GLdouble, zNear::GLdouble, zFar::GLdouble)::Void),
:(glPolygonStipple(mask::Ptr{GLubyte})::Void),
:(glIndexsv(c::Ptr{GLshort})::Void),
:(glRasterPos3fv(v::Ptr{GLfloat})::Void),
:(glClientActiveTexture(texture::GLenum)::Void),
:(glSecondaryColor3dv(v::Ptr{GLdouble})::Void),
:(glPixelTransferi(pname::GLenum, param::GLint)::Void),
:(glVertexAttrib2s(index::GLuint, x::GLshort, y::GLshort)::Void),
:(glListBase(base::GLuint)::Void),
:(glGetMinmax(target::GLenum, reset::GLboolean, format::GLenum, type_::GLenum, values::Ptr{Void})::Void),
:(glRasterPos2fv(v::Ptr{GLfloat})::Void),
:(glTexCoord3d(s::GLdouble, t::GLdouble, r::GLdouble)::Void),
:(glGetColorTableParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glFogCoordPointer(type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glFogiv(pname::GLenum, params::Ptr{GLint})::Void),
:(glGetTexEnvfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glMultiTexCoord2iv(target::GLenum, v::Ptr{GLint})::Void),
:(glRasterPos4d(x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glWindowPos3sv(v::Ptr{GLshort})::Void),
:(glTexCoord3dv(v::Ptr{GLdouble})::Void),
:(glVertex2f(x::GLfloat, y::GLfloat)::Void),
:(glMultiTexCoord1f(target::GLenum, s::GLfloat)::Void),
:(glPixelMapusv(map_::GLenum, mapsize::GLsizei, values::Ptr{GLushort})::Void),
:(glPushMatrix()::Void),
:(glMultiTexCoord3d(target::GLenum, s::GLdouble, t::GLdouble, r::GLdouble)::Void),
:(glVertexAttrib4Nubv(index::GLuint, v::Ptr{GLubyte})::Void),
:(glVertexAttrib3s(index::GLuint, x::GLshort, y::GLshort, z::GLshort)::Void),
:(glGetTexGenfv(coord::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glWindowPos2dv(v::Ptr{GLdouble})::Void),
:(glMultiTexCoord4f(target::GLenum, s::GLfloat, t::GLfloat, r::GLfloat, q::GLfloat)::Void),
:(glCopyColorSubTable(target::GLenum, start::GLsizei, x::GLint, y::GLint, width::GLsizei)::Void),
:(glMultiTexCoord3f(target::GLenum, s::GLfloat, t::GLfloat, r::GLfloat)::Void),
:(glIndexfv(c::Ptr{GLfloat})::Void),
:(glTexEnvfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glClearAccum(red::GLfloat, green::GLfloat, blue::GLfloat, alpha::GLfloat)::Void),
:(glLightModeli(pname::GLenum, param::GLint)::Void),
:(glInterleavedArrays(format::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glWindowPos2sv(v::Ptr{GLshort})::Void),
:(glMinmax(target::GLenum, internalformat::GLenum, sink::GLboolean)::Void),
:(glTexGenfv(coord::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glMultTransposeMatrixf(m::Ptr{GLfloat})::Void),
:(glRects(x1::GLshort, y1::GLshort, x2::GLshort, y2::GLshort)::Void),
:(glGetPixelMapuiv(map_::GLenum, values::Ptr{GLuint})::Void),
:(glScaled(x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glRenderMode(mode::GLenum)::Cint),
:(glPrioritizeTextures(n::GLsizei, textures::Ptr{GLuint}, priorities::Ptr{GLfloat})::Void),
:(glNormal3dv(v::Ptr{GLdouble})::Void),
:(glGetColorTableParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glLightModelf(pname::GLenum, param::GLfloat)::Void),
:(glClipPlane(plane::GLenum, equation::Ptr{GLdouble})::Void),
:(glGetConvolutionParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glBitmap(width::GLsizei, height::GLsizei, xorig::GLfloat, yorig::GLfloat, xmove::GLfloat, ymove::GLfloat, bitmap::Ptr{GLubyte})::Void),
:(glNormal3sv(v::Ptr{GLshort})::Void),
:(glCopyColorTable(target::GLenum, internalformat::GLenum, x::GLint, y::GLint, width::GLsizei)::Void),
:(glGetPixelMapfv(map_::GLenum, values::Ptr{GLfloat})::Void),
:(glTexCoord2s(s::GLshort, t::GLshort)::Void),
:(glDeleteLists(list::GLuint, range_::GLsizei)::Void),
:(glColorSubTable(target::GLenum, start::GLsizei, count::GLsizei, format::GLenum, type_::GLenum, data::Ptr{Void})::Void),
:(glVertex3d(x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glTexCoord2sv(v::Ptr{GLshort})::Void),
:(glVertex3f(x::GLfloat, y::GLfloat, z::GLfloat)::Void),
:(glSelectBuffer(size::GLsizei, buffer::Ptr{GLuint})::Void),
:(glEvalPoint1(i::GLint)::Void),
:(glDrawPixels(width::GLsizei, height::GLsizei, format::GLenum, type_::GLenum, pixels::Ptr{Void})::Void),
:(glMultiTexCoord4i(target::GLenum, s::GLint, t::GLint, r::GLint, q::GLint)::Void),
:(glNormal3fv(v::Ptr{GLfloat})::Void),
:(glIndexd(c::GLdouble)::Void),
:(glVertex2iv(v::Ptr{GLint})::Void),
:(glInitNames()::Void),
:(glNormal3s(nx::GLshort, ny::GLshort, nz::GLshort)::Void),
:(glVertexAttrib4usv(index::GLuint, v::Ptr{GLushort})::Void),
:(glWindowPos2f(x::GLfloat, y::GLfloat)::Void),
:(glVertex3iv(v::Ptr{GLint})::Void),
:(glRasterPos4iv(v::Ptr{GLint})::Void),
:(glGetHistogram(target::GLenum, reset::GLboolean, format::GLenum, type_::GLenum, values::Ptr{Void})::Void),
:(glSeparableFilter2D(target::GLenum, internalformat::GLenum, width::GLsizei, height::GLsizei, format::GLenum, type_::GLenum, row::Ptr{Void}, column::Ptr{Void})::Void),
:(glColor3b(red::GLbyte, green::GLbyte, blue::GLbyte)::Void),
:(glGetMinmaxParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glSecondaryColor3sv(v::Ptr{GLshort})::Void),
:(glVertexAttrib4Nsv(index::GLuint, v::Ptr{GLshort})::Void),
:(glBegin(mode::GLenum)::Void),
:(glClearIndex(c::GLfloat)::Void),
:(glMultiTexCoord2fv(target::GLenum, v::Ptr{GLfloat})::Void),
:(glRasterPos3f(x::GLfloat, y::GLfloat, z::GLfloat)::Void),
:(glColor3ub(red::GLubyte, green::GLubyte, blue::GLubyte)::Void),
:(glRasterPos2sv(v::Ptr{GLshort})::Void),
:(glRectd(x1::GLdouble, y1::GLdouble, x2::GLdouble, y2::GLdouble)::Void),
:(glMateriali(face::GLenum, pname::GLenum, param::GLint)::Void),
:(glMultiTexCoord3i(target::GLenum, s::GLint, t::GLint, r::GLint)::Void),
:(glFogCoordd(coord::GLdouble)::Void),
:(glMultiTexCoord1dv(target::GLenum, v::Ptr{GLdouble})::Void),
:(glIndexs(c::GLshort)::Void),
:(glColorPointer(size::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glEvalPoint2(i::GLint, j::GLint)::Void),
:(glRasterPos3sv(v::Ptr{GLshort})::Void),
:(glIndexiv(c::Ptr{GLint})::Void),
:(glPopName()::Void),
:(glRasterPos3dv(v::Ptr{GLdouble})::Void),
:(glRotated(angle::GLdouble, x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glEvalCoord1fv(u::Ptr{GLfloat})::Void),
:(glColor4s(red::GLshort, green::GLshort, blue::GLshort, alpha::GLshort)::Void),
:(glMaterialiv(face::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetPolygonStipple(mask::Ptr{GLubyte})::Void),
:(glIndexf(c::GLfloat)::Void),
:(glGenLists(range_::GLsizei)::Cuint),
:(glMultiTexCoord1s(target::GLenum, s::GLshort)::Void),
:(glEvalMesh2(mode::GLenum, i1::GLint, i2::GLint, j1::GLint, j2::GLint)::Void),
:(glCopyConvolutionFilter2D(target::GLenum, internalformat::GLenum, x::GLint, y::GLint, width::GLsizei, height::GLsizei)::Void),
:(glMultiTexCoord3sv(target::GLenum, v::Ptr{GLshort})::Void),
:(glSecondaryColor3b(red::GLbyte, green::GLbyte, blue::GLbyte)::Void),
:(glVertex2s(x::GLshort, y::GLshort)::Void),
:(glMultMatrixd(m::Ptr{GLdouble})::Void),
:(glWindowPos2s(x::GLshort, y::GLshort)::Void),
:(glRasterPos3i(x::GLint, y::GLint, z::GLint)::Void),
:(glTexCoord3i(s::GLint, t::GLint, r::GLint)::Void),
:(glGetMaterialiv(face::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetHistogramParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glMultiTexCoord1fv(target::GLenum, v::Ptr{GLfloat})::Void),
:(glOrtho(left::GLdouble, right::GLdouble, bottom::GLdouble, top::GLdouble, zNear::GLdouble, zFar::GLdouble)::Void),
:(glVertexAttrib1f(index::GLuint, x::GLfloat)::Void),
:(glRasterPos2dv(v::Ptr{GLdouble})::Void),
:(glCopyConvolutionFilter1D(target::GLenum, internalformat::GLenum, x::GLint, y::GLint, width::GLsizei)::Void),
:(glGetTexGeniv(coord::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttrib3sv(index::GLuint, v::Ptr{GLshort})::Void),
:(glColor4sv(v::Ptr{GLshort})::Void),
:(glNormal3iv(v::Ptr{GLint})::Void),
:(glTexCoord3fv(v::Ptr{GLfloat})::Void),
:(glColor4ub(red::GLubyte, green::GLubyte, blue::GLubyte, alpha::GLubyte)::Void),
:(glVertexAttrib1d(index::GLuint, x::GLdouble)::Void),
:(glSecondaryColor3f(red::GLfloat, green::GLfloat, blue::GLfloat)::Void),
:(glSecondaryColor3s(red::GLshort, green::GLshort, blue::GLshort)::Void),
:(glConvolutionParameterf(target::GLenum, pname::GLenum, params::GLfloat)::Void),
:(glColor3i(red::GLint, green::GLint, blue::GLint)::Void),
:(glColor3f(red::GLfloat, green::GLfloat, blue::GLfloat)::Void),
:(glEdgeFlagv(flag::Ptr{GLboolean})::Void),
:(glConvolutionParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glMapGrid1d(un::GLint, u1::GLdouble, u2::GLdouble)::Void),
:(glEvalCoord2dv(u::Ptr{GLdouble})::Void),
:(glRasterPos4sv(v::Ptr{GLshort})::Void),
:(glVertex3s(x::GLshort, y::GLshort, z::GLshort)::Void),
:(glPushClientAttrib(mask::GLbitfield)::Void),
:(glMultiTexCoord3fv(target::GLenum, v::Ptr{GLfloat})::Void),
:(glSecondaryColor3d(red::GLdouble, green::GLdouble, blue::GLdouble)::Void),
:(glColorTable(target::GLenum, internalformat::GLenum, width::GLsizei, format::GLenum, type_::GLenum, table::Ptr{Void})::Void),
:(glSecondaryColor3i(red::GLint, green::GLint, blue::GLint)::Void),
:(glColor4usv(v::Ptr{GLushort})::Void),
:(glColor4ui(red::GLuint, green::GLuint, blue::GLuint, alpha::GLuint)::Void),
:(glColor4f(red::GLfloat, green::GLfloat, blue::GLfloat, alpha::GLfloat)::Void),
:(glPushAttrib(mask::GLbitfield)::Void),
:(glVertexAttrib1fv(index::GLuint, v::Ptr{GLfloat})::Void),
:(glColor3sv(v::Ptr{GLshort})::Void),
:(glTexCoord3s(s::GLshort, t::GLshort, r::GLshort)::Void),
:(glVertexAttrib4bv(index::GLuint, v::Ptr{GLbyte})::Void),
:(glVertex3i(x::GLint, y::GLint, z::GLint)::Void),
:(glMultiTexCoord1i(target::GLenum, s::GLint)::Void),
:(glLighti(light::GLenum, pname::GLenum, param::GLint)::Void),
:(glColor4d(red::GLdouble, green::GLdouble, blue::GLdouble, alpha::GLdouble)::Void),
:(glShadeModel(mode::GLenum)::Void),
:(glEvalCoord2d(u::GLdouble, v::GLdouble)::Void),
:(glVertex2sv(v::Ptr{GLshort})::Void),
:(glLineStipple(factor::GLint, pattern::GLushort)::Void),
:(glEvalMesh1(mode::GLenum, i1::GLint, i2::GLint)::Void),
:(glMultiTexCoord4sv(target::GLenum, v::Ptr{GLshort})::Void),
:(glVertex4f(x::GLfloat, y::GLfloat, z::GLfloat, w::GLfloat)::Void),
:(glWindowPos2i(x::GLint, y::GLint)::Void),
:(glTexEnviv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glEdgeFlagPointer(stride::GLsizei, pointer::Ptr{Void})::Void),
:(glTexCoord4fv(v::Ptr{GLfloat})::Void),
:(glColor4bv(v::Ptr{GLbyte})::Void),
:(glColorTableParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glVertexAttrib2d(index::GLuint, x::GLdouble, y::GLdouble)::Void),
:(glVertex4fv(v::Ptr{GLfloat})::Void),
:(glMultiTexCoord1d(target::GLenum, s::GLdouble)::Void),
:(glRectsv(v1::Ptr{GLshort}, v2::Ptr{GLshort})::Void),
:(glGetMapdv(target::GLenum, query::GLenum, v::Ptr{GLdouble})::Void),
:(glTexCoord2fv(v::Ptr{GLfloat})::Void),
:(glLoadIdentity()::Void),
:(glTexGeniv(coord::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glMultiTexCoord2i(target::GLenum, s::GLint, t::GLint)::Void),
:(glTexCoord4d(s::GLdouble, t::GLdouble, r::GLdouble, q::GLdouble)::Void),
:(glMatrixMode(mode::GLenum)::Void),
:(glConvolutionFilter2D(target::GLenum, internalformat::GLenum, width::GLsizei, height::GLsizei, format::GLenum, type_::GLenum, image::Ptr{Void})::Void),
:(glRasterPos2d(x::GLdouble, y::GLdouble)::Void),
:(glSecondaryColor3ui(red::GLuint, green::GLuint, blue::GLuint)::Void),
:(glVertexAttrib2f(index::GLuint, x::GLfloat, y::GLfloat)::Void),
:(glColor4b(red::GLbyte, green::GLbyte, blue::GLbyte, alpha::GLbyte)::Void),
:(glTexCoord4s(s::GLshort, t::GLshort, r::GLshort, q::GLshort)::Void),
:(glColor4iv(v::Ptr{GLint})::Void),
:(glAreTexturesResident(n::GLsizei, textures::Ptr{GLuint}, residences::Ptr{GLboolean})::Bool),
:(glPopMatrix()::Void),
:(glVertex3fv(v::Ptr{GLfloat})::Void),
:(glVertexAttrib1dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glTexCoord4f(s::GLfloat, t::GLfloat, r::GLfloat, q::GLfloat)::Void),
:(glFeedbackBuffer(size::GLsizei, type_::GLenum, buffer::Ptr{GLfloat})::Void),
:(glSecondaryColor3ubv(v::Ptr{GLubyte})::Void),
:(glLoadName(name::GLuint)::Void),
:(glEndList()::Void),
:(glEvalCoord1f(u::GLfloat)::Void),
:(glGetConvolutionFilter(target::GLenum, format::GLenum, type_::GLenum, image::Ptr{Void})::Void),
:(glVertexAttrib3f(index::GLuint, x::GLfloat, y::GLfloat, z::GLfloat)::Void),
:(glDisableClientState(array::GLenum)::Void),
:(glColor3d(red::GLdouble, green::GLdouble, blue::GLdouble)::Void),
:(glWindowPos2d(x::GLdouble, y::GLdouble)::Void),
:(glRotatef(angle::GLfloat, x::GLfloat, y::GLfloat, z::GLfloat)::Void),
:(glRasterPos3d(x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glRasterPos2f(x::GLfloat, y::GLfloat)::Void),
:(glGetMapfv(target::GLenum, query::GLenum, v::Ptr{GLfloat})::Void),
:(glGetMaterialfv(face::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glVertexPointer(size::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glVertexAttrib4fv(index::GLuint, v::Ptr{GLfloat})::Void),
:(glSecondaryColor3usv(v::Ptr{GLushort})::Void),
:(glNormal3bv(v::Ptr{GLbyte})::Void),
:(glIndexPointer(type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glSecondaryColorPointer(size::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glColor3usv(v::Ptr{GLushort})::Void),
:(glColor4fv(v::Ptr{GLfloat})::Void),
:(glGetColorTable(target::GLenum, format::GLenum, type_::GLenum, table::Ptr{Void})::Void),
:(glTexCoord4dv(v::Ptr{GLdouble})::Void),
:(glVertexAttrib4Nub(index::GLuint, x::GLubyte, y::GLubyte, z::GLubyte, w::GLubyte)::Void),
:(glTexCoord1dv(v::Ptr{GLdouble})::Void),
:(glVertexAttrib4uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glResetMinmax(target::GLenum)::Void),
:(glVertexAttrib4f(index::GLuint, x::GLfloat, y::GLfloat, z::GLfloat, w::GLfloat)::Void),
:(glVertexAttrib4ubv(index::GLuint, v::Ptr{GLubyte})::Void),
:(glLightModeliv(pname::GLenum, params::Ptr{GLint})::Void),
:(glMultMatrixf(m::Ptr{GLfloat})::Void),
:(glColor4uiv(v::Ptr{GLuint})::Void),
:(glCopyPixels(x::GLint, y::GLint, width::GLsizei, height::GLsizei, type_::GLenum)::Void),
:(glRectiv(v1::Ptr{GLint}, v2::Ptr{GLint})::Void),
:(glTexGend(coord::GLenum, pname::GLenum, param::GLdouble)::Void),
:(glColor4dv(v::Ptr{GLdouble})::Void),
:(glMap2f(target::GLenum, u1::GLfloat, u2::GLfloat, ustride::GLint, uorder::GLint, v1::GLfloat, v2::GLfloat, vstride::GLint, vorder::GLint, points::Ptr{GLfloat})::Void),
:(glGetTexEnviv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetSeparableFilter(target::GLenum, format::GLenum, type_::GLenum, row::Ptr{Void}, column::Ptr{Void}, span::Ptr{Void})::Void),
:(glVertexAttrib3dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glVertexAttrib4Nusv(index::GLuint, v::Ptr{GLushort})::Void),
:(glPixelMapuiv(map_::GLenum, mapsize::GLsizei, values::Ptr{GLuint})::Void),
:(glConvolutionParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glTexCoord1s(s::GLshort)::Void),
:(glVertexAttrib4Nuiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glColor4us(red::GLushort, green::GLushort, blue::GLushort, alpha::GLushort)::Void),
:(glFogCoordf(coord::GLfloat)::Void)]
