#Types, functions and constants, needed on top of the common ones
#types
const GL_GL33_TYPES = [
]
#constants
const GL_GL33_CONSTANTS = [
:(const SYNC_GPU_COMMANDS_COMPLETE                                      = 0x9117),
:(const ONE_MINUS_SRC1_COLOR                                            = 0x88FA),
:(const R8I                                                             = 0x8231),
:(const TEXTURE_FIXED_SAMPLE_LOCATIONS                                  = 0x9107),
:(const QUERY_BY_REGION_NO_WAIT                                         = 0x8E16),
:(const FRAMEBUFFER_ATTACHMENT_RED_SIZE                                 = 0x8212),
:(const R11F_G11F_B10F                                                  = 0x8C3A),
:(const MAX_VERTEX_UNIFORM_BLOCKS                                       = 0x8A2B),
:(const COMPRESSED_SIGNED_RED_RGTC1                                     = 0x8DBC),
:(const RGB8I                                                           = 0x8D8F),
:(const RGBA16I                                                         = 0x8D88),
:(const MAX_CLIP_DISTANCES                                              = 0x0D32),
:(const RGB9_E5                                                         = 0x8C3D),
:(const PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY                              = 0x9103),
:(const TEXTURE_BINDING_BUFFER                                          = 0x8C2C),
:(const RG_INTEGER                                                      = 0x8228),
:(const RENDERBUFFER_BINDING                                            = 0x8CA7),
:(const SYNC_FLUSH_COMMANDS_BIT                                         = 0x00000001),
:(const GEOMETRY_INPUT_TYPE                                             = 0x8917),
:(const DRAW_FRAMEBUFFER                                                = 0x8CA9),
:(const MAX_UNIFORM_BLOCK_SIZE                                          = 0x8A30),
:(const R16                                                             = 0x822A),
:(const TEXTURE_RED_TYPE                                                = 0x8C10),
:(const MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS                        = 0x8A33),
:(const TEXTURE_STENCIL_SIZE                                            = 0x88F1),
:(const R32F                                                            = 0x822E),
:(const TRANSFORM_FEEDBACK_VARYINGS                                     = 0x8C83),
:(const TIMEOUT_EXPIRED                                                 = 0x911B),
:(const PRIMITIVE_RESTART_INDEX                                         = 0x8F9E),
:(const MAX_COMBINED_UNIFORM_BLOCKS                                     = 0x8A2E),
:(const FIRST_VERTEX_CONVENTION                                         = 0x8E4D),
:(const TEXTURE_GREEN_TYPE                                              = 0x8C11),
:(const WAIT_FAILED                                                     = 0x911D),
:(const RENDERBUFFER_STENCIL_SIZE                                       = 0x8D55),
:(const INT_SAMPLER_2D_RECT                                             = 0x8DCD),
:(const MAX_ARRAY_TEXTURE_LAYERS                                        = 0x88FF),
:(const CLIP_DISTANCE3                                                  = 0x3003),
:(const RGB16_SNORM                                                     = 0x8F9A),
:(const COLOR_ATTACHMENT0                                               = 0x8CE0),
:(const MAX_INTEGER_SAMPLES                                             = 0x9110),
:(const MAX_DUAL_SOURCE_DRAW_BUFFERS                                    = 0x88FC),
:(const FRAMEBUFFER_INCOMPLETE_MULTISAMPLE                              = 0x8D56),
:(const COLOR_ATTACHMENT13                                              = 0x8CED),
:(const TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN                           = 0x8C88),
:(const STENCIL_INDEX1                                                  = 0x8D46),
:(const RGB8UI                                                          = 0x8D7D),
:(const CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT                             = 0x0001),
:(const BUFFER_MAP_LENGTH                                               = 0x9120),
:(const R32UI                                                           = 0x8236),
:(const ANY_SAMPLES_PASSED                                              = 0x8C2F),
:(const TEXTURE_2D_MULTISAMPLE                                          = 0x9100),
:(const R8                                                              = 0x8229),
:(const VERTEX_ARRAY_BINDING                                            = 0x85B5),
:(const UNIFORM_SIZE                                                    = 0x8A38),
:(const SIGNED_NORMALIZED                                               = 0x8F9C),
:(const UNIFORM_OFFSET                                                  = 0x8A3B),
:(const RG8I                                                            = 0x8237),
:(const FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER                              = 0x8CDB),
:(const SAMPLER_2D_ARRAY_SHADOW                                         = 0x8DC4),
:(const HALF_FLOAT                                                      = 0x140B),
:(const DEPTH_ATTACHMENT                                                = 0x8D00),
:(const UNIFORM_BLOCK_DATA_SIZE                                         = 0x8A40),
:(const RGB16I                                                          = 0x8D89),
:(const RENDERBUFFER_INTERNAL_FORMAT                                    = 0x8D44),
:(const TEXTURE_INTENSITY_TYPE                                          = 0x8C15),
:(const MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS                   = 0x8C8A),
:(const SYNC_FENCE                                                      = 0x9116),
:(const UNSIGNED_INT_24_8                                               = 0x84FA),
:(const PROXY_TEXTURE_2D_ARRAY                                          = 0x8C1B),
:(const PROVOKING_VERTEX                                                = 0x8E4F),
:(const TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY                            = 0x9105),
:(const RGB10_A2UI                                                      = 0x906F),
:(const RED_INTEGER                                                     = 0x8D94),
:(const OBJECT_TYPE                                                     = 0x9112),
:(const TEXTURE_LUMINANCE_TYPE                                          = 0x8C14),
:(const RGB_INTEGER                                                     = 0x8D98),
:(const UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY                       = 0x910D),
:(const MAX_RECTANGLE_TEXTURE_SIZE                                      = 0x84F8),
:(const UNIFORM_TYPE                                                    = 0x8A37),
:(const COLOR_ATTACHMENT2                                               = 0x8CE2),
:(const MAX_SAMPLE_MASK_WORDS                                           = 0x8E59),
:(const CONDITION_SATISFIED                                             = 0x911C),
:(const MAX_GEOMETRY_INPUT_COMPONENTS                                   = 0x9123),
:(const UNSIGNED_NORMALIZED                                             = 0x8C17),
:(const VERTEX_ATTRIB_ARRAY_DIVISOR                                     = 0x88FE),
:(const TEXTURE_RECTANGLE                                               = 0x84F5),
:(const UNIFORM_NAME_LENGTH                                             = 0x8A39),
:(const MAX_GEOMETRY_TEXTURE_IMAGE_UNITS                                = 0x8C29),
:(const FRAMEBUFFER_COMPLETE                                            = 0x8CD5),
:(const TEXTURE_BUFFER                                                  = 0x8C2A),
:(const INT_SAMPLER_CUBE                                                = 0x8DCC),
:(const UNIFORM_BUFFER_OFFSET_ALIGNMENT                                 = 0x8A34),
:(const MAP_FLUSH_EXPLICIT_BIT                                          = 0x0010),
:(const BUFFER_MAP_OFFSET                                               = 0x9121),
:(const UNSIGNED_INT_5_9_9_9_REV                                        = 0x8C3E),
:(const READ_FRAMEBUFFER                                                = 0x8CA8),
:(const RENDERBUFFER_ALPHA_SIZE                                         = 0x8D53),
:(const TEXTURE_SWIZZLE_G                                               = 0x8E43),
:(const BGRA_INTEGER                                                    = 0x8D9B),
:(const RG16UI                                                          = 0x823A),
:(const RG8_SNORM                                                       = 0x8F95),
:(const MAX_RENDERBUFFER_SIZE                                           = 0x84E8),
:(const TRANSFORM_FEEDBACK_BUFFER_BINDING                               = 0x8C8F),
:(const STENCIL_INDEX8                                                  = 0x8D48),
:(const UNIFORM_BLOCK_NAME_LENGTH                                       = 0x8A41),
:(const INT_SAMPLER_1D                                                  = 0x8DC9),
:(const MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS                          = 0x8A31),
:(const R8_SNORM                                                        = 0x8F94),
:(const TIME_ELAPSED                                                    = 0x88BF),
:(const TEXTURE_2D_ARRAY                                                = 0x8C1A),
:(const CLAMP_READ_COLOR                                                = 0x891C),
:(const TRANSFORM_FEEDBACK_BUFFER                                       = 0x8C8E),
:(const FRAMEBUFFER_INCOMPLETE_READ_BUFFER                              = 0x8CDC),
:(const FRAMEBUFFER_ATTACHMENT_GREEN_SIZE                               = 0x8213),
:(const NUM_EXTENSIONS                                                  = 0x821D),
:(const DEPTH_STENCIL_ATTACHMENT                                        = 0x821A),
:(const UNSIGNED_INT_SAMPLER_2D                                         = 0x8DD2),
:(const RENDERBUFFER_RED_SIZE                                           = 0x8D50),
:(const TEXTURE_1D_ARRAY                                                = 0x8C18),
:(const INT_2_10_10_10_REV                                              = 0x8D9F),
:(const PROXY_TEXTURE_1D_ARRAY                                          = 0x8C19),
:(const CLAMP_VERTEX_COLOR                                              = 0x891A),
:(const R16UI                                                           = 0x8234),
:(const DRAW_FRAMEBUFFER_BINDING                                        = 0x8CA6),
:(const UNIFORM_BUFFER_START                                            = 0x8A29),
:(const LINES_ADJACENCY                                                 = 0x000A),
:(const COLOR_ATTACHMENT6                                               = 0x8CE6),
:(const UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER                       = 0x8A44),
:(const DEPTH32F_STENCIL8                                               = 0x8CAD),
:(const COMPRESSED_RG                                                   = 0x8226),
:(const R8UI                                                            = 0x8232),
:(const UNIFORM_MATRIX_STRIDE                                           = 0x8A3D),
:(const FRAMEBUFFER_ATTACHMENT_BLUE_SIZE                                = 0x8214),
:(const RENDERBUFFER_HEIGHT                                             = 0x8D43),
:(const FLOAT_32_UNSIGNED_INT_24_8_REV                                  = 0x8DAD),
:(const RG16F                                                           = 0x822F),
:(const MAX_COLOR_TEXTURE_SAMPLES                                       = 0x910E),
:(const SAMPLE_MASK                                                     = 0x8E51),
:(const TEXTURE_ALPHA_TYPE                                              = 0x8C13),
:(const UNSIGNED_INT_SAMPLER_CUBE                                       = 0x8DD4),
:(const PROXY_TEXTURE_2D_MULTISAMPLE                                    = 0x9101),
:(const R32I                                                            = 0x8235),
:(const VERTEX_ATTRIB_ARRAY_INTEGER                                     = 0x88FD),
:(const COLOR_ATTACHMENT10                                              = 0x8CEA),
:(const RGBA32UI                                                        = 0x8D70),
:(const FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE                    = 0x8CD3),
:(const RG8UI                                                           = 0x8238),
:(const RGBA16UI                                                        = 0x8D76),
:(const PRIMITIVES_GENERATED                                            = 0x8C87),
:(const FRAMEBUFFER_SRGB                                                = 0x8DB9),
:(const RGBA8_SNORM                                                     = 0x8F97),
:(const UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE                             = 0x910A),
:(const RENDERBUFFER_WIDTH                                              = 0x8D42),
:(const TIMESTAMP                                                       = 0x8E28),
:(const DEPTH_CLAMP                                                     = 0x864F),
:(const RGBA_INTEGER                                                    = 0x8D99),
:(const TEXTURE_CUBE_MAP_SEAMLESS                                       = 0x884F),
:(const SIGNALED                                                        = 0x9119),
:(const UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES                            = 0x8A43),
:(const RGBA16F                                                         = 0x881A),
:(const COLOR_ATTACHMENT11                                              = 0x8CEB),
:(const FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE                           = 0x8211),
:(const MAJOR_VERSION                                                   = 0x821B),
:(const COLOR_ATTACHMENT5                                               = 0x8CE5),
:(const R16_SNORM                                                       = 0x8F98),
:(const UNSIGNED_INT_SAMPLER_3D                                         = 0x8DD3),
:(const MAX_PROGRAM_TEXEL_OFFSET                                        = 0x8905),
:(const MAP_UNSYNCHRONIZED_BIT                                          = 0x0020),
:(const RG                                                              = 0x8227),
:(const BGR_INTEGER                                                     = 0x8D9A),
:(const FIXED_ONLY                                                      = 0x891D),
:(const UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER                     = 0x8A46),
:(const INT_SAMPLER_2D_ARRAY                                            = 0x8DCF),
:(const RASTERIZER_DISCARD                                              = 0x8C89),
:(const FRAMEBUFFER                                                     = 0x8D40),
:(const INT_SAMPLER_3D                                                  = 0x8DCB),
:(const RGBA8UI                                                         = 0x8D7C),
:(const COLOR_ATTACHMENT9                                               = 0x8CE9),
:(const MAX_GEOMETRY_OUTPUT_VERTICES                                    = 0x8DE0),
:(const FRAMEBUFFER_INCOMPLETE_ATTACHMENT                               = 0x8CD6),
:(const ACTIVE_UNIFORM_BLOCKS                                           = 0x8A36),
:(const COLOR_ATTACHMENT15                                              = 0x8CEF),
:(const SAMPLER_2D_RECT_SHADOW                                          = 0x8B64),
:(const UNSIGNED_INT_VEC4                                               = 0x8DC8),
:(const ONE_MINUS_SRC1_ALPHA                                            = 0x88FB),
:(const GEOMETRY_OUTPUT_TYPE                                            = 0x8918),
:(const TRANSFORM_FEEDBACK_BUFFER_START                                 = 0x8C84),
:(const UNIFORM_BLOCK_ACTIVE_UNIFORMS                                   = 0x8A42),
:(const SYNC_FLAGS                                                      = 0x9115),
:(const INT_SAMPLER_2D_MULTISAMPLE_ARRAY                                = 0x910C),
:(const TRIANGLES_ADJACENCY                                             = 0x000C),
:(const MAX_VARYING_COMPONENTS                                          = 0x8B4B),
:(const MAP_INVALIDATE_RANGE_BIT                                        = 0x0004),
:(const CONTEXT_COMPATIBILITY_PROFILE_BIT                               = 0x00000002),
:(const RENDERBUFFER_GREEN_SIZE                                         = 0x8D51),
:(const RG16_SNORM                                                      = 0x8F99),
:(const QUERY_WAIT                                                      = 0x8E13),
:(const FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS                            = 0x8DA8),
:(const UNIFORM_BLOCK_INDEX                                             = 0x8A3A),
:(const UNSIGNED_INT_SAMPLER_1D_ARRAY                                   = 0x8DD6),
:(const RG8                                                             = 0x822B),
:(const SAMPLER_1D_ARRAY                                                = 0x8DC0),
:(const FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING                           = 0x8210),
:(const RGBA32F                                                         = 0x8814),
:(const LAST_VERTEX_CONVENTION                                          = 0x8E4E),
:(const BLUE_INTEGER                                                    = 0x8D96),
:(const MAX_TEXTURE_BUFFER_SIZE                                         = 0x8C2B),
:(const CLIP_DISTANCE1                                                  = 0x3001),
:(const READ_FRAMEBUFFER_BINDING                                        = 0x8CAA),
:(const TEXTURE_BINDING_2D_MULTISAMPLE                                  = 0x9104),
:(const INDEX                                                           = 0x8222),
:(const TEXTURE_SHARED_SIZE                                             = 0x8C3F),
:(const TEXTURE_BINDING_RECTANGLE                                       = 0x84F6),
:(const UNSIGNED_INT_SAMPLER_BUFFER                                     = 0x8DD8),
:(const COLOR_ATTACHMENT14                                              = 0x8CEE),
:(const GREEN_INTEGER                                                   = 0x8D95),
:(const FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL                            = 0x8CD2),
:(const SAMPLER_1D_ARRAY_SHADOW                                         = 0x8DC3),
:(const TEXTURE_2D_MULTISAMPLE_ARRAY                                    = 0x9102),
:(const RENDERBUFFER_BLUE_SIZE                                          = 0x8D52),
:(const SAMPLE_POSITION                                                 = 0x8E50),
:(const SAMPLER_BUFFER                                                  = 0x8DC2),
:(const RENDERBUFFER_SAMPLES                                            = 0x8CAB),
:(const COLOR_ATTACHMENT12                                              = 0x8CEC),
:(const RGB32F                                                          = 0x8815),
:(const RENDERBUFFER                                                    = 0x8D41),
:(const RGBA8I                                                          = 0x8D8E),
:(const CLIP_DISTANCE2                                                  = 0x3002),
:(const FRAMEBUFFER_UNSUPPORTED                                         = 0x8CDD),
:(const ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH                            = 0x8A35),
:(const INT_SAMPLER_2D                                                  = 0x8DCA),
:(const SAMPLER_CUBE_SHADOW                                             = 0x8DC5),
:(const SAMPLER_2D_MULTISAMPLE                                          = 0x9108),
:(const UNSIGNALED                                                      = 0x9118),
:(const INTERLEAVED_ATTRIBS                                             = 0x8C8C),
:(const SAMPLER_2D_ARRAY                                                = 0x8DC1),
:(const QUERY_NO_WAIT                                                   = 0x8E14),
:(const UNIFORM_IS_ROW_MAJOR                                            = 0x8A3E),
:(const SAMPLE_MASK_VALUE                                               = 0x8E52),
:(const BUFFER_ACCESS_FLAGS                                             = 0x911F),
:(const COMPARE_REF_TO_TEXTURE                                          = 0x884E),
:(const MAP_READ_BIT                                                    = 0x0001),
:(const RG16                                                            = 0x822C),
:(const MAX_UNIFORM_BUFFER_BINDINGS                                     = 0x8A2F),
:(const UNIFORM_BUFFER_SIZE                                             = 0x8A2A),
:(const UNSIGNED_INT_VEC3                                               = 0x8DC7),
:(const INT_SAMPLER_BUFFER                                              = 0x8DD0),
:(const TEXTURE_SWIZZLE_R                                               = 0x8E42),
:(const RENDERBUFFER_DEPTH_SIZE                                         = 0x8D54),
:(const MAX_COLOR_ATTACHMENTS                                           = 0x8CDF),
:(const RG32F                                                           = 0x8230),
:(const CONTEXT_CORE_PROFILE_BIT                                        = 0x00000001),
:(const RGBA32I                                                         = 0x8D82),
:(const TEXTURE_BINDING_1D_ARRAY                                        = 0x8C1C),
:(const INT_SAMPLER_2D_MULTISAMPLE                                      = 0x9109),
:(const FRAMEBUFFER_ATTACHMENT_OBJECT_NAME                              = 0x8CD1),
:(const MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS                      = 0x8C80),
:(const MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS                            = 0x8DE1),
:(const UNSIGNED_INT_10F_11F_11F_REV                                    = 0x8C3B),
:(const MAX_SAMPLES                                                     = 0x8D57),
:(const RG32UI                                                          = 0x823C),
:(const DEPTH_COMPONENT32F                                              = 0x8CAC),
:(const PROXY_TEXTURE_RECTANGLE                                         = 0x84F7),
:(const UNIFORM_BUFFER                                                  = 0x8A11),
:(const SYNC_CONDITION                                                  = 0x9113),
:(const CONTEXT_PROFILE_MASK                                            = 0x9126),
:(const MAP_INVALIDATE_BUFFER_BIT                                       = 0x0008),
:(const FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE                             = 0x8217),
:(const FRAMEBUFFER_DEFAULT                                             = 0x8218),
:(const UNIFORM_ARRAY_STRIDE                                            = 0x8A3C),
:(const SAMPLER_BINDING                                                 = 0x8919),
:(const MAP_WRITE_BIT                                                   = 0x0002),
:(const FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER                            = 0x8CD4),
:(const MIN_PROGRAM_TEXEL_OFFSET                                        = 0x8904),
:(const DEPTH24_STENCIL8                                                = 0x88F0),
:(const MAX_SERVER_WAIT_TIMEOUT                                         = 0x9111),
:(const PROGRAM_POINT_SIZE                                              = 0x8642),
:(const INVALID_FRAMEBUFFER_OPERATION                                   = 0x0506),
:(const FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE                               = 0x8216),
:(const FRAMEBUFFER_BINDING                                             = 0x8CA6),
:(const RGB32I                                                          = 0x8D83),
:(const COLOR_ATTACHMENT1                                               = 0x8CE1),
:(const COPY_WRITE_BUFFER                                               = 0x8F37),
:(const RGB16F                                                          = 0x881B),
:(const RGB16UI                                                         = 0x8D77),
:(const MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS                         = 0x8C8B),
:(const CLIP_DISTANCE4                                                  = 0x3004),
:(const MINOR_VERSION                                                   = 0x821C),
:(const STENCIL_INDEX4                                                  = 0x8D47),
:(const R16I                                                            = 0x8233),
:(const CLAMP_FRAGMENT_COLOR                                            = 0x891B),
:(const STENCIL_ATTACHMENT                                              = 0x8D20),
:(const TEXTURE_SWIZZLE_RGBA                                            = 0x8E46),
:(const COLOR_ATTACHMENT3                                               = 0x8CE3),
:(const COMPRESSED_SIGNED_RG_RGTC2                                      = 0x8DBE),
:(const MAX_FRAGMENT_UNIFORM_BLOCKS                                     = 0x8A2D),
:(const TEXTURE_BINDING_2D_ARRAY                                        = 0x8C1D),
:(const MAX_GEOMETRY_UNIFORM_COMPONENTS                                 = 0x8DDF),
:(const CLIP_DISTANCE0                                                  = 0x3000),
:(const MAX_GEOMETRY_OUTPUT_COMPONENTS                                  = 0x9124),
:(const RGBA16_SNORM                                                    = 0x8F9B),
:(const TEXTURE_BUFFER_DATA_STORE_BINDING                               = 0x8C2D),
:(const FRAMEBUFFER_UNDEFINED                                           = 0x8219),
:(const TRANSFORM_FEEDBACK_BUFFER_SIZE                                  = 0x8C85),
:(const RGBA_SNORM                                                      = 0x8F93),
:(const UNSIGNED_INT_VEC2                                               = 0x8DC6),
:(const CLIP_DISTANCE5                                                  = 0x3005),
:(const R16F                                                            = 0x822D),
:(const TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH                           = 0x8C76),
:(const TEXTURE_BLUE_TYPE                                               = 0x8C12),
:(const GEOMETRY_VERTICES_OUT                                           = 0x8916),
:(const UNSIGNED_INT_SAMPLER_1D                                         = 0x8DD1),
:(const COLOR_ATTACHMENT8                                               = 0x8CE8),
:(const GEOMETRY_SHADER                                                 = 0x8DD9),
:(const QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION                        = 0x8E4C),
:(const FRAMEBUFFER_ATTACHMENT_LAYERED                                  = 0x8DA7),
:(const RGB8_SNORM                                                      = 0x8F96),
:(const TIMEOUT_IGNORED                                                 = 0xFFFFFFFFFFFFFFFF),
:(const TEXTURE_DEPTH_TYPE                                              = 0x8C16),
:(const TRANSFORM_FEEDBACK_BUFFER_MODE                                  = 0x8C7F),
:(const TEXTURE_SAMPLES                                                 = 0x9106),
:(const RG32I                                                           = 0x823B),
:(const TEXTURE_SWIZZLE_A                                               = 0x8E45),
:(const MAX_VERTEX_OUTPUT_COMPONENTS                                    = 0x9122),
:(const SAMPLER_2D_MULTISAMPLE_ARRAY                                    = 0x910B),
:(const COMPRESSED_RED                                                  = 0x8225),
:(const CONTEXT_FLAGS                                                   = 0x821E),
:(const RGB_SNORM                                                       = 0x8F92),
:(const FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE                              = 0x8CD0),
:(const UNIFORM_BLOCK_BINDING                                           = 0x8A3F),
:(const UNSIGNED_INT_SAMPLER_2D_RECT                                    = 0x8DD5),
:(const SAMPLER_2D_RECT                                                 = 0x8B63),
:(const MAX_FRAGMENT_INPUT_COMPONENTS                                   = 0x9125),
:(const MAX_DEPTH_TEXTURE_SAMPLES                                       = 0x910F),
:(const QUERY_BY_REGION_WAIT                                            = 0x8E15),
:(const ALREADY_SIGNALED                                                = 0x911A),
:(const PRIMITIVE_RESTART                                               = 0x8F9D),
:(const COLOR_ATTACHMENT7                                               = 0x8CE7),
:(const SEPARATE_ATTRIBS                                                = 0x8C8D),
:(const UNIFORM_BUFFER_BINDING                                          = 0x8A28),
:(const INVALID_INDEX                                                   = 0xFFFFFFFF),
:(const LINE_STRIP_ADJACENCY                                            = 0x000B),
:(const SRC1_COLOR                                                      = 0x88F9),
:(const RG16I                                                           = 0x8239),
:(const STENCIL_INDEX16                                                 = 0x8D49),
:(const SYNC_STATUS                                                     = 0x9114),
:(const UNSIGNED_INT_SAMPLER_2D_ARRAY                                   = 0x8DD7),
:(const RG_SNORM                                                        = 0x8F91),
:(const ALPHA_INTEGER                                                   = 0x8D97),
:(const DEPTH_STENCIL                                                   = 0x84F9),
:(const FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT                       = 0x8CD7),
:(const RGB32UI                                                         = 0x8D71),
:(const FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE                               = 0x8215),
:(const TRIANGLE_STRIP_ADJACENCY                                        = 0x000D),
:(const CLIP_DISTANCE7                                                  = 0x3007),
:(const COMPRESSED_RG_RGTC2                                             = 0x8DBD),
:(const TEXTURE_SWIZZLE_B                                               = 0x8E44),
:(const INT_SAMPLER_1D_ARRAY                                            = 0x8DCE),
:(const CLIP_DISTANCE6                                                  = 0x3006),
:(const COPY_READ_BUFFER                                                = 0x8F36),
:(const COMPRESSED_RED_RGTC1                                            = 0x8DBB),
:(const RED_SNORM                                                       = 0x8F90),
:(const COLOR_ATTACHMENT4                                               = 0x8CE4)]
#function bodies
const GL_GL33_FUNCTIONS = [
:(glClearBufferfv(buffer::GLenum, drawbuffer::GLint, value::Ptr{GLfloat})::Void),
:(glTexImage2DMultisample(target::GLenum, samples::GLsizei, internalformat::GLint, width::GLsizei, height::GLsizei, fixedsamplelocations::GLboolean)::Void),
:(glVertexAttribP4ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glUniform2uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glMultiTexCoordP3uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glEnablei(target::GLenum, index::GLuint)::Void),
:(glGetVertexAttribIiv(index::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glProvokingVertex(mode::GLenum)::Void),
:(glDeleteVertexArrays(n::GLsizei, arrays::Ptr{GLuint})::Void),
:(glVertexAttribI1iv(index::GLuint, v::Ptr{GLint})::Void),
:(glFramebufferTexture3D(target::GLenum, attachment::GLenum, textarget::GLenum, texture::GLuint, level::GLint, zoffset::GLint)::Void),
:(glVertexP2ui(type_::GLenum, value::GLuint)::Void),
:(glVertexAttribI2iv(index::GLuint, v::Ptr{GLint})::Void),
:(glTexCoordP2ui(type_::GLenum, coords::GLuint)::Void),
:(glVertexAttribP4uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glTexCoordP1ui(type_::GLenum, coords::GLuint)::Void),
:(glEndConditionalRender()::Void),
:(glTexParameterIiv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glDeleteSync(sync::GLsync)::Void),
:(glSamplerParameteri(sampler::GLuint, pname::GLenum, param::GLint)::Void),
:(glNormalP3uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glGetBufferParameteri64v(target::GLenum, pname::GLenum, params::Ptr{GLint64})::Void),
:(glClientWaitSync(sync::GLsync, flags::GLbitfield, timeout::GLuClonglong)::Cint),
:(glGetActiveUniformName(program::GLuint, uniformIndex::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, uniformName::Ptr{GLchar})::Void),
:(glMultiTexCoordP4uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glVertexAttribI4bv(index::GLuint, v::Ptr{GLbyte})::Void),
:(glGetUniformBlockIndex(program::GLuint, uniformBlockName::Ptr{GLchar})::Cuint),
:(glMultiTexCoordP1ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glGetBooleani_v(target::GLenum, index::GLuint, data::Ptr{GLboolean})::Void),
:(glGetSamplerParameterfv(sampler::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glGetQueryObjecti64v(id::GLuint, pname::GLenum, params::Ptr{GLint64})::Void),
:(glVertexAttribI3uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glMultiTexCoordP3ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glUniform4uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glClearBufferfi(buffer::GLenum, drawbuffer::GLint, depth::GLfloat, stencil::GLint)::Void),
:(glGenerateMipmap(target::GLenum)::Void),
:(glVertexAttribI3ui(index::GLuint, x::GLuint, y::GLuint, z::GLuint)::Void),
:(glTexCoordP4uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glEndTransformFeedback()::Void),
:(glBindBufferBase(target::GLenum, index::GLuint, buffer::GLuint)::Void),
:(glUniform1uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glSamplerParameterIuiv(sampler::GLuint, pname::GLenum, param::Ptr{GLuint})::Void),
:(glVertexAttribDivisor(index::GLuint, divisor::GLuint)::Void),
:(glMultiTexCoordP4ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glClampColor(target::GLenum, clamp::GLenum)::Void),
:(glTexBuffer(target::GLenum, internalformat::GLenum, buffer::GLuint)::Void),
:(glBlitFramebuffer(srcX0::GLint, srcY0::GLint, srcX1::GLint, srcY1::GLint, dstX0::GLint, dstY0::GLint, dstX1::GLint, dstY1::GLint, mask::GLbitfield, filter::GLenum)::Void),
:(glVertexAttribP2ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glSamplerParameterfv(sampler::GLuint, pname::GLenum, param::Ptr{GLfloat})::Void),
:(glGetFragDataLocation(program::GLuint, name::Ptr{GLchar})::Cint),
:(glSecondaryColorP3uiv(type_::GLenum, color::Ptr{GLuint})::Void),
:(glGetActiveUniformsiv(program::GLuint, uniformCount::GLsizei, uniformIndices::Ptr{GLuint}, pname::GLenum, params::Ptr{GLint})::Void),
:(glGenRenderbuffers(n::GLsizei, renderbuffers::Ptr{GLuint})::Void),
:(glBindFramebuffer(target::GLenum, framebuffer::GLuint)::Void),
:(glGetUniformIndices(program::GLuint, uniformCount::GLsizei, uniformNames::Ptr{Uint8}, uniformIndices::Ptr{GLuint})::Void),
:(glGetMultisamplefv(pname::GLenum, index::GLuint, val::Ptr{GLfloat})::Void),
:(glIsRenderbuffer(renderbuffer::GLuint)::Bool),
:(glVertexAttribI2i(index::GLuint, x::GLint, y::GLint)::Void),
:(glVertexP3ui(type_::GLenum, value::GLuint)::Void),
:(glBeginTransformFeedback(primitiveMode::GLenum)::Void),
:(glVertexAttribI1ui(index::GLuint, x::GLuint)::Void),
:(glDrawArraysInstanced(mode::GLenum, first::GLint, count::GLsizei, instancecount::GLsizei)::Void),
:(glTexCoordP1uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glSecondaryColorP3ui(type_::GLenum, color::GLuint)::Void),
:(glRenderbufferStorage(target::GLenum, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glTexCoordP3uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glTexParameterIuiv(target::GLenum, pname::GLenum, params::Ptr{GLuint})::Void),
:(glGetSamplerParameterIuiv(sampler::GLuint, pname::GLenum, params::Ptr{GLuint})::Void),
:(glVertexAttribI4i(index::GLuint, x::GLint, y::GLint, z::GLint, w::GLint)::Void),
:(glColorMaski(index::GLuint, r::GLboolean, g::GLboolean, b::GLboolean, a::GLboolean)::Void),
:(glGenVertexArrays(n::GLsizei, arrays::Ptr{GLuint})::Void),
:(glVertexAttribI3iv(index::GLuint, v::Ptr{GLint})::Void),
:(glSamplerParameterf(sampler::GLuint, pname::GLenum, param::GLfloat)::Void),
:(glVertexAttribP1uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glGetInteger64i_v(target::GLenum, index::GLuint, data::Ptr{GLint64})::Void),
:(glTexCoordP3ui(type_::GLenum, coords::GLuint)::Void),
:(glClearBufferuiv(buffer::GLenum, drawbuffer::GLint, value::Ptr{GLuint})::Void),
:(glVertexAttribI4uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glBindSampler(unit::GLuint, sampler::GLuint)::Void),
:(glMapBufferRange(target::GLenum, offset::GLintptr, length::GLsizeiptr, access::GLbitfield)::Ptr{Void}),
:(glCopyBufferSubData(readTarget::GLenum, writeTarget::GLenum, readOffset::GLintptr, writeOffset::GLintptr, size::GLsizeiptr)::Void),
:(glUniformBlockBinding(program::GLuint, uniformBlockIndex::GLuint, uniformBlockBinding::GLuint)::Void),
:(glVertexAttribI4ui(index::GLuint, x::GLuint, y::GLuint, z::GLuint, w::GLuint)::Void),
:(glBindRenderbuffer(target::GLenum, renderbuffer::GLuint)::Void),
:(glMultiTexCoordP1uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glGetIntegeri_v(target::GLenum, index::GLuint, data::Ptr{GLint})::Void),
:(glSamplerParameteriv(sampler::GLuint, pname::GLenum, param::Ptr{GLint})::Void),
:(glGetTransformFeedbackVarying(program::GLuint, index::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, size::Ptr{GLsizei}, type_::Ptr{GLenum}, name::Ptr{GLchar})::Void),
:(glBeginConditionalRender(id::GLuint, mode::GLenum)::Void),
:(glGetFragDataIndex(program::GLuint, name::Ptr{GLchar})::Cint),
:(glFramebufferTexture2D(target::GLenum, attachment::GLenum, textarget::GLenum, texture::GLuint, level::GLint)::Void),
:(glGetSamplerParameteriv(sampler::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glFenceSync(condition::GLenum, flags::GLbitfield)::Sync),
:(glMultiDrawElementsBaseVertex(mode::GLenum, count::Ptr{GLsizei}, type_::GLenum, indices::Ptr{Ptr{Void}}, drawcount::GLsizei, basevertex::Ptr{GLint})::Void),
:(glIsEnabledi(target::GLenum, index::GLuint)::Bool),
:(glFramebufferTexture1D(target::GLenum, attachment::GLenum, textarget::GLenum, texture::GLuint, level::GLint)::Void),
:(glVertexAttribI2uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glVertexAttribIPointer(index::GLuint, size::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glColorP4uiv(type_::GLenum, color::Ptr{GLuint})::Void),
:(glBindFragDataLocationIndexed(program::GLuint, colorNumber::GLuint, index::GLuint, name::Ptr{GLchar})::Void),
:(glMultiTexCoordP2ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glDeleteFramebuffers(n::GLsizei, framebuffers::Ptr{GLuint})::Void),
:(glGetQueryObjectui64v(id::GLuint, pname::GLenum, params::Ptr{GLuint64})::Void),
:(glIsVertexArray(array::GLuint)::Bool),
:(glGetTexParameterIiv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glRenderbufferStorageMultisample(target::GLenum, samples::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glVertexAttribI4usv(index::GLuint, v::Ptr{GLushort})::Void),
:(glVertexAttribI1i(index::GLuint, x::GLint)::Void),
:(glVertexP2uiv(type_::GLenum, value::Ptr{GLuint})::Void),
:(glTexCoordP2uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glGetStringi(name::GLenum, index::GLuint)::Ptr{Cuchar}),
:(glGetSamplerParameterIiv(sampler::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glIsSampler(sampler::GLuint)::Bool),
:(glIsSync(sync::GLsync)::Bool),
:(glGetVertexAttribIuiv(index::GLuint, pname::GLenum, params::Ptr{GLuint})::Void),
:(glColorP3ui(type_::GLenum, color::GLuint)::Void),
:(glUniform3uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glVertexP4ui(type_::GLenum, value::GLuint)::Void),
:(glVertexAttribI4sv(index::GLuint, v::Ptr{GLshort})::Void),
:(glCheckFramebufferStatus(target::GLenum)::Cint),
:(glGetActiveUniformBlockiv(program::GLuint, uniformBlockIndex::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glBindFragDataLocation(program::GLuint, color::GLuint, name::Ptr{GLchar})::Void),
:(glWaitSync(sync::GLsync, flags::GLbitfield, timeout::GLuint64)::Void),
:(glBindVertexArray(array::GLuint)::Void),
:(glDrawElementsBaseVertex(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, basevertex::GLint)::Void),
:(glDrawElementsInstancedBaseVertex(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, instancecount::GLsizei, basevertex::GLint)::Void),
:(glGetActiveUniformBlockName(program::GLuint, uniformBlockIndex::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, uniformBlockName::Ptr{GLchar})::Void),
:(glGenSamplers(count::GLsizei, samplers::Ptr{GLuint})::Void),
:(glVertexAttribP2uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glClearBufferiv(buffer::GLenum, drawbuffer::GLint, value::Ptr{GLint})::Void),
:(glGetRenderbufferParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribP1ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glFramebufferTexture(target::GLenum, attachment::GLenum, texture::GLuint, level::GLint)::Void),
:(glGetUniformuiv(program::GLuint, location::GLint, params::Ptr{GLuint})::Void),
:(glVertexAttribI1uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glSamplerParameterIiv(sampler::GLuint, pname::GLenum, param::Ptr{GLint})::Void),
:(glColorP4ui(type_::GLenum, color::GLuint)::Void),
:(glColorP3uiv(type_::GLenum, color::Ptr{GLuint})::Void),
:(glUniform1ui(location::GLint, v0::GLuint)::Void),
:(glVertexAttribI4ubv(index::GLuint, v::Ptr{GLubyte})::Void),
:(glVertexP3uiv(type_::GLenum, value::Ptr{GLuint})::Void),
:(glDeleteRenderbuffers(n::GLsizei, renderbuffers::Ptr{GLuint})::Void),
:(glIsFramebuffer(framebuffer::GLuint)::Bool),
:(glVertexAttribI4iv(index::GLuint, v::Ptr{GLint})::Void),
:(glFramebufferTextureLayer(target::GLenum, attachment::GLenum, texture::GLuint, level::GLint, layer::GLint)::Void),
:(glVertexAttribP3ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glTransformFeedbackVaryings(program::GLuint, count::GLsizei, varyings::Ptr{Uint8}, bufferMode::GLenum)::Void),
:(glVertexAttribP3uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glGetTexParameterIuiv(target::GLenum, pname::GLenum, params::Ptr{GLuint})::Void),
:(glGetInteger64v(pname::GLenum, params::Ptr{GLint64})::Void),
:(glDrawElementsInstanced(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, instancecount::GLsizei)::Void),
:(glVertexP4uiv(type_::GLenum, value::Ptr{GLuint})::Void),
:(glNormalP3ui(type_::GLenum, coords::GLuint)::Void),
:(glFramebufferRenderbuffer(target::GLenum, attachment::GLenum, renderbuffertarget::GLenum, renderbuffer::GLuint)::Void),
:(glDrawRangeElementsBaseVertex(mode::GLenum, start::GLuint, END::GLuint, count::GLsizei, type_::GLenum, indices::Ptr{Void}, basevertex::GLint)::Void),
:(glUniform3ui(location::GLint, v0::GLuint, v1::GLuint, v2::GLuint)::Void),
:(glTexCoordP4ui(type_::GLenum, coords::GLuint)::Void),
:(glMultiTexCoordP2uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glFlushMappedBufferRange(target::GLenum, offset::GLintptr, length::GLsizeiptr)::Void),
:(glTexImage3DMultisample(target::GLenum, samples::GLsizei, internalformat::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, fixedsamplelocations::GLboolean)::Void),
:(glSampleMaski(index::GLuint, mask::GLbitfield)::Void),
:(glGetSynciv(sync::GLsync, pname::GLenum, bufSize::GLsizei, length::Ptr{GLsizei}, values::Ptr{GLint})::Void),
:(glDeleteSamplers(count::GLsizei, samplers::Ptr{GLuint})::Void),
:(glPrimitiveRestartIndex(index::GLuint)::Void),
:(glQueryCounter(id::GLuint, target::GLenum)::Void),
:(glGenFramebuffers(n::GLsizei, framebuffers::Ptr{GLuint})::Void),
:(glGetFramebufferAttachmentParameteriv(target::GLenum, attachment::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glBindBufferRange(target::GLenum, index::GLuint, buffer::GLuint, offset::GLintptr, size::GLsizeiptr)::Void),
:(glDisablei(target::GLenum, index::GLuint)::Void),
:(glVertexAttribI3i(index::GLuint, x::GLint, y::GLint, z::GLint)::Void),
:(glVertexAttribI2ui(index::GLuint, x::GLuint, y::GLuint)::Void),
:(glUniform2ui(location::GLint, v0::GLuint, v1::GLuint)::Void),
:(glUniform4ui(location::GLint, v0::GLuint, v1::GLuint, v2::GLuint, v3::GLuint)::Void)]
