#Types, functions and constants, needed on top of the common ones
#types
const GL_GL42_TYPES = [
]
#constants
const GL_GL42_CONSTANTS = [
:(const DOUBLE_MAT3                                                     = 0x8F47),
:(const FRACTIONAL_EVEN                                                 = 0x8E7C),
:(const COMPRESSED_RED_RGTC1                                            = 0x8DBB),
:(const INT_IMAGE_CUBE_MAP_ARRAY                                        = 0x905F),
:(const SYNC_GPU_COMMANDS_COMPLETE                                      = 0x9117),
:(const ONE_MINUS_SRC1_COLOR                                            = 0x88FA),
:(const HIGH_INT                                                        = 0x8DF5),
:(const IMAGE_2D_MULTISAMPLE                                            = 0x9055),
:(const R8I                                                             = 0x8231),
:(const UNSIGNED_INT_IMAGE_1D                                           = 0x9062),
:(const TEXTURE_FIXED_SAMPLE_LOCATIONS                                  = 0x9107),
:(const QUERY_BY_REGION_NO_WAIT                                         = 0x8E16),
:(const FRAMEBUFFER_ATTACHMENT_RED_SIZE                                 = 0x8212),
:(const R11F_G11F_B10F                                                  = 0x8C3A),
:(const MAX_VERTEX_UNIFORM_BLOCKS                                       = 0x8A2B),
:(const COMPRESSED_SIGNED_RED_RGTC1                                     = 0x8DBC),
:(const RGB8I                                                           = 0x8D8F),
:(const RGBA16I                                                         = 0x8D88),
:(const ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER         = 0x92C8),
:(const MAX_CLIP_DISTANCES                                              = 0x0D32),
:(const RGB9_E5                                                         = 0x8C3D),
:(const PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY                              = 0x9103),
:(const TEXTURE_BINDING_BUFFER                                          = 0x8C2C),
:(const SHADER_IMAGE_ACCESS_BARRIER_BIT                                 = 0x00000020),
:(const MIN_PROGRAM_TEXTURE_GATHER_OFFSET                               = 0x8E5E),
:(const RG_INTEGER                                                      = 0x8228),
:(const RENDERBUFFER_BINDING                                            = 0x8CA7),
:(const SYNC_FLUSH_COMMANDS_BIT                                         = 0x00000001),
:(const DOUBLE_VEC3                                                     = 0x8FFD),
:(const PROGRAM_PIPELINE_BINDING                                        = 0x825A),
:(const ACTIVE_SUBROUTINES                                              = 0x8DE5),
:(const GEOMETRY_INPUT_TYPE                                             = 0x8917),
:(const DRAW_FRAMEBUFFER                                                = 0x8CA9),
:(const NUM_COMPATIBLE_SUBROUTINES                                      = 0x8E4A),
:(const MAX_UNIFORM_BLOCK_SIZE                                          = 0x8A30),
:(const R16                                                             = 0x822A),
:(const PIXEL_BUFFER_BARRIER_BIT                                        = 0x00000080),
:(const TEXTURE_RED_TYPE                                                = 0x8C10),
:(const MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS                         = 0x92CD),
:(const MAX_FRAGMENT_ATOMIC_COUNTERS                                    = 0x92D6),
:(const UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY                         = 0x906C),
:(const MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS                        = 0x8A33),
:(const TEXTURE_STENCIL_SIZE                                            = 0x88F1),
:(const MAX_TESS_EVALUATION_ATOMIC_COUNTERS                             = 0x92D4),
:(const R32F                                                            = 0x822E),
:(const TRANSFORM_FEEDBACK_VARYINGS                                     = 0x8C83),
:(const TIMEOUT_EXPIRED                                                 = 0x911B),
:(const PRIMITIVE_RESTART_INDEX                                         = 0x8F9E),
:(const MAX_COMBINED_UNIFORM_BLOCKS                                     = 0x8A2E),
:(const FIRST_VERTEX_CONVENTION                                         = 0x8E4D),
:(const TEXTURE_GREEN_TYPE                                              = 0x8C11),
:(const WAIT_FAILED                                                     = 0x911D),
:(const MAX_TESS_EVALUATION_UNIFORM_BLOCKS                              = 0x8E8A),
:(const RENDERBUFFER_STENCIL_SIZE                                       = 0x8D55),
:(const INT_SAMPLER_2D_RECT                                             = 0x8DCD),
:(const IMAGE_BINDING_NAME                                              = 0x8F3A),
:(const PROGRAM_BINARY_LENGTH                                           = 0x8741),
:(const MAX_ARRAY_TEXTURE_LAYERS                                        = 0x88FF),
:(const CLIP_DISTANCE3                                                  = 0x3003),
:(const RGB16_SNORM                                                     = 0x8F9A),
:(const COLOR_ATTACHMENT0                                               = 0x8CE0),
:(const PATCH_DEFAULT_INNER_LEVEL                                       = 0x8E73),
:(const VIEWPORT_SUBPIXEL_BITS                                          = 0x825C),
:(const ATOMIC_COUNTER_BUFFER_DATA_SIZE                                 = 0x92C4),
:(const NUM_PROGRAM_BINARY_FORMATS                                      = 0x87FE),
:(const MAX_TESS_PATCH_COMPONENTS                                       = 0x8E84),
:(const SAMPLE_SHADING                                                  = 0x8C36),
:(const MAX_INTEGER_SAMPLES                                             = 0x9110),
:(const MAX_DUAL_SOURCE_DRAW_BUFFERS                                    = 0x88FC),
:(const FRAMEBUFFER_INCOMPLETE_MULTISAMPLE                              = 0x8D56),
:(const ALL_SHADER_BITS                                                 = 0xFFFFFFFF),
:(const TEXTURE_FETCH_BARRIER_BIT                                       = 0x00000008),
:(const FIXED                                                           = 0x140C),
:(const LOW_FLOAT                                                       = 0x8DF0),
:(const COLOR_ATTACHMENT13                                              = 0x8CED),
:(const TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN                           = 0x8C88),
:(const STENCIL_INDEX1                                                  = 0x8D46),
:(const RGB8UI                                                          = 0x8D7D),
:(const CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT                             = 0x0001),
:(const UNSIGNED_INT_IMAGE_2D_RECT                                      = 0x9065),
:(const INT_IMAGE_CUBE                                                  = 0x905B),
:(const BUFFER_MAP_LENGTH                                               = 0x9120),
:(const ATOMIC_COUNTER_BUFFER_BINDING                                   = 0x92C1),
:(const R32UI                                                           = 0x8236),
:(const ANY_SAMPLES_PASSED                                              = 0x8C2F),
:(const DRAW_INDIRECT_BUFFER_BINDING                                    = 0x8F43),
:(const TEXTURE_2D_MULTISAMPLE                                          = 0x9100),
:(const R8                                                              = 0x8229),
:(const VERTEX_ARRAY_BINDING                                            = 0x85B5),
:(const UNIFORM_SIZE                                                    = 0x8A38),
:(const DRAW_INDIRECT_BUFFER                                            = 0x8F3F),
:(const NUM_SAMPLE_COUNTS                                               = 0x9380),
:(const IMAGE_BINDING_LAYER                                             = 0x8F3D),
:(const SIGNED_NORMALIZED                                               = 0x8F9C),
:(const TEXTURE_CUBE_MAP_ARRAY                                          = 0x9009),
:(const UNIFORM_OFFSET                                                  = 0x8A3B),
:(const RG8I                                                            = 0x8237),
:(const DOUBLE_MAT4                                                     = 0x8F48),
:(const MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS                         = 0x8E82),
:(const FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER                              = 0x8CDB),
:(const SAMPLER_2D_ARRAY_SHADOW                                         = 0x8DC4),
:(const HALF_FLOAT                                                      = 0x140B),
:(const DEPTH_ATTACHMENT                                                = 0x8D00),
:(const UNIFORM_BLOCK_DATA_SIZE                                         = 0x8A40),
:(const IMPLEMENTATION_COLOR_READ_TYPE                                  = 0x8B9A),
:(const MAX_GEOMETRY_SHADER_INVOCATIONS                                 = 0x8E5A),
:(const RGB16I                                                          = 0x8D89),
:(const RENDERBUFFER_INTERNAL_FORMAT                                    = 0x8D44),
:(const DOUBLE_MAT2                                                     = 0x8F46),
:(const IMAGE_2D_ARRAY                                                  = 0x9053),
:(const TEXTURE_INTENSITY_TYPE                                          = 0x8C15),
:(const MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS                   = 0x8C8A),
:(const DOUBLE_MAT2x3                                                   = 0x8F49),
:(const PACK_COMPRESSED_BLOCK_DEPTH                                     = 0x912D),
:(const IMAGE_BINDING_ACCESS                                            = 0x8F3E),
:(const SYNC_FENCE                                                      = 0x9116),
:(const UNSIGNED_INT_24_8                                               = 0x84FA),
:(const PACK_COMPRESSED_BLOCK_HEIGHT                                    = 0x912C),
:(const PROXY_TEXTURE_2D_ARRAY                                          = 0x8C1B),
:(const PROVOKING_VERTEX                                                = 0x8E4F),
:(const TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY                            = 0x9105),
:(const RGB10_A2UI                                                      = 0x906F),
:(const RED_INTEGER                                                     = 0x8D94),
:(const OBJECT_TYPE                                                     = 0x9112),
:(const TEXTURE_LUMINANCE_TYPE                                          = 0x8C14),
:(const UNSIGNED_INT_IMAGE_CUBE                                         = 0x9066),
:(const RGB_INTEGER                                                     = 0x8D98),
:(const UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY                       = 0x910D),
:(const FRAGMENT_INTERPOLATION_OFFSET_BITS                              = 0x8E5D),
:(const IMPLEMENTATION_COLOR_READ_FORMAT                                = 0x8B9B),
:(const MAX_RECTANGLE_TEXTURE_SIZE                                      = 0x84F8),
:(const UNIFORM_TYPE                                                    = 0x8A37),
:(const DOUBLE_MAT3x2                                                   = 0x8F4B),
:(const COLOR_ATTACHMENT2                                               = 0x8CE2),
:(const UNIFORM_BARRIER_BIT                                             = 0x00000004),
:(const TESS_CONTROL_SHADER_BIT                                         = 0x00000008),
:(const MAX_SAMPLE_MASK_WORDS                                           = 0x8E59),
:(const DOUBLE_MAT4x3                                                   = 0x8F4E),
:(const MAX_GEOMETRY_IMAGE_UNIFORMS                                     = 0x90CD),
:(const CONDITION_SATISFIED                                             = 0x911C),
:(const DOUBLE_VEC2                                                     = 0x8FFC),
:(const UNSIGNED_NORMALIZED                                             = 0x8C17),
:(const IMAGE_2D_RECT                                                   = 0x904F),
:(const MAX_GEOMETRY_INPUT_COMPONENTS                                   = 0x9123),
:(const TEXTURE_RECTANGLE                                               = 0x84F5),
:(const VERTEX_ATTRIB_ARRAY_DIVISOR                                     = 0x88FE),
:(const ATOMIC_COUNTER_BUFFER_START                                     = 0x92C2),
:(const UNIFORM_NAME_LENGTH                                             = 0x8A39),
:(const IMAGE_FORMAT_COMPATIBILITY_TYPE                                 = 0x90C7),
:(const MAX_GEOMETRY_TEXTURE_IMAGE_UNITS                                = 0x8C29),
:(const MAX_VERTEX_IMAGE_UNIFORMS                                       = 0x90CA),
:(const UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY                               = 0x906A),
:(const MAX_ATOMIC_COUNTER_BUFFER_BINDINGS                              = 0x92DC),
:(const IMAGE_CUBE_MAP_ARRAY                                            = 0x9054),
:(const FRAMEBUFFER_COMPLETE                                            = 0x8CD5),
:(const TEXTURE_BUFFER                                                  = 0x8C2A),
:(const IMAGE_3D                                                        = 0x904E),
:(const TEXTURE_BINDING_CUBE_MAP_ARRAY                                  = 0x900A),
:(const INT_SAMPLER_CUBE                                                = 0x8DCC),
:(const UNIFORM_BUFFER_OFFSET_ALIGNMENT                                 = 0x8A34),
:(const VIEWPORT_INDEX_PROVOKING_VERTEX                                 = 0x825F),
:(const MAP_FLUSH_EXPLICIT_BIT                                          = 0x0010),
:(const INT_SAMPLER_CUBE_MAP_ARRAY                                      = 0x900E),
:(const UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY                             = 0x900F),
:(const BUFFER_MAP_OFFSET                                               = 0x9121),
:(const UNSIGNED_INT_5_9_9_9_REV                                        = 0x8C3E),
:(const IMAGE_FORMAT_COMPATIBILITY_BY_SIZE                              = 0x90C8),
:(const READ_FRAMEBUFFER                                                = 0x8CA8),
:(const PROGRAM_SEPARABLE                                               = 0x8258),
:(const RENDERBUFFER_ALPHA_SIZE                                         = 0x8D53),
:(const INT_IMAGE_1D_ARRAY                                              = 0x905D),
:(const DOUBLE_MAT2x4                                                   = 0x8F4A),
:(const MAX_FRAGMENT_UNIFORM_VECTORS                                    = 0x8DFD),
:(const TEXTURE_SWIZZLE_G                                               = 0x8E43),
:(const MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS                            = 0x8E81),
:(const BGRA_INTEGER                                                    = 0x8D9B),
:(const RG16UI                                                          = 0x823A),
:(const RG8_SNORM                                                       = 0x8F95),
:(const LAYER_PROVOKING_VERTEX                                          = 0x825E),
:(const MAX_RENDERBUFFER_SIZE                                           = 0x84E8),
:(const TRANSFORM_FEEDBACK_BUFFER_BINDING                               = 0x8C8F),
:(const STENCIL_INDEX8                                                  = 0x8D48),
:(const FRAMEBUFFER_BARRIER_BIT                                         = 0x00000400),
:(const UNIFORM_BLOCK_NAME_LENGTH                                       = 0x8A41),
:(const MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS                          = 0x8A31),
:(const INT_SAMPLER_1D                                                  = 0x8DC9),
:(const TIME_ELAPSED                                                    = 0x88BF),
:(const SAMPLER_CUBE_MAP_ARRAY_SHADOW                                   = 0x900D),
:(const UNPACK_COMPRESSED_BLOCK_DEPTH                                   = 0x9129),
:(const TRANSFORM_FEEDBACK_BUFFER                                       = 0x8C8E),
:(const UNPACK_COMPRESSED_BLOCK_HEIGHT                                  = 0x9128),
:(const R8_SNORM                                                        = 0x8F94),
:(const TEXTURE_2D_ARRAY                                                = 0x8C1A),
:(const FRAMEBUFFER_ATTACHMENT_GREEN_SIZE                               = 0x8213),
:(const CLAMP_READ_COLOR                                                = 0x891C),
:(const FRAMEBUFFER_INCOMPLETE_READ_BUFFER                              = 0x8CDC),
:(const PATCH_VERTICES                                                  = 0x8E72),
:(const NUM_EXTENSIONS                                                  = 0x821D),
:(const MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS                        = 0x8E85),
:(const DEPTH_STENCIL_ATTACHMENT                                        = 0x821A),
:(const RENDERBUFFER_RED_SIZE                                           = 0x8D50),
:(const TEXTURE_1D_ARRAY                                                = 0x8C18),
:(const UNSIGNED_INT_SAMPLER_2D                                         = 0x8DD2),
:(const MAX_TESS_CONTROL_INPUT_COMPONENTS                               = 0x886C),
:(const INT_2_10_10_10_REV                                              = 0x8D9F),
:(const PROXY_TEXTURE_1D_ARRAY                                          = 0x8C19),
:(const CLAMP_VERTEX_COLOR                                              = 0x891A),
:(const R16UI                                                           = 0x8234),
:(const DRAW_FRAMEBUFFER_BINDING                                        = 0x8CA6),
:(const UNSIGNED_INT_IMAGE_1D_ARRAY                                     = 0x9068),
:(const UNIFORM_BUFFER_START                                            = 0x8A29),
:(const MAX_TESS_EVALUATION_UNIFORM_COMPONENTS                          = 0x8E80),
:(const LINES_ADJACENCY                                                 = 0x000A),
:(const COLOR_ATTACHMENT6                                               = 0x8CE6),
:(const ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER      = 0x92C9),
:(const ACTIVE_SUBROUTINE_MAX_LENGTH                                    = 0x8E48),
:(const UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER                       = 0x8A44),
:(const MIN_FRAGMENT_INTERPOLATION_OFFSET                               = 0x8E5B),
:(const UNPACK_COMPRESSED_BLOCK_SIZE                                    = 0x912A),
:(const DEPTH32F_STENCIL8                                               = 0x8CAD),
:(const COMPRESSED_RG                                                   = 0x8226),
:(const R8UI                                                            = 0x8232),
:(const UNIFORM_MATRIX_STRIDE                                           = 0x8A3D),
:(const FRAMEBUFFER_ATTACHMENT_BLUE_SIZE                                = 0x8214),
:(const DOUBLE_MAT4x2                                                   = 0x8F4D),
:(const RENDERBUFFER_HEIGHT                                             = 0x8D43),
:(const FLOAT_32_UNSIGNED_INT_24_8_REV                                  = 0x8DAD),
:(const RG16F                                                           = 0x822F),
:(const MAX_COLOR_TEXTURE_SAMPLES                                       = 0x910E),
:(const SAMPLE_MASK                                                     = 0x8E51),
:(const ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES             = 0x92C6),
:(const TEXTURE_ALPHA_TYPE                                              = 0x8C13),
:(const UNSIGNED_INT_SAMPLER_CUBE                                       = 0x8DD4),
:(const R32I                                                            = 0x8235),
:(const PROXY_TEXTURE_2D_MULTISAMPLE                                    = 0x9101),
:(const MAX_TESS_CONTROL_UNIFORM_BLOCKS                                 = 0x8E89),
:(const VERTEX_ATTRIB_ARRAY_INTEGER                                     = 0x88FD),
:(const IMAGE_2D_MULTISAMPLE_ARRAY                                      = 0x9056),
:(const RGBA32UI                                                        = 0x8D70),
:(const COLOR_ATTACHMENT10                                              = 0x8CEA),
:(const MAX_FRAGMENT_INTERPOLATION_OFFSET                               = 0x8E5C),
:(const MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS                             = 0x92D0),
:(const ISOLINES                                                        = 0x8E7A),
:(const FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE                    = 0x8CD3),
:(const RG8UI                                                           = 0x8238),
:(const RGBA16UI                                                        = 0x8D76),
:(const MAX_TESS_GEN_LEVEL                                              = 0x8E7E),
:(const PRIMITIVES_GENERATED                                            = 0x8C87),
:(const FRAMEBUFFER_SRGB                                                = 0x8DB9),
:(const RGBA8_SNORM                                                     = 0x8F97),
:(const UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE                             = 0x910A),
:(const RENDERBUFFER_WIDTH                                              = 0x8D42),
:(const TIMESTAMP                                                       = 0x8E28),
:(const DEPTH_CLAMP                                                     = 0x864F),
:(const RGBA_INTEGER                                                    = 0x8D99),
:(const TEXTURE_CUBE_MAP_SEAMLESS                                       = 0x884F),
:(const SIGNALED                                                        = 0x9119),
:(const UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES                            = 0x8A43),
:(const VERTEX_SHADER_BIT                                               = 0x00000001),
:(const RGBA16F                                                         = 0x881A),
:(const COLOR_ATTACHMENT11                                              = 0x8CEB),
:(const FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE                           = 0x8211),
:(const UNSIGNED_INT_IMAGE_2D_ARRAY                                     = 0x9069),
:(const MAJOR_VERSION                                                   = 0x821B),
:(const COLOR_ATTACHMENT5                                               = 0x8CE5),
:(const MAX_TESS_EVALUATION_IMAGE_UNIFORMS                              = 0x90CC),
:(const MEDIUM_INT                                                      = 0x8DF4),
:(const R16_SNORM                                                       = 0x8F98),
:(const UNSIGNED_INT_SAMPLER_3D                                         = 0x8DD3),
:(const IMAGE_BINDING_LEVEL                                             = 0x8F3B),
:(const MAX_PROGRAM_TEXEL_OFFSET                                        = 0x8905),
:(const UNDEFINED_VERTEX                                                = 0x8260),
:(const MAP_UNSYNCHRONIZED_BIT                                          = 0x0020),
:(const RG                                                              = 0x8227),
:(const BGR_INTEGER                                                     = 0x8D9A),
:(const TESS_GEN_VERTEX_ORDER                                           = 0x8E78),
:(const ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER             = 0x92CA),
:(const FIXED_ONLY                                                      = 0x891D),
:(const UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER                     = 0x8A46),
:(const MAX_IMAGE_SAMPLES                                               = 0x906D),
:(const INT_SAMPLER_2D_ARRAY                                            = 0x8DCF),
:(const UNSIGNED_INT_IMAGE_BUFFER                                       = 0x9067),
:(const RASTERIZER_DISCARD                                              = 0x8C89),
:(const FRAMEBUFFER                                                     = 0x8D40),
:(const INT_SAMPLER_3D                                                  = 0x8DCB),
:(const RGB565                                                          = 0x8D62),
:(const RGBA8UI                                                         = 0x8D7C),
:(const COLOR_ATTACHMENT9                                               = 0x8CE9),
:(const MAX_GEOMETRY_OUTPUT_VERTICES                                    = 0x8DE0),
:(const FRAMEBUFFER_INCOMPLETE_ATTACHMENT                               = 0x8CD6),
:(const ACTIVE_UNIFORM_BLOCKS                                           = 0x8A36),
:(const IMAGE_2D                                                        = 0x904D),
:(const COLOR_ATTACHMENT15                                              = 0x8CEF),
:(const SAMPLER_2D_RECT_SHADOW                                          = 0x8B64),
:(const UNSIGNED_INT_VEC4                                               = 0x8DC8),
:(const ONE_MINUS_SRC1_ALPHA                                            = 0x88FB),
:(const GEOMETRY_OUTPUT_TYPE                                            = 0x8918),
:(const TRANSFORM_FEEDBACK_BUFFER_START                                 = 0x8C84),
:(const UNIFORM_BLOCK_ACTIVE_UNIFORMS                                   = 0x8A42),
:(const COMPATIBLE_SUBROUTINES                                          = 0x8E4B),
:(const SYNC_FLAGS                                                      = 0x9115),
:(const UNSIGNED_INT_IMAGE_3D                                           = 0x9064),
:(const MAX_VIEWPORTS                                                   = 0x825B),
:(const INT_SAMPLER_2D_MULTISAMPLE_ARRAY                                = 0x910C),
:(const TRIANGLES_ADJACENCY                                             = 0x000C),
:(const MAX_VARYING_COMPONENTS                                          = 0x8B4B),
:(const MAP_INVALIDATE_RANGE_BIT                                        = 0x0004),
:(const CONTEXT_COMPATIBILITY_PROFILE_BIT                               = 0x00000002),
:(const MAX_IMAGE_UNITS                                                 = 0x8F38),
:(const RENDERBUFFER_GREEN_SIZE                                         = 0x8D51),
:(const RG16_SNORM                                                      = 0x8F99),
:(const QUERY_WAIT                                                      = 0x8E13),
:(const ATOMIC_COUNTER_BUFFER_SIZE                                      = 0x92C3),
:(const ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER             = 0x92CB),
:(const FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS                            = 0x8DA8),
:(const UNIFORM_BLOCK_INDEX                                             = 0x8A3A),
:(const UNSIGNED_INT_SAMPLER_1D_ARRAY                                   = 0x8DD6),
:(const RG8                                                             = 0x822B),
:(const PATCHES                                                         = 0x000E),
:(const MAX_PATCH_VERTICES                                              = 0x8E7D),
:(const SAMPLER_1D_ARRAY                                                = 0x8DC0),
:(const VERTEX_ATTRIB_ARRAY_BARRIER_BIT                                 = 0x00000001),
:(const FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING                           = 0x8210),
:(const RGBA32F                                                         = 0x8814),
:(const UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER                 = 0x84F0),
:(const PACK_COMPRESSED_BLOCK_SIZE                                      = 0x912E),
:(const LAST_VERTEX_CONVENTION                                          = 0x8E4E),
:(const MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS                           = 0x8F9F),
:(const DOUBLE_VEC4                                                     = 0x8FFE),
:(const BLUE_INTEGER                                                    = 0x8D96),
:(const VIEWPORT_BOUNDS_RANGE                                           = 0x825D),
:(const MAX_TEXTURE_BUFFER_SIZE                                         = 0x8C2B),
:(const CLIP_DISTANCE1                                                  = 0x3001),
:(const READ_FRAMEBUFFER_BINDING                                        = 0x8CAA),
:(const TEXTURE_BINDING_2D_MULTISAMPLE                                  = 0x9104),
:(const INDEX                                                           = 0x8222),
:(const TEXTURE_SHARED_SIZE                                             = 0x8C3F),
:(const TEXTURE_BINDING_RECTANGLE                                       = 0x84F6),
:(const UNSIGNED_INT_SAMPLER_BUFFER                                     = 0x8DD8),
:(const DOUBLE_MAT3x4                                                   = 0x8F4C),
:(const INT_IMAGE_2D_RECT                                               = 0x905A),
:(const COLOR_ATTACHMENT14                                              = 0x8CEE),
:(const GREEN_INTEGER                                                   = 0x8D95),
:(const ATOMIC_COUNTER_BARRIER_BIT                                      = 0x00001000),
:(const MIN_SAMPLE_SHADING_VALUE                                        = 0x8C37),
:(const INT_IMAGE_2D_MULTISAMPLE                                        = 0x9060),
:(const FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL                            = 0x8CD2),
:(const ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS                    = 0x92C5),
:(const SAMPLER_1D_ARRAY_SHADOW                                         = 0x8DC3),
:(const RENDERBUFFER_BLUE_SIZE                                          = 0x8D52),
:(const TEXTURE_2D_MULTISAMPLE_ARRAY                                    = 0x9102),
:(const PROGRAM_BINARY_RETRIEVABLE_HINT                                 = 0x8257),
:(const SAMPLE_POSITION                                                 = 0x8E50),
:(const SAMPLER_BUFFER                                                  = 0x8DC2),
:(const RENDERBUFFER_SAMPLES                                            = 0x8CAB),
:(const COLOR_ATTACHMENT12                                              = 0x8CEC),
:(const RGB32F                                                          = 0x8815),
:(const RENDERBUFFER                                                    = 0x8D41),
:(const RGBA8I                                                          = 0x8D8E),
:(const CLIP_DISTANCE2                                                  = 0x3002),
:(const FRAMEBUFFER_UNSUPPORTED                                         = 0x8CDD),
:(const ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH                            = 0x8A35),
:(const IMAGE_BUFFER                                                    = 0x9051),
:(const INT_SAMPLER_2D                                                  = 0x8DCA),
:(const SAMPLER_CUBE_SHADOW                                             = 0x8DC5),
:(const SAMPLER_2D_MULTISAMPLE                                          = 0x9108),
:(const UNSIGNALED                                                      = 0x9118),
:(const INTERLEAVED_ATTRIBS                                             = 0x8C8C),
:(const MIN_MAP_BUFFER_ALIGNMENT                                        = 0x90BC),
:(const SAMPLER_2D_ARRAY                                                = 0x8DC1),
:(const QUERY_NO_WAIT                                                   = 0x8E14),
:(const UNIFORM_IS_ROW_MAJOR                                            = 0x8A3E),
:(const SAMPLE_MASK_VALUE                                               = 0x8E52),
:(const BUFFER_ACCESS_FLAGS                                             = 0x911F),
:(const COMPARE_REF_TO_TEXTURE                                          = 0x884E),
:(const MAP_READ_BIT                                                    = 0x0001),
:(const TESS_CONTROL_SHADER                                             = 0x8E88),
:(const INT_IMAGE_2D_ARRAY                                              = 0x905E),
:(const RG16                                                            = 0x822C),
:(const ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER               = 0x92C7),
:(const MAX_UNIFORM_BUFFER_BINDINGS                                     = 0x8A2F),
:(const TESS_GEN_POINT_MODE                                             = 0x8E79),
:(const MAX_COMBINED_ATOMIC_COUNTERS                                    = 0x92D7),
:(const MAX_VARYING_VECTORS                                             = 0x8DFC),
:(const UNIFORM_BUFFER_SIZE                                             = 0x8A2A),
:(const UNSIGNED_INT_VEC3                                               = 0x8DC7),
:(const ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH                            = 0x8E49),
:(const INT_SAMPLER_BUFFER                                              = 0x8DD0),
:(const IMAGE_FORMAT_COMPATIBILITY_BY_CLASS                             = 0x90C9),
:(const TEXTURE_SWIZZLE_R                                               = 0x8E42),
:(const RENDERBUFFER_DEPTH_SIZE                                         = 0x8D54),
:(const IMAGE_BINDING_FORMAT                                            = 0x906E),
:(const MAX_COLOR_ATTACHMENTS                                           = 0x8CDF),
:(const MAX_TESS_CONTROL_OUTPUT_COMPONENTS                              = 0x8E83),
:(const RG32F                                                           = 0x8230),
:(const RGBA32I                                                         = 0x8D82),
:(const TEXTURE_BINDING_1D_ARRAY                                        = 0x8C1C),
:(const CONTEXT_CORE_PROFILE_BIT                                        = 0x00000001),
:(const MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS                 = 0x8E1F),
:(const FRAMEBUFFER_ATTACHMENT_OBJECT_NAME                              = 0x8CD1),
:(const INT_SAMPLER_2D_MULTISAMPLE                                      = 0x9109),
:(const MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS                      = 0x8C80),
:(const MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS                            = 0x8DE1),
:(const UNSIGNED_INT_10F_11F_11F_REV                                    = 0x8C3B),
:(const MAX_GEOMETRY_ATOMIC_COUNTERS                                    = 0x92D5),
:(const MAX_SAMPLES                                                     = 0x8D57),
:(const MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS                   = 0x8F39),
:(const MAX_TESS_CONTROL_UNIFORM_COMPONENTS                             = 0x8E7F),
:(const RG32UI                                                          = 0x823C),
:(const DEPTH_COMPONENT32F                                              = 0x8CAC),
:(const INT_IMAGE_3D                                                    = 0x9059),
:(const PROXY_TEXTURE_RECTANGLE                                         = 0x84F7),
:(const LOW_INT                                                         = 0x8DF3),
:(const INT_IMAGE_1D                                                    = 0x9057),
:(const UNIFORM_BUFFER                                                  = 0x8A11),
:(const SYNC_CONDITION                                                  = 0x9113),
:(const NUM_SHADER_BINARY_FORMATS                                       = 0x8DF9),
:(const CONTEXT_PROFILE_MASK                                            = 0x9126),
:(const MAP_INVALIDATE_BUFFER_BIT                                       = 0x0008),
:(const PACK_COMPRESSED_BLOCK_WIDTH                                     = 0x912B),
:(const FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE                             = 0x8217),
:(const FRAMEBUFFER_DEFAULT                                             = 0x8218),
:(const UNIFORM_ARRAY_STRIDE                                            = 0x8A3C),
:(const SAMPLER_BINDING                                                 = 0x8919),
:(const MAP_WRITE_BIT                                                   = 0x0002),
:(const FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER                            = 0x8CD4),
:(const MIN_PROGRAM_TEXEL_OFFSET                                        = 0x8904),
:(const PROXY_TEXTURE_CUBE_MAP_ARRAY                                    = 0x900B),
:(const IMAGE_BINDING_LAYERED                                           = 0x8F3C),
:(const DEPTH24_STENCIL8                                                = 0x88F0),
:(const MAX_SERVER_WAIT_TIMEOUT                                         = 0x9111),
:(const PROGRAM_POINT_SIZE                                              = 0x8642),
:(const INVALID_FRAMEBUFFER_OPERATION                                   = 0x0506),
:(const FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE                               = 0x8216),
:(const IMAGE_CUBE                                                      = 0x9050),
:(const FRAMEBUFFER_BINDING                                             = 0x8CA6),
:(const RGB32I                                                          = 0x8D83),
:(const COLOR_ATTACHMENT1                                               = 0x8CE1),
:(const INT_IMAGE_BUFFER                                                = 0x905C),
:(const ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS                             = 0x8E47),
:(const COPY_WRITE_BUFFER                                               = 0x8F37),
:(const TESS_GEN_SPACING                                                = 0x8E77),
:(const ACTIVE_PROGRAM                                                  = 0x8259),
:(const RGB16F                                                          = 0x881B),
:(const MAX_VERTEX_ATOMIC_COUNTERS                                      = 0x92D2),
:(const UNSIGNED_INT_IMAGE_2D_MULTISAMPLE                               = 0x906B),
:(const MAX_TESS_EVALUATION_INPUT_COMPONENTS                            = 0x886D),
:(const PATCH_DEFAULT_OUTER_LEVEL                                       = 0x8E74),
:(const RGB16UI                                                         = 0x8D77),
:(const GEOMETRY_SHADER_BIT                                             = 0x00000004),
:(const MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS                         = 0x8C8B),
:(const CLIP_DISTANCE4                                                  = 0x3004),
:(const MINOR_VERSION                                                   = 0x821C),
:(const MAX_VERTEX_ATOMIC_COUNTER_BUFFERS                               = 0x92CC),
:(const STENCIL_INDEX4                                                  = 0x8D47),
:(const MAX_COMBINED_ATOMIC_COUNTER_BUFFERS                             = 0x92D1),
:(const R16I                                                            = 0x8233),
:(const CLAMP_FRAGMENT_COLOR                                            = 0x891B),
:(const STENCIL_ATTACHMENT                                              = 0x8D20),
:(const ACTIVE_ATOMIC_COUNTER_BUFFERS                                   = 0x92D9),
:(const TEXTURE_SWIZZLE_RGBA                                            = 0x8E46),
:(const COLOR_ATTACHMENT3                                               = 0x8CE3),
:(const COMPRESSED_SIGNED_RG_RGTC2                                      = 0x8DBE),
:(const MAX_FRAGMENT_UNIFORM_BLOCKS                                     = 0x8A2D),
:(const TEXTURE_BINDING_2D_ARRAY                                        = 0x8C1D),
:(const MAX_GEOMETRY_UNIFORM_COMPONENTS                                 = 0x8DDF),
:(const MAX_TESS_CONTROL_IMAGE_UNIFORMS                                 = 0x90CB),
:(const UNPACK_COMPRESSED_BLOCK_WIDTH                                   = 0x9127),
:(const CLIP_DISTANCE0                                                  = 0x3000),
:(const MAX_GEOMETRY_OUTPUT_COMPONENTS                                  = 0x9124),
:(const RGBA16_SNORM                                                    = 0x8F9B),
:(const UNSIGNED_INT_IMAGE_2D                                           = 0x9063),
:(const TEXTURE_BUFFER_DATA_STORE_BINDING                               = 0x8C2D),
:(const TESS_EVALUATION_SHADER                                          = 0x8E87),
:(const BUFFER_UPDATE_BARRIER_BIT                                       = 0x00000200),
:(const FRAMEBUFFER_UNDEFINED                                           = 0x8219),
:(const TRANSFORM_FEEDBACK_BUFFER_SIZE                                  = 0x8C85),
:(const MAX_SUBROUTINES                                                 = 0x8DE7),
:(const RGBA_SNORM                                                      = 0x8F93),
:(const UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX                             = 0x92DA),
:(const UNSIGNED_INT_VEC2                                               = 0x8DC6),
:(const CLIP_DISTANCE5                                                  = 0x3005),
:(const ALL_BARRIER_BITS                                                = 0xFFFFFFFF),
:(const R16F                                                            = 0x822D),
:(const TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH                           = 0x8C76),
:(const TEXTURE_BLUE_TYPE                                               = 0x8C12),
:(const GEOMETRY_VERTICES_OUT                                           = 0x8916),
:(const UNSIGNED_INT_SAMPLER_1D                                         = 0x8DD1),
:(const COLOR_ATTACHMENT8                                               = 0x8CE8),
:(const GEOMETRY_SHADER                                                 = 0x8DD9),
:(const QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION                        = 0x8E4C),
:(const FRAMEBUFFER_ATTACHMENT_LAYERED                                  = 0x8DA7),
:(const TEXTURE_UPDATE_BARRIER_BIT                                      = 0x00000100),
:(const RGB8_SNORM                                                      = 0x8F96),
:(const TIMEOUT_IGNORED                                                 = 0xFFFFFFFFFFFFFFFF),
:(const TEXTURE_DEPTH_TYPE                                              = 0x8C16),
:(const TRANSFORM_FEEDBACK_BUFFER_MODE                                  = 0x8C7F),
:(const COMMAND_BARRIER_BIT                                             = 0x00000040),
:(const TESS_EVALUATION_SHADER_BIT                                      = 0x00000010),
:(const TEXTURE_SAMPLES                                                 = 0x9106),
:(const MAX_ATOMIC_COUNTER_BUFFER_SIZE                                  = 0x92D8),
:(const HIGH_FLOAT                                                      = 0x8DF2),
:(const MAX_PROGRAM_TEXTURE_GATHER_OFFSET                               = 0x8E5F),
:(const TEXTURE_SWIZZLE_A                                               = 0x8E45),
:(const RG32I                                                           = 0x823B),
:(const MAX_VERTEX_OUTPUT_COMPONENTS                                    = 0x9122),
:(const SAMPLER_2D_MULTISAMPLE_ARRAY                                    = 0x910B),
:(const TESS_CONTROL_OUTPUT_VERTICES                                    = 0x8E75),
:(const FRACTIONAL_ODD                                                  = 0x8E7B),
:(const MAX_FRAGMENT_IMAGE_UNIFORMS                                     = 0x90CE),
:(const COMPRESSED_RED                                                  = 0x8225),
:(const FRAGMENT_SHADER_BIT                                             = 0x00000002),
:(const TRANSFORM_FEEDBACK_BARRIER_BIT                                  = 0x00000800),
:(const CONTEXT_FLAGS                                                   = 0x821E),
:(const INT_IMAGE_2D                                                    = 0x9058),
:(const SAMPLER_CUBE_MAP_ARRAY                                          = 0x900C),
:(const RGB_SNORM                                                       = 0x8F92),
:(const FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE                              = 0x8CD0),
:(const UNIFORM_BLOCK_BINDING                                           = 0x8A3F),
:(const IMAGE_1D                                                        = 0x904C),
:(const SAMPLER_2D_RECT                                                 = 0x8B63),
:(const UNSIGNED_INT_SAMPLER_2D_RECT                                    = 0x8DD5),
:(const ATOMIC_COUNTER_BUFFER                                           = 0x92C0),
:(const MAX_DEPTH_TEXTURE_SAMPLES                                       = 0x910F),
:(const MAX_FRAGMENT_INPUT_COMPONENTS                                   = 0x9125),
:(const INT_IMAGE_2D_MULTISAMPLE_ARRAY                                  = 0x9061),
:(const QUERY_BY_REGION_WAIT                                            = 0x8E15),
:(const ALREADY_SIGNALED                                                = 0x911A),
:(const PRIMITIVE_RESTART                                               = 0x8F9D),
:(const SHADER_BINARY_FORMATS                                           = 0x8DF8),
:(const COLOR_ATTACHMENT7                                               = 0x8CE7),
:(const SEPARATE_ATTRIBS                                                = 0x8C8D),
:(const MAX_TESS_CONTROL_ATOMIC_COUNTERS                                = 0x92D3),
:(const UNIFORM_BUFFER_BINDING                                          = 0x8A28),
:(const ELEMENT_ARRAY_BARRIER_BIT                                       = 0x00000002),
:(const INVALID_INDEX                                                   = 0xFFFFFFFF),
:(const LINE_STRIP_ADJACENCY                                            = 0x000B),
:(const ACTIVE_SUBROUTINE_UNIFORMS                                      = 0x8DE6),
:(const RG16I                                                           = 0x8239),
:(const SRC1_COLOR                                                      = 0x88F9),
:(const STENCIL_INDEX16                                                 = 0x8D49),
:(const SYNC_STATUS                                                     = 0x9114),
:(const MAX_SUBROUTINE_UNIFORM_LOCATIONS                                = 0x8DE8),
:(const UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER              = 0x84F1),
:(const MAX_VERTEX_UNIFORM_VECTORS                                      = 0x8DFB),
:(const UNSIGNED_INT_SAMPLER_2D_ARRAY                                   = 0x8DD7),
:(const RG_SNORM                                                        = 0x8F91),
:(const MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS                      = 0x92CE),
:(const GEOMETRY_SHADER_INVOCATIONS                                     = 0x887F),
:(const ALPHA_INTEGER                                                   = 0x8D97),
:(const SHADER_COMPILER                                                 = 0x8DFA),
:(const MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS                    = 0x8E1E),
:(const DEPTH_STENCIL                                                   = 0x84F9),
:(const MAX_COMBINED_IMAGE_UNIFORMS                                     = 0x90CF),
:(const FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT                       = 0x8CD7),
:(const RGB32UI                                                         = 0x8D71),
:(const MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS                             = 0x92CF),
:(const FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE                               = 0x8215),
:(const TRIANGLE_STRIP_ADJACENCY                                        = 0x000D),
:(const CLIP_DISTANCE7                                                  = 0x3007),
:(const IMAGE_1D_ARRAY                                                  = 0x9052),
:(const MEDIUM_FLOAT                                                    = 0x8DF1),
:(const COMPRESSED_RG_RGTC2                                             = 0x8DBD),
:(const TEXTURE_IMMUTABLE_FORMAT                                        = 0x912F),
:(const TEXTURE_SWIZZLE_B                                               = 0x8E44),
:(const INT_SAMPLER_1D_ARRAY                                            = 0x8DCE),
:(const TESS_GEN_MODE                                                   = 0x8E76),
:(const CLIP_DISTANCE6                                                  = 0x3006),
:(const UNSIGNED_INT_ATOMIC_COUNTER                                     = 0x92DB),
:(const PROGRAM_BINARY_FORMATS                                          = 0x87FF),
:(const COPY_READ_BUFFER                                                = 0x8F36),
:(const MAX_TESS_EVALUATION_OUTPUT_COMPONENTS                           = 0x8E86),
:(const RED_SNORM                                                       = 0x8F90),
:(const COLOR_ATTACHMENT4                                               = 0x8CE4)]
#function bodies
const GL_GL42_FUNCTIONS = [
:(glClearBufferfv(buffer::GLenum, drawbuffer::GLint, value::Ptr{GLfloat})::Void),
:(glTexImage2DMultisample(target::GLenum, samples::GLsizei, internalformat::GLint, width::GLsizei, height::GLsizei, fixedsamplelocations::GLboolean)::Void),
:(glVertexAttribP4ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glUniform2uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glMultiTexCoordP3uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glUniform4dv(location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glProgramUniform1f(program::GLuint, location::GLint, v0::GLfloat)::Void),
:(glGetVertexAttribIiv(index::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glEnablei(target::GLenum, index::GLuint)::Void),
:(glGetSubroutineUniformLocation(program::GLuint, shadertype::GLenum, name::Ptr{GLchar})::Cint),
:(glProvokingVertex(mode::GLenum)::Void),
:(glProgramUniformMatrix2x4fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glProgramUniformMatrix2x4dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glDeleteVertexArrays(n::GLsizei, arrays::Ptr{GLuint})::Void),
:(glGetProgramPipelineInfoLog(pipeline::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, infoLog::Ptr{GLchar})::Void),
:(glVertexAttribI1iv(index::GLuint, v::Ptr{GLint})::Void),
:(glProgramParameteri(program::GLuint, pname::GLenum, value::GLint)::Void),
:(glFramebufferTexture3D(target::GLenum, attachment::GLenum, textarget::GLenum, texture::GLuint, level::GLint, zoffset::GLint)::Void),
:(glVertexP2ui(type_::GLenum, value::GLuint)::Void),
:(glVertexAttribI2iv(index::GLuint, v::Ptr{GLint})::Void),
:(glTexCoordP2ui(type_::GLenum, coords::GLuint)::Void),
:(glTexStorage3D(target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei, depth::GLsizei)::Void),
:(glVertexAttribP4uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glTexCoordP1ui(type_::GLenum, coords::GLuint)::Void),
:(glEndConditionalRender()::Void),
:(glTexParameterIiv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glDeleteSync(sync::GLsync)::Void),
:(glSamplerParameteri(sampler::GLuint, pname::GLenum, param::GLint)::Void),
:(glNormalP3uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glClearDepthf(d::GLfloat)::Void),
:(glDrawElementsIndirect(mode::GLenum, type_::GLenum, indirect::Ptr{Void})::Void),
:(glMinSampleShading(value::GLfloat)::Void),
:(glScissorIndexed(index::GLuint, left::GLint, bottom::GLint, width::GLsizei, height::GLsizei)::Void),
:(glGetActiveAtomicCounterBufferiv(program::GLuint, bufferIndex::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetBufferParameteri64v(target::GLenum, pname::GLenum, params::Ptr{GLint64})::Void),
:(glClientWaitSync(sync::GLsync, flags::GLbitfield, timeout::GLuClonglong)::Cint),
:(glViewportArrayv(first::GLuint, count::GLsizei, v::Ptr{GLfloat})::Void),
:(glProgramUniform4uiv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glGetActiveUniformName(program::GLuint, uniformIndex::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, uniformName::Ptr{GLchar})::Void),
:(glMultiTexCoordP4uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glTexStorage2D(target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glVertexAttribI4bv(index::GLuint, v::Ptr{GLbyte})::Void),
:(glGetUniformBlockIndex(program::GLuint, uniformBlockName::Ptr{GLchar})::Cuint),
:(glMultiTexCoordP1ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glBlendEquationi(buf::GLuint, mode::GLenum)::Void),
:(glGetProgramStageiv(program::GLuint, shadertype::GLenum, pname::GLenum, values::Ptr{GLint})::Void),
:(glProgramUniform3iv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glGetBooleani_v(target::GLenum, index::GLuint, data::Ptr{GLboolean})::Void),
:(glGetSamplerParameterfv(sampler::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glGetQueryObjecti64v(id::GLuint, pname::GLenum, params::Ptr{GLint64})::Void),
:(glVertexAttribI3uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glGetShaderPrecisionFormat(shadertype::GLenum, precisiontype::GLenum, range_::Ptr{GLint}, precision::Ptr{GLint})::Void),
:(glProgramUniform4dv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glShaderBinary(count::GLsizei, shaders::Ptr{GLuint}, binaryformat::GLenum, binary::Ptr{Void}, length::GLsizei)::Void),
:(glUniform1d(location::GLint, x::GLdouble)::Void),
:(glProgramUniform4d(program::GLuint, location::GLint, v0::GLdouble, v1::GLdouble, v2::GLdouble, v3::GLdouble)::Void),
:(glMultiTexCoordP3ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glProgramUniform2iv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glProgramUniformMatrix3fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glUniform4uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glClearBufferfi(buffer::GLenum, drawbuffer::GLint, depth::GLfloat, stencil::GLint)::Void),
:(glGenerateMipmap(target::GLenum)::Void),
:(glVertexAttribI3ui(index::GLuint, x::GLuint, y::GLuint, z::GLuint)::Void),
:(glTexCoordP4uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glEndTransformFeedback()::Void),
:(glBindBufferBase(target::GLenum, index::GLuint, buffer::GLuint)::Void),
:(glUniform1uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glSamplerParameterIuiv(sampler::GLuint, pname::GLenum, param::Ptr{GLuint})::Void),
:(glVertexAttribDivisor(index::GLuint, divisor::GLuint)::Void),
:(glMultiTexCoordP4ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glGetUniformdv(program::GLuint, location::GLint, params::Ptr{GLdouble})::Void),
:(glProgramUniform1iv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glClampColor(target::GLenum, clamp::GLenum)::Void),
:(glTexBuffer(target::GLenum, internalformat::GLenum, buffer::GLuint)::Void),
:(glBlendFunci(buf::GLuint, src::GLenum, dst::GLenum)::Void),
:(glProgramUniformMatrix4fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glBlitFramebuffer(srcX0::GLint, srcY0::GLint, srcX1::GLint, srcY1::GLint, dstX0::GLint, dstY0::GLint, dstX1::GLint, dstY1::GLint, mask::GLbitfield, filter::GLenum)::Void),
:(glVertexAttribP2ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glSamplerParameterfv(sampler::GLuint, pname::GLenum, param::Ptr{GLfloat})::Void),
:(glProgramUniformMatrix4x2dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glVertexAttribL4d(index::GLuint, x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glUseProgramStages(pipeline::GLuint, stages::GLbitfield, program::GLuint)::Void),
:(glGetFragDataLocation(program::GLuint, name::Ptr{GLchar})::Cint),
:(glSecondaryColorP3uiv(type_::GLenum, color::Ptr{GLuint})::Void),
:(glGetActiveUniformsiv(program::GLuint, uniformCount::GLsizei, uniformIndices::Ptr{GLuint}, pname::GLenum, params::Ptr{GLint})::Void),
:(glProgramUniform3dv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glGenRenderbuffers(n::GLsizei, renderbuffers::Ptr{GLuint})::Void),
:(glBindFramebuffer(target::GLenum, framebuffer::GLuint)::Void),
:(glUniformMatrix2dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glGetUniformIndices(program::GLuint, uniformCount::GLsizei, uniformNames::Ptr{Uint8}, uniformIndices::Ptr{GLuint})::Void),
:(glGetMultisamplefv(pname::GLenum, index::GLuint, val::Ptr{GLfloat})::Void),
:(glIsRenderbuffer(renderbuffer::GLuint)::Bool),
:(glBindTransformFeedback(target::GLenum, id::GLuint)::Void),
:(glProgramUniform2i(program::GLuint, location::GLint, v0::GLint, v1::GLint)::Void),
:(glVertexAttribI2i(index::GLuint, x::GLint, y::GLint)::Void),
:(glProgramUniform2d(program::GLuint, location::GLint, v0::GLdouble, v1::GLdouble)::Void),
:(glMemoryBarrier(barriers::GLbitfield)::Void),
:(glVertexP3ui(type_::GLenum, value::GLuint)::Void),
:(glDepthRangef(n::GLfloat, f::GLfloat)::Void),
:(glBeginTransformFeedback(primitiveMode::GLenum)::Void),
:(glVertexAttribI1ui(index::GLuint, x::GLuint)::Void),
:(glDrawArraysInstanced(mode::GLenum, first::GLint, count::GLsizei, instancecount::GLsizei)::Void),
:(glTexCoordP1uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glSecondaryColorP3ui(type_::GLenum, color::GLuint)::Void),
:(glPauseTransformFeedback()::Void),
:(glRenderbufferStorage(target::GLenum, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glTexCoordP3uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glVertexAttribL4dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glDepthRangeArrayv(first::GLuint, count::GLsizei, v::Ptr{GLdouble})::Void),
:(glTexParameterIuiv(target::GLenum, pname::GLenum, params::Ptr{GLuint})::Void),
:(glProgramUniform4ui(program::GLuint, location::GLint, v0::GLuint, v1::GLuint, v2::GLuint, v3::GLuint)::Void),
:(glGetSamplerParameterIuiv(sampler::GLuint, pname::GLenum, params::Ptr{GLuint})::Void),
:(glProgramUniform1ui(program::GLuint, location::GLint, v0::GLuint)::Void),
:(glVertexAttribI4i(index::GLuint, x::GLint, y::GLint, z::GLint, w::GLint)::Void),
:(glColorMaski(index::GLuint, r::GLboolean, g::GLboolean, b::GLboolean, a::GLboolean)::Void),
:(glProgramUniformMatrix2x3dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glGenVertexArrays(n::GLsizei, arrays::Ptr{GLuint})::Void),
:(glVertexAttribI3iv(index::GLuint, v::Ptr{GLint})::Void),
:(glSamplerParameterf(sampler::GLuint, pname::GLenum, param::GLfloat)::Void),
:(glVertexAttribP1uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glUniform4d(location::GLint, x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glDrawTransformFeedback(mode::GLenum, id::GLuint)::Void),
:(glGetInteger64i_v(target::GLenum, index::GLuint, data::Ptr{GLint64})::Void),
:(glGetFloati_v(target::GLenum, index::GLuint, data::Ptr{GLfloat})::Void),
:(glTexCoordP3ui(type_::GLenum, coords::GLuint)::Void),
:(glUniformMatrix4x2dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glClearBufferuiv(buffer::GLenum, drawbuffer::GLint, value::Ptr{GLuint})::Void),
:(glVertexAttribI4uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glBlendEquationSeparatei(buf::GLuint, modeRGB::GLenum, modeAlpha::GLenum)::Void),
:(glBindSampler(unit::GLuint, sampler::GLuint)::Void),
:(glProgramUniform1i(program::GLuint, location::GLint, v0::GLint)::Void),
:(glMapBufferRange(target::GLenum, offset::GLintptr, length::GLsizeiptr, access::GLbitfield)::Ptr{Void}),
:(glUniformMatrix2x4dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glProgramUniform4f(program::GLuint, location::GLint, v0::GLfloat, v1::GLfloat, v2::GLfloat, v3::GLfloat)::Void),
:(glCopyBufferSubData(readTarget::GLenum, writeTarget::GLenum, readOffset::GLintptr, writeOffset::GLintptr, size::GLsizeiptr)::Void),
:(glUniformBlockBinding(program::GLuint, uniformBlockIndex::GLuint, uniformBlockBinding::GLuint)::Void),
:(glProgramUniform4i(program::GLuint, location::GLint, v0::GLint, v1::GLint, v2::GLint, v3::GLint)::Void),
:(glIsTransformFeedback(id::GLuint)::Bool),
:(glPatchParameterfv(pname::GLenum, values::Ptr{GLfloat})::Void),
:(glResumeTransformFeedback()::Void),
:(glVertexAttribL2dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glProgramUniform2dv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glVertexAttribI4ui(index::GLuint, x::GLuint, y::GLuint, z::GLuint, w::GLuint)::Void),
:(glProgramUniformMatrix4x2fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glScissorArrayv(first::GLuint, count::GLsizei, v::Ptr{GLint})::Void),
:(glBindRenderbuffer(target::GLenum, renderbuffer::GLuint)::Void),
:(glMultiTexCoordP1uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glCreateShaderProgramv(type_::GLenum, count::GLsizei, strings::Ptr{Cuchar})::Cuint),
:(glUniformMatrix3x4dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glGetIntegeri_v(target::GLenum, index::GLuint, data::Ptr{GLint})::Void),
:(glGetSubroutineIndex(program::GLuint, shadertype::GLenum, name::Ptr{GLchar})::Cuint),
:(glSamplerParameteriv(sampler::GLuint, pname::GLenum, param::Ptr{GLint})::Void),
:(glUniformMatrix4x3dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glGetTransformFeedbackVarying(program::GLuint, index::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, size::Ptr{GLsizei}, type_::Ptr{GLenum}, name::Ptr{GLchar})::Void),
:(glBeginConditionalRender(id::GLuint, mode::GLenum)::Void),
:(glGetFragDataIndex(program::GLuint, name::Ptr{GLchar})::Cint),
:(glProgramUniform4fv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glFramebufferTexture2D(target::GLenum, attachment::GLenum, textarget::GLenum, texture::GLuint, level::GLint)::Void),
:(glGetSamplerParameteriv(sampler::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glProgramUniformMatrix3dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glFenceSync(condition::GLenum, flags::GLbitfield)::Sync),
:(glGenProgramPipelines(n::GLsizei, pipelines::Ptr{GLuint})::Void),
:(glReleaseShaderCompiler()::Void),
:(glMultiDrawElementsBaseVertex(mode::GLenum, count::Ptr{GLsizei}, type_::GLenum, indices::Ptr{Ptr{Void}}, drawcount::GLsizei, basevertex::Ptr{GLint})::Void),
:(glUniformSubroutinesuiv(shadertype::GLenum, count::GLsizei, indices::Ptr{GLuint})::Void),
:(glDeleteProgramPipelines(n::GLsizei, pipelines::Ptr{GLuint})::Void),
:(glProgramUniform2uiv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glProgramUniformMatrix3x2fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glGetVertexAttribLdv(index::GLuint, pname::GLenum, params::Ptr{GLdouble})::Void),
:(glIsEnabledi(target::GLenum, index::GLuint)::Bool),
:(glFramebufferTexture1D(target::GLenum, attachment::GLenum, textarget::GLenum, texture::GLuint, level::GLint)::Void),
:(glVertexAttribI2uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glVertexAttribIPointer(index::GLuint, size::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glColorP4uiv(type_::GLenum, color::Ptr{GLuint})::Void),
:(glDrawElementsInstancedBaseVertexBaseInstance(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, instancecount::GLsizei, basevertex::GLint, baseinstance::GLuint)::Void),
:(glBindFragDataLocationIndexed(program::GLuint, colorNumber::GLuint, index::GLuint, name::Ptr{GLchar})::Void),
:(glMultiTexCoordP2ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glProgramUniformMatrix3x2dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glProgramUniformMatrix4x3dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glDrawArraysInstancedBaseInstance(mode::GLenum, first::GLint, count::GLsizei, instancecount::GLsizei, baseinstance::GLuint)::Void),
:(glIsProgramPipeline(pipeline::GLuint)::Bool),
:(glDeleteFramebuffers(n::GLsizei, framebuffers::Ptr{GLuint})::Void),
:(glVertexAttribL2d(index::GLuint, x::GLdouble, y::GLdouble)::Void),
:(glGetQueryObjectui64v(id::GLuint, pname::GLenum, params::Ptr{GLuint64})::Void),
:(glProgramUniformMatrix3x4dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glIsVertexArray(array::GLuint)::Bool),
:(glGetTexParameterIiv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glRenderbufferStorageMultisample(target::GLenum, samples::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glUniform2d(location::GLint, x::GLdouble, y::GLdouble)::Void),
:(glVertexAttribI4usv(index::GLuint, v::Ptr{GLushort})::Void),
:(glVertexAttribI1i(index::GLuint, x::GLint)::Void),
:(glTextureStorage1DEXT(texture::GLuint, target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei)::Void),
:(glUniform3d(location::GLint, x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glDrawTransformFeedbackInstanced(mode::GLenum, id::GLuint, instancecount::GLsizei)::Void),
:(glProgramUniformMatrix4dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glActiveShaderProgram(pipeline::GLuint, program::GLuint)::Void),
:(glVertexP2uiv(type_::GLenum, value::Ptr{GLuint})::Void),
:(glVertexAttribLPointer(index::GLuint, size::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glDrawArraysIndirect(mode::GLenum, indirect::Ptr{Void})::Void),
:(glProgramUniform1dv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glTexCoordP2uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glGetStringi(name::GLenum, index::GLuint)::Ptr{Cuchar}),
:(glGetSamplerParameterIiv(sampler::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glIsSampler(sampler::GLuint)::Bool),
:(glIsSync(sync::GLsync)::Bool),
:(glGetVertexAttribIuiv(index::GLuint, pname::GLenum, params::Ptr{GLuint})::Void),
:(glColorP3ui(type_::GLenum, color::GLuint)::Void),
:(glUniform3uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glUniformMatrix3dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glVertexP4ui(type_::GLenum, value::GLuint)::Void),
:(glVertexAttribI4sv(index::GLuint, v::Ptr{GLshort})::Void),
:(glCheckFramebufferStatus(target::GLenum)::Cint),
:(glGetActiveUniformBlockiv(program::GLuint, uniformBlockIndex::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glProgramUniformMatrix2x3fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glBindFragDataLocation(program::GLuint, color::GLuint, name::Ptr{GLchar})::Void),
:(glProgramUniform3uiv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glVertexAttribL3dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glWaitSync(sync::GLsync, flags::GLbitfield, timeout::GLuint64)::Void),
:(glGetDoublei_v(target::GLenum, index::GLuint, data::Ptr{GLdouble})::Void),
:(glBindVertexArray(array::GLuint)::Void),
:(glProgramBinary(program::GLuint, binaryFormat::GLenum, binary::Ptr{Void}, length::GLsizei)::Void),
:(glVertexAttribL1dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glDrawElementsBaseVertex(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, basevertex::GLint)::Void),
:(glUniform3dv(location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glDrawElementsInstancedBaseVertex(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, instancecount::GLsizei, basevertex::GLint)::Void),
:(glGetActiveUniformBlockName(program::GLuint, uniformBlockIndex::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, uniformBlockName::Ptr{GLchar})::Void),
:(glGenSamplers(count::GLsizei, samplers::Ptr{GLuint})::Void),
:(glBeginQueryIndexed(target::GLenum, index::GLuint, id::GLuint)::Void),
:(glUniform2dv(location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glVertexAttribP2uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glVertexAttribL3d(index::GLuint, x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glGetInternalformativ(target::GLenum, internalformat::GLenum, pname::GLenum, bufSize::GLsizei, params::Ptr{GLint})::Void),
:(glGetActiveSubroutineUniformiv(program::GLuint, shadertype::GLenum, index::GLuint, pname::GLenum, values::Ptr{GLint})::Void),
:(glProgramUniformMatrix2fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glUniform1dv(location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glGetUniformSubroutineuiv(shadertype::GLenum, location::GLint, params::Ptr{GLuint})::Void),
:(glClearBufferiv(buffer::GLenum, drawbuffer::GLint, value::Ptr{GLint})::Void),
:(glGetRenderbufferParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribP1ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glFramebufferTexture(target::GLenum, attachment::GLenum, texture::GLuint, level::GLint)::Void),
:(glGetUniformuiv(program::GLuint, location::GLint, params::Ptr{GLuint})::Void),
:(glVertexAttribI1uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glProgramUniformMatrix4x3fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glBindProgramPipeline(pipeline::GLuint)::Void),
:(glUniformMatrix4dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glSamplerParameterIiv(sampler::GLuint, pname::GLenum, param::Ptr{GLint})::Void),
:(glColorP4ui(type_::GLenum, color::GLuint)::Void),
:(glColorP3uiv(type_::GLenum, color::Ptr{GLuint})::Void),
:(glUniform1ui(location::GLint, v0::GLuint)::Void),
:(glVertexAttribI4ubv(index::GLuint, v::Ptr{GLubyte})::Void),
:(glVertexP3uiv(type_::GLenum, value::Ptr{GLuint})::Void),
:(glProgramUniform4iv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glDeleteRenderbuffers(n::GLsizei, renderbuffers::Ptr{GLuint})::Void),
:(glIsFramebuffer(framebuffer::GLuint)::Bool),
:(glProgramUniformMatrix3x4fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glScissorIndexedv(index::GLuint, v::Ptr{GLint})::Void),
:(glVertexAttribI4iv(index::GLuint, v::Ptr{GLint})::Void),
:(glProgramUniform1uiv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glFramebufferTextureLayer(target::GLenum, attachment::GLenum, texture::GLuint, level::GLint, layer::GLint)::Void),
:(glVertexAttribP3ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glTransformFeedbackVaryings(program::GLuint, count::GLsizei, varyings::Ptr{Uint8}, bufferMode::GLenum)::Void),
:(glDeleteTransformFeedbacks(n::GLsizei, ids::Ptr{GLuint})::Void),
:(glVertexAttribP3uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glProgramUniform3i(program::GLuint, location::GLint, v0::GLint, v1::GLint, v2::GLint)::Void),
:(glDepthRangeIndexed(index::GLuint, n::GLdouble, f::GLdouble)::Void),
:(glGetTexParameterIuiv(target::GLenum, pname::GLenum, params::Ptr{GLuint})::Void),
:(glGetInteger64v(pname::GLenum, params::Ptr{GLint64})::Void),
:(glDrawElementsInstanced(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, instancecount::GLsizei)::Void),
:(glProgramUniform3d(program::GLuint, location::GLint, v0::GLdouble, v1::GLdouble, v2::GLdouble)::Void),
:(glVertexP4uiv(type_::GLenum, value::Ptr{GLuint})::Void),
:(glGetProgramPipelineiv(pipeline::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glNormalP3ui(type_::GLenum, coords::GLuint)::Void),
:(glProgramUniformMatrix2dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glFramebufferRenderbuffer(target::GLenum, attachment::GLenum, renderbuffertarget::GLenum, renderbuffer::GLuint)::Void),
:(glDrawTransformFeedbackStreamInstanced(mode::GLenum, id::GLuint, stream::GLuint, instancecount::GLsizei)::Void),
:(glDrawElementsInstancedBaseInstance(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, instancecount::GLsizei, baseinstance::GLuint)::Void),
:(glUniformMatrix2x3dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glUniformMatrix3x2dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glViewportIndexedfv(index::GLuint, v::Ptr{GLfloat})::Void),
:(glProgramUniform2f(program::GLuint, location::GLint, v0::GLfloat, v1::GLfloat)::Void),
:(glDrawRangeElementsBaseVertex(mode::GLenum, start::GLuint, END::GLuint, count::GLsizei, type_::GLenum, indices::Ptr{Void}, basevertex::GLint)::Void),
:(glUniform3ui(location::GLint, v0::GLuint, v1::GLuint, v2::GLuint)::Void),
:(glTexCoordP4ui(type_::GLenum, coords::GLuint)::Void),
:(glMultiTexCoordP2uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glFlushMappedBufferRange(target::GLenum, offset::GLintptr, length::GLsizeiptr)::Void),
:(glBindImageTexture(unit::GLuint, texture::GLuint, level::GLint, layered::GLboolean, layer::GLint, access::GLenum, format::GLenum)::Void),
:(glTexImage3DMultisample(target::GLenum, samples::GLsizei, internalformat::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, fixedsamplelocations::GLboolean)::Void),
:(glSampleMaski(index::GLuint, mask::GLbitfield)::Void),
:(glProgramUniform1d(program::GLuint, location::GLint, v0::GLdouble)::Void),
:(glGetSynciv(sync::GLsync, pname::GLenum, bufSize::GLsizei, length::Ptr{GLsizei}, values::Ptr{GLint})::Void),
:(glDeleteSamplers(count::GLsizei, samplers::Ptr{GLuint})::Void),
:(glTextureStorage2DEXT(texture::GLuint, target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glPrimitiveRestartIndex(index::GLuint)::Void),
:(glProgramUniform2ui(program::GLuint, location::GLint, v0::GLuint, v1::GLuint)::Void),
:(glGetQueryIndexediv(target::GLenum, index::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetActiveSubroutineUniformName(program::GLuint, shadertype::GLenum, index::GLuint, bufsize::GLsizei, length::Ptr{GLsizei}, name::Ptr{GLchar})::Void),
:(glProgramUniform1fv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glQueryCounter(id::GLuint, target::GLenum)::Void),
:(glGenFramebuffers(n::GLsizei, framebuffers::Ptr{GLuint})::Void),
:(glProgramUniform3fv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glVertexAttribL1d(index::GLuint, x::GLdouble)::Void),
:(glEndQueryIndexed(target::GLenum, index::GLuint)::Void),
:(glPatchParameteri(pname::GLenum, value::GLint)::Void),
:(glProgramUniform3f(program::GLuint, location::GLint, v0::GLfloat, v1::GLfloat, v2::GLfloat)::Void),
:(glGetFramebufferAttachmentParameteriv(target::GLenum, attachment::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glBindBufferRange(target::GLenum, index::GLuint, buffer::GLuint, offset::GLintptr, size::GLsizeiptr)::Void),
:(glDisablei(target::GLenum, index::GLuint)::Void),
:(glValidateProgramPipeline(pipeline::GLuint)::Void),
:(glDrawTransformFeedbackStream(mode::GLenum, id::GLuint, stream::GLuint)::Void),
:(glBlendFuncSeparatei(buf::GLuint, srcRGB::GLenum, dstRGB::GLenum, srcAlpha::GLenum, dstAlpha::GLenum)::Void),
:(glGetProgramBinary(program::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, binaryFormat::Ptr{GLenum}, binary::Ptr{Void})::Void),
:(glTexStorage1D(target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei)::Void),
:(glVertexAttribI3i(index::GLuint, x::GLint, y::GLint, z::GLint)::Void),
:(glVertexAttribI2ui(index::GLuint, x::GLuint, y::GLuint)::Void),
:(glUniform2ui(location::GLint, v0::GLuint, v1::GLuint)::Void),
:(glViewportIndexedf(index::GLuint, x::GLfloat, y::GLfloat, w::GLfloat, h::GLfloat)::Void),
:(glGenTransformFeedbacks(n::GLsizei, ids::Ptr{GLuint})::Void),
:(glProgramUniform2fv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glUniform4ui(location::GLint, v0::GLuint, v1::GLuint, v2::GLuint, v3::GLuint)::Void),
:(glTextureStorage3DEXT(texture::GLuint, target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei, depth::GLsizei)::Void),
:(glGetActiveSubroutineName(program::GLuint, shadertype::GLenum, index::GLuint, bufsize::GLsizei, length::Ptr{GLsizei}, name::Ptr{GLchar})::Void),
:(glProgramUniform3ui(program::GLuint, location::GLint, v0::GLuint, v1::GLuint, v2::GLuint)::Void)]
