#Types, functions and constants, needed on top of the common ones
#types
const GL_GL42_TYPES = [
]
#constants
const GL_GL42_CONSTANTS = [
:(const GL_UNIFORM_BLOCK_NAME_LENGTH                                    = 0x8A41),
:(const GL_RGBA8UI                                                      = 0x8D7C),
:(const GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE                           = 0x8CD0),
:(const GL_DEPTH32F_STENCIL8                                            = 0x8CAD),
:(const GL_FRACTIONAL_ODD                                               = 0x8E7B),
:(const GL_TEXTURE_SWIZZLE_A                                            = 0x8E45),
:(const GL_SAMPLER_2D_RECT                                              = 0x8B63),
:(const GL_MAX_VERTEX_OUTPUT_COMPONENTS                                 = 0x9122),
:(const GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL                         = 0x8CD2),
:(const GL_RGBA8_SNORM                                                  = 0x8F97),
:(const GL_UNIFORM_BLOCK_BINDING                                        = 0x8A3F),
:(const GL_DOUBLE_MAT2x3                                                = 0x8F49),
:(const GL_UNIFORM_NAME_LENGTH                                          = 0x8A39),
:(const GL_TIME_ELAPSED                                                 = 0x88BF),
:(const GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER                           = 0x8CDC),
:(const GL_IMPLEMENTATION_COLOR_READ_TYPE                               = 0x8B9A),
:(const GL_NUM_EXTENSIONS                                               = 0x821D),
:(const GL_UNSIGNED_INT_IMAGE_1D_ARRAY                                  = 0x9068),
:(const GL_IMAGE_CUBE_MAP_ARRAY                                         = 0x9054),
:(const GL_SHADER_BINARY_FORMATS                                        = 0x8DF8),
:(const GL_COMPRESSED_RED                                               = 0x8225),
:(const GL_RGBA32I                                                      = 0x8D82),
:(const GL_IMAGE_3D                                                     = 0x904E),
:(const GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS                           = 0x8E83),
:(const GL_FRAMEBUFFER_UNSUPPORTED                                      = 0x8CDD),
:(const GL_SAMPLER_2D_ARRAY                                             = 0x8DC1),
:(const GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS                          = 0x92D1),
:(const GL_CLAMP_READ_COLOR                                             = 0x891C),
:(const GL_MIN_SAMPLE_SHADING_VALUE                                     = 0x8C37),
:(const GL_UNSIGNED_INT_ATOMIC_COUNTER                                  = 0x92DB),
:(const GL_UNIFORM_OFFSET                                               = 0x8A3B),
:(const GL_RG16UI                                                       = 0x823A),
:(const GL_TESS_EVALUATION_SHADER                                       = 0x8E87),
:(const GL_ELEMENT_ARRAY_BARRIER_BIT                                    = 0x00000002),
:(const GL_NUM_SAMPLE_COUNTS                                            = 0x9380),
:(const GL_TEXTURE_SWIZZLE_B                                            = 0x8E44),
:(const GL_RASTERIZER_DISCARD                                           = 0x8C89),
:(const GL_PROGRAM_BINARY_FORMATS                                       = 0x87FF),
:(const GL_PIXEL_BUFFER_BARRIER_BIT                                     = 0x00000080),
:(const GL_MAX_GEOMETRY_OUTPUT_VERTICES                                 = 0x8DE0),
:(const GL_RG_SNORM                                                     = 0x8F91),
:(const GL_READ_FRAMEBUFFER_BINDING                                     = 0x8CAA),
:(const GL_MEDIUM_FLOAT                                                 = 0x8DF1),
:(const GL_R32UI                                                        = 0x8236),
:(const GL_UNSIGNED_INT_IMAGE_2D_RECT                                   = 0x9065),
:(const GL_RG16I                                                        = 0x8239),
:(const GL_UNIFORM_BUFFER_BINDING                                       = 0x8A28),
:(const GL_MAX_TEXTURE_BUFFER_SIZE                                      = 0x8C2B),
:(const GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS                     = 0x8A33),
:(const GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH                         = 0x8E49),
:(const GL_SIGNED_NORMALIZED                                            = 0x8F9C),
:(const GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS                           = 0x8E8A),
:(const GL_RGB32F                                                       = 0x8815),
:(const GL_RED_INTEGER                                                  = 0x8D94),
:(const GL_SAMPLER_2D_MULTISAMPLE                                       = 0x9108),
:(const GL_RENDERBUFFER_INTERNAL_FORMAT                                 = 0x8D44),
:(const GL_COLOR_ATTACHMENT13                                           = 0x8CED),
:(const GL_SYNC_GPU_COMMANDS_COMPLETE                                   = 0x9117),
:(const GL_BGRA_INTEGER                                                 = 0x8D9B),
:(const GL_INT_IMAGE_2D_RECT                                            = 0x905A),
:(const GL_MAP_WRITE_BIT                                                = 0x0002),
:(const GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS                       = 0x8A31),
:(const GL_SAMPLE_SHADING                                               = 0x8C36),
:(const GL_MAX_PROGRAM_TEXEL_OFFSET                                     = 0x8905),
:(const GL_TEXTURE_DEPTH_TYPE                                           = 0x8C16),
:(const GL_MAX_TESS_PATCH_COMPONENTS                                    = 0x8E84),
:(const GL_LAYER_PROVOKING_VERTEX                                       = 0x825E),
:(const GL_SAMPLER_CUBE_MAP_ARRAY                                       = 0x900C),
:(const GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET                            = 0x8E5E),
:(const GL_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX                          = 0x92DA),
:(const GL_MAP_FLUSH_EXPLICIT_BIT                                       = 0x0010),
:(const GL_RGB9_E5                                                      = 0x8C3D),
:(const GL_FRACTIONAL_EVEN                                              = 0x8E7C),
:(const GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER          = 0x92CA),
:(const GL_TEXTURE_LUMINANCE_TYPE                                       = 0x8C14),
:(const GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS                         = 0x8DE1),
:(const GL_IMAGE_1D_ARRAY                                               = 0x9052),
:(const GL_LINES_ADJACENCY                                              = 0x000A),
:(const GL_CLIP_DISTANCE0                                               = 0x3000),
:(const GL_INT_SAMPLER_CUBE                                             = 0x8DCC),
:(const GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES          = 0x92C6),
:(const GL_DEPTH_COMPONENT32F                                           = 0x8CAC),
:(const GL_FLOAT_32_UNSIGNED_INT_24_8_REV                               = 0x8DAD),
:(const GL_TRANSFORM_FEEDBACK_BUFFER_MODE                               = 0x8C7F),
:(const GL_CLIP_DISTANCE6                                               = 0x3006),
:(const GL_BUFFER_ACCESS_FLAGS                                          = 0x911F),
:(const GL_PROXY_TEXTURE_2D_MULTISAMPLE                                 = 0x9101),
:(const GL_INT_SAMPLER_CUBE_MAP_ARRAY                                   = 0x900E),
:(const GL_FRAGMENT_INTERPOLATION_OFFSET_BITS                           = 0x8E5D),
:(const GL_UNSIGNED_INT_VEC2                                            = 0x8DC6),
:(const GL_MINOR_VERSION                                                = 0x821C),
:(const GL_PROGRAM_SEPARABLE                                            = 0x8258),
:(const GL_MEDIUM_INT                                                   = 0x8DF4),
:(const GL_MAX_COMBINED_ATOMIC_COUNTERS                                 = 0x92D7),
:(const GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME                           = 0x8CD1),
:(const GL_UNSIGNED_INT_IMAGE_BUFFER                                    = 0x9067),
:(const GL_COLOR_ATTACHMENT2                                            = 0x8CE2),
:(const GL_SHADER_COMPILER                                              = 0x8DFA),
:(const GL_BUFFER_MAP_LENGTH                                            = 0x9120),
:(const GL_ACTIVE_PROGRAM                                               = 0x8259),
:(const GL_MAJOR_VERSION                                                = 0x821B),
:(const GL_CLIP_DISTANCE5                                               = 0x3005),
:(const GL_MAP_UNSYNCHRONIZED_BIT                                       = 0x0020),
:(const GL_RENDERBUFFER_HEIGHT                                          = 0x8D43),
:(const GL_DOUBLE_VEC2                                                  = 0x8FFC),
:(const GL_INT_SAMPLER_1D                                               = 0x8DC9),
:(const GL_CONDITION_SATISFIED                                          = 0x911C),
:(const GL_TEXTURE_BUFFER_DATA_STORE_BINDING                            = 0x8C2D),
:(const GL_R32F                                                         = 0x822E),
:(const GL_INT_SAMPLER_2D                                               = 0x8DCA),
:(const GL_COPY_WRITE_BUFFER                                            = 0x8F37),
:(const GL_DOUBLE_MAT4x3                                                = 0x8F4E),
:(const GL_MAP_INVALIDATE_BUFFER_BIT                                    = 0x0008),
:(const GL_DOUBLE_MAT4x2                                                = 0x8F4D),
:(const GL_UNSIGNED_INT_SAMPLER_1D                                      = 0x8DD1),
:(const GL_ATOMIC_COUNTER_BUFFER                                        = 0x92C0),
:(const GL_TEXTURE_FETCH_BARRIER_BIT                                    = 0x00000008),
:(const GL_R8_SNORM                                                     = 0x8F94),
:(const GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER          = 0x92CB),
:(const GL_PROXY_TEXTURE_2D_ARRAY                                       = 0x8C1B),
:(const GL_UNSIGNED_INT_IMAGE_CUBE                                      = 0x9066),
:(const GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS                        = 0x8E86),
:(const GL_SYNC_FLUSH_COMMANDS_BIT                                      = 0x00000001),
:(const GL_CLIP_DISTANCE4                                               = 0x3004),
:(const GL_UNIFORM_BUFFER_START                                         = 0x8A29),
:(const GL_DOUBLE_VEC3                                                  = 0x8FFD),
:(const GL_CONTEXT_PROFILE_MASK                                         = 0x9126),
:(const GL_INT_SAMPLER_2D_MULTISAMPLE                                   = 0x9109),
:(const GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS                                = 0x8A42),
:(const GL_TIMESTAMP                                                    = 0x8E28),
:(const GL_DOUBLE_MAT3x2                                                = 0x8F4B),
:(const GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN                        = 0x8C88),
:(const GL_SAMPLE_MASK_VALUE                                            = 0x8E52),
:(const GL_TESS_EVALUATION_SHADER_BIT                                   = 0x00000010),
:(const GL_INT_SAMPLER_3D                                               = 0x8DCB),
:(const GL_SAMPLER_BINDING                                              = 0x8919),
:(const GL_BUFFER_MAP_OFFSET                                            = 0x9121),
:(const GL_MAX_GEOMETRY_SHADER_INVOCATIONS                              = 0x8E5A),
:(const GL_IMAGE_BINDING_LAYER                                          = 0x8F3D),
:(const GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS                          = 0x92CF),
:(const GL_TEXTURE_BINDING_CUBE_MAP_ARRAY                               = 0x900A),
:(const GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS                          = 0x8E47),
:(const GL_HIGH_FLOAT                                                   = 0x8DF2),
:(const GL_INT_SAMPLER_1D_ARRAY                                         = 0x8DCE),
:(const GL_MAX_FRAGMENT_INTERPOLATION_OFFSET                            = 0x8E5C),
:(const GL_RGB16_SNORM                                                  = 0x8F9A),
:(const GL_TRANSFORM_FEEDBACK_BARRIER_BIT                               = 0x00000800),
:(const GL_SAMPLE_MASK                                                  = 0x8E51),
:(const GL_SAMPLE_POSITION                                              = 0x8E50),
:(const GL_UNSIGNED_INT_IMAGE_3D                                        = 0x9064),
:(const GL_ACTIVE_SUBROUTINE_MAX_LENGTH                                 = 0x8E48),
:(const GL_R8                                                           = 0x8229),
:(const GL_RG32F                                                        = 0x8230),
:(const GL_COMMAND_BARRIER_BIT                                          = 0x00000040),
:(const GL_CLAMP_FRAGMENT_COLOR                                         = 0x891B),
:(const GL_TESS_GEN_VERTEX_ORDER                                        = 0x8E78),
:(const GL_RGB10_A2UI                                                   = 0x906F),
:(const GL_IMAGE_2D_MULTISAMPLE_ARRAY                                   = 0x9056),
:(const GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER                  = 0x8A46),
:(const GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER                           = 0x8CDB),
:(const GL_INVALID_INDEX                                                = 0xFFFFFFFF),
:(const GL_LAST_VERTEX_CONVENTION                                       = 0x8E4E),
:(const GL_MAX_TESS_CONTROL_INPUT_COMPONENTS                            = 0x886C),
:(const GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER              = 0x84F0),
:(const GL_MAX_SAMPLE_MASK_WORDS                                        = 0x8E59),
:(const GL_VERTEX_ARRAY_BINDING                                         = 0x85B5),
:(const GL_STENCIL_INDEX16                                              = 0x8D49),
:(const GL_RED_SNORM                                                    = 0x8F90),
:(const GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING                        = 0x8210),
:(const GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER   = 0x92C9),
:(const GL_UNSIGNED_INT_24_8                                            = 0x84FA),
:(const GL_MAX_GEOMETRY_UNIFORM_COMPONENTS                              = 0x8DDF),
:(const GL_MAX_VERTEX_ATOMIC_COUNTERS                                   = 0x92D2),
:(const GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT                              = 0x8A34),
:(const GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS                 = 0x92C5),
:(const GL_TEXTURE_BUFFER                                               = 0x8C2A),
:(const GL_SAMPLER_1D_ARRAY                                             = 0x8DC0),
:(const GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY                         = 0x9105),
:(const GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE                            = 0x8216),
:(const GL_TEXTURE_BINDING_2D_ARRAY                                     = 0x8C1D),
:(const GL_IMAGE_2D                                                     = 0x904D),
:(const GL_MIN_PROGRAM_TEXEL_OFFSET                                     = 0x8904),
:(const GL_MAX_VARYING_VECTORS                                          = 0x8DFC),
:(const GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS                         = 0x886D),
:(const GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE                               = 0x92D8),
:(const GL_BLUE_INTEGER                                                 = 0x8D96),
:(const GL_RGB32UI                                                      = 0x8D71),
:(const GL_MIN_MAP_BUFFER_ALIGNMENT                                     = 0x90BC),
:(const GL_COLOR_ATTACHMENT15                                           = 0x8CEF),
:(const GL_UNIFORM_BARRIER_BIT                                          = 0x00000004),
:(const GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY                            = 0x906A),
:(const GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS              = 0x8E1F),
:(const GL_UNSIGNED_INT_VEC3                                            = 0x8DC7),
:(const GL_IMAGE_BINDING_ACCESS                                         = 0x8F3E),
:(const GL_MAX_IMAGE_UNITS                                              = 0x8F38),
:(const GL_TEXTURE_INTENSITY_TYPE                                       = 0x8C15),
:(const GL_MAX_RENDERBUFFER_SIZE                                        = 0x84E8),
:(const GL_IMAGE_BINDING_LAYERED                                        = 0x8F3C),
:(const GL_GEOMETRY_SHADER_BIT                                          = 0x00000004),
:(const GL_ACTIVE_ATOMIC_COUNTER_BUFFERS                                = 0x92D9),
:(const GL_RGBA16UI                                                     = 0x8D76),
:(const GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS                           = 0x90CC),
:(const GL_DEPTH_CLAMP                                                  = 0x864F),
:(const GL_ACTIVE_UNIFORM_BLOCKS                                        = 0x8A36),
:(const GL_COLOR_ATTACHMENT10                                           = 0x8CEA),
:(const GL_IMAGE_BINDING_LEVEL                                          = 0x8F3B),
:(const GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET                            = 0x8E5F),
:(const GL_FRAMEBUFFER_UNDEFINED                                        = 0x8219),
:(const GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE                 = 0x8CD3),
:(const GL_R8UI                                                         = 0x8232),
:(const GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE                             = 0x8214),
:(const GL_TEXTURE_CUBE_MAP_SEAMLESS                                    = 0x884F),
:(const GL_BUFFER_UPDATE_BARRIER_BIT                                    = 0x00000200),
:(const GL_TEXTURE_1D_ARRAY                                             = 0x8C18),
:(const GL_ALPHA_INTEGER                                                = 0x8D97),
:(const GL_MAX_GEOMETRY_INPUT_COMPONENTS                                = 0x9123),
:(const GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH                         = 0x8A35),
:(const GL_RENDERBUFFER_GREEN_SIZE                                      = 0x8D51),
:(const GL_IMAGE_2D_RECT                                                = 0x904F),
:(const GL_SRC1_COLOR                                                   = 0x88F9),
:(const GL_PRIMITIVES_GENERATED                                         = 0x8C87),
:(const GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS                = 0x8F39),
:(const GL_IMPLEMENTATION_COLOR_READ_FORMAT                             = 0x8B9B),
:(const GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS                     = 0x8E85),
:(const GL_FRAMEBUFFER_ATTACHMENT_LAYERED                               = 0x8DA7),
:(const GL_PATCH_DEFAULT_INNER_LEVEL                                    = 0x8E73),
:(const GL_ISOLINES                                                     = 0x8E7A),
:(const GL_R16                                                          = 0x822A),
:(const GL_R32I                                                         = 0x8235),
:(const GL_MAX_ARRAY_TEXTURE_LAYERS                                     = 0x88FF),
:(const GL_ACTIVE_SUBROUTINES                                           = 0x8DE5),
:(const GL_MAX_DEPTH_TEXTURE_SAMPLES                                    = 0x910F),
:(const GL_ATOMIC_COUNTER_BUFFER_BINDING                                = 0x92C1),
:(const GL_UNSIGNED_INT_IMAGE_2D_ARRAY                                  = 0x9069),
:(const GL_UNSIGNED_INT_10F_11F_11F_REV                                 = 0x8C3B),
:(const GL_PRIMITIVE_RESTART_INDEX                                      = 0x8F9E),
:(const GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE                              = 0x92C4),
:(const GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE                           = 0x8D56),
:(const GL_MAX_VERTEX_UNIFORM_VECTORS                                   = 0x8DFB),
:(const GL_IMAGE_2D_ARRAY                                               = 0x9053),
:(const GL_MAX_GEOMETRY_ATOMIC_COUNTERS                                 = 0x92D5),
:(const GL_TEXTURE_UPDATE_BARRIER_BIT                                   = 0x00000100),
:(const GL_MAX_GEOMETRY_OUTPUT_COMPONENTS                               = 0x9124),
:(const GL_STENCIL_INDEX1                                               = 0x8D46),
:(const GL_INT_SAMPLER_BUFFER                                           = 0x8DD0),
:(const GL_RENDERBUFFER_STENCIL_SIZE                                    = 0x8D55),
:(const GL_TESS_CONTROL_SHADER_BIT                                      = 0x00000008),
:(const GL_DRAW_INDIRECT_BUFFER                                         = 0x8F3F),
:(const GL_COLOR_ATTACHMENT3                                            = 0x8CE3),
:(const GL_INT_IMAGE_CUBE_MAP_ARRAY                                     = 0x905F),
:(const GL_SAMPLER_2D_RECT_SHADOW                                       = 0x8B64),
:(const GL_TRANSFORM_FEEDBACK_BUFFER_SIZE                               = 0x8C85),
:(const GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS                          = 0x90C9),
:(const GL_READ_FRAMEBUFFER                                             = 0x8CA8),
:(const GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS                         = 0x8DA8),
:(const GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE                              = 0x8212),
:(const GL_PROXY_TEXTURE_1D_ARRAY                                       = 0x8C19),
:(const GL_UNDEFINED_VERTEX                                             = 0x8260),
:(const GL_UNPACK_COMPRESSED_BLOCK_HEIGHT                               = 0x9128),
:(const GL_OBJECT_TYPE                                                  = 0x9112),
:(const GL_PROGRAM_POINT_SIZE                                           = 0x8642),
:(const GL_UNIFORM_SIZE                                                 = 0x8A38),
:(const GL_TRANSFORM_FEEDBACK_VARYINGS                                  = 0x8C83),
:(const GL_COLOR_ATTACHMENT7                                            = 0x8CE7),
:(const GL_VERTEX_SHADER_BIT                                            = 0x00000001),
:(const GL_RENDERBUFFER_BINDING                                         = 0x8CA7),
:(const GL_TIMEOUT_EXPIRED                                              = 0x911B),
:(const GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE                           = 0x90C8),
:(const GL_COLOR_ATTACHMENT12                                           = 0x8CEC),
:(const GL_IMAGE_BINDING_FORMAT                                         = 0x906E),
:(const GL_GEOMETRY_SHADER_INVOCATIONS                                  = 0x887F),
:(const GL_INT_SAMPLER_2D_ARRAY                                         = 0x8DCF),
:(const GL_STENCIL_INDEX8                                               = 0x8D48),
:(const GL_RGB16UI                                                      = 0x8D77),
:(const GL_RGB8I                                                        = 0x8D8F),
:(const GL_DOUBLE_VEC4                                                  = 0x8FFE),
:(const GL_FRAMEBUFFER_COMPLETE                                         = 0x8CD5),
:(const GL_UNIFORM_BUFFER                                               = 0x8A11),
:(const GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER                    = 0x8A44),
:(const GL_CLIP_DISTANCE2                                               = 0x3002),
:(const GL_INT_2_10_10_10_REV                                           = 0x8D9F),
:(const GL_CLAMP_VERTEX_COLOR                                           = 0x891A),
:(const GL_UNSIGNED_INT_SAMPLER_3D                                      = 0x8DD3),
:(const GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION                     = 0x8E4C),
:(const GL_DEPTH_ATTACHMENT                                             = 0x8D00),
:(const GL_QUERY_NO_WAIT                                                = 0x8E14),
:(const GL_UNSIGNED_INT_SAMPLER_1D_ARRAY                                = 0x8DD6),
:(const GL_PROVOKING_VERTEX                                             = 0x8E4F),
:(const GL_COMPRESSED_RG_RGTC2                                          = 0x8DBD),
:(const GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS                = 0x8C8A),
:(const GL_PROGRAM_BINARY_LENGTH                                        = 0x8741),
:(const GL_TEXTURE_2D_MULTISAMPLE_ARRAY                                 = 0x9102),
:(const GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY                      = 0x906C),
:(const GL_MAX_COLOR_ATTACHMENTS                                        = 0x8CDF),
:(const GL_LOW_INT                                                      = 0x8DF3),
:(const GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE                            = 0x8215),
:(const GL_COMPRESSED_RG                                                = 0x8226),
:(const GL_R16I                                                         = 0x8233),
:(const GL_FRAMEBUFFER_DEFAULT                                          = 0x8218),
:(const GL_ONE_MINUS_SRC1_COLOR                                         = 0x88FA),
:(const GL_UNSIGNED_NORMALIZED                                          = 0x8C17),
:(const GL_COMPRESSED_SIGNED_RG_RGTC2                                   = 0x8DBE),
:(const GL_SEPARATE_ATTRIBS                                             = 0x8C8D),
:(const GL_PACK_COMPRESSED_BLOCK_HEIGHT                                 = 0x912C),
:(const GL_MAX_INTEGER_SAMPLES                                          = 0x9110),
:(const GL_SYNC_FENCE                                                   = 0x9116),
:(const GL_INT_IMAGE_CUBE                                               = 0x905B),
:(const GL_FRAMEBUFFER_BINDING                                          = 0x8CA6),
:(const GL_INTERLEAVED_ATTRIBS                                          = 0x8C8C),
:(const GL_UNIFORM_MATRIX_STRIDE                                        = 0x8A3D),
:(const GL_ONE_MINUS_SRC1_ALPHA                                         = 0x88FB),
:(const GL_SAMPLER_2D_ARRAY_SHADOW                                      = 0x8DC4),
:(const GL_RG32UI                                                       = 0x823C),
:(const GL_MAX_GEOMETRY_IMAGE_UNIFORMS                                  = 0x90CD),
:(const GL_RGBA16F                                                      = 0x881A),
:(const GL_COPY_READ_BUFFER                                             = 0x8F36),
:(const GL_TRANSFORM_FEEDBACK_BUFFER_BINDING                            = 0x8C8F),
:(const GL_MAP_READ_BIT                                                 = 0x0001),
:(const GL_GEOMETRY_SHADER                                              = 0x8DD9),
:(const GL_RG16_SNORM                                                   = 0x8F99),
:(const GL_MAX_VERTEX_UNIFORM_BLOCKS                                    = 0x8A2B),
:(const GL_RGBA8I                                                       = 0x8D8E),
:(const GL_RGB8_SNORM                                                   = 0x8F96),
:(const GL_RENDERBUFFER_SAMPLES                                         = 0x8CAB),
:(const GL_TEXTURE_BINDING_1D_ARRAY                                     = 0x8C1C),
:(const GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS                         = 0x8E81),
:(const GL_TRIANGLES_ADJACENCY                                          = 0x000C),
:(const GL_COLOR_ATTACHMENT0                                            = 0x8CE0),
:(const GL_FIRST_VERTEX_CONVENTION                                      = 0x8E4D),
:(const GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS                   = 0x8C80),
:(const GL_MAX_CLIP_DISTANCES                                           = 0x0D32),
:(const GL_TRIANGLE_STRIP_ADJACENCY                                     = 0x000D),
:(const GL_MAX_VIEWPORTS                                                = 0x825B),
:(const GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS                             = 0x8C29),
:(const GL_SYNC_FLAGS                                                   = 0x9115),
:(const GL_INVALID_FRAMEBUFFER_OPERATION                                = 0x0506),
:(const GL_IMAGE_CUBE                                                   = 0x9050),
:(const GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY                           = 0x9103),
:(const GL_RENDERBUFFER_WIDTH                                           = 0x8D42),
:(const GL_RGBA16I                                                      = 0x8D88),
:(const GL_BGR_INTEGER                                                  = 0x8D9A),
:(const GL_R16_SNORM                                                    = 0x8F98),
:(const GL_PATCH_DEFAULT_OUTER_LEVEL                                    = 0x8E74),
:(const GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE                            = 0x906B),
:(const GL_DRAW_INDIRECT_BUFFER_BINDING                                 = 0x8F43),
:(const GL_MAX_SAMPLES                                                  = 0x8D57),
:(const GL_TEXTURE_SWIZZLE_G                                            = 0x8E43),
:(const GL_UNSIGNED_INT_IMAGE_2D                                        = 0x9063),
:(const GL_GEOMETRY_INPUT_TYPE                                          = 0x8917),
:(const GL_TEXTURE_IMMUTABLE_FORMAT                                     = 0x912F),
:(const GL_R8I                                                          = 0x8231),
:(const GL_MAX_SUBROUTINES                                              = 0x8DE7),
:(const GL_TRANSFORM_FEEDBACK_BUFFER                                    = 0x8C8E),
:(const GL_COLOR_ATTACHMENT4                                            = 0x8CE4),
:(const GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS                            = 0x92CC),
:(const GL_COLOR_ATTACHMENT9                                            = 0x8CE9),
:(const GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER           = 0x84F1),
:(const GL_UNIFORM_BUFFER_SIZE                                          = 0x8A2A),
:(const GL_STENCIL_INDEX4                                               = 0x8D47),
:(const GL_MAX_IMAGE_SAMPLES                                            = 0x906D),
:(const GL_RGB_SNORM                                                    = 0x8F92),
:(const GL_FRAMEBUFFER                                                  = 0x8D40),
:(const GL_COLOR_ATTACHMENT6                                            = 0x8CE6),
:(const GL_UNSIGNED_INT_SAMPLER_2D                                      = 0x8DD2),
:(const GL_TEXTURE_RECTANGLE                                            = 0x84F5),
:(const GL_TEXTURE_BINDING_2D_MULTISAMPLE                               = 0x9104),
:(const GL_TEXTURE_CUBE_MAP_ARRAY                                       = 0x9009),
:(const GL_FRAMEBUFFER_SRGB                                             = 0x8DB9),
:(const GL_DRAW_FRAMEBUFFER                                             = 0x8CA9),
:(const GL_TEXTURE_BLUE_TYPE                                            = 0x8C12),
:(const GL_RG                                                           = 0x8227),
:(const GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE                          = 0x8217),
:(const GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER            = 0x92C7),
:(const GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT                    = 0x8CD7),
:(const GL_LINE_STRIP_ADJACENCY                                         = 0x000B),
:(const GL_IMAGE_BINDING_NAME                                           = 0x8F3A),
:(const GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE                        = 0x8211),
:(const GL_PROGRAM_PIPELINE_BINDING                                     = 0x825A),
:(const GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT                          = 0x0001),
:(const GL_UNSIGNED_INT_SAMPLER_2D_ARRAY                                = 0x8DD7),
:(const GL_RGBA_SNORM                                                   = 0x8F93),
:(const GL_INT_IMAGE_1D_ARRAY                                           = 0x905D),
:(const GL_TEXTURE_SWIZZLE_RGBA                                         = 0x8E46),
:(const GL_PROXY_TEXTURE_RECTANGLE                                      = 0x84F7),
:(const GL_DOUBLE_MAT3                                                  = 0x8F47),
:(const GL_IMAGE_FORMAT_COMPATIBILITY_TYPE                              = 0x90C7),
:(const GL_UNIFORM_BLOCK_INDEX                                          = 0x8A3A),
:(const GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY                    = 0x910D),
:(const GL_RGBA32F                                                      = 0x8814),
:(const GL_MAX_DUAL_SOURCE_DRAW_BUFFERS                                 = 0x88FC),
:(const GL_ANY_SAMPLES_PASSED                                           = 0x8C2F),
:(const GL_RGBA_INTEGER                                                 = 0x8D99),
:(const GL_ATOMIC_COUNTER_BUFFER_SIZE                                   = 0x92C3),
:(const GL_RGB16I                                                       = 0x8D89),
:(const GL_MAX_COMBINED_IMAGE_UNIFORMS                                  = 0x90CF),
:(const GL_HIGH_INT                                                     = 0x8DF5),
:(const GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES                         = 0x8A43),
:(const GL_UNSIGNED_INT_IMAGE_1D                                        = 0x9062),
:(const GL_RGB16F                                                       = 0x881B),
:(const GL_MAX_COMBINED_UNIFORM_BLOCKS                                  = 0x8A2E),
:(const GL_TESS_GEN_POINT_MODE                                          = 0x8E79),
:(const GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY                               = 0x9061),
:(const GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY                             = 0x910C),
:(const GL_FRAMEBUFFER_BARRIER_BIT                                      = 0x00000400),
:(const GL_RGB_INTEGER                                                  = 0x8D98),
:(const GL_PACK_COMPRESSED_BLOCK_DEPTH                                  = 0x912D),
:(const GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW                                = 0x900D),
:(const GL_FIXED_ONLY                                                   = 0x891D),
:(const GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS                             = 0x92D3),
:(const GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS                             = 0x8DE8),
:(const GL_ATOMIC_COUNTER_BUFFER_START                                  = 0x92C2),
:(const GL_MAX_UNIFORM_BLOCK_SIZE                                       = 0x8A30),
:(const GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS                           = 0x92DC),
:(const GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS                              = 0x8E89),
:(const GL_UNSIGNED_INT_SAMPLER_CUBE                                    = 0x8DD4),
:(const GL_INT_IMAGE_2D                                                 = 0x9058),
:(const GL_RGBA16_SNORM                                                 = 0x8F9B),
:(const GL_UNSIGNED_INT_SAMPLER_BUFFER                                  = 0x8DD8),
:(const GL_CLIP_DISTANCE3                                               = 0x3003),
:(const GL_COMPRESSED_RED_RGTC1                                         = 0x8DBB),
:(const GL_INDEX                                                        = 0x8222),
:(const GL_GREEN_INTEGER                                                = 0x8D95),
:(const GL_RG_INTEGER                                                   = 0x8228),
:(const GL_PROXY_TEXTURE_CUBE_MAP_ARRAY                                 = 0x900B),
:(const GL_RENDERBUFFER_DEPTH_SIZE                                      = 0x8D54),
:(const GL_HALF_FLOAT                                                   = 0x140B),
:(const GL_CONTEXT_FLAGS                                                = 0x821E),
:(const GL_DEPTH_STENCIL                                                = 0x84F9),
:(const GL_MAP_INVALIDATE_RANGE_BIT                                     = 0x0004),
:(const GL_SAMPLER_BUFFER                                               = 0x8DC2),
:(const GL_MAX_SERVER_WAIT_TIMEOUT                                      = 0x9111),
:(const GL_SAMPLER_1D_ARRAY_SHADOW                                      = 0x8DC3),
:(const GL_TEXTURE_2D_MULTISAMPLE                                       = 0x9100),
:(const GL_PATCH_VERTICES                                               = 0x8E72),
:(const GL_QUERY_BY_REGION_NO_WAIT                                      = 0x8E16),
:(const GL_DOUBLE_MAT3x4                                                = 0x8F4C),
:(const GL_VIEWPORT_INDEX_PROVOKING_VERTEX                              = 0x825F),
:(const GL_R11F_G11F_B10F                                               = 0x8C3A),
:(const GL_RENDERBUFFER_ALPHA_SIZE                                      = 0x8D53),
:(const GL_TEXTURE_SHARED_SIZE                                          = 0x8C3F),
:(const GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS                   = 0x92CE),
:(const GL_RG8UI                                                        = 0x8238),
:(const GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS                          = 0x8E7F),
:(const GL_RENDERBUFFER                                                 = 0x8D41),
:(const GL_INT_IMAGE_2D_MULTISAMPLE                                     = 0x9060),
:(const GL_DOUBLE_MAT2                                                  = 0x8F46),
:(const GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT                              = 0x00000001),
:(const GL_RENDERBUFFER_BLUE_SIZE                                       = 0x8D52),
:(const GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH                        = 0x8C76),
:(const GL_UNSIGNED_INT_SAMPLER_2D_RECT                                 = 0x8DD5),
:(const GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS                      = 0x8E82),
:(const GL_INT_IMAGE_1D                                                 = 0x9057),
:(const GL_SHADER_IMAGE_ACCESS_BARRIER_BIT                              = 0x00000020),
:(const GL_MAX_FRAGMENT_UNIFORM_BLOCKS                                  = 0x8A2D),
:(const GL_IMAGE_BUFFER                                                 = 0x9051),
:(const GL_DOUBLE_MAT4                                                  = 0x8F48),
:(const GL_RG32I                                                        = 0x823B),
:(const GL_ATOMIC_COUNTER_BARRIER_BIT                                   = 0x00001000),
:(const GL_TEXTURE_SAMPLES                                              = 0x9106),
:(const GL_NUM_COMPATIBLE_SUBROUTINES                                   = 0x8E4A),
:(const GL_MAX_RECTANGLE_TEXTURE_SIZE                                   = 0x84F8),
:(const GL_MAX_VARYING_COMPONENTS                                       = 0x8B4B),
:(const GL_RGB32I                                                       = 0x8D83),
:(const GL_COLOR_ATTACHMENT8                                            = 0x8CE8),
:(const GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS                      = 0x92CD),
:(const GL_NUM_PROGRAM_BINARY_FORMATS                                   = 0x87FE),
:(const GL_RGB565                                                       = 0x8D62),
:(const GL_STENCIL_ATTACHMENT                                           = 0x8D20),
:(const GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS                              = 0x90CB),
:(const GL_SAMPLER_2D_MULTISAMPLE_ARRAY                                 = 0x910B),
:(const GL_MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS                        = 0x8F9F),
:(const GL_RG16                                                         = 0x822C),
:(const GL_COMPRESSED_SIGNED_RED_RGTC1                                  = 0x8DBC),
:(const GL_DEPTH24_STENCIL8                                             = 0x88F0),
:(const GL_RG16F                                                        = 0x822F),
:(const GL_INT_IMAGE_3D                                                 = 0x9059),
:(const GL_RENDERBUFFER_RED_SIZE                                        = 0x8D50),
:(const GL_DEPTH_STENCIL_ATTACHMENT                                     = 0x821A),
:(const GL_MAX_TESS_GEN_LEVEL                                           = 0x8E7E),
:(const GL_UNPACK_COMPRESSED_BLOCK_DEPTH                                = 0x9129),
:(const GL_QUERY_BY_REGION_WAIT                                         = 0x8E15),
:(const GL_INT_SAMPLER_2D_RECT                                          = 0x8DCD),
:(const GL_MAX_PATCH_VERTICES                                           = 0x8E7D),
:(const GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER                         = 0x8CD4),
:(const GL_ALL_SHADER_BITS                                              = 0xFFFFFFFF),
:(const GL_UNSIGNED_INT_5_9_9_9_REV                                     = 0x8C3E),
:(const GL_PACK_COMPRESSED_BLOCK_SIZE                                   = 0x912E),
:(const GL_UNIFORM_ARRAY_STRIDE                                         = 0x8A3C),
:(const GL_COLOR_ATTACHMENT5                                            = 0x8CE5),
:(const GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT                            = 0x8CD6),
:(const GL_PACK_COMPRESSED_BLOCK_WIDTH                                  = 0x912B),
:(const GL_DOUBLE_MAT2x4                                                = 0x8F4A),
:(const GL_UNSIGNALED                                                   = 0x9118),
:(const GL_UNPACK_COMPRESSED_BLOCK_SIZE                                 = 0x912A),
:(const GL_MAX_COLOR_TEXTURE_SAMPLES                                    = 0x910E),
:(const GL_FRAGMENT_SHADER_BIT                                          = 0x00000002),
:(const GL_SIGNALED                                                     = 0x9119),
:(const GL_MAX_FRAGMENT_UNIFORM_VECTORS                                 = 0x8DFD),
:(const GL_INT_IMAGE_2D_ARRAY                                           = 0x905E),
:(const GL_NUM_SHADER_BINARY_FORMATS                                    = 0x8DF9),
:(const GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE                            = 0x8213),
:(const GL_RGBA32UI                                                     = 0x8D70),
:(const GL_COLOR_ATTACHMENT14                                           = 0x8CEE),
:(const GL_TESS_CONTROL_SHADER                                          = 0x8E88),
:(const GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS                          = 0x92D4),
:(const GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS                          = 0x92D0),
:(const GL_TEXTURE_RED_TYPE                                             = 0x8C10),
:(const GL_TEXTURE_2D_ARRAY                                             = 0x8C1A),
:(const GL_CONTEXT_CORE_PROFILE_BIT                                     = 0x00000001),
:(const GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER      = 0x92C8),
:(const GL_RG8_SNORM                                                    = 0x8F95),
:(const GL_DRAW_FRAMEBUFFER_BINDING                                     = 0x8CA6),
:(const GL_UNPACK_COMPRESSED_BLOCK_WIDTH                                = 0x9127),
:(const GL_QUERY_WAIT                                                   = 0x8E13),
:(const GL_ALL_BARRIER_BITS                                             = 0xFFFFFFFF),
:(const GL_TESS_GEN_SPACING                                             = 0x8E77),
:(const GL_TRANSFORM_FEEDBACK_BUFFER_START                              = 0x8C84),
:(const GL_MIN_FRAGMENT_INTERPOLATION_OFFSET                            = 0x8E5B),
:(const GL_MAX_FRAGMENT_IMAGE_UNIFORMS                                  = 0x90CE),
:(const GL_TIMEOUT_IGNORED                                              = 0xFFFFFFFFFFFFFFFF),
:(const GL_ACTIVE_SUBROUTINE_UNIFORMS                                   = 0x8DE6),
:(const GL_GEOMETRY_OUTPUT_TYPE                                         = 0x8918),
:(const GL_TEXTURE_FIXED_SAMPLE_LOCATIONS                               = 0x9107),
:(const GL_INT_IMAGE_BUFFER                                             = 0x905C),
:(const GL_FIXED                                                        = 0x140C),
:(const GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS                       = 0x8E80),
:(const GL_UNSIGNED_INT_VEC4                                            = 0x8DC8),
:(const GL_UNIFORM_IS_ROW_MAJOR                                         = 0x8A3E),
:(const GL_TEXTURE_BINDING_BUFFER                                       = 0x8C2C),
:(const GL_RG8                                                          = 0x822B),
:(const GL_TEXTURE_GREEN_TYPE                                           = 0x8C11),
:(const GL_RGB8UI                                                       = 0x8D7D),
:(const GL_ALREADY_SIGNALED                                             = 0x911A),
:(const GL_GEOMETRY_VERTICES_OUT                                        = 0x8916),
:(const GL_TEXTURE_STENCIL_SIZE                                         = 0x88F1),
:(const GL_VERTEX_ATTRIB_ARRAY_DIVISOR                                  = 0x88FE),
:(const GL_MAX_FRAGMENT_INPUT_COMPONENTS                                = 0x9125),
:(const GL_IMAGE_1D                                                     = 0x904C),
:(const GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE                          = 0x910A),
:(const GL_R16UI                                                        = 0x8234),
:(const GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS                      = 0x8C8B),
:(const GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS                 = 0x8E1E),
:(const GL_SYNC_CONDITION                                               = 0x9113),
:(const GL_VIEWPORT_BOUNDS_RANGE                                        = 0x825D),
:(const GL_TESS_GEN_MODE                                                = 0x8E76),
:(const GL_COMPATIBLE_SUBROUTINES                                       = 0x8E4B),
:(const GL_COLOR_ATTACHMENT11                                           = 0x8CEB),
:(const GL_PROGRAM_BINARY_RETRIEVABLE_HINT                              = 0x8257),
:(const GL_WAIT_FAILED                                                  = 0x911D),
:(const GL_MAX_VERTEX_IMAGE_UNIFORMS                                    = 0x90CA),
:(const GL_TEXTURE_BINDING_RECTANGLE                                    = 0x84F6),
:(const GL_R16F                                                         = 0x822D),
:(const GL_RG8I                                                         = 0x8237),
:(const GL_UNIFORM_TYPE                                                 = 0x8A37),
:(const GL_CONTEXT_COMPATIBILITY_PROFILE_BIT                            = 0x00000002),
:(const GL_SAMPLER_CUBE_SHADOW                                          = 0x8DC5),
:(const GL_VIEWPORT_SUBPIXEL_BITS                                       = 0x825C),
:(const GL_TESS_CONTROL_OUTPUT_VERTICES                                 = 0x8E75),
:(const GL_MAX_UNIFORM_BUFFER_BINDINGS                                  = 0x8A2F),
:(const GL_CLIP_DISTANCE1                                               = 0x3001),
:(const GL_PATCHES                                                      = 0x000E),
:(const GL_UNIFORM_BLOCK_DATA_SIZE                                      = 0x8A40),
:(const GL_COMPARE_REF_TO_TEXTURE                                       = 0x884E),
:(const GL_LOW_FLOAT                                                    = 0x8DF0),
:(const GL_IMAGE_2D_MULTISAMPLE                                         = 0x9055),
:(const GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY                          = 0x900F),
:(const GL_PRIMITIVE_RESTART                                            = 0x8F9D),
:(const GL_SYNC_STATUS                                                  = 0x9114),
:(const GL_TEXTURE_SWIZZLE_R                                            = 0x8E42),
:(const GL_MAX_FRAGMENT_ATOMIC_COUNTERS                                 = 0x92D6),
:(const GL_COLOR_ATTACHMENT1                                            = 0x8CE1),
:(const GL_TEXTURE_ALPHA_TYPE                                           = 0x8C13),
:(const GL_CLIP_DISTANCE7                                               = 0x3007),
:(const GL_VERTEX_ATTRIB_ARRAY_INTEGER                                  = 0x88FD)]
#function bodies
const GL_GL42_FUNCTIONS = [
:(glDrawElementsInstancedBaseVertexBaseInstance(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, instancecount::GLsizei, basevertex::GLint, baseinstance::GLuint)::Void),
:(glIsProgramPipeline(pipeline::GLuint)::Bool),
:(glVertexAttribL2dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glFramebufferRenderbuffer(target::GLenum, attachment::GLenum, renderbuffertarget::GLenum, renderbuffer::GLuint)::Void),
:(glBindBufferBase(target::GLenum, index::GLuint, buffer::GLuint)::Void),
:(glClientWaitSync(sync::GLsync, flags::GLbitfield, timeout::GLuClonglong)::Cint),
:(glGetIntegeri_v(target::GLenum, index::GLuint, data::Ptr{GLint})::Void),
:(glBindProgramPipeline(pipeline::GLuint)::Void),
:(glTexCoordP2ui(type_::GLenum, coords::GLuint)::Void),
:(glGetActiveUniformBlockName(program::GLuint, uniformBlockIndex::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, uniformBlockName::Ptr{GLchar})::Void),
:(glProvokingVertex(mode::GLenum)::Void),
:(glVertexAttribL3d(index::GLuint, x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glTexParameterIiv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribI4usv(index::GLuint, v::Ptr{GLushort})::Void),
:(glVertexAttribI2iv(index::GLuint, v::Ptr{GLint})::Void),
:(glProgramParameteri(program::GLuint, pname::GLenum, value::GLint)::Void),
:(glTexStorage3D(target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei, depth::GLsizei)::Void),
:(glTexCoordP3ui(type_::GLenum, coords::GLuint)::Void),
:(glDeleteSync(sync::GLsync)::Void),
:(glGenSamplers(count::GLsizei, samplers::Ptr{GLuint})::Void),
:(glBindFragDataLocation(program::GLuint, color::GLuint, name::Ptr{GLchar})::Void),
:(glGetSubroutineIndex(program::GLuint, shadertype::GLenum, name::Ptr{GLchar})::Cuint),
:(glProgramUniformMatrix4fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glVertexAttribL3dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glGetShaderPrecisionFormat(shadertype::GLenum, precisiontype::GLenum, range_::Ptr{GLint}, precision::Ptr{GLint})::Void),
:(glProgramUniformMatrix2fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glSamplerParameteri(sampler::GLuint, pname::GLenum, param::GLint)::Void),
:(glGenTransformFeedbacks(n::GLsizei, ids::Ptr{GLuint})::Void),
:(glProgramUniform1fv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glResumeTransformFeedback()::Void),
:(glProgramUniform4iv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glProgramUniform3uiv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glMultiDrawElementsBaseVertex(mode::GLenum, count::Ptr{GLsizei}, type_::GLenum, indices::Ptr{Ptr{Void}}, drawcount::GLsizei, basevertex::Ptr{GLint})::Void),
:(glDrawElementsInstancedBaseInstance(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, instancecount::GLsizei, baseinstance::GLuint)::Void),
:(glGenRenderbuffers(n::GLsizei, renderbuffers::Ptr{GLuint})::Void),
:(glDrawTransformFeedback(mode::GLenum, id::GLuint)::Void),
:(glUniform1d(location::GLint, x::GLdouble)::Void),
:(glProgramUniform4dv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glProgramUniformMatrix2x3dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glFlushMappedBufferRange(target::GLenum, offset::GLintptr, length::GLsizeiptr)::Void),
:(glUniformMatrix2x4dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glGetUniformdv(program::GLuint, location::GLint, params::Ptr{GLdouble})::Void),
:(glUniform1ui(location::GLint, v0::GLuint)::Void),
:(glProgramUniformMatrix2x3fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glBindTransformFeedback(target::GLenum, id::GLuint)::Void),
:(glBeginConditionalRender(id::GLuint, mode::GLenum)::Void),
:(glGetActiveUniformsiv(program::GLuint, uniformCount::GLsizei, uniformIndices::Ptr{GLuint}, pname::GLenum, params::Ptr{GLint})::Void),
:(glDrawElementsIndirect(mode::GLenum, type_::GLenum, indirect::Ptr{Void})::Void),
:(glGetStringi(name::GLenum, index::GLuint)::Ptr{Cuchar}),
:(glUniformMatrix3dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glTransformFeedbackVaryings(program::GLuint, count::GLsizei, varyings::Ptr{Uint8}, bufferMode::GLenum)::Void),
:(glGetSamplerParameterIiv(sampler::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetVertexAttribIuiv(index::GLuint, pname::GLenum, params::Ptr{GLuint})::Void),
:(glRenderbufferStorageMultisample(target::GLenum, samples::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glVertexAttribL4d(index::GLuint, x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glUniform2ui(location::GLint, v0::GLuint, v1::GLuint)::Void),
:(glUseProgramStages(pipeline::GLuint, stages::GLbitfield, program::GLuint)::Void),
:(glReleaseShaderCompiler()::Void),
:(glBindFramebuffer(target::GLenum, framebuffer::GLuint)::Void),
:(glGetQueryObjectui64v(id::GLuint, pname::GLenum, params::Ptr{GLuint64})::Void),
:(glFramebufferTexture3D(target::GLenum, attachment::GLenum, textarget::GLenum, texture::GLuint, level::GLint, zoffset::GLint)::Void),
:(glVertexAttribDivisor(index::GLuint, divisor::GLuint)::Void),
:(glBindFragDataLocationIndexed(program::GLuint, colorNumber::GLuint, index::GLuint, name::Ptr{GLchar})::Void),
:(glDrawElementsBaseVertex(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, basevertex::GLint)::Void),
:(glMultiTexCoordP4ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glProgramUniform1i(program::GLuint, location::GLint, v0::GLint)::Void),
:(glVertexAttribP4ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glGetVertexAttribLdv(index::GLuint, pname::GLenum, params::Ptr{GLdouble})::Void),
:(glUniformMatrix4dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glProgramUniformMatrix4x3dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glProgramUniformMatrix3x4fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glSamplerParameterIuiv(sampler::GLuint, pname::GLenum, param::Ptr{GLuint})::Void),
:(glClearDepthf(d::GLfloat)::Void),
:(glDeleteProgramPipelines(n::GLsizei, pipelines::Ptr{GLuint})::Void),
:(glProgramUniform2fv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glProgramUniformMatrix4x2dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glProgramUniform1iv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glDrawElementsInstancedBaseVertex(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, instancecount::GLsizei, basevertex::GLint)::Void),
:(glUniform3dv(location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glProgramUniform2iv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glProgramUniform4fv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glDrawTransformFeedbackInstanced(mode::GLenum, id::GLuint, instancecount::GLsizei)::Void),
:(glColorMaski(index::GLuint, r::GLboolean, g::GLboolean, b::GLboolean, a::GLboolean)::Void),
:(glNormalP3ui(type_::GLenum, coords::GLuint)::Void),
:(glVertexP3ui(type_::GLenum, value::GLuint)::Void),
:(glUniformMatrix2dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glGenerateMipmap(target::GLenum)::Void),
:(glScissorArrayv(first::GLuint, count::GLsizei, v::Ptr{GLint})::Void),
:(glProgramUniform2dv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glUniform4d(location::GLint, x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glDrawArraysInstanced(mode::GLenum, first::GLint, count::GLsizei, instancecount::GLsizei)::Void),
:(glProgramUniform3ui(program::GLuint, location::GLint, v0::GLuint, v1::GLuint, v2::GLuint)::Void),
:(glDeleteRenderbuffers(n::GLsizei, renderbuffers::Ptr{GLuint})::Void),
:(glGetProgramPipelineInfoLog(pipeline::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, infoLog::Ptr{GLchar})::Void),
:(glVertexAttribP1ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glUniformSubroutinesuiv(shadertype::GLenum, count::GLsizei, indices::Ptr{GLuint})::Void),
:(glWaitSync(sync::GLsync, flags::GLbitfield, timeout::GLuint64)::Void),
:(glMultiTexCoordP1ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glVertexAttribI1uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glGetUniformBlockIndex(program::GLuint, uniformBlockName::Ptr{GLchar})::Cuint),
:(glIsVertexArray(array::GLuint)::Bool),
:(glVertexAttribP2uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glIsEnabledi(target::GLenum, index::GLuint)::Bool),
:(glPatchParameteri(pname::GLenum, value::GLint)::Void),
:(glProgramUniform4uiv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glVertexAttribP2ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glGenVertexArrays(n::GLsizei, arrays::Ptr{GLuint})::Void),
:(glProgramBinary(program::GLuint, binaryFormat::GLenum, binary::Ptr{Void}, length::GLsizei)::Void),
:(glSecondaryColorP3uiv(type_::GLenum, color::Ptr{GLuint})::Void),
:(glGetInternalformativ(target::GLenum, internalformat::GLenum, pname::GLenum, bufSize::GLsizei, params::Ptr{GLint})::Void),
:(glMinSampleShading(value::GLfloat)::Void),
:(glProgramUniform2f(program::GLuint, location::GLint, v0::GLfloat, v1::GLfloat)::Void),
:(glProgramUniform2uiv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glQueryCounter(id::GLuint, target::GLenum)::Void),
:(glNormalP3uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glTexStorage2D(target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glDrawArraysIndirect(mode::GLenum, indirect::Ptr{Void})::Void),
:(glTexCoordP2uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glUniform4ui(location::GLint, v0::GLuint, v1::GLuint, v2::GLuint, v3::GLuint)::Void),
:(glProgramUniformMatrix4x3fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glProgramUniform4f(program::GLuint, location::GLint, v0::GLfloat, v1::GLfloat, v2::GLfloat, v3::GLfloat)::Void),
:(glVertexAttribI4i(index::GLuint, x::GLint, y::GLint, z::GLint, w::GLint)::Void),
:(glDrawRangeElementsBaseVertex(mode::GLenum, start::GLuint, END::GLuint, count::GLsizei, type_::GLenum, indices::Ptr{Void}, basevertex::GLint)::Void),
:(glGenProgramPipelines(n::GLsizei, pipelines::Ptr{GLuint})::Void),
:(glProgramUniform3i(program::GLuint, location::GLint, v0::GLint, v1::GLint, v2::GLint)::Void),
:(glVertexAttribI4uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glActiveShaderProgram(pipeline::GLuint, program::GLuint)::Void),
:(glProgramUniformMatrix2dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glGetInteger64v(pname::GLenum, params::Ptr{GLint64})::Void),
:(glProgramUniformMatrix4dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glVertexAttribI2ui(index::GLuint, x::GLuint, y::GLuint)::Void),
:(glPrimitiveRestartIndex(index::GLuint)::Void),
:(glShaderBinary(count::GLsizei, shaders::Ptr{GLuint}, binaryformat::GLenum, binary::Ptr{Void}, length::GLsizei)::Void),
:(glProgramUniformMatrix3x2dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glGetActiveSubroutineUniformiv(program::GLuint, shadertype::GLenum, index::GLuint, pname::GLenum, values::Ptr{GLint})::Void),
:(glPauseTransformFeedback()::Void),
:(glGetSamplerParameteriv(sampler::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribI3uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glVertexAttribP4uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glProgramUniform3d(program::GLuint, location::GLint, v0::GLdouble, v1::GLdouble, v2::GLdouble)::Void),
:(glVertexAttribI1iv(index::GLuint, v::Ptr{GLint})::Void),
:(glFramebufferTexture1D(target::GLenum, attachment::GLenum, textarget::GLenum, texture::GLuint, level::GLint)::Void),
:(glUniform2uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glEndConditionalRender()::Void),
:(glUniform3uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glBlendFuncSeparatei(buf::GLuint, srcRGB::GLenum, dstRGB::GLenum, srcAlpha::GLenum, dstAlpha::GLenum)::Void),
:(glProgramUniform1dv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glProgramUniform1uiv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glGetActiveSubroutineUniformName(program::GLuint, shadertype::GLenum, index::GLuint, bufsize::GLsizei, length::Ptr{GLsizei}, name::Ptr{GLchar})::Void),
:(glProgramUniform2ui(program::GLuint, location::GLint, v0::GLuint, v1::GLuint)::Void),
:(glGenFramebuffers(n::GLsizei, framebuffers::Ptr{GLuint})::Void),
:(glFramebufferTextureLayer(target::GLenum, attachment::GLenum, texture::GLuint, level::GLint, layer::GLint)::Void),
:(glScissorIndexedv(index::GLuint, v::Ptr{GLint})::Void),
:(glSecondaryColorP3ui(type_::GLenum, color::GLuint)::Void),
:(glClearBufferfi(buffer::GLenum, drawbuffer::GLint, depth::GLfloat, stencil::GLint)::Void),
:(glProgramUniformMatrix3dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glViewportArrayv(first::GLuint, count::GLsizei, v::Ptr{GLfloat})::Void),
:(glBlendEquationi(buf::GLuint, mode::GLenum)::Void),
:(glDrawArraysInstancedBaseInstance(mode::GLenum, first::GLint, count::GLsizei, instancecount::GLsizei, baseinstance::GLuint)::Void),
:(glUniform4uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glGetVertexAttribIiv(index::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetTransformFeedbackVarying(program::GLuint, index::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, size::Ptr{GLsizei}, type_::Ptr{GLenum}, name::Ptr{GLchar})::Void),
:(glVertexAttribLPointer(index::GLuint, size::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glGetFramebufferAttachmentParameteriv(target::GLenum, attachment::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribI1i(index::GLuint, x::GLint)::Void),
:(glVertexAttribI3ui(index::GLuint, x::GLuint, y::GLuint, z::GLuint)::Void),
:(glGetActiveAtomicCounterBufferiv(program::GLuint, bufferIndex::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glProgramUniform3dv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glGetActiveUniformBlockiv(program::GLuint, uniformBlockIndex::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glBlitFramebuffer(srcX0::GLint, srcY0::GLint, srcX1::GLint, srcY1::GLint, dstX0::GLint, dstY0::GLint, dstX1::GLint, dstY1::GLint, mask::GLbitfield, filter::GLenum)::Void),
:(glUniformMatrix4x3dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glBeginTransformFeedback(primitiveMode::GLenum)::Void),
:(glVertexAttribI4bv(index::GLuint, v::Ptr{GLbyte})::Void),
:(glIsSampler(sampler::GLuint)::Bool),
:(glVertexAttribI3i(index::GLuint, x::GLint, y::GLint, z::GLint)::Void),
:(glVertexAttribI4ui(index::GLuint, x::GLuint, y::GLuint, z::GLuint, w::GLuint)::Void),
:(glCheckFramebufferStatus(target::GLenum)::Cint),
:(glVertexAttribI4ubv(index::GLuint, v::Ptr{GLubyte})::Void),
:(glUniformBlockBinding(program::GLuint, uniformBlockIndex::GLuint, uniformBlockBinding::GLuint)::Void),
:(glProgramUniformMatrix3x4dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glEndQueryIndexed(target::GLenum, index::GLuint)::Void),
:(glBlendFunci(buf::GLuint, src::GLenum, dst::GLenum)::Void),
:(glGetSynciv(sync::GLsync, pname::GLenum, bufSize::GLsizei, length::Ptr{GLsizei}, values::Ptr{GLint})::Void),
:(glClampColor(target::GLenum, clamp::GLenum)::Void),
:(glVertexAttribP3ui(index::GLuint, type_::GLenum, normalized::GLboolean, value::GLuint)::Void),
:(glFenceSync(condition::GLenum, flags::GLbitfield)::Sync),
:(glSamplerParameterfv(sampler::GLuint, pname::GLenum, param::Ptr{GLfloat})::Void),
:(glProgramUniformMatrix3fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glProgramUniform3f(program::GLuint, location::GLint, v0::GLfloat, v1::GLfloat, v2::GLfloat)::Void),
:(glDeleteTransformFeedbacks(n::GLsizei, ids::Ptr{GLuint})::Void),
:(glMapBufferRange(target::GLenum, offset::GLintptr, length::GLsizeiptr, access::GLbitfield)::Ptr{Void}),
:(glTexCoordP4uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glGetActiveUniformName(program::GLuint, uniformIndex::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, uniformName::Ptr{GLchar})::Void),
:(glPatchParameterfv(pname::GLenum, values::Ptr{GLfloat})::Void),
:(glProgramUniform4d(program::GLuint, location::GLint, v0::GLdouble, v1::GLdouble, v2::GLdouble, v3::GLdouble)::Void),
:(glClearBufferiv(buffer::GLenum, drawbuffer::GLint, value::Ptr{GLint})::Void),
:(glDepthRangeArrayv(first::GLuint, count::GLsizei, v::Ptr{GLdouble})::Void),
:(glBindVertexArray(array::GLuint)::Void),
:(glSamplerParameteriv(sampler::GLuint, pname::GLenum, param::Ptr{GLint})::Void),
:(glProgramUniformMatrix4x2fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glGetSamplerParameterfv(sampler::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glScissorIndexed(index::GLuint, left::GLint, bottom::GLint, width::GLsizei, height::GLsizei)::Void),
:(glVertexAttribI3iv(index::GLuint, v::Ptr{GLint})::Void),
:(glVertexP4uiv(type_::GLenum, value::Ptr{GLuint})::Void),
:(glIsTransformFeedback(id::GLuint)::Bool),
:(glMultiTexCoordP1uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glBeginQueryIndexed(target::GLenum, index::GLuint, id::GLuint)::Void),
:(glValidateProgramPipeline(pipeline::GLuint)::Void),
:(glSamplerParameterIiv(sampler::GLuint, pname::GLenum, param::Ptr{GLint})::Void),
:(glProgramUniform2i(program::GLuint, location::GLint, v0::GLint, v1::GLint)::Void),
:(glUniform4dv(location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glVertexAttribI2uiv(index::GLuint, v::Ptr{GLuint})::Void),
:(glGetBooleani_v(target::GLenum, index::GLuint, data::Ptr{GLboolean})::Void),
:(glMultiTexCoordP2uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glTexCoordP1uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glSampleMaski(index::GLuint, mask::GLbitfield)::Void),
:(glFramebufferTexture2D(target::GLenum, attachment::GLenum, textarget::GLenum, texture::GLuint, level::GLint)::Void),
:(glEndTransformFeedback()::Void),
:(glGetSubroutineUniformLocation(program::GLuint, shadertype::GLenum, name::Ptr{GLchar})::Cint),
:(glProgramUniform1f(program::GLuint, location::GLint, v0::GLfloat)::Void),
:(glUniform1uiv(location::GLint, count::GLsizei, value::Ptr{GLuint})::Void),
:(glVertexAttribI2i(index::GLuint, x::GLint, y::GLint)::Void),
:(glProgramUniform4ui(program::GLuint, location::GLint, v0::GLuint, v1::GLuint, v2::GLuint, v3::GLuint)::Void),
:(glTexParameterIuiv(target::GLenum, pname::GLenum, params::Ptr{GLuint})::Void),
:(glProgramUniform2d(program::GLuint, location::GLint, v0::GLdouble, v1::GLdouble)::Void),
:(glVertexAttribP3uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glProgramUniform3iv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glIsSync(sync::GLsync)::Bool),
:(glUniformMatrix2x3dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glGetTexParameterIiv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glUniform3ui(location::GLint, v0::GLuint, v1::GLuint, v2::GLuint)::Void),
:(glDeleteFramebuffers(n::GLsizei, framebuffers::Ptr{GLuint})::Void),
:(glGetTexParameterIuiv(target::GLenum, pname::GLenum, params::Ptr{GLuint})::Void),
:(glUniformMatrix4x2dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glFramebufferTexture(target::GLenum, attachment::GLenum, texture::GLuint, level::GLint)::Void),
:(glTexImage3DMultisample(target::GLenum, samples::GLsizei, internalformat::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, fixedsamplelocations::GLboolean)::Void),
:(glGetUniformSubroutineuiv(shadertype::GLenum, location::GLint, params::Ptr{GLuint})::Void),
:(glVertexAttribL1d(index::GLuint, x::GLdouble)::Void),
:(glTextureStorage3DEXT(texture::GLuint, target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei, depth::GLsizei)::Void),
:(glUniformMatrix3x2dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glTexCoordP4ui(type_::GLenum, coords::GLuint)::Void),
:(glUniform3d(location::GLint, x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glCopyBufferSubData(readTarget::GLenum, writeTarget::GLenum, readOffset::GLintptr, writeOffset::GLintptr, size::GLsizeiptr)::Void),
:(glSamplerParameterf(sampler::GLuint, pname::GLenum, param::GLfloat)::Void),
:(glDepthRangeIndexed(index::GLuint, n::GLdouble, f::GLdouble)::Void),
:(glTextureStorage1DEXT(texture::GLuint, target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei)::Void),
:(glEnablei(target::GLenum, index::GLuint)::Void),
:(glTexBuffer(target::GLenum, internalformat::GLenum, buffer::GLuint)::Void),
:(glGetProgramBinary(program::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, binaryFormat::Ptr{GLenum}, binary::Ptr{Void})::Void),
:(glTexCoordP3uiv(type_::GLenum, coords::Ptr{GLuint})::Void),
:(glVertexAttribL1dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glMultiTexCoordP3ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glClearBufferfv(buffer::GLenum, drawbuffer::GLint, value::Ptr{GLfloat})::Void),
:(glGetRenderbufferParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glDisablei(target::GLenum, index::GLuint)::Void),
:(glVertexAttribI4sv(index::GLuint, v::Ptr{GLshort})::Void),
:(glGetActiveSubroutineName(program::GLuint, shadertype::GLenum, index::GLuint, bufsize::GLsizei, length::Ptr{GLsizei}, name::Ptr{GLchar})::Void),
:(glColorP3ui(type_::GLenum, color::GLuint)::Void),
:(glCreateShaderProgramv(type_::GLenum, count::GLsizei, strings::Ptr{Cuchar})::Cuint),
:(glProgramUniformMatrix2x4dv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glVertexP2ui(type_::GLenum, value::GLuint)::Void),
:(glDrawElementsInstanced(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void}, instancecount::GLsizei)::Void),
:(glGetQueryObjecti64v(id::GLuint, pname::GLenum, params::Ptr{GLint64})::Void),
:(glTextureStorage2DEXT(texture::GLuint, target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glMemoryBarrier(barriers::GLbitfield)::Void),
:(glDrawTransformFeedbackStream(mode::GLenum, id::GLuint, stream::GLuint)::Void),
:(glGetDoublei_v(target::GLenum, index::GLuint, data::Ptr{GLdouble})::Void),
:(glGetMultisamplefv(pname::GLenum, index::GLuint, val::Ptr{GLfloat})::Void),
:(glDeleteVertexArrays(n::GLsizei, arrays::Ptr{GLuint})::Void),
:(glUniform2dv(location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glIsRenderbuffer(renderbuffer::GLuint)::Bool),
:(glClearBufferuiv(buffer::GLenum, drawbuffer::GLint, value::Ptr{GLuint})::Void),
:(glRenderbufferStorage(target::GLenum, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glViewportIndexedf(index::GLuint, x::GLfloat, y::GLfloat, w::GLfloat, h::GLfloat)::Void),
:(glGetInteger64i_v(target::GLenum, index::GLuint, data::Ptr{GLint64})::Void),
:(glVertexAttribI1ui(index::GLuint, x::GLuint)::Void),
:(glGetFragDataIndex(program::GLuint, name::Ptr{GLchar})::Cint),
:(glVertexP2uiv(type_::GLenum, value::Ptr{GLuint})::Void),
:(glGetUniformIndices(program::GLuint, uniformCount::GLsizei, uniformNames::Ptr{Uint8}, uniformIndices::Ptr{GLuint})::Void),
:(glUniform1dv(location::GLint, count::GLsizei, value::Ptr{GLdouble})::Void),
:(glGetFragDataLocation(program::GLuint, name::Ptr{GLchar})::Cint),
:(glGetQueryIndexediv(target::GLenum, index::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glMultiTexCoordP2ui(texture::GLenum, type_::GLenum, coords::GLuint)::Void),
:(glProgramUniform1ui(program::GLuint, location::GLint, v0::GLuint)::Void),
:(glGetUniformuiv(program::GLuint, location::GLint, params::Ptr{GLuint})::Void),
:(glBindImageTexture(unit::GLuint, texture::GLuint, level::GLint, layered::GLboolean, layer::GLint, access::GLenum, format::GLenum)::Void),
:(glVertexAttribI4iv(index::GLuint, v::Ptr{GLint})::Void),
:(glVertexAttribL4dv(index::GLuint, v::Ptr{GLdouble})::Void),
:(glDrawTransformFeedbackStreamInstanced(mode::GLenum, id::GLuint, stream::GLuint, instancecount::GLsizei)::Void),
:(glColorP4ui(type_::GLenum, color::GLuint)::Void),
:(glViewportIndexedfv(index::GLuint, v::Ptr{GLfloat})::Void),
:(glProgramUniform3fv(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glBindBufferRange(target::GLenum, index::GLuint, buffer::GLuint, offset::GLintptr, size::GLsizeiptr)::Void),
:(glDeleteSamplers(count::GLsizei, samplers::Ptr{GLuint})::Void),
:(glVertexAttribL2d(index::GLuint, x::GLdouble, y::GLdouble)::Void),
:(glUniform2d(location::GLint, x::GLdouble, y::GLdouble)::Void),
:(glGetProgramStageiv(program::GLuint, shadertype::GLenum, pname::GLenum, values::Ptr{GLint})::Void),
:(glGetBufferParameteri64v(target::GLenum, pname::GLenum, params::Ptr{GLint64})::Void),
:(glBindSampler(unit::GLuint, sampler::GLuint)::Void),
:(glColorP4uiv(type_::GLenum, color::Ptr{GLuint})::Void),
:(glVertexAttribIPointer(index::GLuint, size::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glTexCoordP1ui(type_::GLenum, coords::GLuint)::Void),
:(glBindRenderbuffer(target::GLenum, renderbuffer::GLuint)::Void),
:(glColorP3uiv(type_::GLenum, color::Ptr{GLuint})::Void),
:(glProgramUniformMatrix2x4fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glGetProgramPipelineiv(pipeline::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glMultiTexCoordP4uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glTexStorage1D(target::GLenum, levels::GLsizei, internalformat::GLenum, width::GLsizei)::Void),
:(glGetSamplerParameterIuiv(sampler::GLuint, pname::GLenum, params::Ptr{GLuint})::Void),
:(glMultiTexCoordP3uiv(texture::GLenum, type_::GLenum, coords::Ptr{GLuint})::Void),
:(glVertexP3uiv(type_::GLenum, value::Ptr{GLuint})::Void),
:(glVertexP4ui(type_::GLenum, value::GLuint)::Void),
:(glProgramUniform4i(program::GLuint, location::GLint, v0::GLint, v1::GLint, v2::GLint, v3::GLint)::Void),
:(glUniformMatrix3x4dv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLdouble})::Void),
:(glBlendEquationSeparatei(buf::GLuint, modeRGB::GLenum, modeAlpha::GLenum)::Void),
:(glProgramUniform1d(program::GLuint, location::GLint, v0::GLdouble)::Void),
:(glGetFloati_v(target::GLenum, index::GLuint, data::Ptr{GLfloat})::Void),
:(glIsFramebuffer(framebuffer::GLuint)::Bool),
:(glVertexAttribP1uiv(index::GLuint, type_::GLenum, normalized::GLboolean, value::Ptr{GLuint})::Void),
:(glTexImage2DMultisample(target::GLenum, samples::GLsizei, internalformat::GLint, width::GLsizei, height::GLsizei, fixedsamplelocations::GLboolean)::Void),
:(glDepthRangef(n::GLfloat, f::GLfloat)::Void),
:(glProgramUniformMatrix3x2fv(program::GLuint, location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void)]
