#Types, functions and constants, that are available in all OpenGL versions
#The Types are also valid for all extensions (but GLU)
#types
const GL_COMMON_TYPES = [
:(typealias GLhalfNV                                                    Cushort),
:(typealias GLint                                                       Cint),
:(typealias GLdouble                                                    Cdouble),
:(typealias GLuint                                                      Cuint),
:(typealias GLushort                                                    Cushort),
:(typealias GLsync                                                      Ptr{Void}),
:(typealias GLuint64                                                    Culonglong),
:(typealias GLchar                                                      Cchar),
:(typealias GLenum                                                      Cuint),
:(typealias GLsizei                                                     Csize_t),
:(typealias GLintptr                                                    Cptrdiff_t),
:(typealias GLhalfARB                                                   Cushort),
:(typealias GLubyte                                                     Cuchar),
:(typealias GLclampf                                                    Cfloat),
:(typealias GLclampd                                                    Cdouble),
:(typealias GLvoid                                                      Void),
:(typealias GLbyte                                                      Cuchar),
:(typealias GLfloat                                                     Cfloat),
:(typealias GLhalf                                                      Cushort),
:(typealias GLbitfield                                                  Cuint),
:(typealias GLshort                                                     Cshort),
:(typealias GLint64                                                     Clonglong),
:(typealias GLboolean                                                   Cuchar),
:(typealias Pointer                                                     Ptr{Void}),
:(typealias GLsizeiptr                                                  Cint)]
#constants
const GL_COMMON_CONSTANTS = [
:(const ONE_MINUS_DST_COLOR                                             = 0x0307),
:(const POINT_SMOOTH_HINT                                               = 0x0C51),
:(const AUX2                                                            = 0x040B),
:(const BUFFER_ACCESS                                                   = 0x88BB),
:(const FOG_END                                                         = 0x0B64),
:(const ALIASED_POINT_SIZE_RANGE                                        = 0x846D),
:(const VERTEX_ARRAY_SIZE                                               = 0x807A),
:(const FEEDBACK_BUFFER_POINTER                                         = 0x0DF0),
:(const LINES                                                           = 0x0001),
:(const SHADER_TYPE                                                     = 0x8B4F),
:(const C3F_V3F                                                         = 0x2A24),
:(const INDEX_MODE                                                      = 0x0C30),
:(const T                                                               = 0x2001),
:(const TEXTURE_CUBE_MAP_NEGATIVE_X                                     = 0x8516),
:(const COMPRESSED_INTENSITY                                            = 0x84EC),
:(const TEXTURE9                                                        = 0x84C9),
:(const SMOOTH_LINE_WIDTH_GRANULARITY                                   = 0x0B23),
:(const COMPRESSED_RGB                                                  = 0x84ED),
:(const CULL_FACE                                                       = 0x0B44),
:(const FOG_BIT                                                         = 0x00000080),
:(const COMBINE_RGB                                                     = 0x8571),
:(const MAP1_TEXTURE_COORD_3                                            = 0x0D95),
:(const ATTRIB_STACK_DEPTH                                              = 0x0BB0),
:(const TEXTURE_COORD_ARRAY_POINTER                                     = 0x8092),
:(const ZOOM_X                                                          = 0x0D16),
:(const AND_INVERTED                                                    = 0x1504),
:(const POLYGON                                                         = 0x0009),
:(const ORDER                                                           = 0x0A01),
:(const T2F_C3F_V3F                                                     = 0x2A2A),
:(const ALPHA                                                           = 0x1906),
:(const COLOR_MATERIAL                                                  = 0x0B57),
:(const READ_BUFFER                                                     = 0x0C02),
:(const DRAW_BUFFER10                                                   = 0x882F),
:(const DEPTH_BIAS                                                      = 0x0D1F),
:(const FRONT_AND_BACK                                                  = 0x0408),
:(const NOOP                                                            = 0x1505),
:(const INTENSITY4                                                      = 0x804A),
:(const TRANSPOSE_COLOR_MATRIX                                          = 0x84E6),
:(const INDEX_WRITEMASK                                                 = 0x0C21),
:(const MAX_MODELVIEW_STACK_DEPTH                                       = 0x0D36),
:(const PACK_SKIP_PIXELS                                                = 0x0D04),
:(const SHININESS                                                       = 0x1601),
:(const FOG_COORD                                                       = 0x8451),
:(const MAP1_VERTEX_4                                                   = 0x0D98),
:(const ACCUM_CLEAR_VALUE                                               = 0x0B80),
:(const POLYGON_SMOOTH_HINT                                             = 0x0C53),
:(const STENCIL_CLEAR_VALUE                                             = 0x0B91),
:(const PACK_IMAGE_HEIGHT                                               = 0x806C),
:(const FOG_INDEX                                                       = 0x0B61),
:(const SRC_COLOR                                                       = 0x0300),
:(const CLIP_PLANE3                                                     = 0x3003),
:(const SRGB8_ALPHA8                                                    = 0x8C43),
:(const RGB16                                                           = 0x8054),
:(const NAME_STACK_DEPTH                                                = 0x0D70),
:(const DEPTH_CLEAR_VALUE                                               = 0x0B73),
:(const MAX_ELEMENTS_INDICES                                            = 0x80E9),
:(const ADD                                                             = 0x0104),
:(const EDGE_FLAG_ARRAY_BUFFER_BINDING                                  = 0x889B),
:(const CLAMP                                                           = 0x2900),
:(const CLAMP_TO_BORDER                                                 = 0x812D),
:(const NEVER                                                           = 0x0200),
:(const UNSIGNED_INT_2_10_10_10_REV                                     = 0x8368),
:(const RETURN                                                          = 0x0102),
:(const POLYGON_SMOOTH                                                  = 0x0B41),
:(const TEXTURE_COORD_ARRAY_SIZE                                        = 0x8088),
:(const EYE_LINEAR                                                      = 0x2400),
:(const LUMINANCE12_ALPHA4                                              = 0x8046),
:(const COEFF                                                           = 0x0A00),
:(const PACK_SKIP_IMAGES                                                = 0x806B),
:(const AND_REVERSE                                                     = 0x1502),
:(const NOR                                                             = 0x1508),
:(const PROXY_TEXTURE_1D                                                = 0x8063),
:(const TEXTURE_WRAP_T                                                  = 0x2803),
:(const UNSIGNED_INT_8_8_8_8_REV                                        = 0x8367),
:(const POLYGON_OFFSET_LINE                                             = 0x2A02),
:(const FOG_COORD_ARRAY_POINTER                                         = 0x8456),
:(const TEXTURE_BORDER_COLOR                                            = 0x1004),
:(const POSITION                                                        = 0x1203),
:(const MAP1_COLOR_4                                                    = 0x0D90),
:(const TEXTURE_ENV_MODE                                                = 0x2200),
:(const EDGE_FLAG_ARRAY_POINTER                                         = 0x8093),
:(const SAMPLE_BUFFERS                                                  = 0x80A8),
:(const SOURCE0_RGB                                                     = 0x8580),
:(const PERSPECTIVE_CORRECTION_HINT                                     = 0x0C50),
:(const CURRENT_RASTER_COLOR                                            = 0x0B04),
:(const DEPTH_FUNC                                                      = 0x0B74),
:(const FOG_DENSITY                                                     = 0x0B62),
:(const DRAW_BUFFER2                                                    = 0x8827),
:(const COLOR_MATERIAL_PARAMETER                                        = 0x0B56),
:(const SRGB8                                                           = 0x8C41),
:(const COPY                                                            = 0x1503),
:(const TEXTURE_GEN_T                                                   = 0x0C61),
:(const ARRAY_BUFFER_BINDING                                            = 0x8894),
:(const UNSIGNED_SHORT_4_4_4_4                                          = 0x8033),
:(const T4F_C4F_N3F_V4F                                                 = 0x2A2D),
:(const T2F_N3F_V3F                                                     = 0x2A2B),
:(const TEXTURE_MAX_LEVEL                                               = 0x813D),
:(const EVAL_BIT                                                        = 0x00010000),
:(const SAMPLER_2D_SHADOW                                               = 0x8B62),
:(const UNSIGNED_SHORT_5_5_5_1                                          = 0x8034),
:(const SAMPLES                                                         = 0x80A9),
:(const VERTEX_ARRAY_BUFFER_BINDING                                     = 0x8896),
:(const EDGE_FLAG_ARRAY_STRIDE                                          = 0x808C),
:(const AMBIENT_AND_DIFFUSE                                             = 0x1602),
:(const AUTO_NORMAL                                                     = 0x0D80),
:(const FOG_COORD_ARRAY                                                 = 0x8457),
:(const POINTS                                                          = 0x0000),
:(const FLOAT_VEC3                                                      = 0x8B51),
:(const N3F_V3F                                                         = 0x2A25),
:(const TEXTURE22                                                       = 0x84D6),
:(const SMOOTH                                                          = 0x1D01),
:(const INT_VEC3                                                        = 0x8B54),
:(const SAMPLE_COVERAGE_VALUE                                           = 0x80AA),
:(const COLOR_WRITEMASK                                                 = 0x0C23),
:(const MAX_TEXTURE_SIZE                                                = 0x0D33),
:(const BLEND_SRC_RGB                                                   = 0x80C9),
:(const LOGIC_OP_MODE                                                   = 0x0BF0),
:(const EQUIV                                                           = 0x1509),
:(const TEXTURE_BINDING_CUBE_MAP                                        = 0x8514),
:(const LIGHT4                                                          = 0x4004),
:(const STENCIL_BACK_REF                                                = 0x8CA3),
:(const TEXTURE17                                                       = 0x84D1),
:(const INVERT                                                          = 0x150A),
:(const CURRENT_PROGRAM                                                 = 0x8B8D),
:(const MODULATE                                                        = 0x2100),
:(const SPOT_EXPONENT                                                   = 0x1205),
:(const MAX_CUBE_MAP_TEXTURE_SIZE                                       = 0x851C),
:(const TEXTURE_WRAP_R                                                  = 0x8072),
:(const POINT_SPRITE                                                    = 0x8861),
:(const EDGE_FLAG_ARRAY                                                 = 0x8079),
:(const CLIENT_VERTEX_ARRAY_BIT                                         = 0x00000002),
:(const LINEAR                                                          = 0x2601),
:(const PACK_LSB_FIRST                                                  = 0x0D01),
:(const LINE_TOKEN                                                      = 0x0702),
:(const RGBA_MODE                                                       = 0x0C31),
:(const PACK_SKIP_ROWS                                                  = 0x0D03),
:(const ALPHA_BIAS                                                      = 0x0D1D),
:(const BITMAP                                                          = 0x1A00),
:(const DEPTH                                                           = 0x1801),
:(const QUERY_RESULT                                                    = 0x8866),
:(const MAP1_NORMAL                                                     = 0x0D92),
:(const MAX_ATTRIB_STACK_DEPTH                                          = 0x0D35),
:(const LIGHT6                                                          = 0x4006),
:(const UNPACK_SKIP_PIXELS                                              = 0x0CF4),
:(const RENDER_MODE                                                     = 0x0C40),
:(const PIXEL_MAP_R_TO_R                                                = 0x0C76),
:(const DRAW_PIXEL_TOKEN                                                = 0x0705),
:(const UNPACK_LSB_FIRST                                                = 0x0CF1),
:(const COMPILE_AND_EXECUTE                                             = 0x1301),
:(const T4F_V4F                                                         = 0x2A28),
:(const TEXTURE_CUBE_MAP                                                = 0x8513),
:(const TEXTURE_INTERNAL_FORMAT                                         = 0x1003),
:(const CLEAR                                                           = 0x1500),
:(const NORMAL_ARRAY_POINTER                                            = 0x808F),
:(const RGB4                                                            = 0x804F),
:(const T2F_C4UB_V3F                                                    = 0x2A29),
:(const POLYGON_STIPPLE_BIT                                             = 0x00000010),
:(const RGBA2                                                           = 0x8055),
:(const SHADING_LANGUAGE_VERSION                                        = 0x8B8C),
:(const LIGHT_MODEL_AMBIENT                                             = 0x0B53),
:(const PIXEL_MAP_I_TO_G                                                = 0x0C73),
:(const WEIGHT_ARRAY_BUFFER_BINDING                                     = 0x889E),
:(const Q                                                               = 0x2003),
:(const BGRA                                                            = 0x80E1),
:(const LUMINANCE6_ALPHA2                                               = 0x8044),
:(const LIGHT_MODEL_COLOR_CONTROL                                       = 0x81F8),
:(const VIEWPORT_BIT                                                    = 0x00000800),
:(const COMPRESSED_SLUMINANCE                                           = 0x8C4A),
:(const KEEP                                                            = 0x1E00),
:(const MAX_PROJECTION_STACK_DEPTH                                      = 0x0D38),
:(const NORMAL_ARRAY_TYPE                                               = 0x807E),
:(const SAMPLE_COVERAGE_INVERT                                          = 0x80AB),
:(const SRC2_ALPHA                                                      = 0x858A),
:(const DITHER                                                          = 0x0BD0),
:(const FRAGMENT_SHADER                                                 = 0x8B30),
:(const SLUMINANCE8                                                     = 0x8C47),
:(const TEXTURE_PRIORITY                                                = 0x8066),
:(const LIGHT3                                                          = 0x4003),
:(const TEXTURE_MIN_LOD                                                 = 0x813A),
:(const GENERATE_MIPMAP_HINT                                            = 0x8192),
:(const VERTEX_ATTRIB_ARRAY_BUFFER_BINDING                              = 0x889F),
:(const PROXY_TEXTURE_2D                                                = 0x8064),
:(const STENCIL_BACK_VALUE_MASK                                         = 0x8CA4),
:(const LINE_SMOOTH_HINT                                                = 0x0C52),
:(const LINEAR_MIPMAP_NEAREST                                           = 0x2701),
:(const NEAREST_MIPMAP_NEAREST                                          = 0x2700),
:(const MAX_LIGHTS                                                      = 0x0D31),
:(const SAMPLER_1D_SHADOW                                               = 0x8B61),
:(const INDEX_ARRAY                                                     = 0x8077),
:(const OPERAND1_ALPHA                                                  = 0x8599),
:(const NORMAL_MAP                                                      = 0x8511),
:(const DEPTH_SCALE                                                     = 0x0D1E),
:(const ACTIVE_UNIFORM_MAX_LENGTH                                       = 0x8B87),
:(const SECONDARY_COLOR_ARRAY_BUFFER_BINDING                            = 0x889C),
:(const BOOL_VEC2                                                       = 0x8B57),
:(const STREAM_READ                                                     = 0x88E1),
:(const ARRAY_BUFFER                                                    = 0x8892),
:(const FLOAT_MAT3x2                                                    = 0x8B67),
:(const SECONDARY_COLOR_ARRAY_SIZE                                      = 0x845A),
:(const TEXTURE_LUMINANCE_SIZE                                          = 0x8060),
:(const TEXTURE_COMPRESSED_IMAGE_SIZE                                   = 0x86A0),
:(const TEXTURE_MAG_FILTER                                              = 0x2800),
:(const LUMINANCE8                                                      = 0x8040),
:(const SCISSOR_BIT                                                     = 0x00080000),
:(const X2_BYTES                                                        = 0x1407),
:(const X3D_COLOR_TEXTURE                                               = 0x0603),
:(const PROJECTION_STACK_DEPTH                                          = 0x0BA4),
:(const DYNAMIC_READ                                                    = 0x88E9),
:(const POINT_TOKEN                                                     = 0x0701),
:(const OPERAND0_ALPHA                                                  = 0x8598),
:(const MAX_VERTEX_ATTRIBS                                              = 0x8869),
:(const REPEAT                                                          = 0x2901),
:(const POINT                                                           = 0x1B00),
:(const CLIP_PLANE2                                                     = 0x3002),
:(const DEPTH_BITS                                                      = 0x0D56),
:(const BYTE                                                            = 0x1400),
:(const VERTEX_ARRAY_STRIDE                                             = 0x807C),
:(const CURRENT_RASTER_POSITION_VALID                                   = 0x0B08),
:(const TEXTURE_BINDING_1D                                              = 0x8068),
:(const DRAW_BUFFER12                                                   = 0x8831),
:(const FRAGMENT_DEPTH                                                  = 0x8452),
:(const BLEND_EQUATION_ALPHA                                            = 0x883D),
:(const MAP2_COLOR_4                                                    = 0x0DB0),
:(const LUMINANCE                                                       = 0x1909),
:(const POLYGON_OFFSET_FACTOR                                           = 0x8038),
:(const SRGB                                                            = 0x8C40),
:(const EQUAL                                                           = 0x0202),
:(const SEPARATE_SPECULAR_COLOR                                         = 0x81FA),
:(const PIXEL_UNPACK_BUFFER_BINDING                                     = 0x88EF),
:(const LINE_LOOP                                                       = 0x0002),
:(const LOWER_LEFT                                                      = 0x8CA1),
:(const EYE_PLANE                                                       = 0x2502),
:(const POINT_SIZE_MIN                                                  = 0x8126),
:(const TEXTURE_ENV_COLOR                                               = 0x2201),
:(const SOURCE0_ALPHA                                                   = 0x8588),
:(const TEXTURE_DEPTH_SIZE                                              = 0x884A),
:(const BOOL_VEC4                                                       = 0x8B59),
:(const VERTEX_SHADER                                                   = 0x8B31),
:(const C4UB_V2F                                                        = 0x2A22),
:(const FLOAT_MAT4                                                      = 0x8B5C),
:(const SOURCE2_RGB                                                     = 0x8582),
:(const LIGHT2                                                          = 0x4002),
:(const SOURCE1_ALPHA                                                   = 0x8589),
:(const FOG_COORDINATE                                                  = 0x8451),
:(const TEXTURE1                                                        = 0x84C1),
:(const DEPTH_TEST                                                      = 0x0B71),
:(const PIXEL_MAP_I_TO_I_SIZE                                           = 0x0CB0),
:(const DRAW_BUFFER15                                                   = 0x8834),
:(const RENDER                                                          = 0x1C00),
:(const DOMAIN                                                          = 0x0A02),
:(const COPY_PIXEL_TOKEN                                                = 0x0706),
:(const BUFFER_MAPPED                                                   = 0x88BC),
:(const DRAW_BUFFER5                                                    = 0x882A),
:(const MAX_LIST_NESTING                                                = 0x0B31),
:(const RED_BITS                                                        = 0x0D52),
:(const SOURCE1_RGB                                                     = 0x8581),
:(const OBJECT_PLANE                                                    = 0x2501),
:(const FLOAT_MAT4x3                                                    = 0x8B6A),
:(const SECONDARY_COLOR_ARRAY_POINTER                                   = 0x845D),
:(const PIXEL_MAP_I_TO_I                                                = 0x0C70),
:(const TEXTURE_GEN_Q                                                   = 0x0C63),
:(const FRAGMENT_SHADER_DERIVATIVE_HINT                                 = 0x8B8B),
:(const TEXTURE_BIT                                                     = 0x00040000),
:(const ACCUM_BLUE_BITS                                                 = 0x0D5A),
:(const TEXTURE_CUBE_MAP_POSITIVE_Z                                     = 0x8519),
:(const ACTIVE_ATTRIBUTES                                               = 0x8B89),
:(const FEEDBACK_BUFFER_TYPE                                            = 0x0DF2),
:(const PIXEL_MAP_I_TO_G_SIZE                                           = 0x0CB3),
:(const LUMINANCE4_ALPHA4                                               = 0x8043),
:(const PIXEL_MAP_A_TO_A_SIZE                                           = 0x0CB9),
:(const C4UB_V3F                                                        = 0x2A23),
:(const CURRENT_FOG_COORDINATE                                          = 0x8453),
:(const COMPRESSED_SRGB                                                 = 0x8C48),
:(const UNSIGNED_SHORT_4_4_4_4_REV                                      = 0x8365),
:(const SHORT                                                           = 0x1402),
:(const ZERO                                                            = 0),
:(const MAP2_VERTEX_4                                                   = 0x0DB8),
:(const FRONT                                                           = 0x0404),
:(const SAMPLER_CUBE                                                    = 0x8B60),
:(const INVALID_OPERATION                                               = 0x0502),
:(const R                                                               = 0x2002),
:(const RGB_SCALE                                                       = 0x8573),
:(const PROXY_TEXTURE_3D                                                = 0x8070),
:(const FOG_COORD_ARRAY_TYPE                                            = 0x8454),
:(const FOG_COORDINATE_SOURCE                                           = 0x8450),
:(const INDEX_ARRAY_BUFFER_BINDING                                      = 0x8899),
:(const CLIENT_PIXEL_STORE_BIT                                          = 0x00000001),
:(const POLYGON_STIPPLE                                                 = 0x0B42),
:(const TEXTURE_COMPARE_MODE                                            = 0x884C),
:(const ELEMENT_ARRAY_BUFFER_BINDING                                    = 0x8895),
:(const DOT3_RGBA                                                       = 0x86AF),
:(const OPERAND2_RGB                                                    = 0x8592),
:(const TEXTURE_FILTER_CONTROL                                          = 0x8500),
:(const ALPHA4                                                          = 0x803B),
:(const LEFT                                                            = 0x0406),
:(const T2F_C4F_N3F_V3F                                                 = 0x2A2C),
:(const REFLECTION_MAP                                                  = 0x8512),
:(const COLOR_INDEXES                                                   = 0x1603),
:(const SELECTION_BUFFER_SIZE                                           = 0x0DF4),
:(const INVALID_VALUE                                                   = 0x0501),
:(const MAP_STENCIL                                                     = 0x0D11),
:(const DEPTH_COMPONENT                                                 = 0x1902),
:(const CLIP_PLANE4                                                     = 0x3004),
:(const COLOR_MATERIAL_FACE                                             = 0x0B55),
:(const COPY_INVERTED                                                   = 0x150C),
:(const TEXTURE3                                                        = 0x84C3),
:(const TEXTURE10                                                       = 0x84CA),
:(const TRANSFORM_BIT                                                   = 0x00001000),
:(const STENCIL_BACK_FAIL                                               = 0x8801),
:(const GENERATE_MIPMAP                                                 = 0x8191),
:(const ELEMENT_ARRAY_BUFFER                                            = 0x8893),
:(const TEXTURE_COORD_ARRAY                                             = 0x8078),
:(const TEXTURE27                                                       = 0x84DB),
:(const BLEND_DST_ALPHA                                                 = 0x80CA),
:(const BACK_RIGHT                                                      = 0x0403),
:(const BLUE_BITS                                                       = 0x0D54),
:(const AMBIENT                                                         = 0x1200),
:(const ONE_MINUS_DST_ALPHA                                             = 0x0305),
:(const VERTEX_ATTRIB_ARRAY_POINTER                                     = 0x8645),
:(const MAX_TEXTURE_STACK_DEPTH                                         = 0x0D39),
:(const TEXTURE_BINDING_3D                                              = 0x806A),
:(const TEXTURE0                                                        = 0x84C0),
:(const TEXTURE_CUBE_MAP_POSITIVE_Y                                     = 0x8517),
:(const DEPTH_COMPONENT24                                               = 0x81A6),
:(const OPERAND0_RGB                                                    = 0x8590),
:(const MAP1_GRID_SEGMENTS                                              = 0x0DD1),
:(const COLOR_LOGIC_OP                                                  = 0x0BF2),
:(const DST_COLOR                                                       = 0x0306),
:(const MAX_PIXEL_MAP_TABLE                                             = 0x0D34),
:(const STENCIL_VALUE_MASK                                              = 0x0B93),
:(const CURRENT_RASTER_TEXTURE_COORDS                                   = 0x0B06),
:(const INVALID_ENUM                                                    = 0x0500),
:(const SAMPLES_PASSED                                                  = 0x8914),
:(const MAX_COMBINED_TEXTURE_IMAGE_UNITS                                = 0x8B4D),
:(const BACK                                                            = 0x0405),
:(const RGB                                                             = 0x1907),
:(const FOG_COORD_ARRAY_BUFFER_BINDING                                  = 0x889D),
:(const LEQUAL                                                          = 0x0203),
:(const UNPACK_IMAGE_HEIGHT                                             = 0x806E),
:(const CW                                                              = 0x0900),
:(const ALPHA_TEST_REF                                                  = 0x0BC2),
:(const UNSIGNED_INT_8_8_8_8                                            = 0x8035),
:(const ALWAYS                                                          = 0x0207),
:(const FOG                                                             = 0x0B60),
:(const DEPTH_TEXTURE_MODE                                              = 0x884B),
:(const BUFFER_USAGE                                                    = 0x8765),
:(const COMPRESSED_TEXTURE_FORMATS                                      = 0x86A3),
:(const NORMAL_ARRAY_BUFFER_BINDING                                     = 0x8897),
:(const CURRENT_RASTER_POSITION                                         = 0x0B07),
:(const BLEND_SRC                                                       = 0x0BE1),
:(const PACK_ALIGNMENT                                                  = 0x0D05),
:(const CURRENT_COLOR                                                   = 0x0B00),
:(const STREAM_COPY                                                     = 0x88E2),
:(const CURRENT_FOG_COORD                                               = 0x8453),
:(const TEXTURE_STACK_DEPTH                                             = 0x0BA5),
:(const MAX_DRAW_BUFFERS                                                = 0x8824),
:(const SRGB_ALPHA                                                      = 0x8C42),
:(const POINT_SIZE_GRANULARITY                                          = 0x0B13),
:(const CURRENT_QUERY                                                   = 0x8865),
:(const NOTEQUAL                                                        = 0x0205),
:(const SCISSOR_TEST                                                    = 0x0C11),
:(const LUMINANCE12_ALPHA12                                             = 0x8047),
:(const DEPTH_COMPONENT16                                               = 0x81A5),
:(const DRAW_BUFFER1                                                    = 0x8826),
:(const INFO_LOG_LENGTH                                                 = 0x8B84),
:(const RGBA12                                                          = 0x805A),
:(const UNPACK_SWAP_BYTES                                               = 0x0CF0),
:(const LINE_STRIP                                                      = 0x0003),
:(const MAP2_VERTEX_3                                                   = 0x0DB7),
:(const UNPACK_ALIGNMENT                                                = 0x0CF5),
:(const SPECULAR                                                        = 0x1202),
:(const TEXTURE_ALPHA_SIZE                                              = 0x805F),
:(const LOAD                                                            = 0x0101),
:(const SUBPIXEL_BITS                                                   = 0x0D50),
:(const FLOAT                                                           = 0x1406),
:(const ALPHA_TEST_FUNC                                                 = 0x0BC1),
:(const V2F                                                             = 0x2A20),
:(const MAP2_TEXTURE_COORD_1                                            = 0x0DB3),
:(const CURRENT_SECONDARY_COLOR                                         = 0x8459),
:(const CULL_FACE_MODE                                                  = 0x0B45),
:(const RGB5_A1                                                         = 0x8057),
:(const LUMINANCE16_ALPHA16                                             = 0x8048),
:(const ACCUM_RED_BITS                                                  = 0x0D58),
:(const STENCIL_BACK_PASS_DEPTH_PASS                                    = 0x8803),
:(const PIXEL_MAP_G_TO_G                                                = 0x0C77),
:(const TEXTURE31                                                       = 0x84DF),
:(const TRIANGLES                                                       = 0x0004),
:(const VIEWPORT                                                        = 0x0BA2),
:(const CURRENT_INDEX                                                   = 0x0B01),
:(const INTENSITY12                                                     = 0x804C),
:(const TEXTURE_MIN_FILTER                                              = 0x2801),
:(const TEXTURE8                                                        = 0x84C8),
:(const ONE_MINUS_SRC_COLOR                                             = 0x0301),
:(const SPOT_DIRECTION                                                  = 0x1204),
:(const OR                                                              = 0x1507),
:(const BLUE                                                            = 0x1905),
:(const CLIP_PLANE5                                                     = 0x3005),
:(const RGBA                                                            = 0x1908),
:(const STACK_OVERFLOW                                                  = 0x0503),
:(const SECONDARY_COLOR_ARRAY                                           = 0x845E),
:(const ALIASED_LINE_WIDTH_RANGE                                        = 0x846E),
:(const MAP_COLOR                                                       = 0x0D10),
:(const ALPHA_SCALE                                                     = 0x0D1C),
:(const EXP2                                                            = 0x0801),
:(const CLIP_PLANE1                                                     = 0x3001),
:(const DRAW_BUFFER7                                                    = 0x882C),
:(const COMPRESSED_ALPHA                                                = 0x84E9),
:(const CLAMP_TO_EDGE                                                   = 0x812F),
:(const DRAW_BUFFER                                                     = 0x0C01),
:(const STENCIL_PASS_DEPTH_PASS                                         = 0x0B96),
:(const NICEST                                                          = 0x1102),
:(const READ_ONLY                                                       = 0x88B8),
:(const TEXTURE_COMPRESSION_HINT                                        = 0x84EF),
:(const FLOAT_MAT3                                                      = 0x8B5B),
:(const LINE_STIPPLE                                                    = 0x0B24),
:(const RED                                                             = 0x1903),
:(const UNSIGNED_SHORT_5_6_5                                            = 0x8363),
:(const TEXTURE13                                                       = 0x84CD),
:(const COMPRESSED_SLUMINANCE_ALPHA                                     = 0x8C4B),
:(const TEXTURE26                                                       = 0x84DA),
:(const MAP2_NORMAL                                                     = 0x0DB2),
:(const ACTIVE_TEXTURE                                                  = 0x84E0),
:(const ALPHA12                                                         = 0x803D),
:(const LINE_WIDTH_RANGE                                                = 0x0B22),
:(const TEXTURE_ENV                                                     = 0x2300),
:(const TEXTURE_GEN_R                                                   = 0x0C62),
:(const TEXTURE_INTENSITY_SIZE                                          = 0x8061),
:(const BLEND_SRC_ALPHA                                                 = 0x80CB),
:(const DRAW_BUFFER4                                                    = 0x8829),
:(const TEXTURE19                                                       = 0x84D3),
:(const DEPTH_WRITEMASK                                                 = 0x0B72),
:(const MODELVIEW_STACK_DEPTH                                           = 0x0BA3),
:(const FLOAT_VEC2                                                      = 0x8B50),
:(const TEXTURE11                                                       = 0x84CB),
:(const CONSTANT_ATTENUATION                                            = 0x1207),
:(const TEXTURE_COORD_ARRAY_BUFFER_BINDING                              = 0x889A),
:(const TEXTURE_CUBE_MAP_POSITIVE_X                                     = 0x8515),
:(const BOOL_VEC3                                                       = 0x8B58),
:(const PIXEL_MAP_S_TO_S_SIZE                                           = 0x0CB1),
:(const XOR                                                             = 0x1506),
:(const TEXTURE_HEIGHT                                                  = 0x1001),
:(const FALSE                                                           = 0),
:(const NORMAL_ARRAY                                                    = 0x8075),
:(const STENCIL_FUNC                                                    = 0x0B92),
:(const INDEX_ARRAY_STRIDE                                              = 0x8086),
:(const PIXEL_MAP_I_TO_A_SIZE                                           = 0x0CB5),
:(const UPPER_LEFT                                                      = 0x8CA2),
:(const FRONT_FACE                                                      = 0x0B46),
:(const X4_BYTES                                                        = 0x1409),
:(const TEXTURE16                                                       = 0x84D0),
:(const DRAW_BUFFER11                                                   = 0x8830),
:(const QUADRATIC_ATTENUATION                                           = 0x1209),
:(const PIXEL_MAP_B_TO_B_SIZE                                           = 0x0CB8),
:(const SLUMINANCE                                                      = 0x8C46),
:(const STATIC_COPY                                                     = 0x88E6),
:(const SMOOTH_LINE_WIDTH_RANGE                                         = 0x0B22),
:(const RGBA4                                                           = 0x8056),
:(const SPOT_CUTOFF                                                     = 0x1206),
:(const DYNAMIC_COPY                                                    = 0x88EA),
:(const COORD_REPLACE                                                   = 0x8862),
:(const AND                                                             = 0x1501),
:(const LINE                                                            = 0x1B01),
:(const EXTENSIONS                                                      = 0x1F03),
:(const ONE                                                             = 1),
:(const MAX_VARYING_FLOATS                                              = 0x8B4B),
:(const TEXTURE7                                                        = 0x84C7),
:(const EXP                                                             = 0x0800),
:(const PIXEL_MAP_G_TO_G_SIZE                                           = 0x0CB7),
:(const POINT_SIZE_RANGE                                                = 0x0B12),
:(const CURRENT_RASTER_DISTANCE                                         = 0x0B09),
:(const TEXTURE_3D                                                      = 0x806F),
:(const TEXTURE_COMPARE_FUNC                                            = 0x884D),
:(const TEXTURE30                                                       = 0x84DE),
:(const COMPILE                                                         = 0x1300),
:(const CLIENT_ACTIVE_TEXTURE                                           = 0x84E1),
:(const COMPRESSED_LUMINANCE_ALPHA                                      = 0x84EB),
:(const PIXEL_UNPACK_BUFFER                                             = 0x88EC),
:(const X3D                                                             = 0x0601),
:(const FOG_COORDINATE_ARRAY_BUFFER_BINDING                             = 0x889D),
:(const POLYGON_OFFSET_FILL                                             = 0x8037),
:(const AUX_BUFFERS                                                     = 0x0C00),
:(const AUX3                                                            = 0x040C),
:(const COLOR_ARRAY_TYPE                                                = 0x8082),
:(const LIGHT1                                                          = 0x4001),
:(const POLYGON_MODE                                                    = 0x0B40),
:(const CURRENT_VERTEX_ATTRIB                                           = 0x8626),
:(const SHADER_SOURCE_LENGTH                                            = 0x8B88),
:(const INTERPOLATE                                                     = 0x8575),
:(const TEXTURE5                                                        = 0x84C5),
:(const QUAD_STRIP                                                      = 0x0008),
:(const TEXTURE_2D                                                      = 0x0DE1),
:(const INT_VEC2                                                        = 0x8B53),
:(const MAX_TEXTURE_IMAGE_UNITS                                         = 0x8872),
:(const INCR                                                            = 0x1E02),
:(const TEXTURE_WRAP_S                                                  = 0x2802),
:(const INT_VEC4                                                        = 0x8B55),
:(const INDEX_ARRAY_POINTER                                             = 0x8091),
:(const ADD_SIGNED                                                      = 0x8574),
:(const LINE_BIT                                                        = 0x00000004),
:(const RGBA16                                                          = 0x805B),
:(const DEPTH_RANGE                                                     = 0x0B70),
:(const LUMINANCE4                                                      = 0x803F),
:(const LUMINANCE8_ALPHA8                                               = 0x8045),
:(const INTENSITY16                                                     = 0x804D),
:(const ACCUM_ALPHA_BITS                                                = 0x0D5B),
:(const SAMPLER_1D                                                      = 0x8B5D),
:(const MAP1_TEXTURE_COORD_2                                            = 0x0D94),
:(const TEXTURE                                                         = 0x1702),
:(const CURRENT_TEXTURE_COORDS                                          = 0x0B03),
:(const COLOR_BUFFER_BIT                                                = 0x00004000),
:(const SAMPLE_COVERAGE                                                 = 0x80A0),
:(const PACK_SWAP_BYTES                                                 = 0x0D00),
:(const INT                                                             = 0x1404),
:(const HINT_BIT                                                        = 0x00008000),
:(const CURRENT_RASTER_INDEX                                            = 0x0B05),
:(const TEXTURE_COORD_ARRAY_TYPE                                        = 0x8089),
:(const MAX_CLIP_PLANES                                                 = 0x0D32),
:(const MAP1_VERTEX_3                                                   = 0x0D97),
:(const PREVIOUS                                                        = 0x8578),
:(const STENCIL_WRITEMASK                                               = 0x0B98),
:(const MAP2_GRID_SEGMENTS                                              = 0x0DD3),
:(const COLOR_ARRAY                                                     = 0x8076),
:(const ACCUM_GREEN_BITS                                                = 0x0D59),
:(const DECR                                                            = 0x1E03),
:(const LINEAR_MIPMAP_LINEAR                                            = 0x2703),
:(const MODELVIEW                                                       = 0x1700),
:(const DRAW_BUFFER9                                                    = 0x882E),
:(const GEQUAL                                                          = 0x0206),
:(const VERTEX_ATTRIB_ARRAY_ENABLED                                     = 0x8622),
:(const PIXEL_MAP_A_TO_A                                                = 0x0C79),
:(const ACTIVE_UNIFORMS                                                 = 0x8B86),
:(const COLOR_SUM                                                       = 0x8458),
:(const FOG_COLOR                                                       = 0x0B66),
:(const MAX_3D_TEXTURE_SIZE                                             = 0x8073),
:(const DRAW_BUFFER14                                                   = 0x8833),
:(const TEXTURE_MATRIX                                                  = 0x0BA8),
:(const MODELVIEW_MATRIX                                                = 0x0BA6),
:(const SOURCE2_ALPHA                                                   = 0x858A),
:(const SCISSOR_BOX                                                     = 0x0C10),
:(const SAMPLE_ALPHA_TO_COVERAGE                                        = 0x809E),
:(const SELECT                                                          = 0x1C02),
:(const PACK_ROW_LENGTH                                                 = 0x0D02),
:(const WRITE_ONLY                                                      = 0x88B9),
:(const STENCIL_TEST                                                    = 0x0B90),
:(const PIXEL_MAP_I_TO_R                                                = 0x0C72),
:(const SRC1_RGB                                                        = 0x8581),
:(const CURRENT_BIT                                                     = 0x00000001),
:(const NO_ERROR                                                        = 0),
:(const PRIMARY_COLOR                                                   = 0x8577),
:(const VERTEX_ATTRIB_ARRAY_TYPE                                        = 0x8625),
:(const GREEN_SCALE                                                     = 0x0D18),
:(const FRONT_RIGHT                                                     = 0x0401),
:(const UNSIGNED_SHORT_1_5_5_5_REV                                      = 0x8366),
:(const DECR_WRAP                                                       = 0x8508),
:(const FOG_START                                                       = 0x0B63),
:(const TEXTURE_CUBE_MAP_NEGATIVE_Z                                     = 0x851A),
:(const STENCIL_BACK_FUNC                                               = 0x8800),
:(const OPERAND2_ALPHA                                                  = 0x859A),
:(const TEXTURE2                                                        = 0x84C2),
:(const QUERY_COUNTER_BITS                                              = 0x8864),
:(const NEAREST_MIPMAP_LINEAR                                           = 0x2702),
:(const NUM_COMPRESSED_TEXTURE_FORMATS                                  = 0x86A2),
:(const CLIENT_ATTRIB_STACK_DEPTH                                       = 0x0BB1),
:(const PASS_THROUGH_TOKEN                                              = 0x0700),
:(const MAX_EVAL_ORDER                                                  = 0x0D30),
:(const LINE_STIPPLE_REPEAT                                             = 0x0B26),
:(const PIXEL_MAP_I_TO_R_SIZE                                           = 0x0CB2),
:(const CURRENT_NORMAL                                                  = 0x0B02),
:(const FRONT_LEFT                                                      = 0x0400),
:(const MIRRORED_REPEAT                                                 = 0x8370),
:(const DRAW_BUFFER3                                                    = 0x8828),
:(const UNSIGNED_BYTE_2_3_3_REV                                         = 0x8362),
:(const COLOR_CLEAR_VALUE                                               = 0x0C22),
:(const RGB10_A2                                                        = 0x8059),
:(const MAP1_TEXTURE_COORD_4                                            = 0x0D96),
:(const DONT_CARE                                                       = 0x1100),
:(const COLOR_ARRAY_STRIDE                                              = 0x8083),
:(const TEXTURE_BORDER                                                  = 0x1005),
:(const STEREO                                                          = 0x0C33),
:(const ATTACHED_SHADERS                                                = 0x8B85),
:(const TEXTURE18                                                       = 0x84D2),
:(const FOG_COORD_ARRAY_STRIDE                                          = 0x8455),
:(const VERTEX_ARRAY_TYPE                                               = 0x807B),
:(const RGB12                                                           = 0x8053),
:(const LINE_RESET_TOKEN                                                = 0x0707),
:(const LESS                                                            = 0x0201),
:(const TEXTURE_GREEN_SIZE                                              = 0x805D),
:(const COLOR_ARRAY_POINTER                                             = 0x8090),
:(const STENCIL_REF                                                     = 0x0B97),
:(const TEXTURE_COMPONENTS                                              = 0x1003),
:(const INDEX_LOGIC_OP                                                  = 0x0BF1),
:(const TEXTURE6                                                        = 0x84C6),
:(const FOG_COORDINATE_ARRAY_STRIDE                                     = 0x8455),
:(const SLUMINANCE8_ALPHA8                                              = 0x8C45),
:(const TEXTURE_COORD_ARRAY_STRIDE                                      = 0x808A),
:(const X3_BYTES                                                        = 0x1408),
:(const X2D                                                             = 0x0600),
:(const MAP1_GRID_DOMAIN                                                = 0x0DD0),
:(const TEXTURE_BLUE_SIZE                                               = 0x805E),
:(const TEXTURE23                                                       = 0x84D7),
:(const MAP2_TEXTURE_COORD_4                                            = 0x0DB6),
:(const FLOAT_MAT3x4                                                    = 0x8B68),
:(const QUADS                                                           = 0x0007),
:(const VERSION                                                         = 0x1F02),
:(const DST_ALPHA                                                       = 0x0304),
:(const INCR_WRAP                                                       = 0x8507),
:(const SPHERE_MAP                                                      = 0x2402),
:(const STENCIL_BITS                                                    = 0x0D57),
:(const VERTEX_ARRAY                                                    = 0x8074),
:(const TRANSPOSE_PROJECTION_MATRIX                                     = 0x84E4),
:(const FLOAT_MAT4x2                                                    = 0x8B69),
:(const SMOOTH_POINT_SIZE_GRANULARITY                                   = 0x0B13),
:(const COMBINE                                                         = 0x8570),
:(const LINE_WIDTH                                                      = 0x0B21),
:(const RGB10                                                           = 0x8052),
:(const SRC1_ALPHA                                                      = 0x8589),
:(const TEXTURE_CUBE_MAP_NEGATIVE_Y                                     = 0x8518),
:(const BLUE_BIAS                                                       = 0x0D1B),
:(const STENCIL                                                         = 0x1802),
:(const TEXTURE_COMPRESSED                                              = 0x86A1),
:(const SMOOTH_POINT_SIZE_RANGE                                         = 0x0B12),
:(const ENABLE_BIT                                                      = 0x00002000),
:(const MULTISAMPLE                                                     = 0x809D),
:(const SLUMINANCE_ALPHA                                                = 0x8C44),
:(const POLYGON_TOKEN                                                   = 0x0703),
:(const INDEX_ARRAY_TYPE                                                = 0x8085),
:(const DRAW_BUFFER13                                                   = 0x8832),
:(const UNSIGNED_BYTE                                                   = 0x1401),
:(const SAMPLE_ALPHA_TO_ONE                                             = 0x809F),
:(const TEXTURE14                                                       = 0x84CE),
:(const CLIP_PLANE0                                                     = 0x3000),
:(const VERTEX_ATTRIB_ARRAY_STRIDE                                      = 0x8624),
:(const CLIENT_ALL_ATTRIB_BITS                                          = 0xFFFFFFFF),
:(const ALPHA8                                                          = 0x803C),
:(const TEXTURE_LOD_BIAS                                                = 0x8501),
:(const RED_BIAS                                                        = 0x0D15),
:(const TEXTURE_BINDING_2D                                              = 0x8069),
:(const EMISSION                                                        = 0x1600),
:(const UNSIGNED_INT                                                    = 0x1405),
:(const RENDERER                                                        = 0x1F01),
:(const TEXTURE_RESIDENT                                                = 0x8067),
:(const DEPTH_COMPONENT32                                               = 0x81A7),
:(const MAP1_INDEX                                                      = 0x0D91),
:(const RGBA8                                                           = 0x8058),
:(const UNPACK_ROW_LENGTH                                               = 0x0CF2),
:(const LIGHT7                                                          = 0x4007),
:(const PIXEL_MODE_BIT                                                  = 0x00000020),
:(const MAX_NAME_STACK_DEPTH                                            = 0x0D37),
:(const DYNAMIC_DRAW                                                    = 0x88E8),
:(const RIGHT                                                           = 0x0407),
:(const ALL_ATTRIB_BITS                                                 = 0xFFFFFFFF),
:(const NEAREST                                                         = 0x2600),
:(const SHADE_MODEL                                                     = 0x0B54),
:(const VERTEX_ATTRIB_ARRAY_NORMALIZED                                  = 0x886A),
:(const PROJECTION                                                      = 0x1701),
:(const POINT_FADE_THRESHOLD_SIZE                                       = 0x8128),
:(const SRC0_RGB                                                        = 0x8580),
:(const TEXTURE_BASE_LEVEL                                              = 0x813C),
:(const SRC_ALPHA_SATURATE                                              = 0x0308),
:(const PIXEL_MAP_B_TO_B                                                = 0x0C78),
:(const BGR                                                             = 0x80E0),
:(const DOUBLEBUFFER                                                    = 0x0C32),
:(const MULT                                                            = 0x0103),
:(const UNSIGNED_SHORT                                                  = 0x1403),
:(const MAX_TEXTURE_UNITS                                               = 0x84E2),
:(const ACCUM                                                           = 0x0100),
:(const MULTISAMPLE_BIT                                                 = 0x20000000),
:(const TEXTURE_RED_SIZE                                                = 0x805C),
:(const ACTIVE_ATTRIBUTE_MAX_LENGTH                                     = 0x8B8A),
:(const DELETE_STATUS                                                   = 0x8B80),
:(const PIXEL_PACK_BUFFER_BINDING                                       = 0x88ED),
:(const FOG_COORD_SRC                                                   = 0x8450),
:(const STENCIL_BACK_WRITEMASK                                          = 0x8CA5),
:(const ALPHA_TEST                                                      = 0x0BC0),
:(const READ_WRITE                                                      = 0x88BA),
:(const SRC0_ALPHA                                                      = 0x8588),
:(const FASTEST                                                         = 0x1101),
:(const NORMAL_ARRAY_STRIDE                                             = 0x807F),
:(const SELECTION_BUFFER_POINTER                                        = 0x0DF3),
:(const FEEDBACK_BUFFER_SIZE                                            = 0x0DF1),
:(const MAX_VERTEX_TEXTURE_IMAGE_UNITS                                  = 0x8B4C),
:(const GREEN_BIAS                                                      = 0x0D19),
:(const STENCIL_FAIL                                                    = 0x0B94),
:(const POLYGON_BIT                                                     = 0x00000008),
:(const R3_G3_B2                                                        = 0x2A10),
:(const LIGHTING                                                        = 0x0B50),
:(const T2F_V3F                                                         = 0x2A27),
:(const CCW                                                             = 0x0901),
:(const OBJECT_LINEAR                                                   = 0x2401),
:(const MAX_FRAGMENT_UNIFORM_COMPONENTS                                 = 0x8B49),
:(const BUFFER_SIZE                                                     = 0x8764),
:(const RED_SCALE                                                       = 0x0D14),
:(const FOG_HINT                                                        = 0x0C54),
:(const PIXEL_MAP_R_TO_R_SIZE                                           = 0x0CB6),
:(const OUT_OF_MEMORY                                                   = 0x0505),
:(const TEXTURE20                                                       = 0x84D4),
:(const RGB5                                                            = 0x8050),
:(const AUX0                                                            = 0x0409),
:(const COLOR                                                           = 0x1800),
:(const INDEX_OFFSET                                                    = 0x0D13),
:(const REPLACE                                                         = 0x1E01),
:(const MAP2_TEXTURE_COORD_2                                            = 0x0DB4),
:(const OR_REVERSE                                                      = 0x150B),
:(const DIFFUSE                                                         = 0x1201),
:(const STREAM_DRAW                                                     = 0x88E0),
:(const BLUE_SCALE                                                      = 0x0D1A),
:(const SAMPLER_2D                                                      = 0x8B5E),
:(const EDGE_FLAG                                                       = 0x0B43),
:(const TEXTURE24                                                       = 0x84D8),
:(const MAP1_TEXTURE_COORD_1                                            = 0x0D93),
:(const NORMALIZE                                                       = 0x0BA1),
:(const COLOR_ARRAY_BUFFER_BINDING                                      = 0x8898),
:(const ACCUM_BUFFER_BIT                                                = 0x00000200),
:(const UNSIGNED_INT_10_10_10_2                                         = 0x8036),
:(const STENCIL_INDEX                                                   = 0x1901),
:(const DOT3_RGB                                                        = 0x86AE),
:(const LIST_MODE                                                       = 0x0B30),
:(const AUX1                                                            = 0x040A),
:(const FOG_MODE                                                        = 0x0B65),
:(const TEXTURE_WIDTH                                                   = 0x1000),
:(const NAND                                                            = 0x150E),
:(const PIXEL_MAP_S_TO_S                                                = 0x0C71),
:(const V3F                                                             = 0x2A21),
:(const COMPRESSED_LUMINANCE                                            = 0x84EA),
:(const POINT_SMOOTH                                                    = 0x0B10),
:(const SINGLE_COLOR                                                    = 0x81F9),
:(const INTENSITY                                                       = 0x8049),
:(const S                                                               = 0x2000),
:(const PIXEL_MAP_I_TO_B                                                = 0x0C74),
:(const TEXTURE12                                                       = 0x84CC),
:(const POINT_SPRITE_COORD_ORIGIN                                       = 0x8CA0),
:(const STACK_UNDERFLOW                                                 = 0x0504),
:(const LIST_BIT                                                        = 0x00020000),
:(const SRC_ALPHA                                                       = 0x0302),
:(const CONSTANT                                                        = 0x8576),
:(const GREEN                                                           = 0x1904),
:(const VALIDATE_STATUS                                                 = 0x8B83),
:(const STENCIL_PASS_DEPTH_FAIL                                         = 0x0B95),
:(const UNSIGNED_BYTE_3_3_2                                             = 0x8032),
:(const LIGHT0                                                          = 0x4000),
:(const SECONDARY_COLOR_ARRAY_STRIDE                                    = 0x845C),
:(const LUMINANCE16                                                     = 0x8042),
:(const FLOAT_VEC4                                                      = 0x8B52),
:(const DRAW_BUFFER6                                                    = 0x882B),
:(const TRIANGLE_FAN                                                    = 0x0006),
:(const TRANSPOSE_MODELVIEW_MATRIX                                      = 0x84E3),
:(const MAX_VERTEX_UNIFORM_COMPONENTS                                   = 0x8B4A),
:(const C4F_N3F_V3F                                                     = 0x2A26),
:(const MAP2_INDEX                                                      = 0x0DB1),
:(const ONE_MINUS_SRC_ALPHA                                             = 0x0303),
:(const TEXTURE4                                                        = 0x84C4),
:(const BLEND_EQUATION_RGB                                              = 0x8009),
:(const FOG_COORDINATE_ARRAY_TYPE                                       = 0x8454),
:(const DRAW_BUFFER8                                                    = 0x882D),
:(const COMPILE_STATUS                                                  = 0x8B81),
:(const FLAT                                                            = 0x1D00),
:(const TRANSPOSE_TEXTURE_MATRIX                                        = 0x84E5),
:(const DECAL                                                           = 0x2101),
:(const FLOAT_MAT2x4                                                    = 0x8B66),
:(const TEXTURE_GEN_MODE                                                = 0x2500),
:(const PIXEL_MAP_I_TO_A                                                = 0x0C75),
:(const TEXTURE_DEPTH                                                   = 0x8071),
:(const INDEX_CLEAR_VALUE                                               = 0x0C20),
:(const TRIANGLE_STRIP                                                  = 0x0005),
:(const DEPTH_BUFFER_BIT                                                = 0x00000100),
:(const STENCIL_BACK_PASS_DEPTH_FAIL                                    = 0x8802),
:(const BLEND_DST_RGB                                                   = 0x80C8),
:(const MAX_TEXTURE_COORDS                                              = 0x8871),
:(const PIXEL_MAP_I_TO_B_SIZE                                           = 0x0CB4),
:(const ALPHA16                                                         = 0x803E),
:(const BITMAP_TOKEN                                                    = 0x0704),
:(const BACK_LEFT                                                       = 0x0402),
:(const DRAW_BUFFER0                                                    = 0x8825),
:(const VERTEX_PROGRAM_POINT_SIZE                                       = 0x8642),
:(const LIST_INDEX                                                      = 0x0B33),
:(const LINE_STIPPLE_PATTERN                                            = 0x0B25),
:(const ALPHA_BITS                                                      = 0x0D55),
:(const COMBINE_ALPHA                                                   = 0x8572),
:(const LIST_BASE                                                       = 0x0B32),
:(const MATRIX_MODE                                                     = 0x0BA0),
:(const SET                                                             = 0x150F),
:(const VERTEX_PROGRAM_TWO_SIDE                                         = 0x8643),
:(const STENCIL_BUFFER_BIT                                              = 0x00000400),
:(const COMPRESSED_RGBA                                                 = 0x84EE),
:(const FILL                                                            = 0x1B02),
:(const POINT_SIZE_MAX                                                  = 0x8127),
:(const NONE                                                            = 0),
:(const POLYGON_OFFSET_UNITS                                            = 0x2A00),
:(const SRC2_RGB                                                        = 0x8582),
:(const OR_INVERTED                                                     = 0x150D),
:(const MAP2_TEXTURE_COORD_3                                            = 0x0DB5),
:(const TEXTURE_MAX_LOD                                                 = 0x813B),
:(const MAX_CLIENT_ATTRIB_STACK_DEPTH                                   = 0x0D3B),
:(const LUMINANCE12                                                     = 0x8041),
:(const PIXEL_PACK_BUFFER                                               = 0x88EB),
:(const FEEDBACK                                                        = 0x1C01),
:(const BLEND                                                           = 0x0BE2),
:(const COLOR_INDEX                                                     = 0x1900),
:(const COMPARE_R_TO_TEXTURE                                            = 0x884E),
:(const POLYGON_OFFSET_POINT                                            = 0x2A01),
:(const TEXTURE_GEN_S                                                   = 0x0C60),
:(const QUERY_RESULT_AVAILABLE                                          = 0x8867),
:(const PROXY_TEXTURE_CUBE_MAP                                          = 0x851B),
:(const VERTEX_ATTRIB_ARRAY_SIZE                                        = 0x8623),
:(const X4D_COLOR_TEXTURE                                               = 0x0604),
:(const MAP2_GRID_DOMAIN                                                = 0x0DD2),
:(const TEXTURE28                                                       = 0x84DC),
:(const FLOAT_MAT2                                                      = 0x8B5A),
:(const TEXTURE25                                                       = 0x84D9),
:(const LIGHT_MODEL_TWO_SIDE                                            = 0x0B52),
:(const COLOR_ARRAY_SIZE                                                = 0x8081),
:(const CURRENT_RASTER_SECONDARY_COLOR                                  = 0x845F),
:(const INDEX_SHIFT                                                     = 0x0D12),
:(const BOOL                                                            = 0x8B56),
:(const UNSIGNED_SHORT_5_6_5_REV                                        = 0x8364),
:(const GREEN_BITS                                                      = 0x0D53),
:(const LINE_WIDTH_GRANULARITY                                          = 0x0B23),
:(const LOGIC_OP                                                        = 0x0BF1),
:(const SECONDARY_COLOR_ARRAY_TYPE                                      = 0x845B),
:(const GREATER                                                         = 0x0204),
:(const SUBTRACT                                                        = 0x84E7),
:(const LINE_SMOOTH                                                     = 0x0B20),
:(const STATIC_READ                                                     = 0x88E5),
:(const INTENSITY8                                                      = 0x804B),
:(const LINEAR_ATTENUATION                                              = 0x1208),
:(const SAMPLER_3D                                                      = 0x8B5F),
:(const UNPACK_SKIP_IMAGES                                              = 0x806D),
:(const COMPRESSED_SRGB_ALPHA                                           = 0x8C49),
:(const BUFFER_MAP_POINTER                                              = 0x88BD),
:(const X3D_COLOR                                                       = 0x0602),
:(const VENDOR                                                          = 0x1F00),
:(const TEXTURE15                                                       = 0x84CF),
:(const POINT_DISTANCE_ATTENUATION                                      = 0x8129),
:(const LIGHT5                                                          = 0x4005),
:(const OPERAND1_RGB                                                    = 0x8591),
:(const FLOAT_MAT2x3                                                    = 0x8B65),
:(const VERTEX_ARRAY_POINTER                                            = 0x808E),
:(const UNPACK_SKIP_ROWS                                                = 0x0CF3),
:(const RESCALE_NORMAL                                                  = 0x803A),
:(const LIGHTING_BIT                                                    = 0x00000040),
:(const ZOOM_Y                                                          = 0x0D17),
:(const INDEX_BITS                                                      = 0x0D51),
:(const TEXTURE29                                                       = 0x84DD),
:(const LIGHT_MODEL_LOCAL_VIEWER                                        = 0x0B51),
:(const BLEND_DST                                                       = 0x0BE0),
:(const TRUE                                                            = 1),
:(const RGB8                                                            = 0x8051),
:(const TEXTURE21                                                       = 0x84D5),
:(const FOG_COORDINATE_ARRAY_POINTER                                    = 0x8456),
:(const POINT_SIZE                                                      = 0x0B11),
:(const STATIC_DRAW                                                     = 0x88E4),
:(const MAX_TEXTURE_LOD_BIAS                                            = 0x84FD),
:(const DOUBLE                                                          = 0x140A),
:(const PROJECTION_MATRIX                                               = 0x0BA7),
:(const MAX_VIEWPORT_DIMS                                               = 0x0D3A),
:(const LINK_STATUS                                                     = 0x8B82),
:(const TEXTURE_1D                                                      = 0x0DE0),
:(const LUMINANCE_ALPHA                                                 = 0x190A),
:(const POINT_BIT                                                       = 0x00000002),
:(const MAX_ELEMENTS_VERTICES                                           = 0x80E8),
:(const FOG_COORDINATE_ARRAY                                            = 0x8457)]
#function bodies
const GL_COMMON_FUNCTIONS = [
:(glDrawRangeElements(mode::GLenum, start::GLuint, END::GLuint, count::GLsizei, type_::GLenum, indices::Ptr{Void})::Void),
:(glDeleteTextures(n::GLsizei, textures::Ptr{GLuint})::Void),
:(glGetVertexAttribdv(index::GLuint, pname::GLenum, params::Ptr{GLdouble})::Void),
:(glGetShaderiv(shader::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glIsShader(shader::GLuint)::Bool),
:(glGetVertexAttribiv(index::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glCreateShader(type_::GLenum)::Cuint),
:(glCopyTexImage1D(target::GLenum, level::GLint, internalformat::GLenum, x::GLint, y::GLint, width::GLsizei, border::GLint)::Void),
:(glGetQueryiv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetTexLevelParameterfv(target::GLenum, level::GLint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glSampleCoverage(value::GLfloat, invert::GLboolean)::Void),
:(glMapBuffer(target::GLenum, access::GLenum)::Ptr{Void}),
:(glGetProgramInfoLog(program::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, infoLog::Ptr{GLchar})::Void),
:(glBlendFunc(sfactor::GLenum, dfactor::GLenum)::Void),
:(glBindAttribLocation(program::GLuint, index::GLuint, name::Ptr{GLchar})::Void),
:(glPointParameteriv(pname::GLenum, params::Ptr{GLint})::Void),
:(glGetTexImage(target::GLenum, level::GLint, format::GLenum, type_::GLenum, pixels::Ptr{Void})::Void),
:(glUniform3f(location::GLint, v0::GLfloat, v1::GLfloat, v2::GLfloat)::Void),
:(glReadPixels(x::GLint, y::GLint, width::GLsizei, height::GLsizei, format::GLenum, type_::GLenum, pixels::Ptr{Void})::Void),
:(glCullFace(mode::GLenum)::Void),
:(glUniform4iv(location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glTexSubImage2D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, width::GLsizei, height::GLsizei, format::GLenum, type_::GLenum, pixels::Ptr{Void})::Void),
:(glGetBufferSubData(target::GLenum, offset::GLintptr, size::GLsizeiptr, data::Ptr{Void})::Void),
:(glUniform4f(location::GLint, v0::GLfloat, v1::GLfloat, v2::GLfloat, v3::GLfloat)::Void),
:(glGetError()::Cint),
:(glTexSubImage3D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, zoffset::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, format::GLenum, type_::GLenum, pixels::Ptr{Void})::Void),
:(glTexParameteri(target::GLenum, pname::GLenum, param::GLint)::Void),
:(glPolygonMode(face::GLenum, mode::GLenum)::Void),
:(glPointParameterf(pname::GLenum, param::GLfloat)::Void),
:(glCompressedTexImage2D(target::GLenum, level::GLint, internalformat::GLenum, width::GLsizei, height::GLsizei, border::GLint, imageSize::GLsizei, data::Ptr{Void})::Void),
:(glUniformMatrix4fv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glUniform2fv(location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glLogicOp(opcode::GLenum)::Void),
:(glGetPointerv(pname::GLenum, params::Ptr{Ptr{Void}})::Void),
:(glDeleteShader(shader::GLuint)::Void),
:(glTexImage2D(target::GLenum, level::GLint, internalformat::GLint, width::GLsizei, height::GLsizei, border::GLint, format::GLenum, type_::GLenum, pixels::Ptr{Void})::Void),
:(glBufferSubData(target::GLenum, offset::GLintptr, size::GLsizeiptr, data::Ptr{Void})::Void),
:(glStencilOpSeparate(face::GLenum, sfail::GLenum, dpfail::GLenum, dppass::GLenum)::Void),
:(glUniform2i(location::GLint, v0::GLint, v1::GLint)::Void),
:(glBlendEquation(mode::GLenum)::Void),
:(glIsEnabled(cap::GLenum)::Bool),
:(glStencilOp(fail::GLenum, zfail::GLenum, zpass::GLenum)::Void),
:(glColorMask(red::GLboolean, green::GLboolean, blue::GLboolean, alpha::GLboolean)::Void),
:(glDrawElements(mode::GLenum, count::GLsizei, type_::GLenum, indices::Ptr{Void})::Void),
:(glPointParameterfv(pname::GLenum, params::Ptr{GLfloat})::Void),
:(glGetQueryObjectuiv(id::GLuint, pname::GLenum, params::Ptr{GLuint})::Void),
:(glGenBuffers(n::GLsizei, buffers::Ptr{GLuint})::Void),
:(glViewport(x::GLint, y::GLint, width::GLsizei, height::GLsizei)::Void),
:(glBufferData(target::GLenum, size::GLsizeiptr, data::Ptr{Void}, usage::GLenum)::Void),
:(glBlendColor(red::GLfloat, green::GLfloat, blue::GLfloat, alpha::GLfloat)::Void),
:(glDetachShader(program::GLuint, shader::GLuint)::Void),
:(glGetFloatv(pname::GLenum, params::Ptr{GLfloat})::Void),
:(glUniformMatrix2x3fv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glUniformMatrix2x4fv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glBindTexture(target::GLenum, texture::GLuint)::Void),
:(glGetActiveAttrib(program::GLuint, index::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, size::Ptr{GLint}, type_::Ptr{GLenum}, name::Ptr{GLchar})::Void),
:(glUniform1iv(location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glDrawBuffers(n::GLsizei, bufs::Ptr{GLenum})::Void),
:(glTexImage3D(target::GLenum, level::GLint, internalformat::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, border::GLint, format::GLenum, type_::GLenum, pixels::Ptr{Void})::Void),
:(glCompressedTexImage1D(target::GLenum, level::GLint, internalformat::GLenum, width::GLsizei, border::GLint, imageSize::GLsizei, data::Ptr{Void})::Void),
:(glClearColor(red::GLfloat, green::GLfloat, blue::GLfloat, alpha::GLfloat)::Void),
:(glFinish()::Void),
:(glTexImage1D(target::GLenum, level::GLint, internalformat::GLint, width::GLsizei, border::GLint, format::GLenum, type_::GLenum, pixels::Ptr{Void})::Void),
:(glCopyTexImage2D(target::GLenum, level::GLint, internalformat::GLenum, x::GLint, y::GLint, width::GLsizei, height::GLsizei, border::GLint)::Void),
:(glIndexub(c::GLubyte)::Void),
:(glBindBuffer(target::GLenum, buffer::GLuint)::Void),
:(glGetVertexAttribPointerv(index::GLuint, pname::GLenum, pointer::Ptr{Ptr{Void}})::Void),
:(glUniform4i(location::GLint, v0::GLint, v1::GLint, v2::GLint, v3::GLint)::Void),
:(glDepthMask(flag::GLboolean)::Void),
:(glMultiDrawArrays(mode::GLenum, first::Ptr{GLint}, count::Ptr{GLsizei}, drawcount::GLsizei)::Void),
:(glBeginQuery(target::GLenum, id::GLuint)::Void),
:(glGetUniformiv(program::GLuint, location::GLint, params::Ptr{GLint})::Void),
:(glVertexAttribPointer(index::GLuint, size::GLint, type_::GLenum, normalized::GLboolean, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glCompressedTexImage3D(target::GLenum, level::GLint, internalformat::GLenum, width::GLsizei, height::GLsizei, depth::GLsizei, border::GLint, imageSize::GLsizei, data::Ptr{Void})::Void),
:(glUnmapBuffer(target::GLenum)::Bool),
:(glClear(mask::GLbitfield)::Void),
:(glUniformMatrix3x2fv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glUniform3iv(location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glScissor(x::GLint, y::GLint, width::GLsizei, height::GLsizei)::Void),
:(glUniform1fv(location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glGenTextures(n::GLsizei, textures::Ptr{GLuint})::Void),
:(glCopyTexSubImage3D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, zoffset::GLint, x::GLint, y::GLint, width::GLsizei, height::GLsizei)::Void),
:(glCompressedTexSubImage1D(target::GLenum, level::GLint, xoffset::GLint, width::GLsizei, format::GLenum, imageSize::GLsizei, data::Ptr{Void})::Void),
:(glDeleteQueries(n::GLsizei, ids::Ptr{GLuint})::Void),
:(glGetActiveUniform(program::GLuint, index::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, size::Ptr{GLint}, type_::Ptr{GLenum}, name::Ptr{GLchar})::Void),
:(glIsBuffer(buffer::GLuint)::Bool),
:(glGetShaderInfoLog(shader::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, infoLog::Ptr{GLchar})::Void),
:(glUniform1f(location::GLint, v0::GLfloat)::Void),
:(glGetTexLevelParameteriv(target::GLenum, level::GLint, pname::GLenum, params::Ptr{GLint})::Void),
:(glBlendFuncSeparate(sfactorRGB::GLenum, dfactorRGB::GLenum, sfactorAlpha::GLenum, dfactorAlpha::GLenum)::Void),
:(glIndexubv(c::Ptr{GLubyte})::Void),
:(glGenQueries(n::GLsizei, ids::Ptr{GLuint})::Void),
:(glShaderSource(shader::GLuint, count::GLsizei, string_::Ptr{Uint8}, length::Ptr{GLint})::Void),
:(glPixelStorei(pname::GLenum, param::GLint)::Void),
:(glCopyTexSubImage2D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, x::GLint, y::GLint, width::GLsizei, height::GLsizei)::Void),
:(glUniformMatrix3x4fv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glPointSize(size::GLfloat)::Void),
:(glGetVertexAttribfv(index::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glClearDepth(depth::GLdouble)::Void),
:(glLineWidth(width::GLfloat)::Void),
:(glMultiDrawElements(mode::GLenum, count::Ptr{GLsizei}, type_::GLenum, indices::Ptr{Ptr{Void}}, drawcount::GLsizei)::Void),
:(glTexSubImage1D(target::GLenum, level::GLint, xoffset::GLint, width::GLsizei, format::GLenum, type_::GLenum, pixels::Ptr{Void})::Void),
:(glGetAttribLocation(program::GLuint, name::Ptr{GLchar})::Cint),
:(glGetIntegerv(pname::GLenum, params::Ptr{GLint})::Void),
:(glCompressedTexSubImage3D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, zoffset::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, format::GLenum, imageSize::GLsizei, data::Ptr{Void})::Void),
:(glUniform2f(location::GLint, v0::GLfloat, v1::GLfloat)::Void),
:(glDepthFunc(func_::GLenum)::Void),
:(glFlush()::Void),
:(glHint(target::GLenum, mode::GLenum)::Void),
:(glClearStencil(s::GLint)::Void),
:(glActiveTexture(texture::GLenum)::Void),
:(glTexParameterf(target::GLenum, pname::GLenum, param::GLfloat)::Void),
:(glDeleteProgram(program::GLuint)::Void),
:(glTexParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetUniformLocation(program::GLuint, name::Ptr{GLchar})::Cint),
:(glEnable(cap::GLenum)::Void),
:(glUniform3i(location::GLint, v0::GLint, v1::GLint, v2::GLint)::Void),
:(glLinkProgram(program::GLuint)::Void),
:(glGetBooleanv(pname::GLenum, params::Ptr{GLboolean})::Void),
:(glUniformMatrix3fv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glGetAttachedShaders(program::GLuint, maxCount::GLsizei, count::Ptr{GLsizei}, obj::Ptr{GLuint})::Void),
:(glGetProgramiv(program::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glDepthRange(near_::GLdouble, far_::GLdouble)::Void),
:(glGetShaderSource(shader::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, source::Ptr{GLchar})::Void),
:(glUniform3fv(location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glDeleteBuffers(n::GLsizei, buffers::Ptr{GLuint})::Void),
:(glStencilMask(mask::GLuint)::Void),
:(glCopyTexSubImage1D(target::GLenum, level::GLint, xoffset::GLint, x::GLint, y::GLint, width::GLsizei)::Void),
:(glUniformMatrix4x3fv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glGetTexParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glTexParameterfv(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glGetString(name::GLenum)::Ptr{Cuchar}),
:(glStencilFunc(func_::GLenum, ref::GLint, mask::GLuint)::Void),
:(glAttachShader(program::GLuint, shader::GLuint)::Void),
:(glUniformMatrix2fv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glGetTexParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glFrontFace(mode::GLenum)::Void),
:(glPointParameteri(pname::GLenum, param::GLint)::Void),
:(glValidateProgram(program::GLuint)::Void),
:(glUniform1i(location::GLint, v0::GLint)::Void),
:(glReadBuffer(mode::GLenum)::Void),
:(glDisableVertexAttribArray(index::GLuint)::Void),
:(glEnableVertexAttribArray(index::GLuint)::Void),
:(glGetBufferPointerv(target::GLenum, pname::GLenum, params::Ptr{Ptr{Void}})::Void),
:(glGetUniformfv(program::GLuint, location::GLint, params::Ptr{GLfloat})::Void),
:(glStencilFuncSeparate(face::GLenum, func_::GLenum, ref::GLint, mask::GLuint)::Void),
:(glIsProgram(program::GLuint)::Bool),
:(glEndQuery(target::GLenum)::Void),
:(glPixelStoref(pname::GLenum, param::GLfloat)::Void),
:(glGetBufferParameteriv(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glIsQuery(id::GLuint)::Bool),
:(glCreateProgram()::Cuint),
:(glGetCompressedTexImage(target::GLenum, level::GLint, img::Ptr{Void})::Void),
:(glUniformMatrix4x2fv(location::GLint, count::GLsizei, transpose::GLboolean, value::Ptr{GLfloat})::Void),
:(glCompileShader(shader::GLuint)::Void),
:(glUniform4fv(location::GLint, count::GLsizei, value::Ptr{GLfloat})::Void),
:(glCompressedTexSubImage2D(target::GLenum, level::GLint, xoffset::GLint, yoffset::GLint, width::GLsizei, height::GLsizei, format::GLenum, imageSize::GLsizei, data::Ptr{Void})::Void),
:(glPolygonOffset(factor::GLfloat, units::GLfloat)::Void),
:(glGetDoublev(pname::GLenum, params::Ptr{GLdouble})::Void),
:(glDrawArrays(mode::GLenum, first::GLint, count::GLsizei)::Void),
:(glDisable(cap::GLenum)::Void),
:(glDrawBuffer(mode::GLenum)::Void),
:(glGetQueryObjectiv(id::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glUniform2iv(location::GLint, count::GLsizei, value::Ptr{GLint})::Void),
:(glBlendEquationSeparate(modeRGB::GLenum, modeAlpha::GLenum)::Void),
:(glUseProgram(program::GLuint)::Void),
:(glIsTexture(texture::GLuint)::Bool),
:(glStencilMaskSeparate(face::GLenum, mask::GLuint)::Void)]
