#Types, functions and constants, needed on top of the common ones
#types
const GL_NV_TYPES = [
]
#constants
const GL_NV_CONSTANTS = [
:(const MAP1_VERTEX_ATTRIB8_4_NV                                        = 0x8668),
:(const READ_PIXEL_DATA_RANGE_POINTER_NV                                = 0x887D),
:(const COLOR_ARRAY_ADDRESS_NV                                          = 0x8F23),
:(const GEOMETRY_PROGRAM_NV                                             = 0x8C26),
:(const COMBINER1_NV                                                    = 0x8551),
:(const DEPTH_STENCIL_TO_RGBA_NV                                        = 0x886E),
:(const DOT_PRODUCT_DEPTH_REPLACE_NV                                    = 0x86ED),
:(const SKIP_COMPONENTS3_NV                                             = -4),
:(const RELATIVE_CUBIC_CURVE_TO_NV                                      = 0x0D),
:(const DEPTH_BUFFER_FLOAT_MODE_NV                                      = 0x8DAF),
:(const TRANSFORM_FEEDBACK_BUFFER_ACTIVE_NV                             = 0x8E24),
:(const TRACK_MATRIX_NV                                                 = 0x8648),
:(const MAP_ATTRIB_V_ORDER_NV                                           = 0x86C4),
:(const PATH_GEN_MODE_NV                                                = 0x90B0),
:(const MAP_ATTRIB_U_ORDER_NV                                           = 0x86C3),
:(const WRITE_DISCARD_NV                                                = 0x88BE),
:(const TEXTURE_LO_SIZE_NV                                              = 0x871C),
:(const PATH_STROKE_COVER_MODE_NV                                       = 0x9083),
:(const ELEMENT_ARRAY_LENGTH_NV                                         = 0x8F33),
:(const TRANSPOSE_PROJECTIVE_3D_NV                                      = 0x9099),
:(const PATH_STROKE_OVERSAMPLE_COUNT_NV                                 = 0x9087),
:(const MATRIX1_NV                                                      = 0x8631),
:(const BUFFER_GPU_ADDRESS_NV                                           = 0x8F1D),
:(const DOT_PRODUCT_CONST_EYE_REFLECT_CUBE_MAP_NV                       = 0x86F3),
:(const OFFSET_TEXTURE_BIAS_NV                                          = 0x86E3),
:(const FLOAT16_VEC2_NV                                                 = 0x8FF9),
:(const OPERAND3_RGB_NV                                                 = 0x8593),
:(const MAX_PROGRAM_GENERIC_RESULTS_NV                                  = 0x8DA6),
:(const VERTEX_ARRAY_ADDRESS_NV                                         = 0x8F21),
:(const DUP_LAST_CUBIC_CURVE_TO_NV                                      = 0xF4),
:(const EVAL_VERTEX_ATTRIB0_NV                                          = 0x86C6),
:(const PROGRAM_STRING_NV                                               = 0x8628),
:(const SCALE_BY_FOUR_NV                                                = 0x853F),
:(const IDENTITY_NV                                                     = 0x862A),
:(const MAP2_VERTEX_ATTRIB0_4_NV                                        = 0x8670),
:(const MATRIX2_NV                                                      = 0x8632),
:(const DT_SCALE_NV                                                     = 0x8711),
:(const MAX_PROGRAM_PARAMETER_BUFFER_BINDINGS_NV                        = 0x8DA0),
:(const SECONDARY_COLOR_NV                                              = 0x852D),
:(const VERTEX_ARRAY_RANGE_NV                                           = 0x851D),
:(const MAP1_VERTEX_ATTRIB2_4_NV                                        = 0x8662),
:(const EVAL_VERTEX_ATTRIB6_NV                                          = 0x86CC),
:(const DOT_PRODUCT_TEXTURE_RECTANGLE_NV                                = 0x864E),
:(const READ_PIXEL_DATA_RANGE_LENGTH_NV                                 = 0x887B),
:(const COMBINER_AB_DOT_PRODUCT_NV                                      = 0x8545),
:(const PRIMITIVE_RESTART_INDEX_NV                                      = 0x8559),
:(const FRAMEBUFFER_ATTACHMENT_LAYERED_EXT                              = 0x8DA7),
:(const CURRENT_MATRIX_NV                                               = 0x8641),
:(const PATH_INITIAL_DASH_CAP_NV                                        = 0x907C),
:(const INT8_NV                                                         = 0x8FE0),
:(const UNSIGNED_INT16_VEC3_NV                                          = 0x8FF2),
:(const PATH_GEN_COEFF_NV                                               = 0x90B1),
:(const UNSIGNED_INT64_VEC4_NV                                          = 0x8FF7),
:(const FONT_HAS_KERNING_NV                                             = 0x10000000),
:(const EVAL_2D_NV                                                      = 0x86C0),
:(const ROUND_NV                                                        = 0x90A4),
:(const TEXTURE_COLOR_SAMPLES_NV                                        = 0x9046),
:(const VERTEX_ATTRIB_ARRAY2_NV                                         = 0x8652),
:(const DEPTH_COMPONENT32F_NV                                           = 0x8DAB),
:(const MAX_GEOMETRY_PROGRAM_INVOCATIONS_NV                             = 0x8E5A),
:(const FONT_X_MAX_BOUNDS_NV                                            = 0x00040000),
:(const MULTI_HULLS_NV                                                  = 0x908C),
:(const TEXTURE_SHADER_NV                                               = 0x86DE),
:(const EYE_RADIAL_NV                                                   = 0x855B),
:(const TRANSFORM_FEEDBACK_BINDING_NV                                   = 0x8E25),
:(const UTF16_NV                                                        = 0x909B),
:(const COMBINER0_NV                                                    = 0x8550),
:(const VIDEO_CAPTURE_FRAME_HEIGHT_NV                                   = 0x9039),
:(const MAX_PROGRAM_LOOP_COUNT_NV                                       = 0x88F8),
:(const POINT_SPRITE_R_MODE_NV                                          = 0x8863),
:(const REFLECTION_MAP_NV                                               = 0x8512),
:(const VERTEX_ARRAY_RANGE_WITHOUT_FLUSH_NV                             = 0x8533),
:(const SAMPLE_MASK_VALUE_NV                                            = 0x8E52),
:(const TEXTURE_DS_SIZE_NV                                              = 0x871D),
:(const WRITE_PIXEL_DATA_RANGE_POINTER_NV                               = 0x887C),
:(const INT8_VEC4_NV                                                    = 0x8FE3),
:(const INT16_VEC4_NV                                                   = 0x8FE7),
:(const HILO8_NV                                                        = 0x885E),
:(const FLOAT_RGBA16_NV                                                 = 0x888A),
:(const VIDEO_BUFFER_PITCH_NV                                           = 0x9028),
:(const OFFSET_TEXTURE_2D_BIAS_NV                                       = 0x86E3),
:(const PROXY_TEXTURE_RECTANGLE_NV                                      = 0x84F7),
:(const PATH_STROKE_BOUND_NV                                            = 0x9086),
:(const DOT_PRODUCT_DIFFUSE_CUBE_MAP_NV                                 = 0x86F1),
:(const VERTICAL_LINE_TO_NV                                             = 0x08),
:(const GLYPH_VERTICAL_BEARING_ADVANCE_BIT_NV                           = 0x80),
:(const OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV                           = 0x8851),
:(const MAP1_VERTEX_ATTRIB6_4_NV                                        = 0x8666),
:(const LINE_TO_NV                                                      = 0x04),
:(const MAP2_VERTEX_ATTRIB1_4_NV                                        = 0x8671),
:(const SKIP_COMPONENTS2_NV                                             = -5),
:(const QUERY_BY_REGION_WAIT_NV                                         = 0x8E15),
:(const OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV                            = 0x8856),
:(const MAP2_VERTEX_ATTRIB14_4_NV                                       = 0x867E),
:(const FONT_DESCENDER_NV                                               = 0x00400000),
:(const NORMAL_ARRAY_LENGTH_NV                                          = 0x8F2C),
:(const SOURCE3_RGB_NV                                                  = 0x8583),
:(const VERTEX_ATTRIB_ARRAY9_NV                                         = 0x8659),
:(const MAP2_VERTEX_ATTRIB11_4_NV                                       = 0x867B),
:(const ITALIC_BIT_NV                                                   = 0x02),
:(const VERTEX_ARRAY_RANGE_POINTER_NV                                   = 0x8521),
:(const YCBAYCR8A_4224_NV                                               = 0x9032),
:(const FIELDS_NV                                                       = 0x8E27),
:(const VIBRANCE_BIAS_NV                                                = 0x8719),
:(const INDEX_ARRAY_ADDRESS_NV                                          = 0x8F24),
:(const SCALE_BY_TWO_NV                                                 = 0x853E),
:(const VERTEX_ATTRIB_ARRAY_ADDRESS_NV                                  = 0x8F20),
:(const VARIABLE_F_NV                                                   = 0x8528),
:(const GLYPH_VERTICAL_BEARING_X_BIT_NV                                 = 0x20),
:(const TRACK_MATRIX_TRANSFORM_NV                                       = 0x8649),
:(const VERTEX_ATTRIB_ARRAY10_NV                                        = 0x865A),
:(const PRESENT_TIME_NV                                                 = 0x8E2A),
:(const RENDERBUFFER_COLOR_SAMPLES_NV                                   = 0x8E10),
:(const SAMPLER_RENDERBUFFER_NV                                         = 0x8E56),
:(const COUNT_UP_NV                                                     = 0x9088),
:(const FAILURE_NV                                                      = 0x9030),
:(const COUNT_DOWN_NV                                                   = 0x9089),
:(const HORIZONTAL_LINE_TO_NV                                           = 0x06),
:(const BOUNDING_BOX_OF_BOUNDING_BOXES_NV                               = 0x909C),
:(const YCBYCR8_422_NV                                                  = 0x9031),
:(const DRAW_INDIRECT_ADDRESS_NV                                        = 0x8F41),
:(const DSDT_MAG_NV                                                     = 0x86F6),
:(const OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV                          = 0x8852),
:(const ATTRIB_ARRAY_TYPE_NV                                            = 0x8625),
:(const VERTEX_ATTRIB_ARRAY12_NV                                        = 0x865C),
:(const LINE_STRIP_ADJACENCY_EXT                                        = 0x000B),
:(const PATH_FILL_BOUNDING_BOX_NV                                       = 0x90A1),
:(const TRANSFORM_FEEDBACK_ATTRIBS_NV                                   = 0x8C7E),
:(const PATH_INITIAL_END_CAP_NV                                         = 0x9077),
:(const COMBINER2_NV                                                    = 0x8552),
:(const MITER_TRUNCATE_NV                                               = 0x90A8),
:(const TEXTURE_BORDER_VALUES_NV                                        = 0x871A),
:(const PROJECTIVE_2D_NV                                                = 0x9093),
:(const HALF_FLOAT_NV                                                   = 0x140B),
:(const NEXT_BUFFER_NV                                                  = -2),
:(const FRAGMENT_PROGRAM_INTERPOLATION_OFFSET_BITS_NV                   = 0x8E5D),
:(const COMBINER_CD_OUTPUT_NV                                           = 0x854B),
:(const FLOAT_RGBA_NV                                                   = 0x8883),
:(const PATH_DASH_ARRAY_COUNT_NV                                        = 0x909F),
:(const PRIMITIVES_GENERATED_NV                                         = 0x8C87),
:(const COMBINER_SCALE_NV                                               = 0x8548),
:(const TRIANGULAR_NV                                                   = 0x90A5),
:(const MAP2_VERTEX_ATTRIB3_4_NV                                        = 0x8673),
:(const SMALL_CCW_ARC_TO_NV                                             = 0x12),
:(const TRANSFORM_FEEDBACK_BUFFER_NV                                    = 0x8C8E),
:(const FLOAT_RGBA32_NV                                                 = 0x888B),
:(const MAP1_VERTEX_ATTRIB11_4_NV                                       = 0x866B),
:(const DRAW_INDIRECT_UNIFIED_NV                                        = 0x8F40),
:(const PARTIAL_SUCCESS_NV                                              = 0x902E),
:(const EXPAND_NORMAL_NV                                                = 0x8538),
:(const INVERSE_TRANSPOSE_NV                                            = 0x862D),
:(const DEPTH_STENCIL_NV                                                = 0x84F9),
:(const DEPENDENT_AR_TEXTURE_2D_NV                                      = 0x86E9),
:(const MAX_TRACK_MATRIX_STACK_DEPTH_NV                                 = 0x862E),
:(const TEXTURE_UNSIGNED_REMAP_MODE_NV                                  = 0x888F),
:(const MAX_FRAGMENT_INTERPOLATION_OFFSET_NV                            = 0x8E5C),
:(const MAP1_VERTEX_ATTRIB9_4_NV                                        = 0x8669),
:(const RELATIVE_LARGE_CCW_ARC_TO_NV                                    = 0x17),
:(const MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT                            = 0x8C29),
:(const FIELD_LOWER_NV                                                  = 0x9023),
:(const PROGRAM_ATTRIB_COMPONENTS_NV                                    = 0x8906),
:(const MAX_PROGRAM_OUTPUT_VERTICES_NV                                  = 0x8C27),
:(const CULL_FRAGMENT_NV                                                = 0x86E7),
:(const PRIMITIVE_ID_NV                                                 = 0x8C7C),
:(const FLOAT16_NV                                                      = 0x8FF8),
:(const SIGNED_RGBA_NV                                                  = 0x86FB),
:(const INT16_NV                                                        = 0x8FE4),
:(const VERTEX_ATTRIB_ARRAY8_NV                                         = 0x8658),
:(const BIAS_BY_NEGATIVE_ONE_HALF_NV                                    = 0x8541),
:(const FLOAT_RGB32_NV                                                  = 0x8889),
:(const SECONDARY_COLOR_ARRAY_LENGTH_NV                                 = 0x8F31),
:(const SPARE0_PLUS_SECONDARY_COLOR_NV                                  = 0x8532),
:(const MATRIX0_NV                                                      = 0x8630),
:(const COMBINER_AB_OUTPUT_NV                                           = 0x854A),
:(const VERTEX_ATTRIB_ARRAY0_NV                                         = 0x8650),
:(const TEXTURE_RECTANGLE_NV                                            = 0x84F5),
:(const PATH_FILL_MASK_NV                                               = 0x9081),
:(const DOT_PRODUCT_REFLECT_CUBE_MAP_NV                                 = 0x86F2),
:(const DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV                               = 0x885A),
:(const PATH_STENCIL_REF_NV                                             = 0x90B8),
:(const UNSIGNED_INT64_VEC2_NV                                          = 0x8FF5),
:(const UNSIGNED_INT8_VEC4_NV                                           = 0x8FEF),
:(const EMBOSS_CONSTANT_NV                                              = 0x855E),
:(const MAX_PROGRAM_TOTAL_OUTPUT_COMPONENTS_NV                          = 0x8C28),
:(const MAX_PROGRAM_RESULT_COMPONENTS_NV                                = 0x8909),
:(const GPU_ADDRESS_NV                                                  = 0x8F34),
:(const FILE_NAME_NV                                                    = 0x9074),
:(const INT8_VEC2_NV                                                    = 0x8FE1),
:(const MAX_TRACK_MATRICES_NV                                           = 0x862F),
:(const UNSIGNED_INT8_VEC3_NV                                           = 0x8FEE),
:(const RELATIVE_SMALL_CCW_ARC_TO_NV                                    = 0x13),
:(const FLOAT_RGB16_NV                                                  = 0x8888),
:(const FONT_MAX_ADVANCE_HEIGHT_NV                                      = 0x02000000),
:(const VERTEX_ATTRIB_ARRAY_UNIFIED_NV                                  = 0x8F1E),
:(const MIN_FRAGMENT_INTERPOLATION_OFFSET_NV                            = 0x8E5B),
:(const MAX_PROGRAM_SUBROUTINE_NUM_NV                                   = 0x8F45),
:(const OFFSET_TEXTURE_SCALE_NV                                         = 0x86E2),
:(const CONST_EYE_NV                                                    = 0x86E5),
:(const DEPTH_STENCIL_TO_BGRA_NV                                        = 0x886F),
:(const OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV                     = 0x8857),
:(const OFFSET_TEXTURE_MATRIX_NV                                        = 0x86E1),
:(const FIELD_UPPER_NV                                                  = 0x9022),
:(const FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT                        = 0x8DA8),
:(const MULTISAMPLE_COVERAGE_MODES_NV                                   = 0x8E12),
:(const VERTEX_ATTRIB_ARRAY15_NV                                        = 0x865F),
:(const VIDEO_COLOR_CONVERSION_MAX_NV                                   = 0x902A),
:(const MAX_PROGRAM_PATCH_ATTRIBS_NV                                    = 0x86D8),
:(const EVAL_VERTEX_ATTRIB7_NV                                          = 0x86CD),
:(const PREVIOUS_TEXTURE_INPUT_NV                                       = 0x86E4),
:(const MAP1_VERTEX_ATTRIB12_4_NV                                       = 0x866C),
:(const FRAGMENT_PROGRAM_NV                                             = 0x8870),
:(const EDGE_FLAG_ARRAY_LENGTH_NV                                       = 0x8F30),
:(const DUP_FIRST_CUBIC_CURVE_TO_NV                                     = 0xF2),
:(const FLOAT_RGB_NV                                                    = 0x8882),
:(const MAX_MULTISAMPLE_COVERAGE_MODES_NV                               = 0x8E11),
:(const BEVEL_NV                                                        = 0x90A6),
:(const EVAL_VERTEX_ATTRIB11_NV                                         = 0x86D1),
:(const VIDEO_CAPTURE_TO_422_SUPPORTED_NV                               = 0x9026),
:(const ACTIVE_VARYING_MAX_LENGTH_NV                                    = 0x8C82),
:(const EVAL_VERTEX_ATTRIB1_NV                                          = 0x86C7),
:(const TEXTURE_COORD_ARRAY_ADDRESS_NV                                  = 0x8F25),
:(const MAP2_VERTEX_ATTRIB9_4_NV                                        = 0x8679),
:(const GLYPH_HEIGHT_BIT_NV                                             = 0x02),
:(const MAX_PROGRAM_IF_DEPTH_NV                                         = 0x88F6),
:(const PATH_DASH_CAPS_NV                                               = 0x907B),
:(const FLOAT_R16_NV                                                    = 0x8884),
:(const PATH_FORMAT_PS_NV                                               = 0x9071),
:(const FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT                        = 0x8CD4),
:(const VERTEX_ARRAY_RANGE_VALID_NV                                     = 0x851F),
:(const PATH_FORMAT_SVG_NV                                              = 0x9070),
:(const DSDT8_MAG8_INTENSITY8_NV                                        = 0x870B),
:(const PATH_STENCIL_DEPTH_OFFSET_FACTOR_NV                             = 0x90BD),
:(const SYSTEM_FONT_NAME_NV                                             = 0x9073),
:(const VERTEX_PROGRAM_NV                                               = 0x8620),
:(const DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV                             = 0x885D),
:(const SIGNED_HILO_NV                                                  = 0x86F9),
:(const FONT_UNITS_PER_EM_NV                                            = 0x00100000),
:(const PATH_COORD_COUNT_NV                                             = 0x909E),
:(const FOG_COORD_ARRAY_LENGTH_NV                                       = 0x8F32),
:(const EVAL_VERTEX_ATTRIB10_NV                                         = 0x86D0),
:(const CLOSE_PATH_NV                                                   = 0x00),
:(const SIGNED_RGB8_UNSIGNED_ALPHA8_NV                                  = 0x870D),
:(const SCALE_BY_ONE_HALF_NV                                            = 0x8540),
:(const EVAL_TRIANGULAR_2D_NV                                           = 0x86C1),
:(const E_TIMES_F_NV                                                    = 0x8531),
:(const Z4Y12Z4CB12Z4CR12_444_NV                                        = 0x9037),
:(const OFFSET_TEXTURE_RECTANGLE_SCALE_NV                               = 0x864D),
:(const TRANSFORM_FEEDBACK_BUFFER_MODE_NV                               = 0x8C7F),
:(const UNSIGNED_INT_24_8_NV                                            = 0x84FA),
:(const QUERY_NO_WAIT_NV                                                = 0x8E14),
:(const SURFACE_REGISTERED_NV                                           = 0x86FD),
:(const SHADER_OPERATION_NV                                             = 0x86DF),
:(const FLOAT16_VEC4_NV                                                 = 0x8FFB),
:(const VERTEX_ATTRIB_ARRAY5_NV                                         = 0x8655),
:(const RELATIVE_QUADRATIC_CURVE_TO_NV                                  = 0x0B),
:(const UNSIGNED_INT_S8_S8_8_8_NV                                       = 0x86DA),
:(const ALL_COMPLETED_NV                                                = 0x84F2),
:(const TESS_CONTROL_PROGRAM_PARAMETER_BUFFER_NV                        = 0x8C74),
:(const UNSIGNED_INT8_VEC2_NV                                           = 0x8FED),
:(const EDGE_FLAG_ARRAY_ADDRESS_NV                                      = 0x8F26),
:(const OFFSET_HILO_TEXTURE_RECTANGLE_NV                                = 0x8855),
:(const VERTEX_ATTRIB_ARRAY4_NV                                         = 0x8654),
:(const INT_SAMPLER_RENDERBUFFER_NV                                     = 0x8E57),
:(const WRITE_PIXEL_DATA_RANGE_NV                                       = 0x8878),
:(const VIDEO_COLOR_CONVERSION_MATRIX_NV                                = 0x9029),
:(const LO_SCALE_NV                                                     = 0x870F),
:(const PATH_END_CAPS_NV                                                = 0x9076),
:(const RELATIVE_MOVE_TO_NV                                             = 0x03),
:(const TRANSLATE_3D_NV                                                 = 0x9091),
:(const MITER_REVERT_NV                                                 = 0x90A7),
:(const MAP2_VERTEX_ATTRIB12_4_NV                                       = 0x867C),
:(const PRESENT_DURATION_NV                                             = 0x8E2B),
:(const DOT_PRODUCT_NV                                                  = 0x86EC),
:(const SOURCE3_ALPHA_NV                                                = 0x858B),
:(const NORMAL_MAP_NV                                                   = 0x8511),
:(const VERTEX_ATTRIB_ARRAY6_NV                                         = 0x8656),
:(const FONT_X_MIN_BOUNDS_NV                                            = 0x00010000),
:(const Z4Y12Z4CB12Z4A12Z4Y12Z4CR12Z4A12_4224_NV                        = 0x9036),
:(const VERTEX_ATTRIB_ARRAY3_NV                                         = 0x8653),
:(const RELATIVE_SMOOTH_CUBIC_CURVE_TO_NV                               = 0x11),
:(const COMBINER_COMPONENT_USAGE_NV                                     = 0x8544),
:(const CONSTANT_COLOR0_NV                                              = 0x852A),
:(const MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS_NV                = 0x8C8A),
:(const MODELVIEW_PROJECTION_NV                                         = 0x8629),
:(const NUM_VIDEO_CAPTURE_STREAMS_NV                                    = 0x9024),
:(const VARIABLE_G_NV                                                   = 0x8529),
:(const LINES_ADJACENCY_EXT                                             = 0x000A),
:(const EYE_PLANE_ABSOLUTE_NV                                           = 0x855C),
:(const PATH_OBJECT_BOUNDING_BOX_NV                                     = 0x908A),
:(const GEOMETRY_INPUT_TYPE_EXT                                         = 0x8DDB),
:(const ACTIVE_VARYINGS_NV                                              = 0x8C81),
:(const QUADRATIC_CURVE_TO_NV                                           = 0x0A),
:(const GLYPH_VERTICAL_BEARING_Y_BIT_NV                                 = 0x40),
:(const INT16_VEC3_NV                                                   = 0x8FE6),
:(const PATH_DASH_OFFSET_NV                                             = 0x907E),
:(const COMBINER3_NV                                                    = 0x8553),
:(const GEOMETRY_VERTICES_OUT_EXT                                       = 0x8DDA),
:(const SMOOTH_CUBIC_CURVE_TO_NV                                        = 0x10),
:(const DS_SCALE_NV                                                     = 0x8710),
:(const PROJECTIVE_3D_NV                                                = 0x9095),
:(const REGISTER_COMBINERS_NV                                           = 0x8522),
:(const TESS_EVALUATION_PROGRAM_PARAMETER_BUFFER_NV                     = 0x8C75),
:(const EVAL_VERTEX_ATTRIB2_NV                                          = 0x86C8),
:(const PROGRAM_RESULT_COMPONENTS_NV                                    = 0x8907),
:(const SIGNED_HILO16_NV                                                = 0x86FA),
:(const OPERAND3_ALPHA_NV                                               = 0x859B),
:(const SKIP_COMPONENTS4_NV                                             = -3),
:(const ELEMENT_ARRAY_UNIFIED_NV                                        = 0x8F1F),
:(const TEXTURE_HI_SIZE_NV                                              = 0x871B),
:(const LARGE_CCW_ARC_TO_NV                                             = 0x16),
:(const EVAL_FRACTIONAL_TESSELLATION_NV                                 = 0x86C5),
:(const MULTISAMPLE_FILTER_HINT_NV                                      = 0x8534),
:(const LAST_VIDEO_CAPTURE_STATUS_NV                                    = 0x9027),
:(const RELATIVE_ARC_TO_NV                                              = 0xFF),
:(const PER_STAGE_CONSTANTS_NV                                          = 0x8535),
:(const VERTEX_ID_NV                                                    = 0x8C7B),
:(const TRANSFORM_FEEDBACK_NV                                           = 0x8E22),
:(const MAP2_VERTEX_ATTRIB13_4_NV                                       = 0x867D),
:(const VERTEX_ATTRIB_ARRAY7_NV                                         = 0x8657),
:(const SURFACE_MAPPED_NV                                               = 0x8700),
:(const MAP2_VERTEX_ATTRIB15_4_NV                                       = 0x867F),
:(const NUM_GENERAL_COMBINERS_NV                                        = 0x854E),
:(const PATH_FILL_COVER_MODE_NV                                         = 0x9082),
:(const MAP1_VERTEX_ATTRIB10_4_NV                                       = 0x866A),
:(const RELATIVE_HORIZONTAL_LINE_TO_NV                                  = 0x07),
:(const PIXEL_COUNTER_BITS_NV                                           = 0x8864),
:(const OFFSET_TEXTURE_2D_MATRIX_NV                                     = 0x86E1),
:(const FLOAT16_VEC3_NV                                                 = 0x8FFA),
:(const PATH_TERMINAL_DASH_CAP_NV                                       = 0x907D),
:(const PATH_TERMINAL_END_CAP_NV                                        = 0x9078),
:(const UNSIGNED_INVERT_NV                                              = 0x8537),
:(const CLIP_DISTANCE_NV                                                = 0x8C7A),
:(const HALF_BIAS_NORMAL_NV                                             = 0x853A),
:(const MAP2_VERTEX_ATTRIB10_4_NV                                       = 0x867A),
:(const DRAW_INDIRECT_LENGTH_NV                                         = 0x8F42),
:(const PIXEL_COUNT_AVAILABLE_NV                                        = 0x8867),
:(const MAX_PROGRAM_LOOP_DEPTH_NV                                       = 0x88F7),
:(const SURFACE_STATE_NV                                                = 0x86EB),
:(const TEXTURE_COORD_NV                                                = 0x8C79),
:(const PROGRAM_LENGTH_NV                                               = 0x8627),
:(const MAP1_VERTEX_ATTRIB15_4_NV                                       = 0x866F),
:(const VIDEO_COLOR_CONVERSION_OFFSET_NV                                = 0x902C),
:(const MAX_RATIONAL_EVAL_ORDER_NV                                      = 0x86D7),
:(const HALF_BIAS_NEGATE_NV                                             = 0x853B),
:(const SMALL_CW_ARC_TO_NV                                              = 0x14),
:(const TRANSLATE_Y_NV                                                  = 0x908F),
:(const SECONDARY_COLOR_ARRAY_ADDRESS_NV                                = 0x8F27),
:(const FRAGMENT_PROGRAM_BINDING_NV                                     = 0x8873),
:(const TEXTURE_RENDERBUFFER_DATA_STORE_BINDING_NV                      = 0x8E54),
:(const FONT_Y_MIN_BOUNDS_NV                                            = 0x00020000),
:(const FONT_UNDERLINE_THICKNESS_NV                                     = 0x08000000),
:(const SIGNED_HILO8_NV                                                 = 0x885F),
:(const GLYPH_HAS_KERNING_NV                                            = 0x100),
:(const DSDT_MAG_INTENSITY_NV                                           = 0x86DC),
:(const SIGNED_INTENSITY_NV                                             = 0x8707),
:(const VIDEO_BUFFER_INTERNAL_FORMAT_NV                                 = 0x902D),
:(const PROGRAM_TARGET_NV                                               = 0x8646),
:(const EVAL_VERTEX_ATTRIB12_NV                                         = 0x86D2),
:(const DSDT_NV                                                         = 0x86F5),
:(const RGBA_UNSIGNED_DOT_PRODUCT_MAPPING_NV                            = 0x86D9),
:(const OFFSET_HILO_TEXTURE_2D_NV                                       = 0x8854),
:(const MATRIX6_NV                                                      = 0x8636),
:(const RELATIVE_SMALL_CW_ARC_TO_NV                                     = 0x15),
:(const PRIMARY_COLOR_NV                                                = 0x852C),
:(const GEOMETRY_OUTPUT_TYPE_EXT                                        = 0x8DDC),
:(const PASS_THROUGH_NV                                                 = 0x86E6),
:(const PATH_GEN_COMPONENTS_NV                                          = 0x90B3),
:(const TRIANGLES_ADJACENCY_EXT                                         = 0x000C),
:(const VERTEX_STATE_PROGRAM_NV                                         = 0x8621),
:(const DS_BIAS_NV                                                      = 0x8716),
:(const EVAL_VERTEX_ATTRIB9_NV                                          = 0x86CF),
:(const FLOAT_R_NV                                                      = 0x8880),
:(const MATRIX3_NV                                                      = 0x8633),
:(const READ_PIXEL_DATA_RANGE_NV                                        = 0x8879),
:(const MAX_FRAGMENT_PROGRAM_LOCAL_PARAMETERS_NV                        = 0x8868),
:(const OFFSET_TEXTURE_2D_SCALE_NV                                      = 0x86E2),
:(const COVERAGE_SAMPLES_NV                                             = 0x80A9),
:(const COLOR_ARRAY_LENGTH_NV                                           = 0x8F2D),
:(const FOG_COORD_ARRAY_ADDRESS_NV                                      = 0x8F28),
:(const MOVE_TO_NV                                                      = 0x02),
:(const VERTEX_PROGRAM_PARAMETER_BUFFER_NV                              = 0x8DA2),
:(const SUCCESS_NV                                                      = 0x902F),
:(const MAX_SHADER_BUFFER_ADDRESS_NV                                    = 0x8F35),
:(const PATH_JOIN_STYLE_NV                                              = 0x9079),
:(const TEXTURE_COVERAGE_SAMPLES_NV                                     = 0x9045),
:(const SIGNED_RGB8_NV                                                  = 0x86FF),
:(const OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV                    = 0x8853),
:(const FENCE_STATUS_NV                                                 = 0x84F3),
:(const SIGNED_RGB_NV                                                   = 0x86FE),
:(const EVAL_VERTEX_ATTRIB4_NV                                          = 0x86CA),
:(const UNSIGNED_INT16_NV                                               = 0x8FF0),
:(const MAP1_VERTEX_ATTRIB13_4_NV                                       = 0x866D),
:(const FRAGMENT_PROGRAM_PARAMETER_BUFFER_NV                            = 0x8DA4),
:(const TRANSLATE_X_NV                                                  = 0x908E),
:(const BACK_PRIMARY_COLOR_NV                                           = 0x8C77),
:(const MAX_RECTANGLE_TEXTURE_SIZE_NV                                   = 0x84F8),
:(const FLOAT_RGBA_MODE_NV                                              = 0x888E),
:(const COMBINE4_NV                                                     = 0x8503),
:(const VARIABLE_E_NV                                                   = 0x8527),
:(const PATH_ERROR_POSITION_NV                                          = 0x90AB),
:(const SHADER_CONSISTENT_NV                                            = 0x86DD),
:(const UNSIGNED_IDENTITY_NV                                            = 0x8536),
:(const MAGNITUDE_BIAS_NV                                               = 0x8718),
:(const MAX_TEXTURE_COORDS_NV                                           = 0x8871),
:(const RECT_NV                                                         = 0xF6),
:(const MAP1_VERTEX_ATTRIB0_4_NV                                        = 0x8660),
:(const EVAL_VERTEX_ATTRIB3_NV                                          = 0x86C9),
:(const PATH_COMPUTED_LENGTH_NV                                         = 0x90A0),
:(const MAP2_VERTEX_ATTRIB4_4_NV                                        = 0x8674),
:(const VERTEX_ATTRIB_ARRAY1_NV                                         = 0x8651),
:(const MAX_PROGRAM_ATTRIB_COMPONENTS_NV                                = 0x8908),
:(const MAP2_VERTEX_ATTRIB8_4_NV                                        = 0x8678),
:(const CURRENT_MATRIX_STACK_DEPTH_NV                                   = 0x8640),
:(const TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN_NV                        = 0x8C88),
:(const DOT_PRODUCT_TEXTURE_CUBE_MAP_NV                                 = 0x86F0),
:(const VERTEX_PROGRAM_POINT_SIZE_NV                                    = 0x8642),
:(const ACCUM_ADJACENT_PAIRS_NV                                         = 0x90AD),
:(const FENCE_CONDITION_NV                                              = 0x84F4),
:(const OFFSET_PROJECTIVE_TEXTURE_2D_NV                                 = 0x8850),
:(const PATH_STROKE_BOUNDING_BOX_NV                                     = 0x90A2),
:(const DOT_PRODUCT_TEXTURE_2D_NV                                       = 0x86EE),
:(const OFFSET_TEXTURE_2D_NV                                            = 0x86E8),
:(const DEPENDENT_RGB_TEXTURE_3D_NV                                     = 0x8859),
:(const PATH_COMMAND_COUNT_NV                                           = 0x909D),
:(const FLOAT_CLEAR_COLOR_VALUE_NV                                      = 0x888D),
:(const EVAL_VERTEX_ATTRIB5_NV                                          = 0x86CB),
:(const TRANSFORM_FEEDBACK_BUFFER_PAUSED_NV                             = 0x8E23),
:(const ATTRIB_ARRAY_STRIDE_NV                                          = 0x8624),
:(const MAX_SHININESS_NV                                                = 0x8504),
:(const VIDEO_BUFFER_NV                                                 = 0x9020),
:(const COMBINER_MUX_SUM_NV                                             = 0x8547),
:(const SHADER_GLOBAL_ACCESS_BARRIER_BIT_NV                             = 0x00000010),
:(const MIN_PROGRAM_TEXTURE_GATHER_OFFSET_NV                            = 0x8E5E),
:(const TEXTURE1_ARB                                                    = 0x84C1),
:(const FLOAT_RG16_NV                                                   = 0x8886),
:(const PATH_STROKE_MASK_NV                                             = 0x9084),
:(const QUERY_BY_REGION_NO_WAIT_NV                                      = 0x8E16),
:(const FLOAT_RG32_NV                                                   = 0x8887),
:(const TRANSLATE_2D_NV                                                 = 0x9090),
:(const INT64_VEC3_NV                                                   = 0x8FEA),
:(const FORCE_BLUE_TO_ONE_NV                                            = 0x8860),
:(const PATH_FOG_GEN_MODE_NV                                            = 0x90AC),
:(const INT64_VEC2_NV                                                   = 0x8FE9),
:(const COMBINER4_NV                                                    = 0x8554),
:(const VIDEO_CAPTURE_FRAME_WIDTH_NV                                    = 0x9038),
:(const CIRCULAR_CCW_ARC_TO_NV                                          = 0xF8),
:(const MAX_VERTEX_ARRAY_RANGE_ELEMENT_NV                               = 0x8520),
:(const VIDEO_CAPTURE_SURFACE_ORIGIN_NV                                 = 0x903C),
:(const TRANSFORM_FEEDBACK_VARYINGS_NV                                  = 0x8C83),
:(const SPARE0_NV                                                       = 0x852E),
:(const VERTEX_PROGRAM_BINDING_NV                                       = 0x864A),
:(const MATRIX5_NV                                                      = 0x8635),
:(const MATRIX7_NV                                                      = 0x8637),
:(const PRIMITIVE_RESTART_NV                                            = 0x8558),
:(const DEPTH32F_STENCIL8_NV                                            = 0x8DAC),
:(const MAP_TESSELLATION_NV                                             = 0x86C2),
:(const ADJACENT_PAIRS_NV                                               = 0x90AE),
:(const COMBINER_INPUT_NV                                               = 0x8542),
:(const TRANSPOSE_AFFINE_3D_NV                                          = 0x9098),
:(const MAX_GENERAL_COMBINERS_NV                                        = 0x854D),
:(const MAP1_VERTEX_ATTRIB3_4_NV                                        = 0x8663),
:(const DSDT8_NV                                                        = 0x8709),
:(const FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT                          = 0x8DA9),
:(const TEXTURE_MAG_SIZE_NV                                             = 0x871F),
:(const SKIP_MISSING_GLYPH_NV                                           = 0x90A9),
:(const PATH_FILL_MODE_NV                                               = 0x9080),
:(const EMBOSS_LIGHT_NV                                                 = 0x855D),
:(const MAP1_VERTEX_ATTRIB14_4_NV                                       = 0x866E),
:(const COMBINER_SUM_OUTPUT_NV                                          = 0x854C),
:(const RESTART_PATH_NV                                                 = 0xF0),
:(const TEXTURE_COORD_ARRAY_LENGTH_NV                                   = 0x8F2F),
:(const ATTRIB_ARRAY_SIZE_NV                                            = 0x8623),
:(const EMBOSS_MAP_NV                                                   = 0x855F),
:(const PATH_CLIENT_LENGTH_NV                                           = 0x907F),
:(const TEXTURE0_ARB                                                    = 0x84C0),
:(const VERTEX_PROGRAM_TWO_SIDE_NV                                      = 0x8643),
:(const GLYPH_HORIZONTAL_BEARING_ADVANCE_BIT_NV                         = 0x10),
:(const COLOR_SUM_CLAMP_NV                                              = 0x854F),
:(const BOLD_BIT_NV                                                     = 0x01),
:(const INT8_VEC3_NV                                                    = 0x8FE2),
:(const FLOAT_32_UNSIGNED_INT_24_8_REV_NV                               = 0x8DAD),
:(const COMBINER5_NV                                                    = 0x8555),
:(const MAX_PROGRAM_TEXEL_OFFSET_NV                                     = 0x8905),
:(const MAP2_VERTEX_ATTRIB5_4_NV                                        = 0x8675),
:(const DSDT8_MAG8_NV                                                   = 0x870A),
:(const UTF8_NV                                                         = 0x909A),
:(const MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS_NV                   = 0x8C80),
:(const DOT_PRODUCT_PASS_THROUGH_NV                                     = 0x885B),
:(const TRANSPOSE_AFFINE_2D_NV                                          = 0x9096),
:(const COLOR_SAMPLES_NV                                                = 0x8E20),
:(const MAX_PROGRAM_GENERIC_ATTRIBS_NV                                  = 0x8DA5),
:(const TEXTURE_FLOAT_COMPONENTS_NV                                     = 0x888C),
:(const HI_SCALE_NV                                                     = 0x870E),
:(const CULL_MODES_NV                                                   = 0x86E0),
:(const GLYPH_WIDTH_BIT_NV                                              = 0x01),
:(const TRANSFORM_FEEDBACK_RECORD_NV                                    = 0x8C86),
:(const MAX_PROGRAM_PARAMETER_BUFFER_SIZE_NV                            = 0x8DA1),
:(const FRAME_NV                                                        = 0x8E26),
:(const SMOOTH_QUADRATIC_CURVE_TO_NV                                    = 0x0E),
:(const CIRCULAR_TANGENT_ARC_TO_NV                                      = 0xFC),
:(const MAP1_VERTEX_ATTRIB7_4_NV                                        = 0x8667),
:(const SKIP_COMPONENTS1_NV                                             = -6),
:(const SIGNED_RGBA8_NV                                                 = 0x86FC),
:(const DOT_PRODUCT_TEXTURE_1D_NV                                       = 0x885C),
:(const ELEMENT_ARRAY_ADDRESS_NV                                        = 0x8F29),
:(const TESS_EVALUATION_PROGRAM_NV                                      = 0x891F),
:(const COORD_REPLACE_NV                                                = 0x8862),
:(const HI_BIAS_NV                                                      = 0x8714),
:(const SIGNED_NEGATE_NV                                                = 0x853D),
:(const VARIABLE_D_NV                                                   = 0x8526),
:(const MAP1_VERTEX_ATTRIB4_4_NV                                        = 0x8664),
:(const CURRENT_TIME_NV                                                 = 0x8E28),
:(const VERTEX_ARRAY_RANGE_LENGTH_NV                                    = 0x851E),
:(const SPARE1_NV                                                       = 0x852F),
:(const BOUNDING_BOX_NV                                                 = 0x908D),
:(const FLOAT_R32_NV                                                    = 0x8885),
:(const SEPARATE_ATTRIBS_NV                                             = 0x8C8D),
:(const INT64_VEC4_NV                                                   = 0x8FEB),
:(const NORMAL_ARRAY_ADDRESS_NV                                         = 0x8F22),
:(const SIGNED_LUMINANCE8_NV                                            = 0x8702),
:(const VERTEX_ATTRIB_ARRAY14_NV                                        = 0x865E),
:(const SAMPLE_MASK_NV                                                  = 0x8E51),
:(const SAMPLE_POSITION_NV                                              = 0x8E50),
:(const GEOMETRY_PROGRAM_PARAMETER_BUFFER_NV                            = 0x8DA3),
:(const SIGNED_IDENTITY_NV                                              = 0x853C),
:(const VARIABLE_A_NV                                                   = 0x8523),
:(const STANDARD_FONT_NAME_NV                                           = 0x9072),
:(const Z6Y10Z6CB10Z6Y10Z6CR10_422_NV                                   = 0x9033),
:(const COMBINER6_NV                                                    = 0x8556),
:(const PATH_STENCIL_DEPTH_OFFSET_UNITS_NV                              = 0x90BE),
:(const CIRCULAR_CW_ARC_TO_NV                                           = 0xFA),
:(const MAX_MAP_TESSELLATION_NV                                         = 0x86D6),
:(const FONT_UNDERLINE_POSITION_NV                                      = 0x04000000),
:(const TEXTURE_BINDING_RECTANGLE_NV                                    = 0x84F6),
:(const PROGRAM_PARAMETER_NV                                            = 0x8644),
:(const MAX_PROGRAM_TEXTURE_GATHER_OFFSET_NV                            = 0x8E5F),
:(const COMBINER7_NV                                                    = 0x8557),
:(const MAP2_VERTEX_ATTRIB6_4_NV                                        = 0x8676),
:(const VERTEX_ATTRIB_ARRAY_INTEGER_NV                                  = 0x88FD),
:(const INDEX_ARRAY_LENGTH_NV                                           = 0x8F2E),
:(const TRANSFORM_FEEDBACK_BUFFER_SIZE_NV                               = 0x8C85),
:(const VARIABLE_C_NV                                                   = 0x8525),
:(const EVAL_VERTEX_ATTRIB14_NV                                         = 0x86D4),
:(const GLYPH_HORIZONTAL_BEARING_Y_BIT_NV                               = 0x08),
:(const PATH_STENCIL_FUNC_NV                                            = 0x90B7),
:(const PATH_COVER_DEPTH_FUNC_NV                                        = 0x90BF),
:(const PROGRAM_POINT_SIZE_EXT                                          = 0x8642),
:(const TRANSFORM_FEEDBACK_BUFFER_START_NV                              = 0x8C84),
:(const Z4Y12Z4CB12Z4Y12Z4CR12_422_NV                                   = 0x9035),
:(const PROGRAM_ERROR_STRING_NV                                         = 0x8874),
:(const FONT_ASCENDER_NV                                                = 0x00200000),
:(const SQUARE_NV                                                       = 0x90A3),
:(const VERTEX_ATTRIB_ARRAY11_NV                                        = 0x865B),
:(const VERTEX_ATTRIB_ARRAY13_NV                                        = 0x865D),
:(const TRANSFORM_FEEDBACK_BUFFER_BINDING_NV                            = 0x8C8F),
:(const EVAL_VERTEX_ATTRIB8_NV                                          = 0x86CE),
:(const MAP1_VERTEX_ATTRIB1_4_NV                                        = 0x8661),
:(const TRANSPOSE_NV                                                    = 0x862C),
:(const POINT_SPRITE_NV                                                 = 0x8861),
:(const NEXT_VIDEO_CAPTURE_BUFFER_STATUS_NV                             = 0x9025),
:(const SIGNED_LUMINANCE_ALPHA_NV                                       = 0x8703),
:(const HILO_NV                                                         = 0x86F4),
:(const VIDEO_CAPTURE_FIELD_UPPER_HEIGHT_NV                             = 0x903A),
:(const PIXEL_COUNT_NV                                                  = 0x8866),
:(const SIGNED_INTENSITY8_NV                                            = 0x8708),
:(const PROGRAM_ERROR_POSITION_NV                                       = 0x864B),
:(const FONT_HEIGHT_NV                                                  = 0x00800000),
:(const MAX_PROGRAM_SUBROUTINE_PARAMETERS_NV                            = 0x8F44),
:(const EXPAND_NEGATE_NV                                                = 0x8539),
:(const OFFSET_TEXTURE_RECTANGLE_NV                                     = 0x864C),
:(const VIDEO_CAPTURE_FIELD_LOWER_HEIGHT_NV                             = 0x903B),
:(const AFFINE_3D_NV                                                    = 0x9094),
:(const LAYER_NV                                                        = 0x8DAA),
:(const RASTERIZER_DISCARD_NV                                           = 0x8C89),
:(const DSDT_MAG_VIB_NV                                                 = 0x86F7),
:(const UNSIGNED_INT_8_8_S8_S8_REV_NV                                   = 0x86DB),
:(const PATH_STENCIL_VALUE_MASK_NV                                      = 0x90B9),
:(const SIGNED_RGB_UNSIGNED_ALPHA_NV                                    = 0x870C),
:(const VERTEX_ATTRIB_ARRAY_LENGTH_NV                                   = 0x8F2A),
:(const MAGNITUDE_SCALE_NV                                              = 0x8712),
:(const PATH_MITER_LIMIT_NV                                             = 0x907A),
:(const DEPENDENT_HILO_TEXTURE_2D_NV                                    = 0x8858),
:(const LARGE_CW_ARC_TO_NV                                              = 0x18),
:(const GLYPH_HORIZONTAL_BEARING_X_BIT_NV                               = 0x04),
:(const MAP1_VERTEX_ATTRIB5_4_NV                                        = 0x8665),
:(const CUBIC_CURVE_TO_NV                                               = 0x0C),
:(const EVAL_VERTEX_ATTRIB15_NV                                         = 0x86D5),
:(const PATCHES                                                         = 0x000E),
:(const VIBRANCE_SCALE_NV                                               = 0x8713),
:(const ARC_TO_NV                                                       = 0xFE),
:(const TEXTURE_BINDING_RENDERBUFFER_NV                                 = 0x8E53),
:(const SIGNED_ALPHA8_NV                                                = 0x8706),
:(const CURRENT_OCCLUSION_QUERY_ID_NV                                   = 0x8865),
:(const TRIANGLE_STRIP_ADJACENCY_EXT                                    = 0x000D),
:(const AFFINE_2D_NV                                                    = 0x9092),
:(const MOVE_TO_CONTINUES_NV                                            = 0x90B6),
:(const DEPENDENT_GB_TEXTURE_2D_NV                                      = 0x86EA),
:(const FOG_DISTANCE_MODE_NV                                            = 0x855A),
:(const INT16_VEC2_NV                                                   = 0x8FE5),
:(const SIGNED_LUMINANCE_NV                                             = 0x8701),
:(const MAP2_VERTEX_ATTRIB2_4_NV                                        = 0x8672),
:(const INVERSE_NV                                                      = 0x862B),
:(const FLOAT_RG_NV                                                     = 0x8881),
:(const COMBINER_BIAS_NV                                                = 0x8549),
:(const DT_BIAS_NV                                                      = 0x8717),
:(const NUM_FILL_STREAMS_NV                                             = 0x8E29),
:(const BACK_SECONDARY_COLOR_NV                                         = 0x8C78),
:(const PATH_STROKE_WIDTH_NV                                            = 0x9075),
:(const UNSIGNED_INT16_VEC2_NV                                          = 0x8FF1),
:(const LO_BIAS_NV                                                      = 0x8715),
:(const UNSIGNED_INT8_NV                                                = 0x8FEC),
:(const VARIABLE_B_NV                                                   = 0x8524),
:(const Z6Y10Z6CB10Z6A10Z6Y10Z6CR10Z6A10_4224_NV                        = 0x9034),
:(const DEPTH_CLAMP_NV                                                  = 0x864F),
:(const MATRIX4_NV                                                      = 0x8634),
:(const MAX_SAMPLE_MASK_WORDS_NV                                        = 0x8E59),
:(const HILO16_NV                                                       = 0x86F8),
:(const PROGRAM_RESIDENT_NV                                             = 0x8647),
:(const RELATIVE_SMOOTH_QUADRATIC_CURVE_TO_NV                           = 0x0F),
:(const CONVEX_HULL_NV                                                  = 0x908B),
:(const USE_MISSING_GLYPH_NV                                            = 0x90AA),
:(const WRITE_PIXEL_DATA_RANGE_LENGTH_NV                                = 0x887A),
:(const MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS_NV                      = 0x8C8B),
:(const COMBINER_CD_DOT_PRODUCT_NV                                      = 0x8546),
:(const SIGNED_ALPHA_NV                                                 = 0x8705),
:(const GENERIC_ATTRIB_NV                                               = 0x8C7D),
:(const TEXTURE_RENDERBUFFER_NV                                         = 0x8E55),
:(const MIN_PROGRAM_TEXEL_OFFSET_NV                                     = 0x8904),
:(const FONT_MAX_ADVANCE_WIDTH_NV                                       = 0x01000000),
:(const CURRENT_ATTRIB_NV                                               = 0x8626),
:(const RELATIVE_LARGE_CW_ARC_TO_NV                                     = 0x19),
:(const MOVE_TO_RESETS_NV                                               = 0x90B5),
:(const UNSIGNED_INT64_VEC3_NV                                          = 0x8FF6),
:(const PATH_GEN_COLOR_FORMAT_NV                                        = 0x90B2),
:(const MAX_TEXTURE_IMAGE_UNITS_NV                                      = 0x8872),
:(const DOT_PRODUCT_TEXTURE_3D_NV                                       = 0x86EF),
:(const PATH_DASH_OFFSET_RESET_NV                                       = 0x90B4),
:(const VIDEO_COLOR_CONVERSION_MIN_NV                                   = 0x902B),
:(const UNSIGNED_INT_SAMPLER_RENDERBUFFER_NV                            = 0x8E58),
:(const RENDERBUFFER_COVERAGE_SAMPLES_NV                                = 0x8CAB),
:(const VERTEX_ARRAY_LENGTH_NV                                          = 0x8F2B),
:(const TRANSPOSE_PROJECTIVE_2D_NV                                      = 0x9097),
:(const TESS_CONTROL_PROGRAM_NV                                         = 0x891E),
:(const DISCARD_NV                                                      = 0x8530),
:(const RELATIVE_VERTICAL_LINE_TO_NV                                    = 0x09),
:(const COMBINER_MAPPING_NV                                             = 0x8543),
:(const QUERY_WAIT_NV                                                   = 0x8E13),
:(const TEXTURE_DT_SIZE_NV                                              = 0x871E),
:(const PATH_SAMPLE_QUALITY_NV                                          = 0x9085),
:(const CONSTANT_COLOR1_NV                                              = 0x852B),
:(const VIDEO_BUFFER_BINDING_NV                                         = 0x9021),
:(const MAX_VERTEX_TEXTURE_IMAGE_UNITS_ARB                              = 0x8B4C),
:(const UNSIGNED_INT16_VEC4_NV                                          = 0x8FF3),
:(const SIGNED_LUMINANCE8_ALPHA8_NV                                     = 0x8704),
:(const MAX_SPOT_EXPONENT_NV                                            = 0x8505),
:(const FONT_Y_MAX_BOUNDS_NV                                            = 0x00080000),
:(const ATTRIB_ARRAY_POINTER_NV                                         = 0x8645),
:(const FIRST_TO_REST_NV                                                = 0x90AF),
:(const EVAL_VERTEX_ATTRIB13_NV                                         = 0x86D3),
:(const MAP2_VERTEX_ATTRIB7_4_NV                                        = 0x8677),
:(const RELATIVE_LINE_TO_NV                                             = 0x05),
:(const INTERLEAVED_ATTRIBS_NV                                          = 0x8C8C)]
#function bodies
const GL_NV_FUNCTIONS = [
:(glVertexAttribL3i64NV(index::GLuint, x::GLint64EXT, y::GLint64EXT, z::GLint64EXT)::Void),
:(glPathCoverDepthFuncNV(func_::GLenum)::Void),
:(glProgramUniform1i64NV(program::GLuint, location::GLint, x::GLint64EXT)::Void),
:(glTransformFeedbackVaryingsNV(program::GLuint, count::GLsizei, locations::Ptr{GLint}, bufferMode::GLenum)::Void),
:(glProgramLocalParameterI4uivNV(target::GLenum, index::GLuint, params::Ptr{GLuint})::Void),
:(glVertexAttribI2ivEXT(index::GLuint, v::Ptr{GLint})::Void),
:(glPathDashArrayNV(path::GLuint, dashCount::GLsizei, dashArray::Ptr{GLfloat})::Void),
:(glUniformHandleui64vNV(location::GLint, count::GLsizei, value::Ptr{GLuint64})::Void),
:(glCoverFillPathInstancedNV(numPaths::GLsizei, pathNameType::GLenum, paths::Ptr{Void}, pathBase::GLuint, coverMode::GLenum, transformType::GLenum, transformValues::Ptr{GLfloat})::Void),
:(glMultiTexCoord2hNV(target::GLenum, s::GLhalfNV, t::GLhalfNV)::Void),
:(glVertex2hNV(x::GLhalfNV, y::GLhalfNV)::Void),
:(glDepthBoundsdNV(zmin::GLdouble, zmax::GLdouble)::Void),
:(glTexImage2DMultisampleCoverageNV(target::GLenum, coverageSamples::GLsizei, colorSamples::GLsizei, internalFormat::GLint, width::GLsizei, height::GLsizei, fixedSampleLocations::GLboolean)::Void),
:(glDeleteTransformFeedbacksNV(n::GLsizei, ids::Ptr{GLuint})::Void),
:(glColor3hNV(red::GLhalfNV, green::GLhalfNV, blue::GLhalfNV)::Void),
:(glPathStencilFuncNV(func_::GLenum, ref::GLint, mask::GLuint)::Void),
:(glGetTextureHandleNV(texture::GLuint)::CuClonglong),
:(glIsImageHandleResidentNV(handle::GLuClonglong)::Bool),
:(glIsBufferResidentNV(target::GLenum)::Bool),
:(glBindBufferOffsetNV(target::GLenum, index::GLuint, buffer::GLuint, offset::GLintptr)::Void),
:(glEndVideoCaptureNV(video_capture_slot::GLuint)::Void),
:(glVertexWeighthvNV(weight::Ptr{GLhalfNV})::Void),
:(glPathCoordsNV(path::GLuint, numCoords::GLsizei, coordType::GLenum, coords::Ptr{Void})::Void),
:(glPointAlongPathNV(path::GLuint, startSegment::GLsizei, numSegments::GLsizei, distance::GLfloat, x::Ptr{GLfloat}, y::Ptr{GLfloat}, tangentX::Ptr{GLfloat}, tangentY::Ptr{GLfloat})::Bool),
:(glEndConditionalRenderNV()::Void),
:(glStencilStrokePathNV(path::GLuint, reference::GLint, mask::GLuint)::Void),
:(glGetVideoi64vNV(video_slot::GLuint, pname::GLenum, params::Ptr{GLint64EXT})::Void),
:(glGetTrackMatrixivNV(target::GLenum, address::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttrib3dNV(index::GLuint, x::GLdouble, y::GLdouble, z::GLdouble)::Void),
:(glTextureImage3DMultisampleNV(texture::GLuint, target::GLenum, samples::GLsizei, internalFormat::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, fixedSampleLocations::GLboolean)::Void),
:(glVertexAttribs2svNV(index::GLuint, count::GLsizei, v::Ptr{GLshort})::Void),
:(glDrawTransformFeedbackNV(mode::GLenum, id::GLuint)::Void),
:(glBeginVideoCaptureNV(video_capture_slot::GLuint)::Void),
:(glPixelDataRangeNV(target::GLenum, length::GLsizei, pointer::Ptr{Void})::Void),
:(glTexCoord4hNV(s::GLhalfNV, t::GLhalfNV, r::GLhalfNV, q::GLhalfNV)::Void),
:(glGetPathTexGenfvNV(texCoordSet::GLenum, pname::GLenum, value::Ptr{GLfloat})::Void),
:(glVertexAttribs4svNV(index::GLuint, count::GLsizei, v::Ptr{GLshort})::Void),
:(glCoverStrokePathInstancedNV(numPaths::GLsizei, pathNameType::GLenum, paths::Ptr{Void}, pathBase::GLuint, coverMode::GLenum, transformType::GLenum, transformValues::Ptr{GLfloat})::Void),
:(glVertexAttribs4dvNV(index::GLuint, count::GLsizei, v::Ptr{GLdouble})::Void),
:(glVertexAttrib4ubNV(index::GLuint, x::GLubyte, y::GLubyte, z::GLubyte, w::GLubyte)::Void),
:(glTextureImage3DMultisampleCoverageNV(texture::GLuint, target::GLenum, coverageSamples::GLsizei, colorSamples::GLsizei, internalFormat::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, fixedSampleLocations::GLboolean)::Void),
:(glProgramEnvParametersI4uivNV(target::GLenum, index::GLuint, count::GLsizei, params::Ptr{GLuint})::Void),
:(glGetPathColorGenfvNV(color::GLenum, pname::GLenum, value::Ptr{GLfloat})::Void),
:(glVertexAttribL1i64vNV(index::GLuint, v::Ptr{GLint64EXT})::Void),
:(glVertexAttribI3uiEXT(index::GLuint, x::GLuint, y::GLuint, z::GLuint)::Void),
:(glGetPathDashArrayNV(path::GLuint, dashArray::Ptr{GLfloat})::Void),
:(glGetNamedBufferParameterui64vNV(buffer::GLuint, pname::GLenum, params::Ptr{GLuint64EXT})::Void),
:(glGetVertexAttribIuivEXT(index::GLuint, pname::GLenum, params::Ptr{GLuint})::Void),
:(glAreProgramsResidentNV(n::GLsizei, programs::Ptr{GLuint}, residences::Ptr{GLboolean})::Bool),
:(glEdgeFlagFormatNV(stride::GLsizei)::Void),
:(glVertexAttrib3sNV(index::GLuint, x::GLshort, y::GLshort, z::GLshort)::Void),
:(glSecondaryColor3hNV(red::GLhalfNV, green::GLhalfNV, blue::GLhalfNV)::Void),
:(glGetFinalCombinerInputParameterivNV(variable::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribs1hvNV(index::GLuint, n::GLsizei, v::Ptr{GLhalfNV})::Void),
:(glGetPathSpacingNV(pathListMode::GLenum, numPaths::GLsizei, pathNameType::GLenum, paths::Ptr{Void}, pathBase::GLuint, advanceScale::GLfloat, kerningScale::GLfloat, transformType::GLenum, returnedSpacing::Ptr{GLfloat})::Void),
:(glVertexAttribFormatNV(index::GLuint, size::GLint, type_::GLenum, normalized::GLboolean, stride::GLsizei)::Void),
:(glVertexAttrib1fNV(index::GLuint, x::GLfloat)::Void),
:(glGetProgramNamedParameterfvNV(id::GLuint, len::GLsizei, name::Ptr{GLubyte}, params::Ptr{GLfloat})::Void),
:(glProgramUniformHandleui64NV(program::GLuint, location::GLint, value::GLuint64)::Void),
:(glGenFencesNV(n::GLsizei, fences::Ptr{GLuint})::Void),
:(glVertexAttribs2hvNV(index::GLuint, n::GLsizei, v::Ptr{GLhalfNV})::Void),
:(glVertexAttrib1hvNV(index::GLuint, v::Ptr{GLhalfNV})::Void),
:(glGetCombinerStageParameterfvNV(stage::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glGetPathCoordsNV(path::GLuint, coords::Ptr{GLfloat})::Void),
:(glProgramUniform2ui64NV(program::GLuint, location::GLint, x::GLuint64EXT, y::GLuint64EXT)::Void),
:(glVertexAttribs4hvNV(index::GLuint, n::GLsizei, v::Ptr{GLhalfNV})::Void),
:(glVertexAttrib4ubvNV(index::GLuint, v::Ptr{GLubyte})::Void),
:(glUniform3ui64vNV(location::GLint, count::GLsizei, value::Ptr{GLuint64EXT})::Void),
:(glPathStringNV(path::GLuint, format::GLenum, length::GLsizei, pathString::Ptr{Void})::Void),
:(glFlushPixelDataRangeNV(target::GLenum)::Void),
:(glFogCoordFormatNV(type_::GLenum, stride::GLsizei)::Void),
:(glMakeTextureHandleNonResidentNV(handle::GLuint64)::Void),
:(glPathParameteriNV(path::GLuint, pname::GLenum, value::GLint)::Void),
:(glStencilFillPathNV(path::GLuint, fillMode::GLenum, mask::GLuint)::Void),
:(glVertexAttrib3fNV(index::GLuint, x::GLfloat, y::GLfloat, z::GLfloat)::Void),
:(glVertex4hvNV(v::Ptr{GLhalfNV})::Void),
:(glTexCoord3hNV(s::GLhalfNV, t::GLhalfNV, r::GLhalfNV)::Void),
:(glVertexAttribI3iEXT(index::GLuint, x::GLint, y::GLint, z::GLint)::Void),
:(glPresentFrameKeyedNV(video_slot::GLuint, minPresentTime::GLuint64EXT, beginPresentTimeId::GLuint, presentDurationId::GLuint, type_::GLenum, target0::GLenum, fill0::GLuint, key0::GLuint, target1::GLenum, fill1::GLuint, key1::GLuint)::Void),
:(glPauseTransformFeedbackNV()::Void),
:(glColor4hvNV(v::Ptr{GLhalfNV})::Void),
:(glVertex3hNV(x::GLhalfNV, y::GLhalfNV, z::GLhalfNV)::Void),
:(glGetVideoui64vNV(video_slot::GLuint, pname::GLenum, params::Ptr{GLuint64EXT})::Void),
:(glProgramUniform4ui64NV(program::GLuint, location::GLint, x::GLuint64EXT, y::GLuint64EXT, z::GLuint64EXT, w::GLuint64EXT)::Void),
:(glVertexAttribI3uivEXT(index::GLuint, v::Ptr{GLuint})::Void),
:(glVertexWeighthNV(weight::GLhalfNV)::Void),
:(glVertexAttrib1fvNV(index::GLuint, v::Ptr{GLfloat})::Void),
:(glMapControlPointsNV(target::GLenum, index::GLuint, type_::GLenum, ustride::GLsizei, vstride::GLsizei, uorder::GLint, vorder::GLint, packed::GLboolean, points::Ptr{Void})::Void),
:(glGetCombinerInputParameterivNV(stage::GLenum, portion::GLenum, variable::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetPathMetricRangeNV(metricQueryMask::GLbitfield, firstPathName::GLuint, numPaths::GLsizei, stride::GLsizei, metrics::Ptr{GLfloat})::Void),
:(glPathParameterfvNV(path::GLuint, pname::GLenum, value::Ptr{GLfloat})::Void),
:(glGetPathMetricsNV(metricQueryMask::GLbitfield, numPaths::GLsizei, pathNameType::GLenum, paths::Ptr{Void}, pathBase::GLuint, stride::GLsizei, metrics::Ptr{GLfloat})::Void),
:(glVideoCaptureNV(video_capture_slot::GLuint, sequence_num::Ptr{GLuint}, capture_time::Ptr{GLuClonglongEXT})::Cint),
:(glGetMapAttribParameterfvNV(target::GLenum, index::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glVertexAttribL3ui64vNV(index::GLuint, v::Ptr{GLuint64EXT})::Void),
:(glTexCoordFormatNV(size::GLint, type_::GLenum, stride::GLsizei)::Void),
:(glStencilStrokePathInstancedNV(numPaths::GLsizei, pathNameType::GLenum, paths::Ptr{Void}, pathBase::GLuint, reference::GLint, mask::GLuint, transformType::GLenum, transformValues::Ptr{GLfloat})::Void),
:(glDeletePathsNV(path::GLuint, range_::GLsizei)::Void),
:(glBindTransformFeedbackNV(target::GLenum, id::GLuint)::Void),
:(glIsFenceNV(fence::GLuint)::Bool),
:(glBindBufferRangeNV(target::GLenum, index::GLuint, buffer::GLuint, offset::GLintptr, size::GLsizeiptr)::Void),
:(glVDPAUUnmapSurfacesNV(numSurface::GLsizei, surfaces::Ptr{GLvdpauSurfaceNV})::Void),
:(glVertex2hvNV(v::Ptr{GLhalfNV})::Void),
:(glVertexAttribI1uiEXT(index::GLuint, x::GLuint)::Void),
:(glBindBufferBaseNV(target::GLenum, index::GLuint, buffer::GLuint)::Void),
:(glProgramParameter4fvNV(target::GLenum, index::GLuint, v::Ptr{GLfloat})::Void),
:(glGetProgramEnvParameterIuivNV(target::GLenum, index::GLuint, params::Ptr{GLuint})::Void),
:(glGetTextureSamplerHandleNV(texture::GLuint, sampler::GLuint)::CuClonglong),
:(glVertexAttrib1hNV(index::GLuint, x::GLhalfNV)::Void),
:(glVertexArrayRangeNV(length::GLsizei, pointer::Ptr{Void})::Void),
:(glProgramEnvParameterI4iNV(target::GLenum, index::GLuint, x::GLint, y::GLint, z::GLint, w::GLint)::Void),
:(glGetMapAttribParameterivNV(target::GLenum, index::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glPointParameteriNV(pname::GLenum, param::GLint)::Void),
:(glIsPathNV(path::GLuint)::Bool),
:(glUniform4i64vNV(location::GLint, count::GLsizei, value::Ptr{GLint64EXT})::Void),
:(glGetImageHandleNV(texture::GLuint, level::GLint, layered::GLboolean, layer::GLint, format::GLenum)::CuClonglong),
:(glVertexAttrib2svNV(index::GLuint, v::Ptr{GLshort})::Void),
:(glVertexAttrib1dvNV(index::GLuint, v::Ptr{GLdouble})::Void),
:(glVideoCaptureStreamParameterfvNV(video_capture_slot::GLuint, stream::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glGetMapParameterivNV(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribs3hvNV(index::GLuint, n::GLsizei, v::Ptr{GLhalfNV})::Void),
:(glGetActiveVaryingNV(program::GLuint, index::GLuint, bufSize::GLsizei, length::Ptr{GLsizei}, size::Ptr{GLsizei}, type_::Ptr{GLenum}, name::Ptr{GLchar})::Void),
:(glWeightPathsNV(resultPath::GLuint, numPaths::GLsizei, paths::Ptr{GLuint}, weights::Ptr{GLfloat})::Void),
:(glVDPAUMapSurfacesNV(numSurfaces::GLsizei, surfaces::Ptr{GLvdpauSurfaceNV})::Void),
:(glGetFenceivNV(fence::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glUniform3i64NV(location::GLint, x::GLint64EXT, y::GLint64EXT, z::GLint64EXT)::Void),
:(glGetPathParameterfvNV(path::GLuint, pname::GLenum, value::Ptr{GLfloat})::Void),
:(glGenProgramsNV(n::GLsizei, programs::Ptr{GLuint})::Void),
:(glCombinerParameterfvNV(pname::GLenum, params::Ptr{GLfloat})::Void),
:(glGetProgramLocalParameterIuivNV(target::GLenum, index::GLuint, params::Ptr{GLuint})::Void),
:(glTestFenceNV(fence::GLuint)::Bool),
:(glGetProgramEnvParameterIivNV(target::GLenum, index::GLuint, params::Ptr{GLint})::Void),
:(glGetMapControlPointsNV(target::GLenum, index::GLuint, type_::GLenum, ustride::GLsizei, vstride::GLsizei, packed::GLboolean, points::Ptr{Void})::Void),
:(glGetMapParameterfvNV(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glStencilFillPathInstancedNV(numPaths::GLsizei, pathNameType::GLenum, paths::Ptr{Void}, pathBase::GLuint, fillMode::GLenum, mask::GLuint, transformType::GLenum, transformValues::Ptr{GLfloat})::Void),
:(glVertexAttribLFormatNV(index::GLuint, size::GLint, type_::GLenum, stride::GLsizei)::Void),
:(glProgramParameters4fvNV(target::GLenum, index::GLuint, count::GLsizei, v::Ptr{GLfloat})::Void),
:(glVideoCaptureStreamParameterdvNV(video_capture_slot::GLuint, stream::GLuint, pname::GLenum, params::Ptr{GLdouble})::Void),
:(glTexCoord4hvNV(v::Ptr{GLhalfNV})::Void),
:(glVertex4hNV(x::GLhalfNV, y::GLhalfNV, z::GLhalfNV, w::GLhalfNV)::Void),
:(glVertexAttribI4usvEXT(index::GLuint, v::Ptr{GLushort})::Void),
:(glTexCoord3hvNV(v::Ptr{GLhalfNV})::Void),
:(glMultiTexCoord3hNV(target::GLenum, s::GLhalfNV, t::GLhalfNV, r::GLhalfNV)::Void),
:(glProgramEnvParameterI4uivNV(target::GLenum, index::GLuint, params::Ptr{GLuint})::Void),
:(glTexCoord2hvNV(v::Ptr{GLhalfNV})::Void),
:(glMultiTexCoord4hvNV(target::GLenum, v::Ptr{GLhalfNV})::Void),
:(glVertexAttrib4dNV(index::GLuint, x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glGetVertexAttribivNV(index::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribs3svNV(index::GLuint, count::GLsizei, v::Ptr{GLshort})::Void),
:(glActiveVaryingNV(program::GLuint, name::Ptr{GLchar})::Void),
:(glVertexAttrib2fNV(index::GLuint, x::GLfloat, y::GLfloat)::Void),
:(glFramebufferTextureEXT(target::GLenum, attachment::GLenum, texture::GLuint, level::GLint)::Void),
:(glVertexAttrib2hvNV(index::GLuint, v::Ptr{GLhalfNV})::Void),
:(glCombinerParameterivNV(pname::GLenum, params::Ptr{GLint})::Void),
:(glProgramBufferParametersfvNV(target::GLenum, buffer::GLuint, index::GLuint, count::GLsizei, params::Ptr{GLfloat})::Void),
:(glVertexAttrib1svNV(index::GLuint, v::Ptr{GLshort})::Void),
:(glVertexAttrib3dvNV(index::GLuint, v::Ptr{GLdouble})::Void),
:(glVertexAttribIPointerEXT(index::GLuint, size::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glVertexAttribs1dvNV(index::GLuint, count::GLsizei, v::Ptr{GLdouble})::Void),
:(glProgramNamedParameter4fNV(id::GLuint, len::GLsizei, name::Ptr{GLubyte}, x::GLfloat, y::GLfloat, z::GLfloat, w::GLfloat)::Void),
:(glProgramParameters4dvNV(target::GLenum, index::GLuint, count::GLsizei, v::Ptr{GLdouble})::Void),
:(glVertexAttrib3svNV(index::GLuint, v::Ptr{GLshort})::Void),
:(glPathFogGenNV(genMode::GLenum)::Void),
:(glEndTransformFeedbackNV()::Void),
:(glGetProgramStringNV(id::GLuint, pname::GLenum, program::Ptr{GLubyte})::Void),
:(glEndOcclusionQueryNV()::Void),
:(glNormalFormatNV(type_::GLenum, stride::GLsizei)::Void),
:(glProgramNamedParameter4fvNV(id::GLuint, len::GLsizei, name::Ptr{GLubyte}, v::Ptr{GLfloat})::Void),
:(glTransformFeedbackAttribsNV(count::GLsizei, attribs::Ptr{GLint}, bufferMode::GLenum)::Void),
:(glVertexAttribL3i64vNV(index::GLuint, v::Ptr{GLint64EXT})::Void),
:(glDeleteProgramsNV(n::GLsizei, programs::Ptr{GLuint})::Void),
:(glGetUniformi64vNV(program::GLuint, location::GLint, params::Ptr{GLint64EXT})::Void),
:(glGenTransformFeedbacksNV(n::GLsizei, ids::Ptr{GLuint})::Void),
:(glNormal3hvNV(v::Ptr{GLhalfNV})::Void),
:(glVertexAttrib3hvNV(index::GLuint, v::Ptr{GLhalfNV})::Void),
:(glPathGlyphRangeNV(firstPathName::GLuint, fontTarget::GLenum, fontName::Ptr{Void}, fontStyle::GLbitfield, firstGlyph::GLuint, numGlyphs::GLsizei, handleMissingGlyphs::GLenum, pathParameterTemplate::GLuint, emScale::GLfloat)::Void),
:(glVertexAttribL1ui64vNV(index::GLuint, v::Ptr{GLuint64EXT})::Void),
:(glUniform2i64NV(location::GLint, x::GLint64EXT, y::GLint64EXT)::Void),
:(glTexCoord1hNV(s::GLhalfNV)::Void),
:(glGenOcclusionQueriesNV(n::GLsizei, ids::Ptr{GLuint})::Void),
:(glGetMultisamplefvNV(pname::GLenum, index::GLuint, val::Ptr{GLfloat})::Void),
:(glCombinerStageParameterfvNV(stage::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glPathSubCommandsNV(path::GLuint, commandStart::GLsizei, commandsToDelete::GLsizei, numCommands::GLsizei, commands::Ptr{GLubyte}, numCoords::GLsizei, coordType::GLenum, coords::Ptr{Void})::Void),
:(glGetOcclusionQueryivNV(id::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glUniformui64vNV(location::GLint, count::GLsizei, value::Ptr{GLuint64EXT})::Void),
:(glVertexAttribI4ivEXT(index::GLuint, v::Ptr{GLint})::Void),
:(glUniform2ui64vNV(location::GLint, count::GLsizei, value::Ptr{GLuint64EXT})::Void),
:(glVDPAUSurfaceAccessNV(surface::GLvdpauSurfaceNV, access::GLenum)::Void),
:(glUniform3i64vNV(location::GLint, count::GLsizei, value::Ptr{GLint64EXT})::Void),
:(glVertexAttribL2ui64vNV(index::GLuint, v::Ptr{GLuint64EXT})::Void),
:(glProgramUniformui64vNV(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint64EXT})::Void),
:(glGetVideoivNV(video_slot::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glProgramEnvParameterI4uiNV(target::GLenum, index::GLuint, x::GLuint, y::GLuint, z::GLuint, w::GLuint)::Void),
:(glColor3hvNV(v::Ptr{GLhalfNV})::Void),
:(glUniform1ui64vNV(location::GLint, count::GLsizei, value::Ptr{GLuint64EXT})::Void),
:(glPathGlyphsNV(firstPathName::GLuint, fontTarget::GLenum, fontName::Ptr{Void}, fontStyle::GLbitfield, numGlyphs::GLsizei, type_::GLenum, charcodes::Ptr{Void}, handleMissingGlyphs::GLenum, pathParameterTemplate::GLuint, emScale::GLfloat)::Void),
:(glGetProgramSubroutineParameteruivNV(target::GLenum, index::GLuint, param::Ptr{GLuint})::Void),
:(glVDPAUFiniNV()::Void),
:(glCombinerParameterfNV(pname::GLenum, param::GLfloat)::Void),
:(glMakeImageHandleNonResidentNV(handle::GLuint64)::Void),
:(glClearDepthdNV(depth::GLdouble)::Void),
:(glProgramUniformui64NV(program::GLuint, location::GLint, value::GLuint64EXT)::Void),
:(glInterpolatePathsNV(resultPath::GLuint, pathA::GLuint, pathB::GLuint, weight::GLfloat)::Void),
:(glBufferAddressRangeNV(pname::GLenum, index::GLuint, address::GLuint64EXT, length::GLsizeiptr)::Void),
:(glGetCombinerInputParameterfvNV(stage::GLenum, portion::GLenum, variable::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glIndexFormatNV(type_::GLenum, stride::GLsizei)::Void),
:(glUniform1i64vNV(location::GLint, count::GLsizei, value::Ptr{GLint64EXT})::Void),
:(glBindVideoCaptureStreamBufferNV(video_capture_slot::GLuint, stream::GLuint, frame_region::GLenum, offset::GLintptrARB)::Void),
:(glPathColorGenNV(color::GLenum, genMode::GLenum, colorFormat::GLenum, coeffs::Ptr{GLfloat})::Void),
:(glProgramBufferParametersIivNV(target::GLenum, buffer::GLuint, index::GLuint, count::GLsizei, params::Ptr{GLint})::Void),
:(glGetPathCommandsNV(path::GLuint, commands::Ptr{GLubyte})::Void),
:(glBeginTransformFeedbackNV(primitiveMode::GLenum)::Void),
:(glVertexAttrib4sNV(index::GLuint, x::GLshort, y::GLshort, z::GLshort, w::GLshort)::Void),
:(glVDPAUGetSurfaceivNV(surface::GLvdpauSurfaceNV, pname::GLenum, bufSize::GLsizei, length::Ptr{GLsizei}, values::Ptr{GLint})::Void),
:(glFramebufferTextureFaceEXT(target::GLenum, attachment::GLenum, texture::GLuint, level::GLint, face::GLenum)::Void),
:(glVertexAttribI2uivEXT(index::GLuint, v::Ptr{GLuint})::Void),
:(glRequestResidentProgramsNV(n::GLsizei, programs::Ptr{GLuint})::Void),
:(glGenPathsNV(range_::GLsizei)::Cuint),
:(glIsPointInFillPathNV(path::GLuint, mask::GLuint, x::GLfloat, y::GLfloat)::Bool),
:(glPrimitiveRestartNV()::Void),
:(glTrackMatrixNV(target::GLenum, address::GLuint, matrix::GLenum, transform::GLenum)::Void),
:(glFramebufferTextureLayerEXT(target::GLenum, attachment::GLenum, texture::GLuint, level::GLint, layer::GLint)::Void),
:(glEvalMapsNV(target::GLenum, mode::GLenum)::Void),
:(glPathTexGenNV(texCoordSet::GLenum, genMode::GLenum, components::GLint, coeffs::Ptr{GLfloat})::Void),
:(glVertexAttribL4i64vNV(index::GLuint, v::Ptr{GLint64EXT})::Void),
:(glVertexAttribI4bvEXT(index::GLuint, v::Ptr{GLbyte})::Void),
:(glProgramVertexLimitNV(target::GLenum, limit::GLint)::Void),
:(glVertexAttribI2iEXT(index::GLuint, x::GLint, y::GLint)::Void),
:(glMakeImageHandleResidentNV(handle::GLuint64, access::GLenum)::Void),
:(glGetVideoCaptureivNV(video_capture_slot::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glProgramLocalParametersI4ivNV(target::GLenum, index::GLuint, count::GLsizei, params::Ptr{GLint})::Void),
:(glFinishFenceNV(fence::GLuint)::Void),
:(glProgramLocalParameterI4uiNV(target::GLenum, index::GLuint, x::GLuint, y::GLuint, z::GLuint, w::GLuint)::Void),
:(glProgramUniformHandleui64vNV(program::GLuint, location::GLint, count::GLsizei, values::Ptr{GLuint64})::Void),
:(glPathParameterivNV(path::GLuint, pname::GLenum, value::Ptr{GLint})::Void),
:(glMultiTexCoord4hNV(target::GLenum, s::GLhalfNV, t::GLhalfNV, r::GLhalfNV, q::GLhalfNV)::Void),
:(glVDPAUUnregisterSurfaceNV(surface::GLvdpauSurfaceNV)::Void),
:(glGetProgramivNV(id::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribs2fvNV(index::GLuint, count::GLsizei, v::Ptr{GLfloat})::Void),
:(glProgramUniform1i64vNV(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint64EXT})::Void),
:(glGetVideoCaptureStreamfvNV(video_capture_slot::GLuint, stream::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glVertexAttrib4fvNV(index::GLuint, v::Ptr{GLfloat})::Void),
:(glVertexAttrib4fNV(index::GLuint, x::GLfloat, y::GLfloat, z::GLfloat, w::GLfloat)::Void),
:(glProgramUniform3ui64vNV(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint64EXT})::Void),
:(glPathParameterfNV(path::GLuint, pname::GLenum, value::GLfloat)::Void),
:(glMakeBufferResidentNV(target::GLenum, access::GLenum)::Void),
:(glTextureImage2DMultisampleCoverageNV(texture::GLuint, target::GLenum, coverageSamples::GLsizei, colorSamples::GLsizei, internalFormat::GLint, width::GLsizei, height::GLsizei, fixedSampleLocations::GLboolean)::Void),
:(glCoverStrokePathNV(path::GLuint, coverMode::GLenum)::Void),
:(glColor4hNV(red::GLhalfNV, green::GLhalfNV, blue::GLhalfNV, alpha::GLhalfNV)::Void),
:(glGetVaryingLocationNV(program::GLuint, name::Ptr{GLchar})::Cint),
:(glVertexAttrib1sNV(index::GLuint, x::GLshort)::Void),
:(glSetFenceNV(fence::GLuint, condition::GLenum)::Void),
:(glGetPathParameterivNV(path::GLuint, pname::GLenum, value::Ptr{GLint})::Void),
:(glProgramParameter4fNV(target::GLenum, index::GLuint, x::GLfloat, y::GLfloat, z::GLfloat, w::GLfloat)::Void),
:(glIsPointInStrokePathNV(path::GLuint, x::GLfloat, y::GLfloat)::Bool),
:(glTexCoord2hNV(s::GLhalfNV, t::GLhalfNV)::Void),
:(glTexCoord1hvNV(v::Ptr{GLhalfNV})::Void),
:(glVertexAttribL4ui64NV(index::GLuint, x::GLuint64EXT, y::GLuint64EXT, z::GLuint64EXT, w::GLuint64EXT)::Void),
:(glVertexFormatNV(size::GLint, type_::GLenum, stride::GLsizei)::Void),
:(glCopyImageSubDataNV(srcName::GLuint, srcTarget::GLenum, srcLevel::GLint, srcX::GLint, srcY::GLint, srcZ::GLint, dstName::GLuint, dstTarget::GLenum, dstLevel::GLint, dstX::GLint, dstY::GLint, dstZ::GLint, width::GLsizei, height::GLsizei, depth::GLsizei)::Void),
:(glProgramSubroutineParametersuivNV(target::GLenum, count::GLsizei, params::Ptr{GLuint})::Void),
:(glColorFormatNV(size::GLint, type_::GLenum, stride::GLsizei)::Void),
:(glProgramLocalParameterI4iNV(target::GLenum, index::GLuint, x::GLint, y::GLint, z::GLint, w::GLint)::Void),
:(glVertexAttribL2i64vNV(index::GLuint, v::Ptr{GLint64EXT})::Void),
:(glUniform4i64NV(location::GLint, x::GLint64EXT, y::GLint64EXT, z::GLint64EXT, w::GLint64EXT)::Void),
:(glProgramUniform3ui64NV(program::GLuint, location::GLint, x::GLuint64EXT, y::GLuint64EXT, z::GLuint64EXT)::Void),
:(glProgramUniform3i64NV(program::GLuint, location::GLint, x::GLint64EXT, y::GLint64EXT, z::GLint64EXT)::Void),
:(glSecondaryColor3hvNV(v::Ptr{GLhalfNV})::Void),
:(glProgramBufferParametersIuivNV(target::GLenum, buffer::GLuint, index::GLuint, count::GLsizei, params::Ptr{GLuint})::Void),
:(glVertexAttribL4ui64vNV(index::GLuint, v::Ptr{GLuint64EXT})::Void),
:(glIsNamedBufferResidentNV(buffer::GLuint)::Bool),
:(glProgramUniform2i64vNV(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint64EXT})::Void),
:(glVertexAttrib2dNV(index::GLuint, x::GLdouble, y::GLdouble)::Void),
:(glVertexAttrib3fvNV(index::GLuint, v::Ptr{GLfloat})::Void),
:(glVertexAttrib4hNV(index::GLuint, x::GLhalfNV, y::GLhalfNV, z::GLhalfNV, w::GLhalfNV)::Void),
:(glRenderbufferStorageMultisampleCoverageNV(target::GLenum, coverageSamples::GLsizei, colorSamples::GLsizei, internalformat::GLenum, width::GLsizei, height::GLsizei)::Void),
:(glGetUniformui64vNV(program::GLuint, location::GLint, params::Ptr{GLuint64EXT})::Void),
:(glGetVertexAttribLi64vNV(index::GLuint, pname::GLenum, params::Ptr{GLint64EXT})::Void),
:(glDepthRangedNV(zNear::GLdouble, zFar::GLdouble)::Void),
:(glProgramParameter4dNV(target::GLenum, index::GLuint, x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glGetVideoCaptureStreamdvNV(video_capture_slot::GLuint, stream::GLuint, pname::GLenum, params::Ptr{GLdouble})::Void),
:(glVertexAttribL1i64NV(index::GLuint, x::GLint64EXT)::Void),
:(glCoverFillPathNV(path::GLuint, coverMode::GLenum)::Void),
:(glVertexAttribI4iEXT(index::GLuint, x::GLint, y::GLint, z::GLint, w::GLint)::Void),
:(glPointParameterivNV(pname::GLenum, params::Ptr{GLint})::Void),
:(glMultiTexCoord2hvNV(target::GLenum, v::Ptr{GLhalfNV})::Void),
:(glMakeNamedBufferNonResidentNV(buffer::GLuint)::Void),
:(glVertexAttrib4svNV(index::GLuint, v::Ptr{GLshort})::Void),
:(glUniform1ui64NV(location::GLint, x::GLuint64EXT)::Void),
:(glMakeNamedBufferResidentNV(buffer::GLuint, access::GLenum)::Void),
:(glGetCombinerOutputParameterivNV(stage::GLenum, portion::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribs4ubvNV(index::GLuint, count::GLsizei, v::Ptr{GLubyte})::Void),
:(glFogCoordhNV(fog::GLhalfNV)::Void),
:(glVertexAttribs4fvNV(index::GLuint, count::GLsizei, v::Ptr{GLfloat})::Void),
:(glTextureBarrierNV()::Void),
:(glPresentFrameDualFillNV(video_slot::GLuint, minPresentTime::GLuint64EXT, beginPresentTimeId::GLuint, presentDurationId::GLuint, type_::GLenum, target0::GLenum, fill0::GLuint, target1::GLenum, fill1::GLuint, target2::GLenum, fill2::GLuint, target3::GLenum, fill3::GLuint)::Void),
:(glPrimitiveRestartIndexNV(index::GLuint)::Void),
:(glGetVertexAttribdvNV(index::GLuint, pname::GLenum, params::Ptr{GLdouble})::Void),
:(glNormal3hNV(nx::GLhalfNV, ny::GLhalfNV, nz::GLhalfNV)::Void),
:(glGetProgramLocalParameterIivNV(target::GLenum, index::GLuint, params::Ptr{GLint})::Void),
:(glGetProgramParameterfvNV(target::GLenum, index::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glGetIntegerui64vNV(value::GLenum, result::Ptr{GLuint64EXT})::Void),
:(glBindVideoCaptureStreamTextureNV(video_capture_slot::GLuint, stream::GLuint, frame_region::GLenum, target::GLenum, texture::GLuint)::Void),
:(glTextureImage2DMultisampleNV(texture::GLuint, target::GLenum, samples::GLsizei, internalFormat::GLint, width::GLsizei, height::GLsizei, fixedSampleLocations::GLboolean)::Void),
:(glUniformHandleui64NV(location::GLint, value::GLuint64)::Void),
:(glIsTextureHandleResidentNV(handle::GLuClonglong)::Bool),
:(glTransformFeedbackStreamAttribsNV(count::GLsizei, attribs::Ptr{GLint}, nbuffers::GLsizei, bufstreams::Ptr{GLint}, bufferMode::GLenum)::Void),
:(glMultiTexCoord3hvNV(target::GLenum, v::Ptr{GLhalfNV})::Void),
:(glVertexAttrib2hNV(index::GLuint, x::GLhalfNV, y::GLhalfNV)::Void),
:(glGetBufferParameterui64vNV(target::GLenum, pname::GLenum, params::Ptr{GLuint64EXT})::Void),
:(glVertexAttrib4hvNV(index::GLuint, v::Ptr{GLhalfNV})::Void),
:(glMultiTexCoord1hvNV(target::GLenum, v::Ptr{GLhalfNV})::Void),
:(glGetCombinerOutputParameterfvNV(stage::GLenum, portion::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glUniform2ui64NV(location::GLint, x::GLuint64EXT, y::GLuint64EXT)::Void),
:(glVertex3hvNV(v::Ptr{GLhalfNV})::Void),
:(glGetFinalCombinerInputParameterfvNV(variable::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glLoadProgramNV(target::GLenum, id::GLuint, len::GLsizei, program::Ptr{GLubyte})::Void),
:(glGetPathColorGenivNV(color::GLenum, pname::GLenum, value::Ptr{GLint})::Void),
:(glTexRenderbufferNV(target::GLenum, renderbuffer::GLuint)::Void),
:(glProgramUniform3i64vNV(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint64EXT})::Void),
:(glMakeBufferNonResidentNV(target::GLenum)::Void),
:(glVertexAttribL4i64NV(index::GLuint, x::GLint64EXT, y::GLint64EXT, z::GLint64EXT, w::GLint64EXT)::Void),
:(glVertexAttribI3ivEXT(index::GLuint, v::Ptr{GLint})::Void),
:(glProgramEnvParameterI4ivNV(target::GLenum, index::GLuint, params::Ptr{GLint})::Void),
:(glVertexAttrib2sNV(index::GLuint, x::GLshort, y::GLshort)::Void),
:(glGetTransformFeedbackVaryingNV(program::GLuint, index::GLuint, location::Ptr{GLint})::Void),
:(glPathStencilDepthOffsetNV(factor::GLfloat, units::GLfloat)::Void),
:(glVertexAttribI1iEXT(index::GLuint, x::GLint)::Void),
:(glVertexAttribL2ui64NV(index::GLuint, x::GLuint64EXT, y::GLuint64EXT)::Void),
:(glVertexAttribs3dvNV(index::GLuint, count::GLsizei, v::Ptr{GLdouble})::Void),
:(glVertexAttribI1uivEXT(index::GLuint, v::Ptr{GLuint})::Void),
:(glIsTransformFeedbackNV(id::GLuint)::Bool),
:(glVertexAttribs1svNV(index::GLuint, count::GLsizei, v::Ptr{GLshort})::Void),
:(glSecondaryColorFormatNV(size::GLint, type_::GLenum, stride::GLsizei)::Void),
:(glFinalCombinerInputNV(variable::GLenum, input::GLenum, mapping::GLenum, componentUsage::GLenum)::Void),
:(glUniform3ui64NV(location::GLint, x::GLuint64EXT, y::GLuint64EXT, z::GLuint64EXT)::Void),
:(glGetIntegerui64i_vNV(value::GLenum, index::GLuint, result::Ptr{GLuint64EXT})::Void),
:(glGetVertexAttribfvNV(index::GLuint, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glUniform2i64vNV(location::GLint, count::GLsizei, value::Ptr{GLint64EXT})::Void),
:(glProgramUniform4i64NV(program::GLuint, location::GLint, x::GLint64EXT, y::GLint64EXT, z::GLint64EXT, w::GLint64EXT)::Void),
:(glFogCoordhvNV(fog::Ptr{GLhalfNV})::Void),
:(glDeleteOcclusionQueriesNV(n::GLsizei, ids::Ptr{GLuint})::Void),
:(glIsProgramNV(id::GLuint)::Bool),
:(glVertexAttribPointerNV(index::GLuint, fsize::GLint, type_::GLenum, stride::GLsizei, pointer::Ptr{Void})::Void),
:(glGetVertexAttribPointervNV(index::GLuint, pname::GLenum, pointer::Ptr{Ptr{Void}})::Void),
:(glVertexAttribI1ivEXT(index::GLuint, v::Ptr{GLint})::Void),
:(glGetVertexAttribIivEXT(index::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glGetVideoCaptureStreamivNV(video_capture_slot::GLuint, stream::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glVertexAttribs2dvNV(index::GLuint, count::GLsizei, v::Ptr{GLdouble})::Void),
:(glProgramLocalParameterI4ivNV(target::GLenum, index::GLuint, params::Ptr{GLint})::Void),
:(glProgramEnvParametersI4ivNV(target::GLenum, index::GLuint, count::GLsizei, params::Ptr{GLint})::Void),
:(glVideoCaptureStreamParameterivNV(video_capture_slot::GLuint, stream::GLuint, pname::GLenum, params::Ptr{GLint})::Void),
:(glMapParameterfvNV(target::GLenum, pname::GLenum, params::Ptr{GLfloat})::Void),
:(glCombinerParameteriNV(pname::GLenum, param::GLint)::Void),
:(glExecuteProgramNV(target::GLenum, id::GLuint, params::Ptr{GLfloat})::Void),
:(glGetPathTexGenivNV(texCoordSet::GLenum, pname::GLenum, value::Ptr{GLint})::Void),
:(glVertexAttribI4ubvEXT(index::GLuint, v::Ptr{GLubyte})::Void),
:(glVDPAUInitNV(vdpDevice::Ptr{Void}, getProcAddress::Ptr{Void})::Void),
:(glVertexAttribI4uivEXT(index::GLuint, v::Ptr{GLuint})::Void),
:(glVertexAttrib4dvNV(index::GLuint, v::Ptr{GLdouble})::Void),
:(glFlushVertexArrayRangeNV()::Void),
:(glVertexAttribI4svEXT(index::GLuint, v::Ptr{GLshort})::Void),
:(glPathSubCoordsNV(path::GLuint, coordStart::GLsizei, numCoords::GLsizei, coordType::GLenum, coords::Ptr{Void})::Void),
:(glVertexAttribL1ui64NV(index::GLuint, x::GLuint64EXT)::Void),
:(glCopyPathNV(resultPath::GLuint, srcPath::GLuint)::Void),
:(glGetPathLengthNV(path::GLuint, startSegment::GLsizei, numSegments::GLsizei)::Float),
:(glBeginOcclusionQueryNV(id::GLuint)::Void),
:(glGetOcclusionQueryuivNV(id::GLuint, pname::GLenum, params::Ptr{GLuint})::Void),
:(glVertexAttrib2dvNV(index::GLuint, v::Ptr{GLdouble})::Void),
:(glProgramUniform1ui64vNV(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint64EXT})::Void),
:(glMapParameterivNV(target::GLenum, pname::GLenum, params::Ptr{GLint})::Void),
:(glProgramNamedParameter4dvNV(id::GLuint, len::GLsizei, name::Ptr{GLubyte}, v::Ptr{GLdouble})::Void),
:(glBindProgramNV(target::GLenum, id::GLuint)::Void),
:(glVertexAttribs1fvNV(index::GLuint, count::GLsizei, v::Ptr{GLfloat})::Void),
:(glTexImage3DMultisampleCoverageNV(target::GLenum, coverageSamples::GLsizei, colorSamples::GLsizei, internalFormat::GLint, width::GLsizei, height::GLsizei, depth::GLsizei, fixedSampleLocations::GLboolean)::Void),
:(glDeleteFencesNV(n::GLsizei, fences::Ptr{GLuint})::Void),
:(glVertexAttribL3ui64NV(index::GLuint, x::GLuint64EXT, y::GLuint64EXT, z::GLuint64EXT)::Void),
:(glProgramParameter4dvNV(target::GLenum, index::GLuint, v::Ptr{GLdouble})::Void),
:(glGetVertexAttribLui64vNV(index::GLuint, pname::GLenum, params::Ptr{GLuint64EXT})::Void),
:(glTransformPathNV(resultPath::GLuint, srcPath::GLuint, transformType::GLenum, transformValues::Ptr{GLfloat})::Void),
:(glCombinerInputNV(stage::GLenum, portion::GLenum, variable::GLenum, input::GLenum, mapping::GLenum, componentUsage::GLenum)::Void),
:(glMultiTexCoord1hNV(target::GLenum, s::GLhalfNV)::Void),
:(glVertexAttribI4uiEXT(index::GLuint, x::GLuint, y::GLuint, z::GLuint, w::GLuint)::Void),
:(glProgramLocalParametersI4uivNV(target::GLenum, index::GLuint, count::GLsizei, params::Ptr{GLuint})::Void),
:(glUniform4ui64vNV(location::GLint, count::GLsizei, value::Ptr{GLuint64EXT})::Void),
:(glProgramUniform4i64vNV(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLint64EXT})::Void),
:(glVertexAttribIFormatNV(index::GLuint, size::GLint, type_::GLenum, stride::GLsizei)::Void),
:(glIsOcclusionQueryNV(id::GLuint)::Bool),
:(glCombinerOutputNV(stage::GLenum, portion::GLenum, abOutput::GLenum, cdOutput::GLenum, sumOutput::GLenum, scale::GLenum, bias::GLenum, abDotProduct::GLboolean, cdDotProduct::GLboolean, muxSum::GLboolean)::Void),
:(glVertexAttrib2fvNV(index::GLuint, v::Ptr{GLfloat})::Void),
:(glVertexAttribs3fvNV(index::GLuint, count::GLsizei, v::Ptr{GLfloat})::Void),
:(glMakeTextureHandleResidentNV(handle::GLuint64)::Void),
:(glProgramUniform2i64NV(program::GLuint, location::GLint, x::GLint64EXT, y::GLint64EXT)::Void),
:(glGetProgramNamedParameterdvNV(id::GLuint, len::GLsizei, name::Ptr{GLubyte}, params::Ptr{GLdouble})::Void),
:(glVDPAURegisterVideoSurfaceNV(vdpSurface::Ptr{Void}, target::GLenum, numTextureNames::GLsizei, textureNames::Ptr{GLuint})::Cintptr),
:(glVDPAURegisterOutputSurfaceNV(vdpSurface::Ptr{Void}, target::GLenum, numTextureNames::GLsizei, textureNames::Ptr{GLuint})::Cintptr),
:(glProgramUniform2ui64vNV(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint64EXT})::Void),
:(glVertexAttrib1dNV(index::GLuint, x::GLdouble)::Void),
:(glVertexAttribI2uiEXT(index::GLuint, x::GLuint, y::GLuint)::Void),
:(glVertexAttribL2i64NV(index::GLuint, x::GLint64EXT, y::GLint64EXT)::Void),
:(glPathCommandsNV(path::GLuint, numCommands::GLsizei, commands::Ptr{GLubyte}, numCoords::GLsizei, coordType::GLenum, coords::Ptr{Void})::Void),
:(glGetVideouivNV(video_slot::GLuint, pname::GLenum, params::Ptr{GLuint})::Void),
:(glUniformui64NV(location::GLint, value::GLuint64EXT)::Void),
:(glProgramUniform1ui64NV(program::GLuint, location::GLint, x::GLuint64EXT)::Void),
:(glProgramNamedParameter4dNV(id::GLuint, len::GLsizei, name::Ptr{GLubyte}, x::GLdouble, y::GLdouble, z::GLdouble, w::GLdouble)::Void),
:(glUniform1i64NV(location::GLint, x::GLint64EXT)::Void),
:(glVDPAUIsSurfaceNV(surface::GLvdpauSurfaceNV)::Void),
:(glBeginConditionalRenderNV(id::GLuint, mode::GLenum)::Void),
:(glVertexAttrib3hNV(index::GLuint, x::GLhalfNV, y::GLhalfNV, z::GLhalfNV)::Void),
:(glProgramUniform4ui64vNV(program::GLuint, location::GLint, count::GLsizei, value::Ptr{GLuint64EXT})::Void),
:(glSampleMaskIndexedNV(index::GLuint, mask::GLbitfield)::Void),
:(glUniform4ui64NV(location::GLint, x::GLuint64EXT, y::GLuint64EXT, z::GLuint64EXT, w::GLuint64EXT)::Void),
:(glResumeTransformFeedbackNV()::Void),
:(glGetProgramParameterdvNV(target::GLenum, index::GLuint, pname::GLenum, params::Ptr{GLdouble})::Void)]
