#Types, functions and constants, needed on top of the common ones
#types
const GL_WGL_TYPES = [
]
#constants
const GL_WGL_CONSTANTS = [
:(const WGL_TEXTURE_TARGET_ARB                                          = 0x2073),
:(const WGL_TYPE_COLORINDEX_EXT                                         = 0x202C),
:(const WGL_STENCIL_BITS_EXT                                            = 0x2023),
:(const WGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV                            = 0x20A0),
:(const WGL_STEREO_POLARITY_NORMAL_3DL                                  = 0x2057),
:(const WGL_SWAP_UNDEFINED_ARB                                          = 0x202A),
:(const WGL_STEREO_EMITTER_ENABLE_3DL                                   = 0x2055),
:(const WGL_STEREO_EMITTER_DISABLE_3DL                                  = 0x2056),
:(const WGL_BIND_TO_VIDEO_RGBA_NV                                       = 0x20C1),
:(const WGL_NEED_SYSTEM_PALETTE_ARB                                     = 0x2005),
:(const WGL_PBUFFER_HEIGHT_EXT                                          = 0x2035),
:(const WGL_ACCUM_ALPHA_BITS_ARB                                        = 0x2021),
:(const WGL_STEREO_ARB                                                  = 0x2012),
:(const WGL_SUPPORT_OPENGL_EXT                                          = 0x2010),
:(const WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB                               = 0x00000004),
:(const WGL_DOUBLE_BUFFER_EXT                                           = 0x2011),
:(const WGL_TEXTURE_FLOAT_RG_NV                                         = 0x20B6),
:(const WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV                      = 0x20B3),
:(const WGL_BLUE_BITS_ARB                                               = 0x2019),
:(const WGL_AUX7_ARB                                                    = 0x208E),
:(const WGL_BLUE_SHIFT_ARB                                              = 0x201A),
:(const WGL_NO_RESET_NOTIFICATION_ARB                                   = 0x8261),
:(const WGL_TEXTURE_RECTANGLE_NV                                        = 0x20A2),
:(const WGL_CONTEXT_LAYER_PLANE_ARB                                     = 0x2093),
:(const WGL_SAMPLES_ARB                                                 = 0x2042),
:(const WGL_ALPHA_BITS_ARB                                              = 0x201B),
:(const WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV                          = 0x20A4),
:(const WGL_SWAP_COPY_ARB                                               = 0x2029),
:(const WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D                  = 0x2050),
:(const WGL_GPU_OPENGL_VERSION_STRING_AMD                               = 0x1F02),
:(const WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV                       = 0x20B2),
:(const WGL_GAMMA_TABLE_SIZE_I3D                                        = 0x204E),
:(const WGL_GPU_NUM_RB_AMD                                              = 0x21A7),
:(const WGL_GENLOCK_SOURCE_EXTERNAL_SYNC_I3D                            = 0x2045),
:(const WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB                             = 0x207E),
:(const WGL_PBUFFER_HEIGHT_ARB                                          = 0x2035),
:(const WGL_LOSE_CONTEXT_ON_RESET_ARB                                   = 0x8252),
:(const WGL_TEXTURE_RGBA_ARB                                            = 0x2076),
:(const WGL_SAMPLE_BUFFERS_EXT                                          = 0x2041),
:(const WGL_GREEN_SHIFT_EXT                                             = 0x2018),
:(const WGL_GENLOCK_SOURCE_EXTERNAL_FIELD_I3D                           = 0x2046),
:(const WGL_DRAW_TO_BITMAP_ARB                                          = 0x2002),
:(const WGL_BLUE_SHIFT_EXT                                              = 0x201A),
:(const WGL_FLOAT_COMPONENTS_NV                                         = 0x20B0),
:(const WGL_VIDEO_OUT_COLOR_NV                                          = 0x20C3),
:(const WGL_AUX4_ARB                                                    = 0x208B),
:(const WGL_RED_BITS_EXT                                                = 0x2015),
:(const WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D                           = 0x2053),
:(const WGL_AUX9_ARB                                                    = 0x2090),
:(const WGL_PBUFFER_WIDTH_ARB                                           = 0x2034),
:(const WGL_NO_TEXTURE_ARB                                              = 0x2077),
:(const WGL_CUBE_MAP_FACE_ARB                                           = 0x207C),
:(const WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB                             = 0x207D),
:(const WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT                                = 0x20A8),
:(const WGL_AUX0_ARB                                                    = 0x2087),
:(const WGL_OPTIMAL_PBUFFER_WIDTH_EXT                                   = 0x2031),
:(const WGL_TEXTURE_CUBE_MAP_ARB                                        = 0x2078),
:(const WGL_TEXTURE_FLOAT_RGBA_NV                                       = 0x20B8),
:(const WGL_BACK_RIGHT_ARB                                              = 0x2086),
:(const WGL_RED_SHIFT_EXT                                               = 0x2016),
:(const WGL_TRANSPARENT_EXT                                             = 0x200A),
:(const WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D                        = 0x2051),
:(const WGL_AUX6_ARB                                                    = 0x208D),
:(const WGL_SWAP_EXCHANGE_ARB                                           = 0x2028),
:(const WGL_NUMBER_UNDERLAYS_EXT                                        = 0x2009),
:(const WGL_NEED_SYSTEM_PALETTE_EXT                                     = 0x2005),
:(const WGL_COLOR_BITS_EXT                                              = 0x2014),
:(const WGL_ACCESS_READ_WRITE_NV                                        = 0x00000001),
:(const WGL_BIND_TO_VIDEO_RGB_NV                                        = 0x20C0),
:(const WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB                                = 0x20A9),
:(const WGL_GPU_NUM_SPI_AMD                                             = 0x21A8),
:(const WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB                       = 0x00000002),
:(const ERROR_INVALID_PIXEL_TYPE_ARB                                    = 0x2043),
:(const WGL_FRONT_RIGHT_ARB                                             = 0x2084),
:(const WGL_ERROR_MISSING_AFFINITY_MASK_NV                              = 0x20D1),
:(const WGL_GAMMA_EXCLUDE_DESKTOP_I3D                                   = 0x204F),
:(const WGL_ACCESS_WRITE_DISCARD_NV                                     = 0x00000002),
:(const WGL_FULL_ACCELERATION_ARB                                       = 0x2027),
:(const WGL_NEED_PALETTE_ARB                                            = 0x2004),
:(const WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB                             = 0x207F),
:(const WGL_STEREO_POLARITY_INVERT_3DL                                  = 0x2058),
:(const WGL_TEXTURE_FORMAT_ARB                                          = 0x2072),
:(const WGL_RED_SHIFT_ARB                                               = 0x2016),
:(const WGL_STENCIL_BITS_ARB                                            = 0x2023),
:(const WGL_FULL_ACCELERATION_EXT                                       = 0x2027),
:(const WGL_PBUFFER_WIDTH_EXT                                           = 0x2034),
:(const WGL_BLUE_BITS_EXT                                               = 0x2019),
:(const WGL_MAX_PBUFFER_WIDTH_ARB                                       = 0x202F),
:(const WGL_SWAP_UNDEFINED_EXT                                          = 0x202A),
:(const WGL_TRANSPARENT_VALUE_EXT                                       = 0x200B),
:(const WGL_MAX_PBUFFER_HEIGHT_EXT                                      = 0x2030),
:(const WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D                             = 0x2048),
:(const WGL_PBUFFER_LARGEST_ARB                                         = 0x2033),
:(const WGL_DEPTH_BUFFER_BIT_ARB                                        = 0x00000004),
:(const WGL_AUX2_ARB                                                    = 0x2089),
:(const WGL_SWAP_METHOD_EXT                                             = 0x2007),
:(const WGL_SWAP_LAYER_BUFFERS_ARB                                      = 0x2006),
:(const WGL_FRONT_LEFT_ARB                                              = 0x2083),
:(const WGL_ACCELERATION_ARB                                            = 0x2003),
:(const WGL_DEPTH_BITS_ARB                                              = 0x2022),
:(const WGL_SHARE_ACCUM_ARB                                             = 0x200E),
:(const WGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV                           = 0x20A1),
:(const WGL_CONTEXT_ES2_PROFILE_BIT_EXT                                 = 0x00000004),
:(const WGL_DEPTH_TEXTURE_FORMAT_NV                                     = 0x20A5),
:(const WGL_MIPMAP_LEVEL_ARB                                            = 0x207B),
:(const WGL_GPU_CLOCK_AMD                                               = 0x21A4),
:(const WGL_CONTEXT_MAJOR_VERSION_ARB                                   = 0x2091),
:(const WGL_BIND_TO_TEXTURE_DEPTH_NV                                    = 0x20A3),
:(const WGL_UNIQUE_ID_NV                                                = 0x20CE),
:(const WGL_COVERAGE_SAMPLES_NV                                         = 0x2042),
:(const WGL_GENERIC_ACCELERATION_ARB                                    = 0x2026),
:(const ERROR_INVALID_PROFILE_ARB                                       = 0x2096),
:(const WGL_NUMBER_PIXEL_FORMATS_EXT                                    = 0x2000),
:(const ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB                          = 0x2054),
:(const WGL_AUX_BUFFERS_ARB                                             = 0x2024),
:(const WGL_DRAW_TO_PBUFFER_ARB                                         = 0x202D),
:(const WGL_ALPHA_SHIFT_ARB                                             = 0x201C),
:(const WGL_TEXTURE_2D_ARB                                              = 0x207A),
:(const WGL_VIDEO_OUT_COLOR_AND_DEPTH_NV                                = 0x20C7),
:(const WGL_DEPTH_BITS_EXT                                              = 0x2022),
:(const WGL_MAX_PBUFFER_PIXELS_EXT                                      = 0x202E),
:(const WGL_TEXTURE_1D_ARB                                              = 0x2079),
:(const WGL_MIPMAP_TEXTURE_ARB                                          = 0x2074),
:(const WGL_PBUFFER_LARGEST_EXT                                         = 0x2033),
:(const WGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB                     = 0x8256),
:(const WGL_TYPE_RGBA_EXT                                               = 0x202B),
:(const WGL_PIXEL_TYPE_EXT                                              = 0x2013),
:(const WGL_SAMPLE_BUFFERS_ARB                                          = 0x2041),
:(const WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D                            = 0x2049),
:(const WGL_BIND_TO_TEXTURE_RGBA_ARB                                    = 0x2071),
:(const WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D                                = 0x204C),
:(const WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV                        = 0x20B1),
:(const WGL_NO_ACCELERATION_EXT                                         = 0x2025),
:(const WGL_GPU_NUM_SIMD_AMD                                            = 0x21A6),
:(const WGL_AUX8_ARB                                                    = 0x208F),
:(const WGL_GREEN_SHIFT_ARB                                             = 0x2018),
:(const WGL_GPU_VENDOR_AMD                                              = 0x1F00),
:(const WGL_MAX_PBUFFER_HEIGHT_ARB                                      = 0x2030),
:(const WGL_MAX_PBUFFER_PIXELS_ARB                                      = 0x202E),
:(const WGL_TEXTURE_DEPTH_COMPONENT_NV                                  = 0x20A6),
:(const WGL_FRONT_COLOR_BUFFER_BIT_ARB                                  = 0x00000001),
:(const WGL_GREEN_BITS_EXT                                              = 0x2017),
:(const WGL_NUMBER_UNDERLAYS_ARB                                        = 0x2009),
:(const WGL_RED_BITS_ARB                                                = 0x2015),
:(const WGL_AUX1_ARB                                                    = 0x2088),
:(const WGL_ACCUM_BLUE_BITS_ARB                                         = 0x2020),
:(const WGL_NO_ACCELERATION_ARB                                         = 0x2025),
:(const WGL_TYPE_COLORINDEX_ARB                                         = 0x202C),
:(const WGL_GENLOCK_SOURCE_EDGE_RISING_I3D                              = 0x204B),
:(const WGL_GPU_RENDERER_STRING_AMD                                     = 0x1F01),
:(const WGL_PBUFFER_LOST_ARB                                            = 0x2036),
:(const WGL_COLOR_SAMPLES_NV                                            = 0x20B9),
:(const WGL_GPU_FASTEST_TARGET_GPUS_AMD                                 = 0x21A2),
:(const WGL_VIDEO_OUT_FIELD_1                                           = 0x20C9),
:(const WGL_ACCESS_READ_ONLY_NV                                         = 0x00000000),
:(const WGL_VIDEO_OUT_FIELD_2                                           = 0x20CA),
:(const WGL_CONTEXT_FLAGS_ARB                                           = 0x2094),
:(const WGL_COLOR_BITS_ARB                                              = 0x2014),
:(const WGL_PIXEL_TYPE_ARB                                              = 0x2013),
:(const WGL_GENERIC_ACCELERATION_EXT                                    = 0x2026),
:(const WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB                          = 0x00000002),
:(const WGL_SWAP_COPY_EXT                                               = 0x2029),
:(const WGL_GENLOCK_SOURCE_EXTERNAL_TTL_I3D                             = 0x2047),
:(const WGL_DRAW_TO_WINDOW_ARB                                          = 0x2001),
:(const WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT                                = 0x20A9),
:(const WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV                     = 0x20B4),
:(const WGL_IMAGE_BUFFER_MIN_ACCESS_I3D                                 = 0x00000001),
:(const WGL_NUM_VIDEO_SLOTS_NV                                          = 0x20F0),
:(const WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB                             = 0x2082),
:(const WGL_TYPE_RGBA_FLOAT_ARB                                         = 0x21A0),
:(const WGL_ALPHA_BITS_EXT                                              = 0x201B),
:(const WGL_ACCUM_ALPHA_BITS_EXT                                        = 0x2021),
:(const WGL_NUMBER_OVERLAYS_EXT                                         = 0x2008),
:(const WGL_DRAW_TO_WINDOW_EXT                                          = 0x2001),
:(const WGL_SUPPORT_OPENGL_ARB                                          = 0x2010),
:(const WGL_VIDEO_OUT_DEPTH_NV                                          = 0x20C5),
:(const WGL_OPTIMAL_PBUFFER_HEIGHT_EXT                                  = 0x2032),
:(const WGL_CONTEXT_PROFILE_MASK_ARB                                    = 0x9126),
:(const WGL_VIDEO_OUT_COLOR_AND_ALPHA_NV                                = 0x20C6),
:(const WGL_TEXTURE_FLOAT_RGB_NV                                        = 0x20B7),
:(const WGL_NUM_VIDEO_CAPTURE_SLOTS_NV                                  = 0x20CF),
:(const WGL_ACCUM_BITS_EXT                                              = 0x201D),
:(const WGL_SWAP_LAYER_BUFFERS_EXT                                      = 0x2006),
:(const WGL_ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV                        = 0x20D0),
:(const WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB                             = 0x2081),
:(const WGL_VIDEO_OUT_STACKED_FIELDS_1_2                                = 0x20CB),
:(const WGL_CONTEXT_MINOR_VERSION_ARB                                   = 0x2092),
:(const WGL_TYPE_RGBA_FLOAT_ATI                                         = 0x21A0),
:(const WGL_SAMPLE_BUFFERS_3DFX                                         = 0x2060),
:(const WGL_ACCUM_RED_BITS_EXT                                          = 0x201E),
:(const WGL_SHARE_STENCIL_EXT                                           = 0x200D),
:(const WGL_VIDEO_OUT_STACKED_FIELDS_2_1                                = 0x20CC),
:(const WGL_STENCIL_BUFFER_BIT_ARB                                      = 0x00000008),
:(const WGL_MAX_PBUFFER_WIDTH_EXT                                       = 0x202F),
:(const WGL_SHARE_DEPTH_EXT                                             = 0x200C),
:(const WGL_NUMBER_OVERLAYS_ARB                                         = 0x2008),
:(const WGL_SAMPLES_EXT                                                 = 0x2042),
:(const WGL_AUX5_ARB                                                    = 0x208C),
:(const WGL_ACCELERATION_EXT                                            = 0x2003),
:(const WGL_SAMPLES_3DFX                                                = 0x2061),
:(const WGL_AUX3_ARB                                                    = 0x208A),
:(const WGL_DEPTH_FLOAT_EXT                                             = 0x2040),
:(const WGL_VIDEO_OUT_ALPHA_NV                                          = 0x20C4),
:(const WGL_DOUBLE_BUFFER_ARB                                           = 0x2011),
:(const WGL_BACK_COLOR_BUFFER_BIT_ARB                                   = 0x00000002),
:(const WGL_SUPPORT_GDI_ARB                                             = 0x200F),
:(const WGL_STEREO_EXT                                                  = 0x2012),
:(const WGL_ACCUM_BITS_ARB                                              = 0x201D),
:(const WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D                           = 0x2052),
:(const WGL_DEPTH_COMPONENT_NV                                          = 0x20A7),
:(const WGL_SUPPORT_GDI_EXT                                             = 0x200F),
:(const WGL_BIND_TO_TEXTURE_RGB_ARB                                     = 0x2070),
:(const WGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV                              = 0x20C2),
:(const WGL_SWAP_METHOD_ARB                                             = 0x2007),
:(const WGL_SHARE_STENCIL_ARB                                           = 0x200D),
:(const ERROR_INVALID_PIXEL_TYPE_EXT                                    = 0x2043),
:(const WGL_ACCUM_BLUE_BITS_EXT                                         = 0x2020),
:(const WGL_ACCUM_RED_BITS_ARB                                          = 0x201E),
:(const WGL_TYPE_RGBA_ARB                                               = 0x202B),
:(const WGL_VIDEO_OUT_FRAME                                             = 0x20C8),
:(const WGL_BACK_LEFT_ARB                                               = 0x2085),
:(const WGL_NUMBER_PIXEL_FORMATS_ARB                                    = 0x2000),
:(const WGL_DRAW_TO_BITMAP_EXT                                          = 0x2002),
:(const WGL_GENLOCK_SOURCE_MULTIVIEW_I3D                                = 0x2044),
:(const WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB                             = 0x2080),
:(const WGL_TEXTURE_RGB_ARB                                             = 0x2075),
:(const WGL_CONTEXT_DEBUG_BIT_ARB                                       = 0x00000001),
:(const WGL_IMAGE_BUFFER_LOCK_I3D                                       = 0x00000002),
:(const WGL_ACCUM_GREEN_BITS_ARB                                        = 0x201F),
:(const WGL_GPU_RAM_AMD                                                 = 0x21A3),
:(const WGL_NEED_PALETTE_EXT                                            = 0x2004),
:(const WGL_SWAP_EXCHANGE_EXT                                           = 0x2028),
:(const ERROR_INVALID_VERSION_ARB                                       = 0x2095),
:(const WGL_SHARE_DEPTH_ARB                                             = 0x200C),
:(const WGL_ALPHA_SHIFT_EXT                                             = 0x201C),
:(const WGL_TEXTURE_FLOAT_R_NV                                          = 0x20B5),
:(const WGL_DRAW_TO_PBUFFER_EXT                                         = 0x202D),
:(const WGL_GPU_NUM_PIPES_AMD                                           = 0x21A5),
:(const WGL_ACCUM_GREEN_BITS_EXT                                        = 0x201F),
:(const WGL_SHARE_ACCUM_EXT                                             = 0x200E),
:(const WGL_TRANSPARENT_ARB                                             = 0x200A),
:(const WGL_GREEN_BITS_ARB                                              = 0x2017),
:(const WGL_AUX_BUFFERS_EXT                                             = 0x2024),
:(const WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D                             = 0x204A),
:(const WGL_CONTEXT_CORE_PROFILE_BIT_ARB                                = 0x00000001)]
#function bodies
const GL_WGL_FUNCTIONS = [
:(wglResetFrameCountNV(hDC::HDC)::Cint),
:(wglGetPbufferDCARB(hPbuffer::HPBUFFERARB)::Ptr{Void}),
:(wglGetPixelFormatAttribfvEXT(hdc::HDC, iPixelFormat::Cint, iLayerPlane::Cint, nAttributes::Cuint, piAttributes::Ptr{Cint}, pfValues::Ptr{Cfloat})::Cint),
:(wglReleaseVideoDeviceNV(hVideoDevice::HPVIDEODEV)::Cint),
:(wglBindVideoCaptureDeviceNV(uVideoSlot::Cuint, hDevice::HVIDEOINPUTDEVICENV)::Cint),
:(wglGetGenlockSourceI3D(hDC::HDC, uSource::Ptr{Cuint})::Cint),
:(wglGetFrameUsageI3D(pUsage::Ptr{Cfloat})::Cint),
:(wglRealizeLayerPalette(hdc::HDC, iLayerPlane::Cint, bRealize::Bool)::Cint),
:(wglEnumGpusNV(iGpuIndex::Cuint, phGpu::HGPUNV)::Cint),
:(wglEnableGenlockI3D(hDC::HDC)::Cint),
:(wglGetDigitalVideoParametersI3D(hDC::HDC, iAttribute::Cint, piValue::Ptr{Cint})::Cint),
:(wglCreateContextAttribsARB(hDC::HDC, hShareContext::HGLRC, attribList::Ptr{Cint})::Ptr{Void}),
:(wglReleaseVideoCaptureDeviceNV(hDc::HDC, hDevice::HVIDEOINPUTDEVICENV)::Cint),
:(wglEnumGpusFromAffinityDCNV(hAffinityDC::HDC, iGpuIndex::Cuint, hGpu::HGPUNV)::Cint),
:(wglQueryPbufferEXT(hPbuffer::HPBUFFEREXT, iAttribute::Cint, piValue::Ptr{Cint})::Cint),
:(wglQueryVideoCaptureDeviceNV(hDc::HDC, hDevice::HVIDEOINPUTDEVICENV, iAttribute::Cint, piValue::Ptr{Cint})::Cint),
:(wglSendPbufferToVideoNV(hPbuffer::HPBUFFERARB, iBufferType::Cint, pulCounterPbuffer::Ptr{Culong}, bBlock::Bool)::Cint),
:(wglDXObjectAccessNV(hObject::HANDLE, access::GLenum)::Cint),
:(wglEnumGpuDevicesNV(hGpu::HGPUNV, iDeviceIndex::Cuint, lpGpuDevice::PGPU_DEVICE)::Cint),
:(wglGetGPUIDsAMD(maxCount::Cuint, ids::Ptr{Cuint})::Cuint),
:(wglCopyImageSubDataNV(hSrcRC::HGLRC, srcName::GLuint, srcTarget::GLenum, srcLevel::GLint, srcX::GLint, srcY::GLint, srcZ::GLint, hDstRC::HGLRC, dstName::GLuint, dstTarget::GLenum, dstLevel::GLint, dstX::GLint, dstY::GLint, dstZ::GLint, width::GLsizei, height::GLsizei, depth::GLsizei)::Cint),
:(wglGetPixelFormatAttribivARB(hdc::HDC, iPixelFormat::Cint, iLayerPlane::Cint, nAttributes::Cuint, piAttributes::Ptr{Cint}, piValues::Ptr{Cint})::Cint),
:(wglIsEnabledFrameLockI3D(pFlag::Ptr{Bool})::Cint),
:(wglDeleteAssociatedContextAMD(hglrc::HGLRC)::Cint),
:(wglDXUnlockObjectsNV(hDevice::HANDLE, count::GLint, hObjects::HANDLE)::Cint),
:(wglUseFontBitmapsW(hDC::HDC, first::DWORD, count::DWORD, listBase::DWORD)::Cint),
:(wglBindSwapBarrierNV(group::GLuint, barrier::GLuint)::Cint),
:(wglQueryFrameTrackingI3D(pFrameCount::Ptr{DWORD}, pMissedFrames::Ptr{DWORD}, pLastMissedUsage::Ptr{Cfloat})::Cint),
:(wglSetPbufferAttribARB(hPbuffer::HPBUFFERARB, piAttribList::Ptr{Cint})::Cint),
:(wglCreateContext(hDc::HDC)::Ptr{Void}),
:(wglWaitForMscOML(hdc::HDC, target_msc::Clonglong, divisor::Clonglong, remainder::Clonglong, ust::Ptr{Clonglong}, msc::Ptr{Clonglong}, sbc::Ptr{Clonglong})::Cint),
:(wglSetGammaTableParametersI3D(hDC::HDC, iAttribute::Cint, piValue::Ptr{Cint})::Cint),
:(wglIsEnabledGenlockI3D(hDC::HDC, pFlag::Ptr{Bool})::Cint),
:(wglLoadDisplayColorTableEXT(table::Ptr{GLushort}, length::GLuint)::Bool),
:(wglSwapBuffers(hdc::HDC)::Cint),
:(wglGetPixelFormatAttribivEXT(hdc::HDC, iPixelFormat::Cint, iLayerPlane::Cint, nAttributes::Cuint, piAttributes::Ptr{Cint}, piValues::Ptr{Cint})::Cint),
:(wglGetDefaultProcAddress(lpszProc::LPCSTR)::Ptr{Void}),
:(wglCreateAssociatedContextAttribsAMD(id::Cuint, hShareContext::HGLRC, attribList::Ptr{Cint})::Ptr{Void}),
:(wglMakeContextCurrentEXT(hDrawDC::HDC, hReadDC::HDC, hglrc::HGLRC)::Cint),
:(wglMakeAssociatedContextCurrentAMD(hglrc::HGLRC)::Cint),
:(wglDestroyPbufferEXT(hPbuffer::HPBUFFEREXT)::Cint),
:(wglGetVideoDeviceNV(hDC::HDC, numDevices::Cint, hVideoDevice::HPVIDEODEV)::Cint),
:(wglDXOpenDeviceNV(dxDevice::Ptr{Void})::Ptr{Void}),
:(wglShareLists(hrcSrvShare::HGLRC, hrcSrvSource::HGLRC)::Cint),
:(wglWaitForSbcOML(hdc::HDC, target_sbc::Clonglong, ust::Ptr{Clonglong}, msc::Ptr{Clonglong}, sbc::Ptr{Clonglong})::Cint),
:(wglRestoreBufferRegionARB(hRegion::HANDLE, x::Cint, y::Cint, width::Cint, height::Cint, xSrc::Cint, ySrc::Cint)::Cint),
:(wglGetGenlockSourceEdgeI3D(hDC::HDC, uEdge::Ptr{Cuint})::Cint),
:(wglCreateDisplayColorTableEXT(id::GLushort)::Bool),
:(wglGetMscRateOML(hdc::HDC, numerator::Ptr{Cint}, denominator::Ptr{Cint})::Cint),
:(wglGenlockSourceDelayI3D(hDC::HDC, uDelay::Cuint)::Cint),
:(wglSwapIntervalEXT(interval::Cint)::Cint),
:(wglCreateBufferRegionARB(hDC::HDC, iLayerPlane::Cint, uType::Cuint)::Ptr{Void}),
:(wglAssociateImageBufferEventsI3D(hDC::HDC, pEvent::HANDLE, pAddress::LPVOID, pSize::Ptr{DWORD}, count::Cuint)::Cint),
:(wglGetGenlockSampleRateI3D(hDC::HDC, uRate::Ptr{Cuint})::Cint),
:(wglGetPixelFormat(hdc::HDC)::Cint),
:(wglSetGammaTableI3D(hDC::HDC, iEntries::Cint, puRed::Ptr{Cushort}, puGreen::Ptr{Cushort}, puBlue::Ptr{Cushort})::Cint),
:(wglDestroyPbufferARB(hPbuffer::HPBUFFERARB)::Cint),
:(wglGetGammaTableParametersI3D(hDC::HDC, iAttribute::Cint, piValue::Ptr{Cint})::Cint),
:(wglDXCloseDeviceNV(hDevice::HANDLE)::Cint),
:(wglQuerySwapGroupNV(hDC::HDC, group::Ptr{GLuint}, barrier::Ptr{GLuint})::Cint),
:(wglGetPixelFormatAttribfvARB(hdc::HDC, iPixelFormat::Cint, iLayerPlane::Cint, nAttributes::Cuint, piAttributes::Ptr{Cint}, pfValues::Ptr{Cfloat})::Cint),
:(wglDXUnregisterObjectNV(hDevice::HANDLE, hObject::HANDLE)::Cint),
:(wglChoosePixelFormatARB(hdc::HDC, piAttribIList::Ptr{Cint}, pfAttribFList::Ptr{Cfloat}, nMaxFormats::Cuint, piFormats::Ptr{Cint}, nNumFormats::Ptr{Cuint})::Cint),
:(wglGenlockSourceI3D(hDC::HDC, uSource::Cuint)::Cint),
:(wglCreateAffinityDCNV(phGpuList::HGPUNV)::Ptr{Void}),
:(wglJoinSwapGroupNV(hDC::HDC, group::GLuint)::Cint),
:(wglMakeCurrent(hDc::HDC, newContext::HGLRC)::Cint),
:(wglGetGPUInfoAMD(id::Cuint, property::Cint, dataType::GLenum, size::Cuint, data::Ptr{Void})::Cint),
:(wglCreateAssociatedContextAMD(id::Cuint)::Ptr{Void}),
:(wglDestroyImageBufferI3D(hDC::HDC, pAddress::LPVOID)::Cint),
:(wglDXLockObjectsNV(hDevice::HANDLE, count::GLint, hObjects::HANDLE)::Cint),
:(wglQueryFrameCountNV(hDC::HDC, count::Ptr{GLuint})::Cint),
:(wglGetSyncValuesOML(hdc::HDC, ust::Ptr{Clonglong}, msc::Ptr{Clonglong}, sbc::Ptr{Clonglong})::Cint),
:(wglLockVideoCaptureDeviceNV(hDc::HDC, hDevice::HVIDEOINPUTDEVICENV)::Cint),
:(wglCopyContext(hglrcSrc::HGLRC, hglrcDst::HGLRC, mask::Cuint)::Cint),
:(wglBindVideoDeviceNV(hDC::HDC, uVideoSlot::Cuint, hVideoDevice::HVIDEOOUTPUTDEVICENV, piAttribList::Ptr{Cint})::Cint),
:(wglSetPixelFormat(hdc::HDC, ipfd::Cint, ppfd::PIXELFORMATDESCRIPTOR)::Cint),
:(wglReleaseTexImageARB(hPbuffer::HPBUFFERARB, iBuffer::Cint)::Cint),
:(wglSetDigitalVideoParametersI3D(hDC::HDC, iAttribute::Cint, piValue::Ptr{Cint})::Cint),
:(wglChoosePixelFormat(hDc::HDC, pPfd::PIXELFORMATDESCRIPTOR)::Cint),
:(wglGetPbufferDCEXT(hPbuffer::HPBUFFEREXT)::Ptr{Void}),
:(wglReleasePbufferDCEXT(hPbuffer::HPBUFFEREXT, hDC::HDC)::Cint),
:(wglChoosePixelFormatEXT(hdc::HDC, piAttribIList::Ptr{Cint}, pfAttribFList::Ptr{Cfloat}, nMaxFormats::Cuint, piFormats::Ptr{Cint}, nNumFormats::Ptr{Cuint})::Cint),
:(wglGenlockSourceEdgeI3D(hDC::HDC, uEdge::Cuint)::Cint),
:(wglDXRegisterObjectNV(hDevice::HANDLE, dxObject::Ptr{Void}, name::GLuint, type_::GLenum, access::GLenum)::Ptr{Void}),
:(wglSaveBufferRegionARB(hRegion::HANDLE, x::Cint, y::Cint, width::Cint, height::Cint)::Cint),
:(wglAllocateMemoryNV(size::GLsizei, readfreq::GLfloat, writefreq::GLfloat, priority::GLfloat)::Ptr{Void}),
:(wglGetProcAddress(lpszProc::LPCSTR)::Ptr{Void}),
:(wglBindTexImageARB(hPbuffer::HPBUFFERARB, iBuffer::Cint)::Cint),
:(wglReleaseImageBufferEventsI3D(hDC::HDC, pAddress::LPVOID, count::Cuint)::Cint),
:(wglSwapLayerBuffers(hdc::HDC, fuFlags::Cuint)::Cint),
:(wglGetExtensionsStringARB(hdc::HDC)::Ptr{Cchar}),
:(wglCreateLayerContext(hDc::HDC, level::Cint)::Ptr{Void}),
:(wglDXSetResourceShareHandleNV(dxObject::Ptr{Void}, shareHandle::HANDLE)::Cint),
:(wglBindVideoImageNV(hVideoDevice::HPVIDEODEV, hPbuffer::HPBUFFERARB, iVideoBuffer::Cint)::Cint),
:(wglQueryCurrentContextNV(iAttribute::Cint, piValue::Ptr{Cint})::Cint),
:(wglSetStereoEmitterState3DL(hDC::HDC, uState::Cuint)::Cint),
:(wglReleaseVideoImageNV(hPbuffer::HPBUFFERARB, iVideoBuffer::Cint)::Cint),
:(wglGetVideoInfoNV(hpVideoDevice::HPVIDEODEV, pulCounterOutputPbuffer::Ptr{Culong}, pulCounterOutputVideo::Ptr{Culong})::Cint),
:(wglQueryPbufferARB(hPbuffer::HPBUFFERARB, iAttribute::Cint, piValue::Ptr{Cint})::Cint),
:(wglDisableGenlockI3D(hDC::HDC)::Cint),
:(wglCreateImageBufferI3D(hDC::HDC, dwSize::DWORD, uFlags::Cuint)::Ptr{Void}),
:(wglQueryMaxSwapGroupsNV(hDC::HDC, maxGroups::Ptr{GLuint}, maxBarriers::Ptr{GLuint})::Cint),
:(wglBindDisplayColorTableEXT(id::GLushort)::Bool),
:(wglGenlockSampleRateI3D(hDC::HDC, uRate::Cuint)::Cint),
:(wglGetContextGPUIDAMD(hglrc::HGLRC)::Cuint),
:(wglCreatePbufferARB(hDC::HDC, iPixelFormat::Cint, iWidth::Cint, iHeight::Cint, piAttribList::Ptr{Cint})::Ptr{Void}),
:(wglMakeContextCurrentARB(hDrawDC::HDC, hReadDC::HDC, hglrc::HGLRC)::Cint),
:(wglSwapLayerBuffersMscOML(hdc::HDC, fuPlanes::Cint, target_msc::Clonglong, divisor::Clonglong, remainder::Clonglong)::CClonglong),
:(wglSwapBuffersMscOML(hdc::HDC, target_msc::Clonglong, divisor::Clonglong, remainder::Clonglong)::CClonglong),
:(wglDeleteContext(oldContext::HGLRC)::Cint),
:(wglQueryFrameLockMasterI3D(pFlag::Ptr{Bool})::Cint),
:(wglDescribeLayerPlane(hDc::HDC, pixelFormat::Cint, layerPlane::Cint, nBytes::Cuint, plpd::LAYERPLANEDESCRIPTOR)::Cint),
:(wglGetGenlockSourceDelayI3D(hDC::HDC, uDelay::Ptr{Cuint})::Cint),
:(wglQueryGenlockMaxSourceDelayI3D(hDC::HDC, uMaxLineDelay::Ptr{Cuint}, uMaxPixelDelay::Ptr{Cuint})::Cint),
:(wglGetGammaTableI3D(hDC::HDC, iEntries::Cint, puRed::Ptr{Cushort}, puGreen::Ptr{Cushort}, puBlue::Ptr{Cushort})::Cint),
:(wglEnumerateVideoCaptureDevicesNV(hDc::HDC, phDeviceList::HVIDEOINPUTDEVICENV)::Cuint),
:(wglReleasePbufferDCARB(hPbuffer::HPBUFFERARB, hDC::HDC)::Cint),
:(wglEnumerateVideoDevicesNV(hDC::HDC, phDeviceList::HVIDEOOUTPUTDEVICENV)::Cint),
:(wglGetLayerPaletteEntries(hdc::HDC, iLayerPlane::Cint, iStart::Cint, cEntries::Cint, pcr::COLORREF)::Cint),
:(wglDeleteDCNV(hdc::HDC)::Cint),
:(wglCreatePbufferEXT(hDC::HDC, iPixelFormat::Cint, iWidth::Cint, iHeight::Cint, piAttribList::Ptr{Cint})::Ptr{Void}),
:(wglSetLayerPaletteEntries(hdc::HDC, iLayerPlane::Cint, iStart::Cint, cEntries::Cint, pcr::COLORREF)::Cint),
:(wglUseFontBitmapsA(hDC::HDC, first::DWORD, count::DWORD, listBase::DWORD)::Cint)]
